### ISSUE TITLE
Run C++ examples with Rust Oak Loader

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#1009]
After merging https://github.com/project-oak/oak/pull/993 we currently do not support the C++ version of the `hello_world` example and `tensorflow` example.

We need to initialize the gRPC server pseudo-Node in:
https://github.com/project-oak/oak/blob/ce3a154315f1191c7ce4dd8f9cde0df3ba9143f5/examples/hello_world/module/cpp/hello_world.cc#L50
https://github.com/project-oak/oak/blob/ce3a154315f1191c7ce4dd8f9cde0df3ba9143f5/examples/tensorflow/module/cpp/tensorflow.cc#L93
and:
https://github.com/project-oak/oak/blob/ce3a154315f1191c7ce4dd8f9cde0df3ba9143f5/examples/tensorflow/module/cpp/tensorflow_micro.cc#L122

**Comment by daviddrysdale** [comment]
Ah, not quite closed yet &ndash; there's still some fixing needed for the tensorflow example and some complaint about 127.0.0.1 not being valid for SNI.

**Comment by ipetr0v** [comment]
It requires:
https://github.com/project-oak/oak/blob/61c9c86886502d72be44fb060d26d76e8121acd4/examples/tensorflow/client/tensorflow.cc#L25
to be changed to `localhost:8080`

**Comment by daviddrysdale** [comment]
Oh, if it's that straightforward I should have included it in #1016.  I thought there was some thing about Tonic not supporting certificates with IP addresses rather than hostnames?  Or was that a different something?

**Comment by ipetr0v** [comment]
Yes, that is the reason: https://github.com/ctz/rustls/issues/184
But our certificates include `localhost`

**Comment by daviddrysdale** [comment]
With #1026 I *think* this the tensorflow example working, but I can't see any output to be sure. Is there anything particular to look for in the logs?

**Comment by ipetr0v** [comment]
Tensorflow example currently doesn't log anything (doesn't use the logger pseudo-Node).
So, if it's responding to the client - everything is fine.
