### ISSUE TITLE
Use `env_logger` instead of `simple_logger`

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1013]
`simple_logger` lacks the ability to whitelist individual modules, which is useful to cut out too verbose logging from dependencies (e.g. http libraries, etc.)

**Comment by tiziano88** [comment]
I think some more references to `simple_logger` popped up, perhaps a race condition with the PR that was meant to fix this.

**Comment by daviddrysdale** [comment]
It would be helpful if you could indicate *where* you saw the references popping up&hellip;

**Comment by tiziano88** [comment]
Sorry you are right, I only saw it in the Cargo.lock file, I didn't look past that. I'll try and be more precise next time.
