### ISSUE TITLE
Split `runtime/mod.rs` into multiple files

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#1022]
Currently `oak_runtime/src/runtime/mod.rs` has over 1500 lines of code:
https://github.com/project-oak/oak/blob/1d54836177c5095f1aeadfd8347230546a2ec700/oak/server/rust/oak_runtime/src/runtime/mod.rs#L1516
I think it'll be good to split the file.

**Comment by daviddrysdale** [comment]
Reduced to 1258 lines by #1025. 

Splitting out the `RuntimeProxy` stuff into a separate module would probably make sense too.

**Comment by daviddrysdale** [comment]
Reduced to 1045 by #1106, current size 1056:
```
Filename   Code     Comments Blanks   
mod.rs      749      213       94 
```
