### ISSUE TITLE
Restructure Oak directories

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#1023]
Since C++ is now [gone](https://github.com/project-oak/oak/pull/1016), should we think about restructuring Oak directories (because currently most of the code is hidden deep inside the `oak/server/rust/oak_runtime/src`) ?

**Comment by tiziano88** [comment]
Yes, in fact I think this overlaps in part with #971

**Comment by ipetr0v** [comment]
Also I like the idea of stripping `oak_` prefixes from directories: https://github.com/project-oak/oak/issues/971#issuecomment-628889674

**Comment by conradgrobler** [comment]
We should also find an appropriate location for authentication.proto (and any other gRPC services exposed directly by the runtime).

Ref: https://github.com/project-oak/oak/pull/1003#discussion_r430970625
