### ISSUE TITLE
Improve or delete ConfigurationError when creating new Oak Nodes

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1027]
When creating a new Node or Pseudo-Node in the Oak Runtime, we represent errors with values of this enum:

https://github.com/project-oak/oak/blob/df425bd7ade82448da8f96b6e59cf52b90c79396/oak/server/rust/oak_runtime/src/node/mod.rs#L88-L96

It only contains some limited amount of details about the failure, and it really needs to be complemented by logs anyways, so we should probably either augment it with all the information needed to identify the failure, or get rid of it and just rely on logging at node creation time.

**Comment by tiziano88** [comment]
Note that currently we just return `ErrInvalidArgs` to the calling node if node creation fails:

https://github.com/project-oak/oak/blob/34630244b17aa231dac9d8f6d578b0ec5ee6eacf/oak/server/rust/oak_runtime/src/runtime/mod.rs#L1014-L1023

If `oak_loader` is built with logging enabled, then the Runtime will log details about the failure, but otherwise they will be lost forever, which is not ideal.

Perhaps we should have a mechanism for returning a string error message alongside an error message from ABI function calls, so that the error message may be printed by the calling node using regular logging pseudo-node (if one available **and** IFC is satisfied).

@daviddrysdale (or anyone else): is there a good pattern that may be used here, short of just adding additional parameters to each ABI function calls with pointer to a buffer in which to write an error message?

**Comment by tiziano88** [comment]
In this particular case, an alternative pattern could be to implement `node_create` as an RPC between the node and the runtime, rather than as an ABI call; we could define a gRPC-like interface for the Runtime, in which one of the methods would allow passing in all the parameters (including node configuration and label, which are conveniently already expressed as protobuf anyways), and get back a structured response (again as protobuf) or an error. This would presumably also allow to move / add more functionality to the Oak Runtime in a more type-safe and self-documenting way.

For instance, it would allow us to move [`random_get`](https://github.com/project-oak/oak/blob/master/docs/abi.md#random_get) from a dedicated ABI function call, to a RPC to the Runtime itself.

There are pros and cons, but I think it would be interesting to consider this approach.

**Comment by ipetr0v** [comment]
Do we need `ConfigurationError` for some complex logic, or it can just be replaced by `anyhow::Error`?
