### ISSUE TITLE
`oak_abi` crate missing from generated docs

### ISSUE THREAD

**Issue by daviddrysdale** [project-oak/oak#1037]
One slightly unexpected side-effect of #1034 &ndash; the online docs no longer include the `oak_abi` [crate](https://project-oak.github.io/oak/doc/oak_abi/index.html).  This is arguably the most important crate to include in the documentation, so it would be good to get it reinstated.

This could possibly be combined with #765.

~~(Also, the generated docs still include the now-deleted [`oak_glue`](https://project-oak.github.io/oak/doc/oak_glue/index.html) crate, which would probably just needs the [dangling line in Cargo.toml](https://github.com/project-oak/oak/blob/master/Cargo.toml#L22) to be removed &ndash; this change is included in #1036)~~ [Edit: I thought I'd deleted `oak_glue` but I hadn't; now coming in #1050)

**Comment by rbehjati** [comment]
This is fixed now. `oak_abi` docs are available at https://project-oak.github.io/oak/oak_abi/.
