### ISSUE TITLE
Perform Node tests over gRPC

### ISSUE THREAD

**Issue by daviddrysdale** [project-oak/oak#1038]
At the moment, Oak Nodes that have tests need to have two distinct Node entrypoints:
 - a `grpc_oak_main` which creates a gRPC server pseudo-Node and uses the resulting handle for its main loop (for "live" use)
 - a bare `oak_main` which expects to be handed a pre-existing handle for use in its main loop (for test use).

It would be nice if our tests of Nodes were closer to the "live" use, by exercising the Node via a real gRPC request rather than one that is specially injected.  This would involve:
 - The `oak_tests` crate would need to use a "real" gRPC client connection to the test Runtime instance.
 - Nodes would only need the single `grpc_oak_main` entrypoint, allowing the `oak_main` equivalent entrypoint to be dropped.
     - Exception: the translator Node is used both standalone (requiring `grpc_oak_main`) and as a library Node directly connected to other Nodes (requiring `oak_main`).
 - The Runtime behaviour of creating an implicit initial Node, and a handle to go with it, could be dropped.  Both the tests and the `oak_loader` would create a `Runtime` instance, not a `RuntimeProxy` instance (with its associated implicit Node), and neither would need any kind of channel reference or handle.
 - The "Programming Oak" [section on testing](https://github.com/project-oak/oak/blob/master/docs/programming-oak.md#testing) would need an update to match the new behaviour.

**Comment by tiziano88** [comment]
This would be useful, but I would not call this "unit testing" any more.

I think in practice we may want to support both:

- application gRPC integration tests (for Oak Applications that include a gRPC server pseudo-node)
- individual node unit tests (even for nodes that do not implement a gRPC service at all)

**Comment by daviddrysdale** [comment]
True, edited to remove the word "unit".  

For actual unit tests, #544 is also relevant (the original `oak_tests` framework allowed fault injection for channel operations, to allow error path testing).

**Comment by daviddrysdale** [comment]
Another thought: as @tiziano88 points out, our current Node tests aren't really "unit" tests &ndash; they rely on compiling the Node code to Wasm and loading the resulting module into a Runtime instance (with its embedded Wasm engine).

So should all these tests be Rust [*integration* tests](https://doc.rust-lang.org/book/ch11-03-test-organization.html#integration-tests) rather than unit tests?  I.e. should we move each `module/rust/src/tests.rs` to be `module/rust/tests/integration_test.rs` ?

**Comment by daviddrysdale** [comment]
#1093 is also related: the integration test will need to use native client code for the gRPC service (i.e. as would normally be generated by `tonic`), rather than the Oak-specific client code that's generated by our own generator.

**Comment by daviddrysdale** [comment]
Fixed in #1156
