### ISSUE TITLE
Add deadlink check for docs in CI

### ISSUE THREAD

**Issue by daviddrysdale** [project-oak/oak#1055]
We run `cargo deadlinks` to check for deadlinks in generated docs, but I don't think we currently have any CI checks for links in human-written docs.  It would be good if things like #1048 could be caught automatically.

Note, however, that this would put our CI builds at the mercy of external website availability, so it may turn out to be more brittle than is worthwhile.

**Comment by tiziano88** [comment]
I would avoid the external websites checks, but it would be nice to check whether our internal links (including links to headers in other markdown documents) are valid.

**Comment by daviddrysdale** [comment]
For external links, we could try it and see how often an external failure causes a CI failure.  Things like Wikipedia and crates.io should be fairly reliable; I'd guess that the links to other github.com sites would be most likely to flake.

We could maybe also police a canonical form for in-project links in docs (do we prefer `(/oak/proto/application.proto)` or `(https://github.com/project-oak/oak/blob/master/oak/proto/application.proto)`?)

**Comment by daviddrysdale** [comment]
Fixed by #1090.
