### ISSUE TITLE
Run Config Serializer without Bazel

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#1058]
After removing C++ from our codebase (https://github.com/project-oak/oak/pull/1016) we are still using Bazel to create a serialized application configuration:
https://github.com/project-oak/oak/blob/9f5d57ffe2887bdfd0b5bdede5fb4404fcfdd735/examples/hello_world/config/BUILD#L26-L33

It could be rewritten as a `bash` script.

Originated from https://project-oak.slack.com/archives/CHE9E13C3/p1591028897061100

**Comment by tiziano88** [comment]
@anghelcovici want to look into this? And then even #740 as a follow-up perhaps
