### ISSUE TITLE
Propagate request label in gRPC server pseudo-node implementation

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1059]
Incoming gRPC requests may contain a serialized Label as part of their metadata, which is supposed to control the label associated with the data once sent in an Oak Application.

This is not yet implemented in the Rust version of the gRPC server node:

https://github.com/project-oak/oak/blob/407bd1169c369838505fbfa12e5be579afb41946/oak/server/rust/oak_runtime/src/node/grpc/server/mod.rs#L338-L342

cc @ipetr0v @rbehjati @daviddrysdale

**Comment by tiziano88** [comment]
I started working on this, but I cannot immediately see how to return an error (ideally from a gRPC status) in this part of the pipeline: 

https://github.com/project-oak/oak/blob/a8a990297eac62eb219201383d936b2527a63c85/oak/server/rust/oak_runtime/src/node/grpc/server/mod.rs#L252

@ipetr0v should I just create an `http::Response` object myself?

**Comment by ipetr0v** [comment]
The error could be returned from `UnaryService::call`:
https://github.com/project-oak/oak/blob/a8a990297eac62eb219201383d936b2527a63c85/oak/server/rust/oak_runtime/src/node/grpc/server/mod.rs#L317

**Comment by tiziano88** [comment]
This should already be fixed by #1068.
