### ISSUE TITLE
Web-based Oak Runtime emulator

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1067]
At a basic level, the Oak Runtime runs WebAssembly modules, and exposes to them [functions](https://github.com/project-oak/oak/blob/master/docs/abi.md#host-functions) that allow them to interoperate with the Runtime itself and with other Nodes / Channels. Since browsers already have a WebAssembly engine built-in, and quite advanced ones at that, and also have debugging capabilities for WebAssembly modules when running it, it would be neat to have essentially an emulator / parallel implementation of the Oak Runtime for the browser.

To start with, it should be able to load an Oak [ApplicationConfiguration](https://github.com/project-oak/oak/blob/master/oak/proto/application.proto) protobuf file, which contains the list of Wasm modules, plus some metadata about how to create the first Wasm node out of that. For the web version, the runtime would basically just instantiate the first Wasm module in a native browser Wasm context, and expose to it the necessary host functions (initially just stubs, to make sure it actually loads, then gradually implement them with the actual functionality). For instance, once the runtime supports creating new nodes, then we can allow creating a log node, and see some output from the running Oak Application to the JS console of the browser. Then we can implement a web UI that allows populating a protobuf (or just parse it from JSON), and simulate sending that to the loaded application.

If this all works out, then we can even consider promoting this as to a first-class programming model Oak. We should consider the implications of Information Flow Control in the context of the browser at that point, but for the time being I would be inclined to just ignore any IFC-related functionality (just allow channel and nodes to talk freely to each other, and ignore labels).

**Comment by juliettepretot** [comment]
Thanks for writing this up! It makes a lot more sense now. :) 

I quite like it, not just because of its utility for debugging, but also because writing an emulator seems like a pretty friendly way to incrementally learn more about the Oak architecture.

**Comment by juliettepretot** [comment]
Yeah would love to work on that

**Comment by tiziano88** [comment]
Awesome! How about we gather some requirements, either here or in a separate doc, about technology to use (is Typescript part of the plan?), milestones (with expected functionality at each of them).

BTW, it occurred to me that the current Rust Oak Runtime could itself be compiled to Wasm, and be the foundation of the emulator, rather than re-implementing it from scratch in another language. If that works, it may massively simplify the scope of this task, in that at least the inner working of the Runtime emulator would rely on the actual code of the Runtime itself.

cc @anghelcovici

**Comment by tiziano88** [comment]
cc @daviddrysdale

**Comment by tiziano88** [comment]
I think it would be worth first trying to compile the current implementation of `oak_loader` to wasm; basically making one of the following commands succeed (will probably require removing / stubbing dependencies on network stuff):

- `cargo build --target=wasm32-unknown-emscripten --manifest-path=oak/server/rust/oak_loader/Cargo.toml`
- `cargo build --target=wasm32-wasi --manifest-path=oak/server/rust/oak_loader/Cargo.toml`

**Comment by juliettepretot** [comment]
Sounds good! I'll see if I can get the oak loader to compile.

RE tech stack & milestones, gathering them sounds good. TypeScript can definitely be part of the plan, you seem excited about it. ;) 

I think TS makes sense here, it'd be consistent with the approach to taken by rust, and makes things a lot easier for nonJs devs.

**Comment by juliettepretot** [comment]
Out of curiosity, what are your thoughts on the different wasm targets? Still wrapping my mind around what they mean. 

I saw you listed both wasm32-wasi (seems more expermental) & wasm32-unknown-emscripten, both of them seem to feature some support from various syscalls. I assume that's because we use some syscalls in Oak?

Reason I'm asking is I used the more barebones "wasm32-unknown-unknown" target in the past. There's [wasm-bind](https://github.com/rustwasm/wasm-bindgen) that provides easy JS interop for that, which can be nice.

**Comment by tiziano88** [comment]
I haven't looked enough into it, in principle I think we can pick whatever target works and is simpler to maintain. My impression was that if you use `wasm32-unknown-unknown` then basically anything related to file system and network fails to compile, but then again that's probably the case for the other targets too given our dependency on gRPC and other low level stuff. If you find a good comparison between them, or it feels to you that any of them is better than the others, happy to go with your suggestion.
