### ISSUE TITLE
WebAssembly module tag privilege

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1069]
Implement functionality for Wasm Nodes to declassify the tag corresponding to their own Wasm module hash.

Blocks #972

**Comment by conradgrobler** [comment]
Is there anything outstanding on this issue, or can it be closed?

**Comment by tiziano88** [comment]
I think this is done, including the wasm signature tag, right @ipetr0v ? I am closing it, but feel free to reopen if anything is outstanding.
