### ISSUE TITLE
Cannot extract client IP address from tonic request

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1089]
Calling this method always return None, at least when running the examples locally.

https://docs.rs/tonic/0.2.1/tonic/struct.Request.html#method.remote_addr

**Comment by ipetr0v** [comment]
There is a new `tonic` version ([0.3.0](https://docs.rs/tonic/0.3.0/tonic/struct.Request.html)), but it looks like they changed some APIs.

**Comment by ipetr0v** [comment]
Even adding `transport` to `features = ["tls", "transport"]` and updating to `tonic` 0.3.1 doesn't seem to solve the issue.
