### ISSUE TITLE
Add support for generating gRPC service code for Runtime pseudo nodes

### ISSUE THREAD

**Issue by conradgrobler** [project-oak/oak#1113]
The `OakServiceGenerator` generates code for use by WASM modules, but the generated code requires a reference to the SDK to compile. We should implement a version that generates gRPC service code that can be used by pseudo nodes in the runtime.

**Comment by daviddrysdale** [comment]
@conradgrobler is this now fixed?

**Comment by conradgrobler** [comment]
I don't think it is fixed. The main event loop and the matching on method_name is still manually done in the Roughtime pseudo node. If there is support for generating the code automatically I am not aware of it.

**Comment by daviddrysdale** [comment]
Ah OK, I misunderstood &ndash; I thought this just covered the generated service code doing `use oak;`.
