### ISSUE TITLE
reserve `error` log level for actual logic errors

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1132]
Some instances in which we log at error level:

https://github.com/project-oak/oak/blob/b19e128db0d6d754418ba373c26d418a7994571a/oak/server/rust/oak_runtime/src/node/wasm/mod.rs#L232-L235

https://github.com/project-oak/oak/blob/b19e128db0d6d754418ba373c26d418a7994571a/oak/server/rust/oak_runtime/src/node/wasm/mod.rs#L239-L242

https://github.com/project-oak/oak/blob/b19e128db0d6d754418ba373c26d418a7994571a/oak/server/rust/oak_runtime/src/node/wasm/mod.rs#L251-L254

https://github.com/project-oak/oak/blob/b19e128db0d6d754418ba373c26d418a7994571a/oak/server/rust/oak_runtime/src/node/wasm/mod.rs#L261-L264

https://github.com/project-oak/oak/blob/b19e128db0d6d754418ba373c26d418a7994571a/oak/server/rust/oak_runtime/src/node/wasm/mod.rs#L292-L295

https://github.com/project-oak/oak/blob/b19e128db0d6d754418ba373c26d418a7994571a/oak/server/rust/oak_runtime/src/node/wasm/mod.rs#L303-L306

https://github.com/project-oak/oak/blob/b19e128db0d6d754418ba373c26d418a7994571a/oak/server/rust/oak_runtime/src/node/wasm/mod.rs#L367-L370

https://github.com/project-oak/oak/blob/b19e128db0d6d754418ba373c26d418a7994571a/oak/server/rust/oak_runtime/src/node/wasm/mod.rs#L379-L382

https://github.com/project-oak/oak/blob/b19e128db0d6d754418ba373c26d418a7994571a/oak/server/rust/oak_runtime/src/node/wasm/mod.rs#L389-L392

https://github.com/project-oak/oak/blob/b19e128db0d6d754418ba373c26d418a7994571a/oak/server/rust/oak_runtime/src/node/wasm/mod.rs#L405-L408

https://github.com/project-oak/oak/blob/b19e128db0d6d754418ba373c26d418a7994571a/oak/server/rust/oak_runtime/src/node/wasm/mod.rs#L450-L453

https://github.com/project-oak/oak/blob/b19e128db0d6d754418ba373c26d418a7994571a/oak/server/rust/oak_runtime/src/node/wasm/mod.rs#L466-L469

https://github.com/project-oak/oak/blob/b19e128db0d6d754418ba373c26d418a7994571a/oak/server/rust/oak_runtime/src/node/wasm/mod.rs#L878

**Comment by ipetr0v** [comment]
Does it mean that these errors should become `warn!(...)` ?

**Comment by daviddrysdale** [comment]
Opinions vary &ndash; see discussion at #1134
