### ISSUE TITLE
Support examples with multiple clients in our CI scripts

### ISSUE THREAD

**Issue by juliettepretot** [project-oak/oak#1145]
Examples can have applications in multiple languages, as well as multiple clients (eg `hello_world`, which features cpp, Android, Node.js or Trusted Information Retrieval featuring cpp + Rust). 

Ideally our scripts should make it easy to run an optimal combination of these in our CI.

**Comment by juliettepretot** [comment]
My idea would be to enable passing a `-c all` flag to `scripts/run_examples`. Which would run all available clients for each example. 

We could then decide to run all clients for only the cpp applications (faster), or decide to run all clients for each application variant (more exhaustive).

**Comment by juliettepretot** [comment]
cc @ipetr0v, I am curious how the Rust Trusted Information Retrieval example handles this. It seems we only run the Rust client now? https://github.com/project-oak/oak/pull/1110/files#r439337221

**Comment by ipetr0v** [comment]
Right now, yes, it only runs a Rust client.
But `-c all` looks nice. Or we can always run all clients by default, and `-c ...` will just specify and restrict clients. Or it can read a list of languages like `-c cpp rust go nodejs` .

**Comment by juliettepretot** [comment]
I like running all clients by default, seems sensible to me :)

**Comment by juliettepretot** [comment]
Closing as my PR was merged
