### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by juliettepretot** [project-oak/oak#1151]
The `master` name in git [originates from the master/slave concept](https://mail.gnome.org/archives/desktop-devel-list/2019-May/msg00066.html). It seems appropiate to rename it. In the current moment it's a small and largely symbolic change, but imho it is worth doing. 

GitHub allows [setting any arbitary branch as the default branch](https://help.github.com/en/enterprise/2.13/user/articles/setting-the-default-branch). It also highlights it as such, so the main branch should be clear to everyone. Cloning works as you'd expect.

<img width="337" alt="Screenshot at Jun 14 10-11-35" src="https://user-images.githubusercontent.com/8875406/84589589-9d0c2d80-ae27-11ea-969b-f1600889960c.png">

Thoughts @tiziano88 @daviddrysdale @ipetr0v @rbehjati @benlaurie @anghelcovici? Are there any other considerations I'm missing? 

[Here's how to rename the branch on GitHub & in git](https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx). Presuambly our Google Cloud Build setup will require updating as well.

**Comment by juliettepretot** [comment]
Also open to other names, eg `trunk`, `head`, `lead`, `canon` but `main` seems most common

**Comment by daviddrysdale** [comment]
Just a reminder that the scripts in [`.github/workflows/`](https://github.com/project-oak/oak/blob/master/.github/workflows) will also need an update for the new name.

(Another option: `dev` is short)

**Comment by anghelcovici** [comment]
Interesting, I've always thought the name master comes from "master copy" and the explanation you linked seems to make a few logic jumps to get to a different origin. However, I don't really have a strong opinion on this, if people associate it with master/slave we should change it.

**Comment by juliettepretot** [comment]
@anghelcovici While I find the explaination linked really quite plausible (with git being created as a succesor to BitKeeper in the linux project), I agree with your overall point: If people associate it with that, let's change it. 

Some people sure associate it with that, so I think we should change it. :)

I also see it as a bit symbolic thing. If we can't even make such a minor change, it really doesn't reflect kindly onto our industry's ability to listen to voices of those currently outside of it.

**Comment by tiziano88** [comment]
I am happy to go forward with this suggestion, regardless of the actual etymology of the current terminology. If someone feels (or would feel) triggered by the current choice of words, and we have the capability to change it, I think we should.

We should probably coordinate this across the other repos in the oak org though (I would say across the google org too, but that seems unlikely to happen in a reasonable time frame).

As a side note, other things we would have to change are the CI triggers on GCB. And make sure that everyone who already had the repo cloned starts pulling from the new remote.

**Comment by tiziano88** [comment]
cc
- @satnam6502 @blaxill for the https://github.com/project-oak/oak-hardware repository
- @hkim15 for the https://github.com/project-oak/hafnium-verification repository

**Comment by juliettepretot** [comment]
https://github.com/project-oak/hafnium-verification already appears to be using `hfo2` as the default branch. If desired we could also rename its `master` branch to something like `legacy`.

**Comment by tiziano88** [comment]
Ah cool, thanks for pointing out!

FYI, I have just made the GCB trigger work for both `main` and `master`: https://pantheon.corp.google.com/cloud-build/triggers/edit/16e67b67-cc42-4799-abf0-ad22b6c8559b?project=oak-ci (ACL'd)

@juliettepretot do you feel like figuring out what needs to change in the repository (cloud steps, scripts, etc.) before we can actually do the rename from the GitHub UI?

**Comment by tiziano88** [comment]
@juliettepretot also perhaps write down anything that developers / contributors should be aware of, and some migration steps for local workflows?

**Comment by juliettepretot** [comment]
@tiziano88 done :) 

https://github.com/project-oak/oak/pull/1157

**Comment by tiziano88** [comment]
I have finally completely removed `master` from our repo, thanks @juliettepretot and everyone else who supported this!
