### ISSUE TITLE
npm dependency

### ISSUE THREAD

**Issue by alastairreid** [project-oak/oak#1159]
Whilst building Oak on a fairly recently checked out cluster machine (not using Docker), I got the following error.

```
+ npm ci --prefix ./examples/hello_world/client/nodejs
./scripts/build_example: line 127: npm: command not found
```

Suggestion: mention 'sudo apt install npm' in build instructions.

**Comment by alastairreid** [comment]
(ps command that triggered error was './scripts/run_example -e hello_world')

**Comment by tiziano88** [comment]
Cc @juliettepretot

**Comment by tiziano88** [comment]
Though in general, if you are not using docker, you would have to install everything that the docker image contains

**Comment by juliettepretot** [comment]
I think there's two improvements that could potentially be made here:

1) I'm still a bit confused by how much documentation we write, whereas how much we want to just point people to the docker file. It seems people have different opinions here. But if we err on the side of docs, then I'm happy to add a line to install Node, now that it's used in an example alongside for formatting

2) We could consider changing the build scripts to only build server, which is shared across clients. The actual client would only be built if `run_example` is run with it explicitly. As we add more clients that may be sensible, and afaik it's the approach we take in the rust runner. 

cc @tiziano88 @daviddrysdale would appreciate your thoughts

**Comment by juliettepretot** [comment]
Specifying explicit built instructions could be sensible, or on the other hand consistently pointing to the docker file.

For example @alastairreid suggested the `sudo apt install npm` (presumably in combination with `sudo apt install node`). This really seems quite sensible, but unfortunately will install an outdated version of node, that could create issues down the road. 

Hence we install node from `deb.nodesource.com` in the dockerfile, but understandably people setting up their local environment may not be aware of that. 


At the moment we do a bit of both ("here's a few commands to get your started locally" AND "please follow the dockerfile exactly") which may not be the best combo. It seems going fully in either direction would be better.

**Comment by daviddrysdale** [comment]
Detailed instructions about specific tools and versions always tend to rot, so personally I prefer that we [defer detailed instructions](https://github.com/project-oak/oak/blob/master/docs/development.md#meta-advice) to something that's machine-readable and guaranteed to be up to date.

(There are exceptions; for example, I thought it worth explicitly flagging (#1111) the need for `musl-tools` because the error message you get when it's missing is very obscure).

**Comment by juliettepretot** [comment]
I agree with you, I think in our case sticking to maintaining the actual code is preferable. 

What I find a confusing in our case is that while having that approach we also maintain a fair amount of prose on getting started locally, which conveys the impression that we actually fully maintain that. 

Some rewording might help to point to the docker file might clearly, as well as prefixing our example commands with `./scripts/docker_run` to make it clear that that's the supported, batteries-included way of doing things. 

If people are cool with that I might author a PR updating the docs a bit later.

**Comment by alastairreid** [comment]
I think I agree with Juliette that the real problem is _too much_ documentation.
It may be useful to say "you will need Rust, nodejs, X, Y and Z" but including some actual commands to cut and paste made me think that those were all the commands resulting in bug reports from me in the hope of improving that documentation.
Just saying, "follow the steps in the Dockerfile" is probably the right approach.
Perhaps with suggestions that some step can be omitted if you don't need some feature or that some specific version number can probably be relaxed (at your own risk).
