### ISSUE TITLE
Investigate fuzz testing for Oak runtime

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1163]
https://rust-fuzz.github.io/book/introduction.html

cc @alastairreid

**Comment by alastairreid** [comment]
I wrote a summary of the four fuzzers that I know about [here](https://docs.google.com/document/d/19qGb0bQS1_h8b6ww-P7WU2SjLabpL0B1bNxft4VkU4M/edit?usp=sharing).

I don't think there is a clear winner at this stage - they all differ in terms of speed, flexibility, value in short term vs. value over the long haul.

**Comment by tiziano88** [comment]
Great summary! Should we start by picking an entry point to fuzz and use one of the tools in your doc? I think it will give us some direction towards future improvements in terms of tooling, fuzzing entry point, and corpus generation. Plus it would make us think about how to integrate it with CI, how to run locally, how it interacts with developer workflows etc.

**Comment by daviddrysdale** [comment]
I suspect that the coverage-guided inputs that [AFL](https://lcamtuf.coredump.cx/afl/)/[libFuzzer](https://llvm.org/docs/LibFuzzer.html) randomly generate are likely to mostly explore the Wasm engine we link in, and might take a very long time to reach any of the Oak Runtime code. 

So I wonder if something along the lines of [syzkaller](https://github.com/google/syzkaller) might be needed to reach and exercise the host functions that form the [Oak ABI](https://github.com/project-oak/oak/blob/main/docs/abi.md#host-functions). 

(However, setting something like that up is obviously a lot more effort than just plugging in an opaque-bytes fuzz target.)

**Comment by alastairreid** [comment]
Yes, that makes sense.

The example of [fuzzing a memory allocator](https://rust-fuzz.github.io/book/cargo-fuzz/structure-aware-fuzzing.html#example-2-fuzzing-allocator-api-calls) in the rust-fuzz book shows how we could consider fuzzing that ABI. (I think it is basically the same approach as syzkaller but with the benefit of Rust's type and macro system to make it easier).

And, if we wanted to fuzz the wasm engine, I suspect that this is best done separately from Oak - though it might be better to make sure that we pick a wasm engine that somebody else is already fuzzing/verifying.

**Comment by tiziano88** [comment]
FYI we already have an `oss-fuzz` entry for Project Oak, though it has been broken since we switched from C++ to Rust: https://github.com/google/oss-fuzz/blob/master/projects/oak/project.yaml
