### ISSUE TITLE
Verify Asylo remote attestation in Oak `ApplicationClient`

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#119]
Similar to #103, but at a lower level.
[NodeClient](https://github.com/project-oak/oak/blob/master/oak/client/node_client.h) must be configurable so that it can verify an attestation provided by Asylo.
See https://github.com/google/asylo/blob/master/asylo/identity/enclave_assertion_verifier.h

**Comment by tiziano88** [comment]
To start with, NodeClient may be configured so that it only accepts an SGX-based attestation with [`MRENCLAVE`](https://insujang.github.io/2017-10-09/intel-sgx-sealing/#mrenclave) set to a known measurement of the Oak VM. In the future, we should support verifying that `MRENCLAVE` is present in a verifiable append-only log containing valid measurements.

**Comment by tiziano88** [comment]
The public log should also contain any other information to verify that a known "good" version of SGX is running (e.g. recent security version number, SMT disabled, debug disabled, etc.)

**Comment by tiziano88** [comment]
I suggest starting off with a protobuf definition for an Oak root-of-trust; the goal is to bootstrap the entire verification process without relying on any external authority. So we should not assume the existence of any system-wide root CAs, ideally all the certs we trust should be explicitly listed in the configuration itself. Then based on those root CAs we could look up further certs in Certificate Transparency logs, or entries (e.g. binary hashes) in generic Trillian logs / maps.

**Comment by tiziano88** [comment]
Taking another step back (and various things have changed since I created this issue).

Currently this is how we create gRPC credentials on the client side:

https://github.com/project-oak/oak/blob/9a8875c39537651be5652efc7a325f2d9cf4c695/oak/client/application_client.h#L91-L107

Note that we are using `BidirectionalNullCredentialsOptions` which means no attestation is actually sent or verified.

As a first goal, we should modify that method so that it does not offer any identity, but it expects an SGX identity from the server, which in our case is a gRPC Node part of a larger Oak Application running in an enclave using Asylo.

It looks like Asylo now supports some of the primitives to express such assertions: https://github.com/google/asylo/tree/master/asylo/identity/sgx

**Comment by tiziano88** [comment]
For now, the API from the client point of view should be parametrised with the intel CA that is allowed to verify attestations (cert / public key, not sure how exactly that would work), and a value (for now hardcoded) of MRENCLAVE that we expect to see as part of the remote attestation report. Note that we would intentionally ignore MRSIGNER, since we only want to rely on code identity and not on the identity of whoever is deploying the enclaves.

ref https://software.intel.com/en-us/blogs/2016/05/04/introduction-to-intel-sgx-sealing

**Comment by ipetr0v** [comment]
Asylo has [definitions](https://github.com/google/asylo/blob/master/asylo/identity/descriptions.h) for several types of assertions:

 - `SetNullAssertionDescription`
 - `SetSgxLocalAssertionDescription`
 - `SetSgxRemoteAssertionDescription`

But it looks like only first two are implemented in a form of credentials:
- [null_credentials_options.cc](https://github.com/google/asylo/blob/master/asylo/grpc/auth/null_credentials_options.cc)
- [sgx_local_credentials_options.cc](https://github.com/google/asylo/blob/master/asylo/grpc/auth/sgx_local_credentials_options.cc)

Will try to make use of local SGX assertions.

**Comment by tiziano88** [comment]
Makes sense for now, but note that local attestation (same machine) is substantially simpler than remote attestation (separate machines), since it does not actually need a third party to provide the verification key: the client can just ask the CPU (which is the same as the other party, and can be trusted) to verify the attestation report directly. So, eventually only remote credentials will be useful, or at least I can't think of a use case for local credentials yet. Perhaps multiple oak applications talking to each other on the same machine could use local attestation between each other as an optimisation / shortcut.

**Comment by tiziano88** [comment]
I think the local attestation supported in Asylo covers MRENCLAVE via https://github.com/google/asylo/blob/befb2efc1aa2bf6cf6f2ced869182ee3ce921817/asylo/identity/sgx/code_identity.proto#L48 , so it should indeed be a good start for Oak, in that we can have the logic that verifies that MRENCLAVE and other parameters are what we expect. When Asylo supports remote attestation, we can just perform the same checks, but using the Intel remote attestation root of trust (certificate or public key).

**Comment by ipetr0v** [comment]
Since `asylo` server was [deleted](https://github.com/project-oak/oak/pull/713), should we close this issue?

**Comment by tiziano88** [comment]
Yes
