### ISSUE TITLE
Clarify inter-node communication (INC) model

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1192]
Currently we use the term "gRPC" to also talk about communication between nodes within the same application, where no "remote" call is happening, and certainly not over the gRPC protocol.

I suggest we name the communication mechanism between nodes Inter-Node Communication (INC) (similar to Inter-Process Communication (IPC)).

Each Node usually has a single type of Message that it handles as input:

https://github.com/project-oak/oak/blob/b8140736e7219cbbd369bfa5d6b4a4c7ed101c69/sdk/rust/oak/src/lib.rs#L461-L468

After https://github.com/project-oak/oak/pull/1108 this message may be defined in a proto file and include strongly typed handles that the node expects to receive.

I will add more details later, but if anyone has any thoughts, please reply here.

cc @project-oak/core @wildarch

**Comment by juliettepretot** [comment]
Good idea, and thanks for clarifying. I was a bit confused by whether nodes communicate with each other over gRPC.

**Comment by wildarch** [comment]
+1 for INC, if we mention the name in the docs and explain the distinction between INC and gRPC I think that should clear things up.

**Comment by tiziano88** [comment]
I wonder whether this means that basically all Nodes would just accept incoming messages of type `GrpcInvocation` (perhaps renamed to `OakNodeInvocation` or something else). Then they would decode the request to a more specific type as part of the Node logic (which may be autogenerated, as it currently is).

**Comment by tiziano88** [comment]
We would also need to generate corresponding client stubs to invoke a node from another node. (@wildarch I think you just proposed something along those lines in https://app.slack.com/client/TC007KHA8/CHE9E13C3/thread/CHE9E13C3-1593003638.448300 )

**Comment by tiziano88** [comment]
An alternative approach, which may avoid having to create stubs:

From a service definition, create strongly typed invocation messages. For instance:

https://github.com/project-oak/oak/blob/5f440585a84362be3beb2487103ac4bdeabd92dc/examples/hello_world/proto/hello_world.proto#L31-L37

may generate the following messages:

```protobuf
message SayHelloInvocation {
  oak.handle.Receiver request = 1 [ (oak.handle.message_type) = "HelloRequest" ];
  oak.handle.Sender response = 2 [ (oak.handle.message_type) = "HelloResponse" ];
}

message LotsOfRepliesInvocation {
  oak.handle.Receiver request = 1 [ (oak.handle.message_type) = "HelloRequest" ];
  oak.handle.Sender responses = 2 [ (oak.handle.message_type) = "HelloResponse" ];
}

...

message SayHelloInvocation {
  oneof {
    SayHelloInvocation say_hello = 1;
    LotsOfRepliesInvocation lots_of_replies = 2;
    ...
  }
}
```

In this model, there is no extra code to generate (though some additional code generation may make things even more ergonomic to use)

**Comment by tiziano88** [comment]
A downside of the message generation approach is that it relies on the order of the methods in the service definition (so reordering methods would be a breaking change in terms of the generated API for the Node).
