### ISSUE TITLE
Build Docker images without Bazel

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1215]
We currently build Docker images via Bazel, but this makes less and less sense, especially since none of the dependencies actually use Bazel any more (neither `oak_loader`, nor the application configuration).

Also we should try and have a representative example that someone not familiar with Oak would be able to understand and modify, and I doubt there are many developers out there who use Bazel to build Docker images in the first place.

We should probably stick to a regular Dockerfile, with `COPY` instructions for the `oak_loader` and application configuration file.

https://github.com/project-oak/oak/blob/08c6a6048e55e5ee6435d992bb1577ec7625ccd0/examples/aggregator/server/BUILD#L32-L44

cc @anghelcovici @ipetr0v

**Comment by ipetr0v** [comment]
Agree, most of the people just used to work with Dockerfiles.
