### ISSUE TITLE
allow `node_create` to refer to entrypoints in the same module as the caller

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1222]
Currently `node_create` requires the fully qualified entrypoint name (module name + exported function name), but in cases in which a node is creating another node from the same module, it still needs to know its own name within the oak application.

It would be simpler if `node_create` allows specifying an empty or special (e.g. `self`) value for the module name in order to refer to the same module as the caller, and it would make multi-entrypoint modules more portable across applications.

**Comment by ipetr0v** [comment]
Where is it using a fully qualified name?
IIUC here it just uses an exported function name:
https://github.com/project-oak/oak/blob/39e0dbb55593d67e45511efdb5727cd2fc80423d/oak/server/rust/oak_runtime/src/node/wasm/mod.rs#L812
And here it runs Wasm using this function (and doesn't use the module name):
https://github.com/project-oak/oak/blob/39e0dbb55593d67e45511efdb5727cd2fc80423d/oak/server/rust/oak_runtime/src/node/wasm/mod.rs#L872-L876

**Comment by tiziano88** [comment]
I meant "fully qualified" in the context of an Oak application, i.e. oak module name + exported function name.

**Comment by tiziano88** [comment]
My suggestion is to allow invoking an entry point in the same module, omitting the Oak module name
