### ISSUE TITLE
Make `runner` show a summary of failed steps at the end of the execution

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1234]
I think it is great that this command runs all the steps even if something fails in between. 
I suggest logging a summary of the failures or the list of failed steps in the end, so that one does not have to go through the entire log to locate the problem.

_Originally posted by @rbehjati in https://github.com/project-oak/oak/pull/1190_

**Comment by ipetr0v** [comment]
Should it only apply to `run_ci`?
If so, we need to also add a `name` for each `Step`.

**Comment by ipetr0v** [comment]
Adding a PR https://github.com/project-oak/oak/pull/1286.
Error summary in the end will look like an exact list of failed steps:
```
Finished with errors:
 ❯ examples ❯ hello_world ❯ build application ⊢ [ERROR]
```
