### ISSUE TITLE
allow running the C++ hello world module with `runner`

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1250]
After https://github.com/project-oak/oak/pull/1190 is submitted, the hello world example is only run in its Rust variant (though the C++ variant is built). In order to support running the C++ variant too, we should either create a separate manifest file, and treat it as a separate example, or extend the manifest format to support multiple application variants for each example.

**Comment by ipetr0v** [comment]
Why do we need a separate manifest file? And what kind of file?
If it's about a `.toml` file with an application configuration, then we already have separate files for Rust and CPP:
https://github.com/project-oak/oak/blob/120484391822adf383695f1312bada02d8d0be12/examples/hello_world/config/config.toml#L1-L5
https://github.com/project-oak/oak/blob/120484391822adf383695f1312bada02d8d0be12/examples/hello_world/config/config_cpp.toml#L1-L4

**Comment by ipetr0v** [comment]
Got it, this is the manifest file:
https://github.com/project-oak/oak/blob/120484391822adf383695f1312bada02d8d0be12/examples/hello_world/example.toml#L3-L5
