### ISSUE TITLE
[runner] coverage mode should be a server type instead of an extra bool

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1251]
https://github.com/project-oak/oak/blob/c099895766237fcebf24aae2886d6be2dbe2052a/runner/src/main.rs#L307-L316

currently we can specify the server type as `base` or `logless`, and we have a separate bool to control whether to build it in coverage mode. It may make sense to just treat the coverage-based version of the server as another server type instead.

cc @daviddrysdale

**Comment by ipetr0v** [comment]
If it will be a separate server type, should it be built as `base` or as `logless`?
