### ISSUE TITLE
[runner] run binaries directly instead of via `cargo run`

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1252]
https://github.com/project-oak/oak/blob/c099895766237fcebf24aae2886d6be2dbe2052a/runner/src/main.rs#L441-L461

we use `cargo run` and `bazel run` in a few places in scripts and in the runner, as a convenience for getting things up and running quickly. This is not necessarily representative of how those binaries will be used in practice (e.g. we still need to invoke the binary itself from the docker image). Also by using `cargo run`, a single step is really doing two things: building and then running the binary, which means that if we just `cargo run` the server, it may take anywhere between a couple of seconds to several minutes for the server to actually start, based on whether the build step was cached.

cc @ipetr0v

**Comment by ipetr0v** [comment]
We used `readonly SERVER_BIN_DIR="${PWD}/oak/server/bin"` in shell scripts:
https://github.com/project-oak/oak/blob/d1e6497e73223afe46ddd9f3618f971bac1b5205/scripts/build_server#L37-L39
https://github.com/project-oak/oak/blob/d1e6497e73223afe46ddd9f3618f971bac1b5205/scripts/run_server#L90-L91

Will add the same this to `runner`.

**Comment by ipetr0v** [comment]
We also are currently copying artifacts to `bin` directory:
https://github.com/project-oak/oak/blob/c099895766237fcebf24aae2886d6be2dbe2052a/runner/src/main.rs#L266-L284

Should we use `out-dir` (it's unstable)?

**Comment by tiziano88** [comment]
`out-dir` looks reasonable, and I think we already use it somewhere? Or maybe it was just in the previous scripts?

**Comment by ipetr0v** [comment]
Yes, it was in `build_server`.
