### ISSUE TITLE
investigate deploying oak applications to Google Cloud Run

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1253]
I had not noticed this before, but [Google Cloud Run](https://cloud.google.com/run) may be what we need to get something up and running for a demo or even some dogfood version of an oak application.

I have already created a test instance, though the container that I selected (the aggregator app) obviously fails to start because of missing flags: https://pantheon.corp.google.com/run/detail/europe-west1/test/metrics?project=oak-ci

AFAICT cloud Run handles TLS termination, which means we may need to add an option to the oak loader to accept HTTP (plaintext) connections, so that it can be run on Cloud Run / App Engine. Also I think it expects the container to listen on the port that is provided in the `$port` env variable (so we would have to find a way of passing that as a flag or as part of a config map).

This would obviously not use any sort of remote attestation, not even the vTPM one (#684 )

@conradgrobler @rbehjati it may be worth looking into this, at least to see if it's something we may be interested in, and if so, then make the necessary changes to the oak loader binary.

**Comment by tiziano88** [comment]
FYI I just deployed a test container, and indeed it got a auto-generated URL assigned to it: https://test-62sa4xcfia-ew.a.run.app/

**Comment by rbehjati** [comment]
Without having looked at Google Cloud Run, how is it different from or bette than the GKE + ESP solution that we already have? I suppose the oak loader option would work with that too.

**Comment by tiziano88** [comment]
From what I can tell, the advantage seems that it is decidedly simpler to deploy (you don't need an entire cluster, just a single docker image, and it scales it automatically), and it does TLS termination with a proper domain (which makes us get up to speed quickly for demo / examples). I think it would be a simple way for people interested in Oak to get things up and running "in the cloud".

OTOH, I don't think it will work at all with remote attestation, even TPM-based ones, so it is probably only good for first party use cases (which anyways is fine for us for now).

**Comment by ipetr0v** [comment]
IIUC Cloud Run applications need to be stateless (cannot rely on a persistent local state). So the service must not perform background activities outside the scope of request handling.
(Code Requirements)[https://cloud.google.com/run/docs/developing#code_requirements]
