### ISSUE TITLE
Check whether LGPL license is OK to use in the runner

### ISSUE THREAD

**Issue by conradgrobler** [project-oak/oak#1266]
The `runner` has a dependency on the `spinner` crate which is LGPL licensed. LGPL is sometimes considered a problematic license due to mandatory source distribution requirements. It is probably OK in the runner as the source is any distributed, but could be more problematic in e.g. the SDK.

**Comment by tiziano88** [comment]
Out of curiosity, why did cargo deny not stop this?

**Comment by conradgrobler** [comment]
It only warns about copyleft licenses. I am in the process of changing that so that these are denied unless explicitly allowed.

**Comment by conradgrobler** [comment]
This is no longer an issue after #1596 removed the dependency.
