### ISSUE TITLE
Use a single shared tokio runtime 

### ISSUE THREAD

**Issue by rbehjati** [project-oak/oak#1280]
Currently we create multiple tokio runtimes in an Oak application. Ideally, there should be just one shared tokio runtime (perhaps as a field on the Oak runtime) that can be used by any server pseudo node, or auxiliary server that needs to spawn things.

Ref: [Comment on #1261](https://github.com/project-oak/oak/pull/1261#discussion_r457948716), #1186

**Comment by tiziano88** [comment]
Even better, make the Oak Runtime properly async, and just create a single runtime in main.
