### ISSUE TITLE
${HOME} is evaluated to the empty string

### ISSUE THREAD

**Issue by fshaked** [project-oak/oak#1282]
In the following line, ${HOME} is interpreted as a Docker argument, not a shell variable, and so it's the empty string. I don't know if this is intentional.
https://github.com/project-oak/oak/blob/6b349bf6db0c543c4fe7c7bd807028efbf1c4e6f/Dockerfile#L110

**Comment by tiziano88** [comment]
From what I can tell, the syntax is correct, i.e. that should expand to the env variable, if one is set. How does the error manifest itself for you? Does building the image fail?

**Comment by fshaked** [comment]
No error, just doesn't look right as there are no ```ARG HOME``` or ```ENV HOME ...``` statements in the file.

**Comment by tiziano88** [comment]
I would have guessed that `HOME` is defined in the base image that we extend, though I have not checked directly.
