### ISSUE TITLE
Mixing of implicit ipv4 and explicit ipv6 in oak_loader and examples code

### ISSUE THREAD

**Issue by ebeasant-arm** [project-oak/oak#1314]
The example servers open three ports: `oak_loader` opens 1909 and 9090 using the URI `localhost:<port number>`, but then the example opens the gRPC server port 8080 using `grpc::server::init([::]:8080)`.
The example clients connect to `localhost:8080`.

The result is that the two monitoring ports (introspection) for the `oak_loader` are opened using ipv4 as default, then the configuration/application opens the main port using ipv6.

This currently works due to the test systems all supporting ipv6: more restricted platforms will have issues.   
In any case, consistency between the port bindings would seem to be A Good Thing (principle of least suprise :-)
```
<sample output from netstat -ln>
tcp    0   0 127.0.0.1:35979     0.0.0.0:*        LISTEN   
tcp    0   0 0.0.0.0:6001      0.0.0.0:*        LISTEN   
tcp    0   0 127.0.0.1:1909     0.0.0.0:*        LISTEN   
tcp    0   0 127.0.0.53:53      0.0.0.0:*        LISTEN   
tcp    0   0 0.0.0.0:22       0.0.0.0:*        LISTEN   
tcp    0   0 127.0.0.1:631      0.0.0.0:*        LISTEN   
tcp    0   0 0.0.0.0:31416      0.0.0.0:*        LISTEN   
tcp6    0   0 ::1:42093        :::*          LISTEN   
tcp6    0   0 :::8080         :::*          LISTEN   
tcp6    0   0 :::6001         :::*          LISTEN   
tcp6    0   0 :::22          :::*          LISTEN   
tcp6    0   0 ::1:631         :::*          LISTEN
```

**Comment by tiziano88** [comment]
@ipetr0v could you take a look? I think it's just a matter or replacing `localhost` with `[::]` in a few places or something along those lines?

**Comment by ipetr0v** [comment]
Sure, I'll take a look.
