### ISSUE TITLE
Upgrade Rust version to 1.36.0

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#134]
https://github.com/project-oak/oak/blob/8006ba7014cfbdb28511053958a82217260d9a5c/Dockerfile#L27

**Comment by Atul9** [comment]
Hi @tiziano88 is this the only change to be made?

**Comment by tiziano88** [comment]
In principle yes, but IIRC when I tried that something (I don't remember what) was failing so I had to postpone it. If you can make CI happy, that should be all we need. :)

**Comment by hansman** [comment]
Rust 1.36.0 introduces a package cache lock file that needs to be read/write. 
https://github.com/rust-lang/cargo/pull/6880/files#diff-4559bc8f75ebf0a4d42be6e4e7fe9eaaR856
