### ISSUE TITLE
TLS certificate for HTTP server pseudo-node

### ISSUE THREAD

**Issue by rbehjati** [project-oak/oak#1345]
HTTP server pseudo-node should be modified to allow only secure connections using TLS.

**Comment by rbehjati** [comment]
@tiziano88 @conradgrobler @ipetr0v Currently Oak loader takes input arguments for `--grpc-tls-private-key` and `--grpc-tls-certificate`. Does it makes sense to use the same certificates for HTTP server nodes too, for applications that have both Grpc and Http server nodes?

**Comment by conradgrobler** [comment]
I think in most cases it would use the same certificate, but there might be cases where the gRPC and HTTP servers run with different domain names that have different certificates, so it should be possible to provide separate certificates.

**Comment by tiziano88** [comment]
Short-term, perhaps it makes sense to have separate flags for the two kinds of certificates.

Long-term I don't think either gRPC or HTTP certificates should be flags of `oak_loader` itself. Rather, they should be passed as extra configuration parameters (via ConfigMap) to the specific Oak application, and then passed to the newly created gRPC or HTTP server pseudo nodes. Then again this may actually complicate things if / when we actually have remote attestation primitives in place. It would be good to keep that use case in mind though.

**Comment by rbehjati** [comment]
I'll keep them separate for now. And I'll make both sets of flags optional.
