### ISSUE TITLE
use standard `http` types in implementation of HTTP server pseudo node helpers in the SDK

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1348]
see https://docs.rs/http/0.2.1/http/

we should at a minimum replicate a similar structure in the proto definition, and provide methods to convert to / from them.

**Comment by tiziano88** [comment]
@rbehjati I believe you have already implemented this, right?

**Comment by rbehjati** [comment]
Yes. It is fixed in https://github.com/project-oak/oak/pull/1528.

**Comment by rbehjati** [comment]
Fixed in #1528.
