### ISSUE TITLE
Rust runner hardcodes the Rust backend target for examples.

### ISSUE THREAD

**Issue by ebeasant-arm** [project-oak/oak#1349]
Whilst it is possible to override the server build target and toolchain using commandline options, the target for the examples is always set to the DEFAULT_EXAMPLE_BACKEND_RUST_TARGET :
This is incorrect for non-x86 targets: It would be useful (and simple?) to follow the pattern of the server-rust-target option, and allow for command line override of the example targets, or to assume that unless it is explicitly overriden, to use the server_rust_target value?

https://github.com/project-oak/oak/blob/d723ac29ac073c8a52ca6e65f4880e838d98f83d/runner/src/main.rs#L768

**Comment by ebeasant-arm** [comment]
(Assign it to me, if possible please :-)

**Comment by ebeasant-arm** [comment]
I'm looking at using Target:: to carry appropriate options for the Cargo target for both server and client: Any objections or suggestions in this area? :-)

**Comment by tiziano88** [comment]
What do you mean with "using Target::" exactly?

**Comment by ebeasant-arm** [comment]
I was looking at using the example manifest to supply target-type information, but decided that it was not in line with the current approaches - I'm going back to the original idea of making the client and server build options more symmetrical. This seems to make more sense as more rust examples seem to be a possibility?

**Comment by ebeasant-arm** [comment]
Closed as PR 1345 has been merged.
