### ISSUE TITLE
gRPC services for Oak applications are (silently) required to be in `oak.` namespace

### ISSUE THREAD

**Issue by daviddrysdale** [project-oak/oak#1361]
The [implementation](https://github.com/project-oak/oak/blob/81861ed03c863894d15ea2a6ed569a508955ed49/oak/server/rust/oak_runtime/src/node/grpc/server/mod.rs#L258-L261) of the [`tonic::transport::server::NamedService` trait](https://docs.rs/tonic/0.3.0/tonic/transport/server/trait.NamedService.html) for the gRPC server pseudo-Node will only match method invocations where the first part of the full method name is "oak":
```Rust
/// Set a mandatory prefix for all gRPC requests processed by a gRPC pseudo-Node.
impl NamedService for HttpRequestHandler {
    const NAME: &'static str = "oak";
}
```

This isn't documented anywhere, so is a bit of a trap for the first application developer who uses a different proto package name.

**Comment by tiziano88** [comment]
I thought that's only for requests that are meant to be handled directly by the Oak Runtime, e.g. authentication. @conradgrobler could you confirm?

**Comment by conradgrobler** [comment]
No, this is not for the authentication. I believe this was there before I added the OIDC authentication service. @ipetr0v do you have any insight on why this is "oak" rather than ""?

**Comment by daviddrysdale** [comment]
(BTW, a `NAME` of `""` does seem to work with a proto package name like `examples.translator`)

**Comment by ipetr0v** [comment]
Yes, I think I added it, because `""` didn't work (so it was mandatory).

**Comment by tiziano88** [comment]
@ipetr0v if it's not necessary any more, could it be removed now?
