### ISSUE TITLE
Add a signature lookup trait

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#1379]
After finishing https://github.com/project-oak/oak/pull/1312 we need to add a lookup function (or trait) that given the module hash, returns potential signatures (and could potentially download them from the Internet).

Originated from https://github.com/project-oak/oak/pull/1312/files#r472939756

**Comment by ipetr0v** [comment]
Following up the https://github.com/project-oak/oak/pull/1312/files#r472939756: why do we need to implement a trait for downloading signatures from the Web in `oak_runtime`, when we can just do it in `oak_loader` once it has been passed a `--signature-manifest=...` file?

cc @tiziano88

**Comment by tiziano88** [comment]
In general, the signatures may not be available as a single file, they may be in a remote database or a verifiable log or some other mechanism. Having a trait for the lookup seems the correct abstraction to me, but there may be other options that work too. What are you suggesting exactly @ipetr0v ?

**Comment by ipetr0v** [comment]
First I thought that the simplest way would be just a `match` in `oak_loader`. It reads a `.toml` file that contains a vector of enums (`path`, `url`, `ver_log_uri` etc.), and just loads corresponding signatures (and verifies them immediately).

The reason is to load and check signatures before `oak_runtime` has started, because otherwise it will not be obvious when signatures are checked against Wasm modules, and why we are not checking them immediately and delaying this check into the `oak_runtime`.

**Comment by tiziano88** [comment]
I see your point now.

It's fine for oak_loader to resolve all the available signatures for all the available modules at startup (though in the future we may want to make this lazier too, if the signatures are too many). But I still think it's useful to have a trait that abstracts over this lookup from hash to signatures, even if it gets used only in oak_loader. And initially it is implemented by looking things up via the provided files, while in the future it may look things up over the internet, if necessary.

WDYT?
