### ISSUE TITLE
Make detection of cargo workspaces more robust in runner

### ISSUE THREAD

**Issue by conradgrobler** [project-oak/oak#1389]
The runner uses pattern matching logic on the content of files to detect `Cargo.toml` files that represent the roots of workspaces. https://github.com/project-oak/oak/blob/d1a8b34e44aef6437bc8cccc3d2be15af6a7f6e4/runner/src/main.rs#L977-L980

These are used for running cargo test, cargo clippy, cargo deny, and cargo fmt. If the pattern-matching logic misses a file, the CI does not cover the workspace any more.

**Comment by conradgrobler** [comment]
I think it would be useful to add a separate list of workspace files and compare the detection logic and the list as part of CI.

Another option is to have a list of non-workspace files. If a Cargo.toml file is not on the list, it should be treated as a workspace to ensure we catch all new crates in CI. It might be a good idea to fail CI if a `Cargo.toml` file is not on the list but also does not contain `[workspace]`.

**Comment by tiziano88** [comment]
Is there really much of an advantage (in terms of time) in running tests for the entire workspace vs individual crates?

**Comment by conradgrobler** [comment]
I don't know. I will do some tests and see.

**Comment by conradgrobler** [comment]
The version that runs only on workspace files took 1519s to complete on my workstation.

The version that runs for all `Cargo.toml` files took 1905s to complete. In the cloudbuild environment I think it will probably add about 10-12 minutes to the CI. I think the main contribution is that it ran all the example integration tests twice (once for the example's `Cargo.toml` and once for the workspace `Cargo.toml`) and the abitest integration tests are slow.

Another issue is that it causes `cargo deny` to emit many warnings. We would need to add a deny.toml per example to stop these, which is not great from a maintenance point of view.

There are a few other options:

- Build a tree of the directory structure and treat all `Cargo.toml` files that do not have an ancestor directory containing `Cargo.toml` as also being workspace files even if they don't contain the pattern (and possibly treating this as an error)
- Run cargo deny only on directories that contain a `deny.toml` file (but there is a risk that we forget to add a `deny.toml` for a new crate and then it is skipped)

**Comment by tiziano88** [comment]
> The version that runs for all Cargo.toml files took 1905s to complete.

Did this run things twice, once for workspace and then again for non-workspace Cargo.toml, in case they overlap? The comparison I was suggesting was running everything **except** the workspace files, basically only the leaf Cargo.toml files.

**Comment by conradgrobler** [comment]
It did run some things twice. I only did a quick test. Implementing the suggested test is a bit more complicated, as many of our `Cargo.toml` files are both leaves and workspace files, so it is not just a case of inverting the logic. This should speed up the process, but will probably still be a bit slower (it seems to create a `target` output directory for each example module, and perhaps seems to rebuild the SDK every time?).

This will also not resolve the `cargo deny` warnings. If we have to build a graph of `Cargo.toml` files to find the leaves, we can just as well use the same graph to find the roots and run it only for the roots, which should be slightly faster and resolve the `cargo deny` warnings.

**Comment by tiziano88** [comment]
Maybe `cargo metadata` or some other command may be used to detect whether a crate is stand-alone or part of a workspace?

**Comment by conradgrobler** [comment]
I faked the option of running the CI only on leaf Cargo.toml files by deleting `[workspace]` from all the leaves that are also workspaces and inverting the logic. It took 1785s to run, which is slower that I thought it would be. This probably translates to about 5-6 minutes extra for CI in the cloudbuild environment.

It looks like `cargo metadata` should work. We can run it against all Cargo.toml files and build a set of unique workspace root paths.
