### ISSUE TITLE
Common server builder for HTTP and gRPC server pseudo-nodes

### ISSUE THREAD

**Issue by rbehjati** [project-oak/oak#1390]
Currently there is some duplication in the code for building HTTP and gRPC server pseudo-node. 
This duplication should be removed, and a unified set of classes and functions should be used for creating both types of server pseudo-nodes. This will be a low-level server builder with support for 
- [configuring TLS](https://github.com/project-oak/oak/pull/1370)
- [challenge-response style authentication](https://github.com/project-oak/oak/issues/1357#issuecomment-674883678)
- [channel-level invocations](https://github.com/project-oak/oak/pull/1261#discussion_r455857852)

Ideally, we'll have builders that allow to declaratively configuring and building a server pseudo-node.

**Comment by tiziano88** [comment]
My suggestion was (and still is) that there really shoud be no gRPC pseudo-node at all. The gRPC logic would be contained in the application logic (using helpers from the SDK), but only using the HTTP pseudo-node.

**Comment by rbehjati** [comment]
Do you mean something like the ServerNode in SDK?

**Comment by tiziano88** [comment]
Not sure, I just meant that we would have a layer in the SDK that "converts" between gRPC and HTTP (since there is not much to convert anyways).
