### ISSUE TITLE
Deduplicate testdata directory

### ISSUE THREAD

**Issue by conradgrobler** [project-oak/oak#1393]
There seems to be duplicate versions of the WASM test data:

- https://github.com/project-oak/oak/tree/main/oak/server/testdata
- https://github.com/project-oak/oak/tree/main/oak_runtime/testdata

I assume https://github.com/project-oak/oak/tree/main/oak_runtime/testdata is the correct new one and https://github.com/project-oak/oak/tree/main/oak/server/testdata is an old copy that should be deleted.

@tiziano88 can you confirm?

**Comment by tiziano88** [comment]
Ah good catch, yes the one under `oak_runtime` should be the only one, it was either a race condition between PRs, or my mistake when rebasing my own commits. Thanks for looking into it!
