### ISSUE TITLE
Bazelify V8: Link V8 engine in Bazel builds.

### ISSUE THREAD

**Issue by hansman** [project-oak/oak#140]
In preparation of https://github.com/project-oak/oak/issues/74 and https://github.com/project-oak/oak/issues/126 we want to link V8 so that it can be included in Bazel BUILD files as dependency.

**Comment by hansman** [comment]
DRAFT commit includes compiled Chrome V8 sources in docker image and links them in Bazel WORKSPACE as `new_local_repository`:   https://github.com/hansman/oak/commit/5d327073ba72cf9b48bbf47ab45d809ef011cf23#diff-09498dbadf45966909850dc8a47ebb13R85

**Comment by tiziano88** [comment]
Hey @hansman , thanks for putting this together! It seems that @ofrobots has already done some of the V8 Bazel-ification work in https://github.com/ofrobots/no-bazel/blob/master/v8.BUILD.bazel .

@ofrobots do you have any thoughts / suggestions about this?

**Comment by ofrobots** [comment]
I was doing the bazelification of the V8 build for an experiment. I am no longer maintaining it, but feel free to use it as a starting point. One challenge would be the busy work needed to keep things functional as upstream GN build file changes. In an ideal world, it would be good to have a tool that does the conversion automatically; or convince upstream to switch to bazel :upside_down_face: .

**Comment by hansman** [comment]
Thanks for sharing @ofrobots! This must have taken you some time to put together. This is awesome!

Maintaining the V8 dependency can be costly in case we want to upgrade to a different V8 version along the way. Is this what you mean with keeping things functional with regards to `BUILD.gn` changes? I guess this is a risk/cost we want to evaluate as we learn how to bazelify V8 @tiziano88 .

I tried running the project and got into some problems on target `@v8//:core_lib`. One thing that seems missing are generated sources referenced as `builtins-generated/*` (https://github.com/ofrobots/no-bazel/blob/master/third_party/v8/BUILD.gn#L1528). It seems some are generated with a python script. Do you know more about how to generate missing source files @ofrobots?

https://github.com/ofrobots/no-bazel/blob/f7eb147044dc35aac86df8bd9bec2cc55863ce17/third_party/v8/BUILD.gn#L996-L1012

**Comment by ofrobots** [comment]
> Maintaining the V8 dependency can be costly in case we want to upgrade to a different V8 version along the way. Is this what you mean with keeping things functional with regards to BUILD.gn changes?

Yes. The V8 build uses lots of tools that generate source files (e.g. the bytecode builtins that you pointed out). In my experience these parts are expensive to update on V8 version upgrades.
