### ISSUE TITLE
Implement support in the SDK for finding the Label associated with a channel

### ISSUE THREAD

**Issue by conradgrobler** [project-oak/oak#1406]
To support a router pattern, where a node routes channels and invocations to specific nodes based on the associated labels, we need to provide a mechanism in the ABI and SDK for looking up the label associated with a channel.

**Comment by ipetr0v** [comment]
> node routes channels and invocations to specific nodes based on the associated labels
Should it choose a destination node based on the incoming data label?
What if multiple nodes have corresponding labels?

**Comment by conradgrobler** [comment]
The typical scenario where the router is needed is for per-user nodes. The router should know which user the data is intended for, and either create a new node with that label if it doesn't exist, or send the data to the right node if it does exist. At the moment the router node cannot tell which user the data is from. This is a prerequisite for #1407.

In cases where multiple nodes have the same label, the router would need to have some additional logic to make the decision (e.g. perhaps round-robin load balancing), but would still need to know which label is associated with the data.

**Comment by ipetr0v** [comment]
I think such hidden logic may not be obvious for clients and application developers, since Oak will choose which node to set as a destination based on some additional logic.

I think, if we want to create per user nodes:
- We either might do something similar to [AWS Lambda](https://aws.amazon.com/lambda/), where nodes are created per each client request, and router doesn't need to route requests to a specific existing (per-client) node, it will just create a new one every time
- Or we can add a `node_id` as a part of the request, if we want to create a per-client node once and reuse it afterwards

**Comment by conradgrobler** [comment]
If we move to a different model of node creation we can add logic to the gRPC server node to create new nodes, but with our current implementation all gRPC invocations are sent down a single channel. The node receiving this will have to create the per-user nodes and foward the invocations.

It most cases the node can just create a new node for every request and not worry about reusing nodes, but it still needs to know which label to set on the newly created node to maintain the right security.

**Comment by ipetr0v** [comment]
> but it still needs to know which label to set on the newly created node to maintain the right security.

Why do we need to add a label to a newly created node?
If this node won't have a label, it will not be able to declassify the client data, and only be able to send it back to the original client. IIUC this is the intended behavior.

**Comment by conradgrobler** [comment]
If the node has no label, there is nothing stopping it from creating another node (such as a gRPC client or log node) and sending the data outside of Oak.

**Comment by conradgrobler** [comment]
To be more precise: a node with no label is public. It will not be able to read the data if it comes from the client with a client-specific labe without the data being declassified by something else. The IFC system will stop a public node from reading from a channel with a non-public label. If the channel ahs a public label, the data is public and the node can then send it anywhere.

**Comment by ipetr0v** [comment]
I thought that (in the case of this example) the data supposed to have a `token(client_1)` label, and thus it cannot be sent to any other client than `client_1` by any node.

**Comment by conradgrobler** [comment]
I tried to clarify in the earlier follow-up response. If the data has label `token(client_1)`, only nodes with labels at least as secret as `token(client_1)` will be able to read the data.

**Comment by tiziano88** [comment]
> > If the node has no label, there is nothing stopping it from creating another node (such as a gRPC client or log node) and sending the data outside of Oak.
> 
> I thought that (in the case of this example) the data supposed to have a `token(client_1)` label, and thus it cannot be sent to any other client than `client_1` by any node.

Correct, therefore it cannot be sent to a node with a public (i.e. empty) label, as @conradgrobler mentioned, right?

**Comment by tiziano88** [comment]
> I think such hidden logic may not be obvious for clients and application developers, since Oak will choose which node to set as a destination based on some additional logic.
> And if there are multiple nodes that can handle the incoming label, developers will need to have a very clear understanding of the underlying mechanism in order to predict what would happen.

Label have a precise meaning, in particular confidentiality labels represent who / what can declassify the labelled data. They are not just pieces of a puzzle (although from an Oak application developer's point of view they also have this aspect).

Like encrypting data with a key, and making that key available to another party; the point is not to get a key that works for the encryption, is to make sure that you use a key that the desired other parties have access to, and no others.

The point of Oak is that, no matter what the application developer does, the fundamental assumptions about labels are not violated, i.e. the IFC system must be **sound**, no matter what the structure of the application is.

**Comment by conradgrobler** [comment]
Description of the expected ABI interface specified in #1137
