### ISSUE TITLE
New example: rustfmt

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#141]
Create a new example that runs the [rustfmt](https://github.com/rust-lang/rustfmt) formatter in an Oak Node, and a sample client that sends a string containing a snippet of Rust code and gets back its formatted version.

**Comment by hansman** [comment]
It looks like `rustfmt` can't be compiled for a webassembly target as is. Some of its [dependencies](https://deps.rs/crate/rustfmt/0.10.0) (i.e. syntex_errors#0.59.1) use features that are not implemented for webassembly.

https://github.com/rust-lang/rust/issues/48304
