### ISSUE TITLE
Set the user's identity as the confidentiality tag in invocation channels for HTTP and gRPC server nodes

### ISSUE THREAD

**Issue by rbehjati** [project-oak/oak#1428]
Each incoming gRPC/HTTP invocation is represented by a message containing two Channel handles: a "request receiver" and a "response sender". 

Currently the "response sender" gets the public_untrusted label. However, as explained in the [docs](https://github.com/project-oak/oak/blob/main/docs/concepts.md#grpc-and-user-labels), it should have a confidentiality component that is set based on the identity of the user. This is needed to avoid any accidental data leaks.

**Comment by tiziano88** [comment]
@rbehjati I believe your changes already fix this, so assigning to you, but let me know if that's not the case.

**Comment by rbehjati** [comment]
Yes. But partially. I'll update the description here, and can create a separate issue to track setting the user identity as the integrity label. Do we have a top-level issue for integrity labels?

**Comment by rbehjati** [comment]
Closing this now, but the work on identity-related integrity labels is going to be part of IFC v1, and #1715.
