### ISSUE TITLE
running examples twice in a row with no modifications results in the introspection client code and the oak loader binary being recompiled

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1456]
To reproduce, run the following command from docker:

```bash
./scripts/runner --logs run-examples --example-name=http_server
```

(or any other example)

then run it again immediately after.

Observed: `build introspection browser client` and `build server` steps are re-run, taking up to a few minutes every time

Expected: these steps should be instantaneous since everything should still be cached

@juliettepretot could you look into it? perhaps there is some flag to make sure that the compilation of those assets only happens when they changed?

**Comment by juliettepretot** [comment]
thx for reporting, will investigate

**Comment by juliettepretot** [comment]
There isn't a build in flag to do this, but will try to write small script that handles this.

**Comment by tiziano88** [comment]
Are the output files deterministic at least? Or does their contents change? I guess either way, `include_bytes` will think they have been updated, even if only the timestamp is different, right?

**Comment by juliettepretot** [comment]
Yes they should be deterministic. What happens right now is that we build client files _every time_, since Webpack & NPM offer no build in cache. Since they are rebuilt every-time. Pretty sure that `include_bytes` indeed only checks the timestamp.

Either way we probs want to skip building the client if its source has not changed, since that itself takes around 15s on my machine.

**Comment by juliettepretot** [comment]
Fixed the issue of cargo rebuilding the `oak_loader` in #1487. 
Reduced the time spent on building introspection assets from ~40s to ~4s with webpack caching. 

I could probably cache building introspection assets even more aggressively (bringing it down to <1s by skipping webpack altogether if source files did not change), but the maintenance cost might not be worth it. 

@tiziano88 Can I close this issue?

**Comment by tiziano88** [comment]
Yeah I think the current state of things looks good, thanks!

**Comment by juliettepretot** [comment]
Cool beans, closing this then :)
