### ISSUE TITLE
Use idiomatic types to represent HTTP requests in SDK

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1459]
e.g. https://docs.rs/http/0.2.1/http/request/struct.Request.html

cc @rbehjati

**Comment by rbehjati** [comment]
Can you please be more specific?

**Comment by tiziano88** [comment]
Currently, HTTP requests and responses are represented as a protobuf objects in the SDK:

https://github.com/project-oak/oak/blob/79de881763b06e83a00e80aeba740978ebd0949e/oak_services/proto/http_encap.proto#L21-L31

https://github.com/project-oak/oak/blob/79de881763b06e83a00e80aeba740978ebd0949e/oak_services/proto/http_encap.proto#L33-L41

For convenience / familiarity / compatibility with other libraries and frameworks, we should expose more idiomatic types for them instead, e.g.:

https://docs.rs/http/0.2.1/http/request/struct.Request.html

https://docs.rs/http/0.2.1/http/response/struct.Response.html

**Comment by conradgrobler** [comment]
This seems like it could cause more confusion. Both of these types expose many things that we do not support (e.g. Request::connect, Request::get, Response::extensions, etc.).

It is also not clear to me how this would work with the current invocation pattern. How will these types be serialised?

**Comment by rbehjati** [comment]
I agree with Conrad. I thought we needed protobuf messages here.

**Comment by tiziano88** [comment]
Those methods seem fine to me, e.g. Request::connect creates a builder for a new request, but with a `CONNECT` method, and same for Request::get etc. They don't perform any operations by themselves, if that's what you meant.

Extensions may actually be useful at some point (e.g. to propagate labels in some more structured way), but for now we can just not use them.

The types will still be serialized as the existing protobuf messages (I'm not suggesting deleting those), but the SDK will convert between protobuf and idiomatic types.

This would make writing HTTP handling code (e.g. https://github.com/project-oak/oak/pull/1461/files) more approachable for developers already familiar with other Rust libraries and frameworks.

In case it is not clear, the `http` crate in Rust only defines the data types, not any HTTP related functionality.

**Comment by conradgrobler** [comment]
I did not notice that the functions such as connect only create builders, so there are fewer unsupported features than I thought.

I don't think extensions would be useful for propagating Labels and we are unlikely to ever support it. If we implement this we should make sure that we raise appropriate errors when the client code uses unsupported features such as extensions.

**Comment by tiziano88** [comment]
Extensions don't have a meaning in the http library anyways, being arbitrary Rust types. See https://docs.rs/http/0.2.1/http/struct.Extensions.html . We can document that in our case they are not used for anything, but that's the default assumption anyways.

**Comment by conradgrobler** [comment]
Is this just a case of implementing the `std::convert::From` trait for proto `HttpRequesst` and `http::response::Response`? Or do you have something else in mind?

**Comment by tiziano88** [comment]
> Is this just a case of implementing the `std::convert::From` trait for proto `HttpRequesst` and `http::response::Response`? Or do you have something else in mind?

pretty much that, but also make the SDK prefer the Rust types over the protos for its own API, namely in:

https://github.com/project-oak/oak/blob/fc4bc5dff43d102aa9c84dec99a8ce16ea54e80d/sdk/rust/oak/src/http/mod.rs#L30-L42

**Comment by rbehjati** [comment]
We can only implement `std::convert::From` for `HttpRequest` in `oak_server`, and that would require adding a dependency to `http` to the `oak_server`. Is that ok? It would also be nice to implement similar conversions for `HttpRequest` and `HttpResponse` to/from hyper `Request` and `Response`. Those conversions are needed in `oak_runtime`. Implementing those conversions requires adding `hyper` as a dependency for `oak_server`. In that case, I could also replace the `OakHeaderMap` that I have added in #1513 with a protobuf message in `http_encap.proto` and move the conversions to `oak_server`.

**Comment by tiziano88** [comment]
That's a good point, what are the actual differences between

- https://docs.rs/hyper/0.13.8/hyper/struct.Request.html
- https://docs.rs/http/0.2.1/http/request/struct.Request.html

?

**Comment by rbehjati** [comment]
Good point! They are the same type. So, we only need to add `http` as a dependency to `oak_services`. Does that match the philosophy of `oak_services`, or is that only for code generation?

**Comment by tiziano88** [comment]
I think a dependency on `http` would be acceptable, it's quite standard and basically just data structures (not much / any logic), and small dependency footprint (https://github.com/hyperium/http/blob/master/Cargo.toml). So if you also think it's a good idea, let's go ahead with that

**Comment by rbehjati** [comment]
Yes. I think it would be nice to have those conversions in `oak_services`.
