### ISSUE TITLE
Represent enclave / platform / storage as IFC label principal

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1473]
Currently, any steps that relies on remote attestation is performed ahead of time by a client connecting to a remote Oak Application, but this is not directly captured by the IFC system, i.e. there are no principals representing an enclave or a trusted cloud platform, and even if there were, there would be no convenient way of combining it with other principals and use them as part of an IFC label.

If the IFC model were extended with implication principals (#1364) then perhaps this aspect may be captured by an implied principal, i.e. an enclave / platform principal implying the desired higher level principal.

## Example

Assuming a world in which we use an enclave technology (e.g. SGX, for the sake of the example), an Oak client connecting to an Oak application would first connect over gRPC to the server, and as part of the establishment of the channel, it would also obtain a verify a remote attestation quote from the server.

Let us assume that the high-level intention of the client-side application (which embeds the Oak client library) is to send data labelled with the principal `user:Alice` to a server running in an SGX enclave which is also run by google.com; currently this would boil down to two separate steps:

- configure the Oak client so that it only allows connecting to a server in an SGX enclave run by google.com (return a connection error if not)
- configure the Oak client so that the gRPC request is labelled with the `user:Alice` label

Conceptually though, both of these aspects refer to an information flow consideration, even though they are not described with a uniform language.

If we imagine the existence of principals that represent the authority of an SGX enclave (e.g. `platform:SGX`) or of google.com as entity co-signing remote attestation quotes (e.g. `platform:google.com`), then we can actually represent the overall intention as a single label with a combined principal (assuming the existence of conjunction and implication connectives): `(platform:SGX ∧ platform:google.com) → user:Alice`.

The intuitive meaning behind this principal is that it refers to `user:Alice`, but only insofar as `(platform:SGX ∧ platform:google.com)` is trusted in the first place. In practice, the Oak client would still verify the remote attestation claim in exactly the same way as before, but data handed over to it by the client-side application is labelled with a single label that expresses both the data flow to the underlying platform, and the desired principal that should be used on top of that platform.

As another example, this may also be used to represent versioning between different versions of an enclave technology. For instance, let us imagine two versions of SGX, with corresponding principals, e.g. `platform:SGX_1` and `platform:SGX_2`. The intention is that data should be allowed to flow towards higher version numbers, and never back to old versions (to prevent downgrading attacks). This would then be represented as `platform:SGX_1 ⊑ platform:SGX_2`, from which it would follow that, for instance, `(platform:SGX_1 → user:Alice) ⊑ (platform:SGX_2 → user:Alice)`, since `platform:SGX_2` offers stronger confidentiality guarantees than `platform:SGX_1`.

## Storage

Similarly, this may also be used to model persistent storage with labels, in which the storage system is also represented by a principal, and the labels of the entries it stores are all "implied" (i.e. conditional on the trust on) the principal of the storage system.

For instance, let us imagine a storage system run by amazon.com, which promises to maintain labels of data that are sent to it. The meaning of the labels is only preserved if the owner of the data already trusts amazon.com. In particular, it should not be possible to take data labelled as `user:Alice` (an absolute principal) and send it to a storage system run by amazon.com, because there would be no way for the data owner to distinguish between a storage that actually respects labels from one that does not.

With the introduction of implication principals, the storage system would be represented by a dedicated principal (e.g. `platform:amazon.com`, representing the fact that the confidentiality of labelled data once in that platform is really guaranteed by the amazon.com entity itself. Therefore, if data was labelled as `platform:amazon.com → user:Alice` then it would be allowed to be stored on amazon.com, and when retrieved, its label would still be `platform:amazon.com → user:Alice` (which represents the fact that the overall label is "implied", i.e. conditional on trusting amazon.com).

This also means that if data is expected to be stored on a system outside of Oak, it needs to be labelled from the start in order to allow for information to flow to that storage system in the first place.

cc @daviddrysdale @anghelcovici @conradgrobler

**Comment by conradgrobler** [comment]
I guess I am misunderstanding implication labels, but intuitively it feels to me like a label such as `platform:amazon.com → user:Alice` (seeing that `platform:amazon.com → user:Alice` is equivalent to `¬platform:amazon.com ∨ user:Alice`) means that that the data will only have label `user:Alice` if it is processed on amazon.com, otherwise it will have no label when it is processed on any other platform (i.e. public).

**Comment by tiziano88** [comment]
Good observation @conradgrobler , I **think** the discrepancy may be explained by the fact that the empty label (i.e. zero element) is "public" in conjunctive normal form (i.e. using `∧`), but really is "private" in disjunctive normal form (i.e. using `∨`).

Also personally I would discourage the interpretation of implication principals as negations on the premise, since negated principals seem a bit counterintuitive (to me at least), but perhaps there is a way of interpreting them this way.

I also mentioned somewhere else that it may be that what I am calling "implication" principals are really the same things as "owned" principals e.g. in [Flam](http://www.cs.cornell.edu/andru/papers/flam/flam-csf15.pdf).

**Comment by rbehjati** [comment]
Without having read the entire discussion under #1364, does this mean that all labels are going to be implications? Since as far as I can see `(A→B)⊑(C→D)⇔(A⊑C)∧(B⊑D)` is the only "flows to" relation for implications. Or are there privileges that can convert implications to atomic principals?
