### ISSUE TITLE
Oak Chrome extension

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1492]
Tracking issue for a Chrome extension that would enforce that a web page is talking to an Oak Application, attaches labels to outgoing requests, and prevents non-Oak requests once a web page switches to Oak mode.

https://developer.chrome.com/extensions/webRequest

**Comment by juliettepretot** [comment]
I'm curious, would this really need to be an extension proprietary to chrome? It seems to me that a [service worker](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API) would be able to achieve most of these tasks.

**Comment by tiziano88** [comment]
AFAICT workers are not a great fit here because:

- there is no UI associated with them, to signal to the user whether a page is *actually* in Oak mode (the extension in the future should make this clearer, e.g. by changing the icon color or something).
- workers need to be associated with a URL, but here the context is that of a tab; i.e. this is similar to "incognito mode", which is a per-tab setting, rather than a per-URL setting.
- it seems that workers are mostly meant to "help" by offloading some of the request handling to local code, but they don't seem to be aimed at capturing all of the outgoing traffic; the extension API seems more specifically geared towards making guarantees that all requests are intercepted.

**Comment by juliettepretot** [comment]
@tiziano88 Thanks for the summary, appreciate it. :) 

- Absence of UI is a fair point. :) Though this would also be possible as a progressive enhancement in a service worker + extension combo. 
- Out of curiosity, why is per-tab behavior desired? This seems potentially confusing from a user perspective. (Also, how do the chrome extensions handle websites that sync state across tabs? Seems like potential way of leaking data)
- True that they are largely advertised as a performance improvement. Though they do serve as a network proxies, it seems quite plausible they could achieve the same purpose.

**Comment by tiziano88** [comment]
pasting my own comment from https://project-oak.slack.com/archives/CHE9E13C3/p1600718595019500?thread_ts=1600691759.016400&cid=CHE9E13C3 :

an alternative idea, which I think would solve some of these issues, would be to also Oakify (part of) the client application. Let's imagine an Oak application "launcher" which is really a web page hosted by (e.g.) google.com , which takes as an argument the URL of a client-side Oak application (or a single Oak wasm node, assuming the application is simple enough). Then the launcher would instantiate the Oak node within a native Wasm context in the browser, and only expose basically something equivalent to the current Oak ABI, except that the function calls would be handled by some JS code (or Wasm code, for that matters) in the "launcher" part of the page itself. For instance, the node may have code that creates an HTTP client node, which would result in the launcher performing XMLHttpRequests to a remote back-end, etc.

cc @conradgrobler

**Comment by juliettepretot** [comment]
![image](https://user-images.githubusercontent.com/8875406/94424896-e1c39680-0182-11eb-83d9-f1404631e24c.png)


RE the comments by @seefeldb from slack, to that's good to know. :) 

On the upside I think in Oak we would be able to avoid complexities stemming from UI composition. In my mind we would have a single note responsible for generating UI.

**Comment by juliettepretot** [comment]
To sum up the discussion we had on slack, the consensus shifted away from a chrome extension:

The chrome extension approach was to permit arbitrary DOM modification & executing arbitrary JavaScript, and then using an extension to safeguard against data leaks. 

Since this was deemed impractical the new approach is to limit which DOM modifications can be performed and which scripts can be rendered in the first place. 

This is achieved with a pseudo UI node that has two handles: 
A) a write handle that is used to declare a UI representation (which cannot include links, scripts, and other opportunities for data leakage)
B) a read handle used to receive events corresponding to user action (clicks etc)

Any actual DOM interactions would then only be performed by a trusted Oak JavaScript library. It receives the declarative UI representation from the Node and renders it (using VDOM or similar to translate the the declarative DOM representation into imperative DOM modifications). It attaches click handlers etc to interactive elements and sends that information back to the UI node in the form of events.

**Comment by ipetr0v** [comment]
> the new approach is to limit which DOM modifications

How the user can be sure that these restrictions are enforced?

> Any actual DOM interactions would then only be performed by a trusted Oak JavaScript library

How is it trusted? Is this VDOM modification happens inside Oak on a separate server, or on the client side? If the latter, do we need client to have SGX/SEV?
And also, are we planning on leveraging SGX/SEV on the client side?

**Comment by juliettepretot** [comment]
> > the new approach is to limit which DOM modifications
> 
> How the user can be sure that these restrictions are enforced?

@tiziano88 idea was use to a node launcher (see their comment above), eg https://oak.google.com?app=https://random-dev/weather.oak 

This would shift the root to the Oak launcher provider (in this case Google). The user would see which Oak launcher is used via the URL. 

> > Any actual DOM interactions would then only be performed by a trusted Oak JavaScript library
> 
> How is it trusted? Is this VDOM modification happens inside Oak on a separate server, or on the client side? If the latter, do we need client to have SGX/SEV?
> And also, are we planning on leveraging SGX/SEV on the client side?

It happens on the client. DOM modifications are only possible from within the browser's main JavaScript thread. It's "trusted" as in the source of this JS lib can only be verified via code review, formal verification is impractical. Similarly we trust that V8 executes it correctly, and the mechanism it has in place to prevent information leakage. 

That's admittedly a lower security standard than enclaves, but imho accounted for by Oak's threat model:

> End users are considered "partly trusted" in that we assume that when two users exchange data, there is a pre-existing basic trust relationship between them; in particular we assume that the recipient of the data is not going to intentionally circumvent robust protection mechanisms on their device in order to extract the received data.

https://github.com/project-oak/oak#threat-model

**Comment by ipetr0v** [comment]
> @tiziano88 idea was use to a node launcher (see their comment above), eg https://oak.google.com?app=https://random-dev/weather.oak

So IIUC there are two separate Oak entities:
- Backend Oak server with the application
- Frontend Oak server that basically acts in a way similar to an [Anonymizer](https://en.wikipedia.org/wiki/Anonymizer) and just renders the requested page

Right?

**Comment by juliettepretot** [comment]
Roughly yes. :) 

I would caution that frontend component doesn't necessarily have to be a WASM oak server, it could just be a simple HTML page that includes the trusted Oak frontend JS lib.

**Comment by seefeldb** [comment]
What's the point if there is only one node that renders UI? You can build examples like #1529, but really all you'd need for that is a host that loads arbitrary code into a sandbox iframe with very strict CSPs. Wasm, etc. becomes useful if you want to run multiple things isolated from each other (even there there are alternatives that web devs find more familiar).

To me at least, the point of introducing policies and so on is to support non-trivial stuff like use-cases where data does leave under some tightly controlled circumstances and then verify those circumstances. If in the end you have one giant UI node that you have to trust for everything (e.g. that the user did in fact press the button that means they wanted to send that data out), you haven't gained much.

So then you are back to the problem I described in chat. Which is an interesting one. Also very big.

**Comment by juliettepretot** [comment]
@seefeldb thanks for your comments, a few clarifications :). Def think it would make sense to chat with Arcs folks about this. 

> What's the point if there is only one node that renders UI? You can build examples like #1529, but really all you'd need for that is a host that loads arbitrary code into a sandbox iframe with very strict CSPs. 

Initially I thought the same, but CSPs aren't quite that powerful. As @conradgrobler pointed out, information can still be leaked via queryparams in links & redirects, alongside potential other avenues such as bluetooth etc.

> Wasm, etc. becomes useful if you want to run multiple things isolated from each other (even there there are alternatives that web devs find more familiar).

With the current approach we wouldn't actually need to run WASM in the browser. It'd be sufficient to run the Oak application on a server, and connect to a Skeleton page featuring a trusted Oak JavaScript client lib that renders the DOM representation received from the server. 

> To me at least, the point of introducing policies and so on is to support non-trivial stuff like use-cases where data does leave under some tightly controlled circumstances and then verify those circumstances. If in the end you have one giant UI node that you have to trust for everything (e.g. that the user did in fact press the button that means they wanted to send that data out), you haven't gained much.

Essentially what we gain is the ability to render some UI without needing to pipe data through a non Oak system first, thereby destroying security guarantees for the user. That's an essential component for any user facing use-case of Oak.

**Comment by seefeldb** [comment]
> Initially I thought the same, but CSPs aren't quite that powerful. As @conradgrobler pointed out, information can still be leaked via queryparams in links & redirects, alongside potential other avenues such as bluetooth etc.

This is IIRC the iframe with some sandboxing is for, so we can limit what the iframe's src is allowed to be which blocks navigation, in addition to blocking popups and top level navigation. Feature policies are the other useful bit here, mostly though to block annoying behavior.

> With the current approach we wouldn't actually need to run WASM in the browser. It'd be sufficient to run the Oak application on a server, and connect to a skeleton page featuring a trusted Oak JavaScript client lib that renders the DOM representation received from the server.

Sure, something very minimalistic here might be useful. I just don't see it as _the_ way to write non-trivial web apps with Oak, but put that way (serverside, etc.), it's a very nice way to layer the stack and just expose this bit of functionality.

Now I wonder whether you could just use postMessage() to communicate with the iframe and map that to the gRPC call and that's all you'd need? Use any JS framework you want inside the iframe.

**Comment by juliettepretot** [comment]
> This is IIRC the iframe with some sandboxing is for, so we can limit what the iframe's src is allowed to be which blocks navigation, in addition to blocking popups and top level navigation. Feature policies are the other useful bit here, mostly though to block annoying behavior.

Interesting. :) I'm not aware of a way to block navigation inside an iframe, but would be very curious to see.

**Comment by seefeldb** [comment]
The CSP of the hosting page restricts the value of `src` on the iframe, which then prevents the iframe from navigating. `iframe sandbox="allow-script"` allows scripts, but not `top-navigation`. CSP inside the iframe restricts it from creating new iframes or do other things like that.

**Comment by juliettepretot** [comment]
Oh nice. That indeed eliminates navigation. :)

It seems that for full pages we could even skip the iframe. Since we already require CSPs inside of the iframe to block other types of leaks it seems we could also use the [sandbox CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/sandbox) to set sandbox rules without needing to use an iframe.

**Comment by juliettepretot** [comment]
`Content-Security-Policy: default-src 'self'; sandbox allow-scripts;`

With these CSPs it seems a trusted Oak host (eg `app-name.oak.google.com`) could allow Oak applications to output arbitrary HTML. It would only allow connections back to the Oak application, and block leaking data via navigation.

Leaks might still occur via the web bluetooth API etc, but that seems less severe.

**Comment by seefeldb** [comment]
Yep. And I didn't know about the sandbox CSP!

Re hostname: Don't use . google.com so cookies can't be read out!
