### ISSUE TITLE
Replace `NodeStopper` with `tokio::sync::watch`

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1551]
The Runtime currently creates a `tokio::sync::oneshot` pair for each node:

https://github.com/project-oak/oak/blob/a8a35498e97174e1d27c1e668b6f306d5157b326/oak_runtime/src/lib.rs#L153-L164

and then signals termination to each of them:

https://github.com/project-oak/oak/blob/a8a35498e97174e1d27c1e668b6f306d5157b326/oak_runtime/src/lib.rs#L556-L571

https://github.com/project-oak/oak/blob/a8a35498e97174e1d27c1e668b6f306d5157b326/oak_runtime/src/lib.rs#L167-L181

I think the logic may be simplified by using a [`tokio::sync::watch`](https://docs.rs/tokio/0.2.22/tokio/sync/watch/index.html) pair to broadcast termination to all nodes; this receiver could perhaps even be included in the `RuntimeProxy` object.

I think this would make the code easier to follow and formalize.

@ipetr0v do you think this makes sense?

cc @daviddrysdale

**Comment by ipetr0v** [comment]
Why do we need to propagate the signal to all nodes simultaneously?
Does SDK have an ability to stop a particular node?

**Comment by tiziano88** [comment]
The SDK does not have such ability (in fact there is no way to refer to a node instance, I think), but you have a point that in principle we may add such functionality in the future, and having separate senders will be useful then. Thanks!
