### ISSUE TITLE
Implement a backend mock for tests

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#1568]
We can run Oak Runtime in tests:
https://github.com/project-oak/oak/blob/a6e62945aa4ad0fdf16c038f081faf9f471c0a63/examples/aggregator/module/rust/tests/integration_test.rs#L47
But we don't have a way of running a backend server in tests. Because we don't stop Oak Runtime if it couldn't connect to the backend (otherwise tests would fail):
https://github.com/project-oak/oak/blob/a6e62945aa4ad0fdf16c038f081faf9f471c0a63/examples/aggregator/module/rust/src/lib.rs#L72-L73
This may lead to undetected errors that the CI will not cover.

We need to implement a mock (or real) object that can run gRPC server and process requests from the Oak Runtime.

**Comment by daviddrysdale** [comment]
BTW, the `abitest` example has a gRPC server in the (C++) client application, which receives gRPC requests from the Runtime allowing testing of gRPC client pseudo-Node functionality &ndash; but only when run "live", [not when run as an in-process integration test](https://github.com/project-oak/oak/blob/01489ff59182e5d5d8817e7f330e5b706482cb1d/examples/abitest/module_0/rust/tests/integration_test.rs#L72-L74).

If/when a mock gRPC server is available, it would be nice to enable those test cases for the in-process version too.
