### ISSUE TITLE
Support init / command pattern for nodes

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1584]
Currently each node expects to read messages from a channel, and ideally all messages on that channel would have the same statically known type. In practice though, it is common for nodes to be initialized via a given message type, and then receive a stream of messages of a different type, so we should make this pattern easier to implement easily.

A possible approach may be to define something like:

```rust
enum NodeMessage<T, S> {
  Init(T),
  Command(S),
}
```

Or similar, that captures the two different types, and is itself Decodable and Encodable as a message.

See https://project-oak.slack.com/archives/CHE9E13C3/p1602673266073500

cc @wildarch

**Comment by wildarch** [comment]
Going with the above mentioned approach, we will probably want something that can map a `Receiver<NodeMessage<T, S>>` to a `Result<(T, Receiver<S>), OakError>`, as after initialization you probably don't want to have to keep unwrapping the commands from this type.

Another thought that occurred to me: could we perhaps make the receiver on entrypoints always read some kind of init struct, which could then itself contain a new receiver from which subsequent commands can be read?

**Comment by tiziano88** [comment]
This is done for now, it may be extended in the future.
