### ISSUE TITLE
Add API for measuring time intervals

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#1605]
After implementing an Oak benchmark (https://github.com/project-oak/oak/pull/1565) we need to add an API for measuring time intervals. It's supposed to be a non-production logic that is necessary for measuring Oak's performance.

In order to implement this we could look into [wasmtime](https://github.com/bytecodealliance/wasmtime) or to add new ABI functions that access system time.
Also implementing this in a form of a pseudo-Node may not be feasible, since it will introduce delays by encoding Protobuf messages.

P.S. It will probably be different from Roughtime (https://github.com/project-oak/oak/pull/1086) since in the case of benchmarking we need precise time values.

**Comment by tiziano88** [comment]
Thanks for creating the issue Ivan. 

Not sure what wasmtime has to do with this though, maybe you meant [wasi](https://wasi.dev/)? At least, that's what I suggested when we talked about it last time.
