### ISSUE TITLE
handle panics in extern function calls

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#161]
We currently rely on well-defined panic behaviour from `extern` functions. This is actually [undefined behaviour](https://doc.rust-lang.org/nomicon/ffi.html#ffi-and-panics).

https://github.com/project-oak/oak/blob/6de88affd8d992a0ed3bb10093a7348a7084dbe2/rust/oak/src/lib.rs#L283

https://github.com/project-oak/oak/blob/6de88affd8d992a0ed3bb10093a7348a7084dbe2/rust/oak/src/tests.rs#L138-L143

For some reason switching from stable to nightly Rust actually this manifests with a weird error:

```
error: process didn't exit successfully: `/usr/local/google/home/tzn/src/oak/rust/target/debug/deps/oak-092a7b70ef31d1ae` (signal: 4, SIGILL: illegal instruction)
```

**Comment by daviddrysdale** [comment]
Fixed in #183 I think.
