### ISSUE TITLE
Refactor keys in `oak_sign`

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#1620]
Right now `KeyBundle` struct has both `private_key` and a `key_pair` fields, where in fact `private_key` already contains a Public Key because it's encoded with PKCS#8 v2 format:
https://github.com/project-oak/oak/blob/27f580699a84e78d7b36c4883ef77b590950c636/oak_sign/src/lib.rs#L34-L39

We need to refactor it and delete `KeyBundle`.

Originated from: https://project-oak.slack.com/archives/CHE9E13C3/p1603722973180400

**Comment by tiziano88** [comment]
I suggest just calling it `KeyPair` and have `pkcs_8` and `parsed` fields (or something like that). AFAICT the only reason for this is that there is no method to go from a parsed key to its PKCS#8 representation, so ideally that should be clearly explained in the comments.

**Comment by tiziano88** [comment]
Since you are at it, could you please also impl Clone for it? It will be useful in tests. Probably it needs to re-parse it from the pkcs8 bytes.
