### ISSUE TITLE
Create labeled nodes in Aggregator example

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#1634]
Currently Aggregator example creates an Aggregator Node with a public label which performs declassifying reads from client requests.

We need to change its behavior in a following way:
- Create an Aggregator node labeled with its SHA256 hash
- Check that client requests are labeled with Aggregator's SHA256 hash
- Perform a declassifying write when sending aggregated data to the backend server

Originated from https://project-oak.slack.com/archives/CHE9E13C3/p1603883481220500

**Comment by ipetr0v** [comment]
cc @tiziano88

**Comment by tiziano88** [comment]
Cc @conradgrobler

**Comment by tiziano88** [comment]
Increasing priority as I think we should get this right sooner rather than later.
