### ISSUE TITLE
Check that privilege of created node is less than or equal to creating node

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1636]
Currently a node without privilege is able to create a child node with arbitrary privilege, which defeats the point of privilege in the first place. We should probably move privilege out of the node implementation, and let the creator assign it upfront, and also check that it is no stronger than the creator.

If / when we switch to using the integrity component as privilege, this basically corresponds to the check that the integrity component of the creator node flows to the integrity component of the created one.

cc @rbehjati as you are looking at similar functionality already

**Comment by conradgrobler** [comment]
I am not sure that this is feasible. At the moment the initial node (which has only the privilege related to its own Wasm hash) creates the gRPC server pseudo node that has top privilge.

Even if we ignore that, seeing that the gRPC server pseudo node is trusted and part of the runtime, the initial nodes still create other nodes with different Wasm hash privileges which is not less than or equal to the intial node.

**Comment by ipetr0v** [comment]
> At the moment the initial node (which has only the privilege related to its own Wasm hash) creates the gRPC server pseudo node that has top privilge.
Do pseudo nodes have **top** integrity components or only confidentiality ones?

**Comment by rbehjati** [comment]
@ipetr0v I think it is only confidentiality.

**Comment by ipetr0v** [comment]
So, it will be ok to make `created` nodes have `less than or equal` integrity labels than the `creator`.

**Comment by conradgrobler** [comment]
> So, it will be ok to make `created` nodes have `less than or equal` integrity labels than the `creator`.
> Since it doesn't break pseudo-nodes.

It should not break anything, but I also don't think it will currently do anything useful. We don't really use integrity labels at the moment.
