### ISSUE TITLE
Distinguish proper gRPC from gRPC-like inter-node communication

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#1650]
Right now in SDK we have both `oak::grpc::client` and `oak::grpc::server`.
And while `server` only corresponds to a gRPC server pseudo-Node, that listens requests coming from the outside of Oak, `client` can be either a client that sends gRPC requests to other nodes or a gRPC client pseudo-Node that sends requests outside of Oak.

We probably should distinguish proper gRPC from gRPC-like inter-node communication and consider renaming `client` or splitting the logic.

Originated from https://project-oak.slack.com/archives/CHE9E13C3/p1603991804243800

**Comment by tiziano88** [comment]
FYI https://github.com/project-oak/oak/issues/1192
