### ISSUE TITLE
misleading error message when downloading module from URL

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1677]
Using an external module as part of an oak application from an invalid URL results in the following message:

```
examples ❯ private_set_intersection ❯ build application ║ [2020-11-03T22:29:48Z INFO  oak_app_build] Couldn't load module from cache "examples/private_set_intersection/bin/cache/e02f347e895810fc32df15883f27840cbb3457d809f4620e4272912221c00c82", downloading from URL https://storage.googleapis.com/oak-modules/private_set_intersection/e02f347e895810fc32df15883f27840cbb3457d809f4620e4272912221c00c82
examples ❯ private_set_intersection ❯ build application ║ Error: Couldn't load module
examples ❯ private_set_intersection ❯ build application ║
examples ❯ private_set_intersection ❯ build application ║ Caused by:
examples ❯ private_set_intersection ❯ build application ║     Incorrect SHA256 sum: expected e02f347e895810fc32df15883f27840cbb3457d809f4620e4272912221c00c82, received b86a7b19b6e3e8b508f09734bcb2f411898e462aa532d03469e800ff5fbd87ca
```

Also it looks like the module gets cached anyways, even if the hash did not match.

In my case, I changed this line:

https://github.com/project-oak/oak/blob/2fbd54a89589385ec007a1011b68a49112eabdd5/examples/private_set_intersection/oak_app_manifest.toml#L5

to the hash of the module that I built locally, but not yet uploaded. Then I guess GCB returned an error page for that URL, which had a different hash, but the oak app builder did not notice the error message and cached it anyways. Then when I finally uploaded the module to GCB under that URL, oak app builder did not fetch it because it kept bringing up the cached error page.

@ipetr0v could you take a look?

**Comment by ipetr0v** [comment]
Looks like `reqwest::get` doesn't fail on 404:
https://github.com/project-oak/oak/blob/d797974e8edaac860f2071cd7d6ff4ec0eca891e/sdk/rust/oak_app_build/src/main.rs#L130-L132

**Comment by tiziano88** [comment]
Good catch! Could you add an explicit check for HTTP status code?

**Comment by tiziano88** [comment]
Also make sure it works with redirects (maybe reqwest does that already?)

**Comment by ipetr0v** [comment]
Will add a PR

**Comment by ipetr0v** [comment]
https://docs.rs/reqwest/0.10.8/reqwest/redirect/index.html
```
By default, a Client will automatically handle HTTP redirects, having a maximum redirect chain of 10 hops.
```
