### ISSUE TITLE
missing instructions on how to update the private set intersection example when the Wasm module is modified

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1679]
Not sure if actually missing or I am looking in the wrong place.

@ipetr0v do you know if we have anything like this? Or do people just do it from scratch every time?

**Comment by ipetr0v** [comment]
Documentation is here:
https://github.com/project-oak/oak/blob/main/docs/development.md#signing-oak-wasm-modules

**Comment by tiziano88** [comment]
That does not seem very discoverable for someone who is just modifying the PSI example. Aso the paths don't really line up, and it does not talk about how to upload the file to Google Cloud.

I have now added a bit more in-context details here:

https://github.com/project-oak/oak/pull/1681/files#diff-fc4a79fea45b5333d678692adb284095dae82af8ce5b37436440ae3c0861379c

but we should think about how to make this process more accessible, perhaps with more actionable error messages, etc.

**Comment by ipetr0v** [comment]
Not sure if we need to recopy these instructions for all examples, because one change in the SDK may result in changing docs for multiple examples.

**Comment by tiziano88** [comment]
I agree, but we need to do something about it, I don't think anyone outside of the Oak team would be able to figure out how to update the PSI example currently for instance, right? That's why I suggested more actionable error messages for things like mismatching hashes / signatures, not sure how much that helps though. Open to suggestions :)

**Comment by ipetr0v** [comment]
I think we can keep these instructions:
https://github.com/project-oak/oak/pull/1681/files#diff-fc4a79fea45b5333d678692adb284095dae82af8ce5b37436440ae3c0861379cR1-R16

But either move them to `examples/README.md` or just to have a separate section in `docs/`.
