### ISSUE TITLE
Use anyhow in HttpServerNode

### ISSUE THREAD

**Issue by rbehjati** [project-oak/oak#1693]
Originated from the following comments: 
https://github.com/project-oak/oak/pull/1652#discussion_r516849374
and 
https://github.com/project-oak/oak/pull/1586/files#r510714975

**Comment by ipetr0v** [comment]
Is `IdentityVerification` used in:
https://github.com/project-oak/oak/blob/e808e160051e18fdedfab5c7d3668e52fefbddc6/oak_runtime/src/node/http/server.rs#L314
returned by `get_oak_label`:
https://github.com/project-oak/oak/blob/e808e160051e18fdedfab5c7d3668e52fefbddc6/oak_runtime/src/node/http/server.rs#L404-L427

**Comment by rbehjati** [comment]
@ipetr0v You are right. Only `RequestLabel` is used. I believe `HttpError::IdentityVerification` is given a separate case because match is exhaustive and it would not make sense to mix `HttpError::IdentityVerification` with the rest of the error types.
