### ISSUE TITLE
Add a new method to the Runtime for stopping a specific node 

### ISSUE THREAD

**Issue by rbehjati** [project-oak/oak#1716]
Investigate the need for a new method in the `Runtime` to stop nodes.

In many cases we have ephemeral nodes that are created to do a specific job and then terminate. These nodes usually don't run in an event loop. 
To check: does the node actually terminate or does it continue to wait on its channel? 
Examples are such nodes are the planner nodes that we currently have in most of the examples. Similarly, per-request or per-user nodes could be ephemeral.

To ensure that these nodes are stopped correctly and their resources are released, we need a `stop_node` method in the Runtime. The `stop_node` needs the id of the node to be able to retrieve the correct node-stopper. So we also need a way to return the `node_id` to the caller when creating a node.

**Comment by daviddrysdale** [comment]
I don't think a `stop_node()` entrypoint is needed to do this<sup>*</sup>, and on a quick experiment it looks like the initial ephemeral Node in the `hello_world`example (which uses `oak::entrypoint_command_handler!`) does indeed terminate.

However, from the logs it looks like the initial Node *is* attempting to do a `wait_on_channels`, which it probably shouldn't &ndash; maybe there needs to be a different entrypoint macro for init nodes that just set other things up and terminate?

(The `wait_on_channels` attempt only has a single handle, and the underlying channel is [closed after the init `ConfigMap` is sent in](https://github.com/project-oak/oak/blob/main/oak_runtime/src/config.rs#L42-L46), so the event loop terminates with a `WARN`ing)

*: Also, I'm not convinced that a `stop_node()` entrypoint would be a good idea &ndash; allowing abrupt external termination of a Node might leave all sorts of external resources in an inconsistent state.

**Comment by rbehjati** [comment]
Thanks for looking into this @daviddrysdale. A separate entrypoint macro sound interesting. 

I think a `stop_node` would be useful for testing (for example to fix #1671). What do you mean by external resources? Does not `NodeStopper` take care of that?

**Comment by daviddrysdale** [comment]
> What do you mean by external resources?

It might be easiest to explain by analogy &ndash; threading libraries typically do not include any kind of `thread_kill` entrypoint, because it makes it far too easy to kill off a thread that's in the middle of holding a mutex.  Once such a thread is dead, the mutex is locked forever and the rest of the program is likely to go seriously awry.

The same is true to a lesser degree with Oak Nodes &ndash; a Node might be in the middle of a sequence of operations involving external services (gRPC, storage, HTTP), where abrupt termination would leave external resources in an inconsistent state.  (A made up example: a Node has retrieved a user email from an HTTP server, but gets terminated before it can write it to a separate storage service, meaning the email is lost).

(Of course, this is only relevant for real-world use &ndash; if it's just for testing then no worries. But I still suspect it's not necessary &ndash; see #1720)

**Comment by tiziano88** [comment]
I suppose applications will have to take into account sudden termination / disconnection of nodes anyways, since Oak does not offer any transactional guarantees by itself.

**Comment by rbehjati** [comment]
Thanks for the explanation @daviddrysdale, and fixing the runtime tests. I think we could use the same pattern in future tests if needed. 

But I am still wondering about ephemeral user-specific or request-specific nodes. The runtime could get into a state where there are plenty of such nodes, actually terminated, but still occupying resources because, IIUC, the runtime holds on to all the `NodeInfo` and `NodeStopper` instances until `stop` is called on it. I think, in the case of user/request-specific nodes, it would be useful to have the creator release these resources. I don't think calling the `node_stop` in these cases would lead the system into an inconsistent state, since the node is terminated. Perhaps a better solution is to have some sort of garbage collection in the runtime. 

However, if user/request-specific nodes are always in fact stateful label-specific nodes, and not exactly ephemeral, as in the chat example, then this should not be an issue.

**Comment by daviddrysdale** [comment]
Terminated nodes get cleaned up [here](https://github.com/project-oak/oak/blob/a668d3706444bd6a0412972ac6428427143e52a2/oak_runtime/src/lib.rs#L1331), calling the code [here](https://github.com/project-oak/oak/blob/a668d3706444bd6a0412972ac6428427143e52a2/oak_runtime/src/lib.rs#L1128-L1161) to remove associated state.

**Comment by tiziano88** [comment]
Is it the case that a Node can intentionally trigger its own termination by closing all the incoming channels it has?

**Comment by daviddrysdale** [comment]
> Is it the case that a Node can intentionally trigger its own termination by closing all the incoming channels it has?

I guess so, but I don't know whether the relevant layers of macros/SDK wrappers allow access to the relevant channel handles.

**Comment by rbehjati** [comment]
> Terminated nodes get cleaned up [here](https://github.com/project-oak/oak/blob/a668d3706444bd6a0412972ac6428427143e52a2/oak_runtime/src/lib.rs#L1331), calling the code [here](https://github.com/project-oak/oak/blob/a668d3706444bd6a0412972ac6428427143e52a2/oak_runtime/src/lib.rs#L1128-L1161) to remove associated state.

Oh! Thanks. I had not noticed that.
