### ISSUE TITLE
Entrypoints generated with `entrypoint_command_handler` leak their initial channel

### ISSUE THREAD

**Issue by daviddrysdale** [project-oak/oak#1718]
Running the `hello_world` example without any connected clients shows a dangling channel in the introspection graph ("handler-in(3)").  It would nice if `entrypoint_command_handler!` were to close the initial channel provided to the Node entrypoint (and similarly if `entrypoint_command_handler_init!` were to do the same once the init message has been read).

```dot
digraph Runtime {
  {
    node [shape=box style=filled fillcolor=red fontsize=24]
    node0 [label="implicit.initial" URL="/node/0"] [style=dashed]
    node3 [label="translator(3)" URL="/node/3"]
    node4 [label="log(4)" URL="/node/4"]
    node5 [label="handler(5)" URL="/node/5"]
    node6 [label="grpc_server(6)" URL="/node/6"]
    node7 [label="log(7)" URL="/node/7"]
  }
  {
    node [shape=hexagon style=filled fillcolor=orange]
    node3_18414706081629265367 [label="3:18414706081629265367" URL="/node/3/18414706081629265367"]
    node3_8011379185114771087 [label="3:8011379185114771087" URL="/node/3/8011379185114771087"]
    node4_6721458046453684609 [label="4:6721458046453684609" URL="/node/4/6721458046453684609"]
    node5_2385839135644088523 [label="5:2385839135644088523" URL="/node/5/2385839135644088523"]
    node5_16858159217652582515 [label="5:16858159217652582515" URL="/node/5/16858159217652582515"]
    node5_6851891889571755915 [label="5:6851891889571755915" URL="/node/5/6851891889571755915"]
    node5_8910040226083540515 [label="5:8910040226083540515" URL="/node/5/8910040226083540515"]
    node6_16856711355704925774 [label="6:16856711355704925774" URL="/node/6/16856711355704925774"]
    node7_7775095612316433006 [label="7:7775095612316433006" URL="/node/7/7775095612316433006"]
  }
  {
    node [shape=ellipse style=filled fillcolor=green]
    channel2 [label="translator-in(2)"]
    channel4 [label="log-in(4)"]
    channel3 [label="handler-in(3)"]
    channel7 [label="log-in(7)"]
    channel5 [label="command sender(5)"]
  }
  node3 -> node3_18414706081629265367 -> channel4
  channel2 -> node3_8011379185114771087 -> node3
  channel4 -> node4_6721458046453684609 -> node4
  channel3 -> node5_2385839135644088523 -> node5
  node5 -> node5_16858159217652582515 -> channel2
  node5 -> node5_6851891889571755915 -> channel7
  channel5 -> node5_8910040226083540515 -> node5
  node6 -> node6_16856711355704925774 -> channel5
  channel7 -> node7_7775095612316433006 -> node7
}
```

**Comment by tiziano88** [comment]
Thanks for creating the issue, I agree about the `_init` version, which should definitely close the init channel and only keep the command channel open; but for the non-init version, I don't think we can just make it close the incoming channel automatically, since it may be the one used to receive gRPC invocations (or other messages), right?

**Comment by tiziano88** [comment]
Actually I don't remember, does the Runtime close its end of the initial channel on which it sends the ConfigMap? If so, we can make `entrypoint_command_handler` terminate when it notices that the channel is orphan (if it doesn't already -- I haven't checked).

**Comment by daviddrysdale** [comment]
- Yes, the Runtime code [closes the init channel](https://github.com/project-oak/oak/blob/main/oak_runtime/src/config.rs#L42-L46) after the sole `ConfigMap` is sent, so the channel becomes orphaned after the message is read.
 - For the non-init case, I don't think its possible to read from the channel anyway because it's leaked &ndash; I can't see the channel handle being passed on to any application code anywhere. (However, I may be getting lost in the various layers of macros involved&hellip;)

**Comment by daviddrysdale** [comment]
See also #1716 &ndash; the init channel becoming orphaned is the reason that the ephemeral nodes terminate.
