### ISSUE TITLE
Partially Secret Labels

### ISSUE THREAD

**Issue by aferr** [project-oak/oak#1722]
Roughly, move to ABI Design 2 here:
https://docs.google.com/document/d/1pd1NfpROHjxmtRZaA9pfAC3zYhhEZ_xRfDU2gyptMg0/edit#

**Comment by aferr** [comment]
@conradgrobler @daviddrysdale @tiziano88 

Just for my own agenda setting, does making this part of v1 mean:
- "We definitely want to use an ABI design closer to 2, but we won't implement that until v1"
or
- "We think we might want to use ABI design 2, and we'lll re-evaluate that when we're working on v1"

On my end, it would be much easier to stick with one set of definitions than trying to keep both alive in the code at once since these definitions are pretty close to the root of the tree of definitions. I'd be inclined to stick with the one you'll wind up with eventually rather than what you have now.

**Comment by conradgrobler** [comment]
My understanding is that it was more the second option (ie "We think we might want to use ABI design 2, and we'lll re-evaluate that when we're working on v1")

**Comment by aferr** [comment]
Got it, thanks.
