### ISSUE TITLE
Merge Node/Channel IDs with debug names to form a single unique identifier

### ISSUE THREAD

**Issue by juliettepretot** [project-oak/oak#1727]
Currently both the Node and Channel struct have both an `id` and `name` property. The `id` is a number that's incremented as new Nodes/Channels are created. The name is used for debugging, and [automatically merged](https://github.com/project-oak/oak/blob/ab7e7f032359e0233ef3f859a9193733a9895372/oak_runtime/src/lib.rs#L1207) with the `id` when set to make it unique.

we end up with Nodes with two unique identifiers.
```
Node {
 id: 5,
 name: "hello_world(5)",
 ...
}
```

Should we instead combine them into a single uid?
```
Node {
 uid: "hello_world(5)",
 ...
}
```

cc @tiziano88 @conradgrobler

**Comment by tiziano88** [comment]
Yes I think I actually suggested exactly that elsewhere, basically name-id or name(id) or some variation

**Comment by juliettepretot** [comment]
SGTM to me. Are there concerns around changing the type of the unique identifier from `u64` to string? I assume it might make ordering harder, perhaps issues occur when devs set very long names?

In the runtime `node_infos: RwLock<HashMap<u64, NodeInfo>>` would become `node_infos: RwLock<HashMap<String, NodeInfo>>,`

**Comment by tiziano88** [comment]
To clarify, I didn't actually mean to change the internal representation of a node ID, that should stay as u64, since it's used to index within maps etc, as you noted. My only suggestion is to expose a method that combines name and id into a uniform user-facing name which is also unique, to use in logs and introspection graph.

**Comment by juliettepretot** [comment]
We currently already have a helper method to set the name, which happens to amend the `id` to make it unique. Changing that to a get method is probably better though, to avoid storing two `uid`s in the struct, which implicitly reference each other. 

Out of curiosity, what's the specific down side of changing the internal representation of a node ID to `String`? I assume performance reasons?
