### ISSUE TITLE
Split Aggregator Wasm module

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#1731]
After finishing https://github.com/project-oak/oak/pull/1646 we will start checking labels of the incoming messages (if they have Aggregator Wasm module hash). But in order to do this, we need this hash to be present in the Aggregator code.

Currently this problem is solved via sending hash as a part of `ConfigMap`, but in the future we need to split these modules into `Router` and `Handler` modules, and hardcode the `Handler`'s hash in the `Router`.

**Comment by ipetr0v** [comment]
The only problem with splitting modules and hardcoding SHA-256 is that Oak tests also compile Wasm modules which result in different SHA-256 hashes.

**Comment by ipetr0v** [comment]
I order to allow both tests and release versions to use the same module (but with different hashes) and also prevent constant re-hardcoding of module hashes - I can add the following function to ABI:
```rust
// `oak::io`
fn module_privilege_read(wasm_module_name: &str) -> Result<Label, OakStatus> {
    ...
    oak_abi::module_privilege_read(...)
    ...
}

```
Similar to existing `node_privilege_read`.

This will also work for Signature labels.

WDYT @tiziano88 ?

**Comment by tiziano88** [comment]
I'm not sure I see how this helps. The problem is the same from the client point of view: the client needs to know the label to assign upfront. So I don't think having a special case to solve it in an Oak application helps much. Or am I missing something?

**Comment by ipetr0v** [comment]
The main problem is - the same module is compiled for release and for tests, resulting in having different hashes. This is problematic if we want to hardcode hashes in `Main` modules.
Second problem (more of an inconvenience) we always need to re-hardcode hashes once we updated an application. This also could result in the avalanche of changes if multiple modules use such hardcoded hashes.

**Comment by tiziano88** [comment]
> The main problem is - the same module is compiled for release and for tests, resulting in having different hashes. This is problematic if we want to hardcode hashes in `Main` modules.

Maybe we should only pick one. The point is that they are in fact different modules, so I don't think we should try and work around this.

> Second problem (more of an inconvenience) - we always need to re-hardcode hashes once we updated an application. This also could result in the avalanche of changes if multiple modules use such hardcoded hashes.

As I said, this is the same problem that a client using these labels would have, so solving it for ourselves is actually counterproductive. If we cannot solve it for ourselves, how do we expect clients to deal with it?
