### ISSUE TITLE
Add `with_downgrade` versions of remaining node and channel functions to ABI and SDK

### ISSUE THREAD

**Issue by conradgrobler** [project-oak/oak#1736]
This is a follow-up to #1670 to cover the remaining functions not implemented as part of the IFC v0 milestone.

After #1734 downgrade privilege is no longer used automatically. Explicit `with_privilege` versions of ABI and SDK functions were only created where they were needed to support the existing examples and tests.

The remaining ABI functions that require explicit `with_downgrade` versions are:
- `wait_on_channels`
- `channel_read`

The related SDK functions should also get explicit `with_downgrade` versions.

**Comment by ipetr0v** [comment]
There is an ABI function called `channel_read`
https://github.com/project-oak/oak/blob/ecc058cc124160341506c655b83eed8874e01d1f/oak_abi/src/lib.rs#L125-L133

And similar function in Runtime
https://github.com/project-oak/oak/blob/ed2808c05ada047227cc26e5d771c9ef319a0404/oak_runtime/src/proxy.rs#L395-L399

But the ABI `channel_read` doesn't use `channel_read` from Runtime - it uses `channel_try_read_message` instead
https://github.com/project-oak/oak/blob/ed2808c05ada047227cc26e5d771c9ef319a0404/oak_runtime/src/proxy.rs#L432-L438

I think this might be confusing
