### ISSUE TITLE
Move debug statements from the RuntimeProxy to the Runtime 

### ISSUE THREAD

**Issue by jul-sh** [project-oak/oak#1737]
Following discussions in #1698 @tiziano88 suggested that conceptually RuntimeProxy conceptually just partially applies Runtime methods. Hence it seems sensible to move debug statements currently in the RuntimeProxy to the Runtime. Z

That also solves the issue presented in #1698 of needing to keep a copy of the node_name in the RuntimeProxy purely for logging.

**Comment by juliettepretot** [comment]
The reason we presently log in the proxy seems to largely be that it makes logging args + the return value easier. One approach to make logging in the Runtime easier would be wrapping methods in a a higher order function that logs args + return values.

**Comment by tiziano88** [comment]
There are some tracing frameworks that use annotations on functions to log arguments and return values (e.g. https://docs.rs/tracing-attributes/0.1.11/tracing_attributes/attr.instrument.html ), but when I tried them they seem pretty opaque and actually generate wrapper functions around the underlying functions, which would be better to avoid in code that is sensitive as the oak runtime.

Anyway, I think we can easily write a `macro_rules` macro that just logs a value and returns it, if we really think that logging it manually is too verbose (though personally I would just say to stick to manually logging the things we care about, even if it means we need to add a few lines here and there to the Runtime -- it is a one-off job, and even if it forget something, we should notice pretty quickly based on the missing logs).

**Comment by juliettepretot** [comment]
@tiziano88 Makes sense, I agree we probably don't need a tracing framework. 

RE manual logging, how would you handle methods that return a `Result` type? For them there's often multiple (easily overlooked) return statements, essentially every time the `?` operator is used.
