### ISSUE TITLE
Design a solution for making use of privilege in gRPC generated code explicit

### ISSUE THREAD

**Issue by conradgrobler** [project-oak/oak#1739]
The gRPC generated code currently automatically uses the node's downgrade privilege to write the response back (in the case of server code) or send the request (in the case of client code). In order to be more explicit about when privilege is being used, we need to design a way for node implementations that based on gRPC code generation to declare whether privilege is being used or not.

**Comment by tiziano88** [comment]
How many (and which ones) of the current examples rely on declassification from a gRPC handler node?

I can think of two options to approach the problem:

- augment the return type of gRPC methods to include a bool / enum of whether to use the node privilege to declassify
- expose sender / writer objects (even for unary gRPC methods) with methods for writing a message with or without declassification

**Comment by conradgrobler** [comment]
There are currently two:

- Aggregator: to send a success response to the client, and to report the aggregated data via the gRPC client
- Private set intersection: to send responses to the clients

**Comment by tiziano88** [comment]
Thanks, makes sense, basically those that use their Wasm declassification privilege.
