### ISSUE TITLE
Modify SDK and examples to create a single log node and pass its handle around

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1740]
Currently most nodes individually create (either directly or via some macro) a log pseudo-node.

This is not very elegant and also problematic because once these nodes are created with the appropriate non-public label, they will not be able to create further nodes any more.

We should move to a pattern in which a single log pseudo-node is created at application startup by the main node, and its handle passed around to any other node that needs logging.

**Comment by conradgrobler** [comment]
This has been fixed by #1741
