### ISSUE TITLE
race condition in node_register

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1762]
from @daviddrysdale 's [comment](https://project-oak.slack.com/archives/CHE9E13C3/p1606141535371100?thread_ts=1606140909.370600&cid=CHE9E13C3):

`node_register()`  calls three things:
- `node_configure_instance`  - sets up nodeID -> `NodeInfo` mapping entry
- `node_start_instance`  - starts the new thread for the Node's execution
- `add_node_stopper` - modifies the per-Node `NodeInfo` to include the stopper

However, if the thread for the new Node kicks off and terminates (in this case because the storage node is unimplemented) between steps 2 and 3, then step 3 tries to modify a `NodeInfo` that's not there any more (thread termination calls remove_node_id on the way out)

**Comment by tiziano88** [comment]
I think the problematic code is here:

https://github.com/project-oak/oak/blob/72049ad8aa88c5fbbf0bf1e395b5f8254cfc14a0/oak_runtime/src/lib.rs#L1416-L1424

**Comment by tiziano88** [comment]
Since this seems to happen very rarely due to a race in the newly created node, adding a sleep just before the `add_node_stopper` call here makes it fail more consistently:

https://github.com/project-oak/oak/blob/72049ad8aa88c5fbbf0bf1e395b5f8254cfc14a0/oak_runtime/src/lib.rs#L1374-L1390

- add `std::thread::sleep(std::time::Duration::from_secs(2));` at line 1387
- run `./scripts/runner run-examples --example-name=abitest`

**Comment by daviddrysdale** [comment]
I think this race has been there for a while (since 76d0ff37cf0edf6f23dffdd5e53dcc4b4695b65f is my best guess).  Simplest quick fix might just be to `warn!` rather than `panic!` in `remove_node_id()` if the `NodeId` is absent.

**Comment by tiziano88** [comment]
A few options to consider:

1. Just keep the `NodeId` entry when the thread terminates, and update the fact that the it was terminated (maybe add a status enum or similar to it). The downside is that it will accumulate entries forever, which is not great.

2. Change the logic to ignore a missing `NodeId`

3. Actually synchronize (or split) the various parts of `NodeId` so that an instance is always present while the Node is running.
