### ISSUE TITLE
Cargo deadlinks version is unpinned in Dockerfile 

### ISSUE THREAD

**Issue by ebeasant-arm** [project-oak/oak#1776]
Current x86 Dockerfile does not pin version of deadlines:

RUN cargo install cargo-deadlinks

Current docker image version of deadlinks:
cargo deadlinks --version
0.4.1

Should probably read something like:
ARG deadlinks_version=0.4.1
RUN cargo install --version=${deadlinks_version} cargo-deadlinks

(Note that Version 0.6.1 and above report errors in documentation)

**Comment by tiziano88** [comment]
Good catch, I think we should fix it for the main Dockerfile too:

https://github.com/project-oak/oak/blob/a3e0ea9351967854f3af536f958fe59c46fa9930/Dockerfile#L218-L219

**Comment by tiziano88** [comment]
(sorry, just realised you **were** talking about the main Dockerfile)
