### ISSUE TITLE
Oak Node lifetime management

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#181]
We should support a way to manage lifetime of Oak Nodes. For now this may be an RPC on Oak Manager that allows the caller to shut down a running Application.

https://github.com/project-oak/oak/blob/fb64cf6a38e512a6d2c66bf0db1921daec983fbf/oak/proto/manager.proto#L135-L143

**Comment by daviddrysdale** [comment]
(Some preparatory work in #183)

**Comment by daviddrysdale** [comment]
Fixed in #220.
