### ISSUE TITLE
Use the challenge-response mechanism in the Chat example

### ISSUE THREAD

**Issue by rbehjati** [project-oak/oak#1851]
The chat example uses the C++ client for which we currently don't have signing support (#1838). It should be possible to spawn a child process running [`oak_sign` cmd tool](https://github.com/project-oak/oak/blob/9584170e0c3e1c38a1b3b1fb4bea86e1125687c1/oak_sign/src/main.rs#L17-L37) and get the signature from it.

**Comment by tiziano88** [comment]
Another option may be to create a linkable library from Rust and call it from C++, though it may be complicated because of Bazel.
