### ISSUE TITLE
Ensure declassification is happening correctly for challenge-response

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1852]
We were discussing earlier today whether there is anything missing from the challenge-response mechanism, in particular whether declassification is happening at the right places, namely as part of the gRPC server node, and only for the correct client that is presenting a valid credentials.

@rbehjati I'm creating this issue so we can confirm whether everything is already implemented, or is there anything left, could you take a look and either close or add more details here? Thanks

**Comment by rbehjati** [comment]
This declassification only happens in the gRPC and HTTP nodes, and those nodes have the top privilege. We also have an issue for replacing the top privilege with the top privilege for the user-identity sub-lattice (when #1631 is completed). Is that all is needed?

**Comment by tiziano88** [comment]
Having the top privilege is necessary but not sufficient. We also need to make sure that they are doing the right declassification for the user that is on the other side of the network connection, and not mixing things up, but if that's already the case then I guess we are done (having the sub-lattices may help with that, since at least we could immediately see that e.g. a gRPC node may never declassify a Wasm label, even by accident).

**Comment by rbehjati** [comment]
Currently in our examples, we don't have any nodes with a `user_identity` label. The pattern is to have a public node that writes into a response channel labeled with a `user_identity` label. The gRPC/HTTP server node then uses its top privilege to read from the response channel. In my opinion, no real declassification happens in this case. But maybe the usage pattern would be more meaningful for the chat example, after we implement the challenge-response for it.

**Comment by rbehjati** [comment]
Is not that the request label? (the receiver in the invocation is a handle to the request channel, which gets the request label) We assign the `user_identity` label only to the response channel, per #1428 and the docs.

**Comment by tiziano88** [comment]
If the request uses a user_identity label, then the code in the example creates a node with that label I think, doesn't it?

**Comment by rbehjati** [comment]
We briefly discussed the possibility of having the `user_identity` as part of the request label for some scenarios, but for that we most likely require disjunctions.

**Comment by rbehjati** [comment]
> If the request uses a user_identity label, then the code in the example creates a node with that label I think, doesn't it?

That is true.

**Comment by tiziano88** [comment]
> We briefly discussed the possibility of having the `user_identity` as part of the request label for some scenarios, but for that we most likely require disjunctions.

I'm confused about this, why are disjunctions relevant? The flow I think this is implementing is that everything (apart from the router node) is at the same label, which in most cases would be a `user_identity`. Note that this is not the case in the client, but I think this is part of the TODO to give examples meaningful labels:

https://github.com/project-oak/oak/blob/1b6d0867c45c4f4ff95eb3c07881904b4e31b813/examples/trusted_database/client/rust/src/main.rs#L77

**Comment by rbehjati** [comment]
I think, in many cases the user would label the request with some `TLS endpoint` tag. Without disjunctions, it would be impossible to have the same request to have the `user_identity` tag too (and I think a conjunction does not make sense, because I don't think any node would be able to use use such a request). But maybe a scenario like that is not realistic?

**Comment by tiziano88** [comment]
I am specifically talking about private lookup / private computation use cases, where there is no declassification to external endpoints. The only expectation is that data goes back to the same client. I think the `trusted_database` example is already built around that idea, except it's missing the appropriate labels (it was blocked on the challenge / response impl and the existence of a Rust client).

**Comment by rbehjati** [comment]
In that case, I think we are done. We just need to fix the request labels.

**Comment by rbehjati** [comment]
Getting back to your question:
> We also need to make sure that they are doing the right declassification for the user that is on the other side of the network connection, and not mixing things up...

I think, assuming that the user/client sets the user-identity in the request label correctly, and none of the wasm nodes can declassify user labels (which I believe is the case), then things won't get mixed up. 

I've fixed the request label for the `trusted_database` example in #1856.

Closing this issue for now.
