### ISSUE TITLE
Investigate creating a JS client equivalent to oak_sign

### ISSUE THREAD

**Issue by juliettepretot** [project-oak/oak#1859]
At the moment in non-Rust clients we have to manually create the client keys, and sign the challenge response via the `oak_sign` CLI. It's an extra layer of complexity, and means we have to hardcode the challenge in the Oak runtime (atm it's just `"oak-challenge"`) thereby compromising the auth security of challenge-response auth, and allowing for replay attacks. 

A native JS way of doing this would be nice. 

Related to #1853, #1855, #1851

**Comment by tiziano88** [comment]
FYI: https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto

**Comment by juliettepretot** [comment]
implemented :]

**Comment by tiziano88** [comment]
Does the current implementation also work from browser, or only in Node.js?

**Comment by juliettepretot** [comment]
All the juicy bits, yes. :) The one exception is the hash function. The API is different for Node.js and browsers.

It's easy to adjust:

https://github.com/project-oak/oak/blob/3deab43be26dff143a5f61ca0ab8ab21b7a94e93/examples/hello_world/client/nodejs/oakSign.js#L45

s/`createHash('sha256').update(input).digest()`/`await globalThis.crypto.subtle.digest('sha256', input)`/

If you think it'd make good, I can add a small browser client to the `hello_world` example. :)
