### ISSUE TITLE
oak_debug: Check that oak_runtime builds without oak_debug

### ISSUE THREAD

**Issue by rbehjati** [project-oak/oak#1862]
- Make sure `oak_runtime` builds without `oak_debug`. Ideally, `oak_debug` should be opt-in, and disabled by default.
- Make sure tests pass without `oak_debug`.
- Explain `oak_debug` in the documentation.
- Replace `oak_debug` with a scarier name!

**Comment by daviddrysdale** [comment]
> * Make sure `oak_runtime` builds without `oak_debug`.

I think CI [does](https://github.com/project-oak/oak/blob/main/.github/workflows/ci.yaml#L22) [this](https://github.com/project-oak/oak/blob/main/runner/src/main.rs#L304-L306) already.

**Comment by rbehjati** [comment]
Does that compile the runtime without `oak_debug` too? When I run `cargo build --manifest-path=oak_runtime/Cargo.toml --no-default-features`, I get several compile errors:
```
   Compiling oak_runtime v0.1.0 (/opt/my-project/oak_runtime)
error[E0432]: unresolved import `crate::graph`
  --> src/channel.rs:18:5
   |
18 |     graph::DotIdentifier,
   |     ^^^^^ maybe a missing crate `graph`?

error[E0433]: failed to resolve: maybe a missing crate `introspect`?
   --> src/proxy.rs:131:32
    |
131 |                         crate::introspect::serve,
    |                                ^^^^^^^^^^ maybe a missing crate `introspect`?

warning: unused import: `Event`
  --> src/introspection_events.rs:18:61
   |
18 |     proto::oak::introspection_events::{event::EventDetails, Event},
   |                                                             ^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

error: aborting due to 2 previous errors; 1 warning emitted
```

**Comment by daviddrysdale** [comment]
Bah, looks like the `oak_debug` feature selection passthrough from `oak_loader` to `oak_runtime` isn't set up right, which means that the `--no-default-features` check has rotted.
