### ISSUE TITLE
Current router implementation is unscalable and leaky

### ISSUE THREAD

**Issue by daviddrysdale** [project-oak/oak#1866]
The simplest example is currently the `translator` example (which is simple because it's intended to be re-usable as a component in other Oak Applications, e.g. `hello_world`).  

After the (Go) `translator` example client has performed its 4 gRPC requests, this is the introspection graph:

![translator](https://user-images.githubusercontent.com/457208/106870981-a5242080-66c9-11eb-86c4-12938985b16c.png)

None of the nodes, channels and handles in the bottom part of this graph will ever be used in subsequent execution of the application. Also, there are five orphaned channels at the top of the graph that can never be used again (which might be #1718).

The `hello_world` example is worse; after the 5 requests from the C++ client the graph is:

![hello-world](https://user-images.githubusercontent.com/457208/106871653-5e82f600-66ca-11eb-942c-b5d428158c42.png)

Only 3 nodes and 2 channels in this graph will be used in subsequent execution.

**Comment by conradgrobler** [comment]
Nice detail. :)

Do you think this is due to the handles being leaked by the router (and therefore should be resolved by linear handles) or are the other issue that need to be addressed as well?

**Comment by daviddrysdale** [comment]
Not completely sure, but I *think*:
 - The dangling channels at the top of the diagrams are just leaks (possibly #1718), which might get automagically fixed by linear handles
 - The morass of nodes and channels at the bottom of the diagram seems to be because a handler node is created per-request, and never goes away.  Linear handles might help with some of the channels, but not with the nodes. For the nodes, I'd guess it depends on what the "handler" nodes are intended to handle:
   - If they are only intended to handle a single request (as they appear to now), then they should probably terminate after doing so.
   - If they are intended to handle multiple requests, e.g. all those this a specific handle, then the router code probably needs adapting to track a label=>existing Node map.  (I don't know what the current status of the router stuff is &ndash; maybe this is already planned somewhere?)

**Comment by tiziano88** [comment]
Correct, the Router currently holds on to all the nodes it creates for any invocation, in case a new invocation with the same label comes up later on, in which case it reuses that part of the sub-graph. For stateless applications such as the translator one, I think the correct thing to do would be to close the invocation channel once the one (and only) invocation is sent to the command handler node by the router, I think around here:

https://github.com/project-oak/oak/blob/1e377619e6e5d537f928c4bbf261603ddbf19adf/examples/translator/module/rust/src/lib.rs#L89-L91

**Comment by daviddrysdale** [comment]
> Correct, the Router currently holds on to all the nodes it creates for any invocation, in case a new invocation with the same label comes up later on, in which case it reuses that part of the sub-graph

Ah, maybe I just picked a bad pair of examples. Is there an example that does this atm?

**Comment by tiziano88** [comment]
I think the chat app is the only one that relies on per-label state, so probably the examples you picked should be fixed to close those channels after each invocation, which I think should trigger the nodes and channels to be freed up afterwards?

**Comment by daviddrysdale** [comment]
Yeah, the `chat` example does seem to have much better node re-use:

![chat-10](https://user-images.githubusercontent.com/457208/106897796-51c2ca00-66eb-11eb-92ff-1b4ebc318160.png)

There's still an awful lot of leaked channels though (this was after 10 messages had been exchanged, so maybe one leaked channel per message?)

**Comment by tiziano88** [comment]
Yeah the incoming gRPC messages hanging around seems definitely a leak, which is odd as even in the graph it seems obvious that they are unreachable.

@rbehjati since you are looking at channels and incoming gRPC messages as part of the fine-grain label proposal, could you take a look and see if you can figure out why those are getting leaked? My guess is that it is something trivial, like forgetting to free the channel when the read count gets to zero, but all the information should be around in the Runtime already.

**Comment by conradgrobler** [comment]
I suspect it is even more trivial than that. The routers are not closing the handles on the invocations they receive after forwarding the invocations.

Also, as far as I can see, the Hello World router (for example) does not close the write handle to the initial channel it creates for the target node. This means the node sees that the channel is still alive and therefore never exits.

**Comment by rbehjati** [comment]
Sure. I'll have a look.

**Comment by tiziano88** [comment]
> Yeah the incoming gRPC messages hanging around seems definitely a leak, which is odd as even in the graph it seems obvious that they are unreachable.

correction: what the graph shows is actually what @conradgrobler said: the router is holding on the read handle for each channel, instead of closing them. I was confused by the direction of the arrows

**Comment by rbehjati** [comment]
It would have been nice to implement Drop for `oak::grpc::Invocation`, and close the channels in the `drop` so that the developers would not have to worry about that. But I was unable to do that without breaking things. So, for now the channels need to be explicitly when implementing `CommandHandler`. Here is the new introspection graph for translator: 
![Screen Shot 2021-02-04 at 16 25 52](https://user-images.githubusercontent.com/12942581/106930108-1507ca80-670d-11eb-9e3b-5d50828c15d0.png)

**Comment by tiziano88** [comment]
I believe implementing Drop for channel handles is effectively what @wildarch is doing in #1850 , so I would leave that out of scope for this issue anyways. Manually closing handles seems all we need for this, the new graph looks much better @rbehjati !
