### ISSUE TITLE
Use signature format compatible with sigstore / rekor

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1912]
See https://sigstore.dev/ for reference (cc @dlorenc )

Since we are using our own signature format based on EdDSA for signing Wasm modules, we should be able to make some minor changes and come up with something that would be supported by sigstore, so that we could benefit from its ecosystem, mainly the command line tool to upload / verify signatures, and corresponding verifiable log infrastructure.

There are a few options that sigstore supports, detailed here: https://github.com/sigstore/rekor/tree/main/pkg/pki

I think for Oak, the closest to what we already have would be minisign / signify, since they are already based on Ed25519 anyways.

**Comment by dlorenc** [comment]
So our "format" here is really just:
* signature bytes (base64 encoded)
* a PEM encoded PKIX public key
* and the signed content (either the hash or the whole thing, depending on how you use EdDSA)

I don't think you'll ned to do anything fancy. We used to use Ed25519 in https://github.com/sigstore/cosign actually, but switched to EcDSA for the hardware support. I'm happy to help out here if you can send me a pointer to the code or an example signature. I'm not as familiar with the rust crypto libraries but can try it out :)

**Comment by tiziano88** [comment]
Thanks for the offer to help @dlorenc !

The relevant code is mostly in https://github.com/project-oak/oak/blob/f3bcf8975acdebf91006bb2d5b7abc6b393c2237/oak_sign/src/lib.rs . BTW @ipetr0v is the main author of that functionality.

For the record, here are the some example keys we currently use:

https://github.com/project-oak/oak/blob/6f254e09d2968a5f548857d76f3b824fcb00f230/examples/keys/ed25519/test.key#L1-L4

https://github.com/project-oak/oak/blob/6f254e09d2968a5f548857d76f3b824fcb00f230/examples/keys/ed25519/test.pub#L1-L3

and an example signature bundle:

https://github.com/project-oak/oak/blob/f3bcf8975acdebf91006bb2d5b7abc6b393c2237/examples/private_set_intersection/private_set_intersection_handler.sign#L1-L12

**Comment by tiziano88** [comment]
for reference, thanks @dlorenc for providing this: https://play.golang.org/p/oi9NT53j5lv

**Comment by dlorenc** [comment]
Yup! The only "problem" with your format is the PUBLIC KEY pem block.

There are no "real" standards here, but https://tools.ietf.org/html/rfc7468 defines a simple wrapper for public keys called "PKIX" which includes a few bytes about what type of key it is (RSA, ECDSA, etc.). ED25519 keys are just bytes so it's easy to forget this step.

If you don't want to get into ASN stuff I'd suggest using a custom header here of something like OAK PUBLIC KEY or something else specific to ed25519 if you can find it.

**Comment by tiziano88** [comment]
Does rekor not care about what we put in the header?

**Comment by dlorenc** [comment]
Ah, for uploads to Rekor the easiest would be if you "correctly" use the PKIX format and the PUBLIC KEY header.

It's really trivial to swap between the formats though if you don't want to change your stuff here, so we would just have to do a bit of unpacking/packing.

I've forgotten to do the PKIX wrapping for ed25519 about 1000 times myself when working on this code too :)

**Comment by tiziano88** [comment]
Uhmm unfortunately I cannot seem to find a Rust library that has the equivalent of Go's `x509.MarshalPKIXPublicKey`. 

But it looks like the only difference between the current format and the expected one is a fixed prefix: https://play.golang.org/p/CFoRZxKxNWF

current key:

```
-----BEGIN PUBLIC KEY-----
f41SClNtR4i46v2Tuh1fQLbt/ZqRr1lENajCW92jyP4=
-----END PUBLIC KEY-----
```

correctly encoded key:

```
-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAf41SClNtR4i46v2Tuh1fQLbt/ZqRr1lENajCW92jyP4=
-----END PUBLIC KEY-----
```

The difference is the base64 string `MCowBQYDK2VwAyEA`, which I guess corresponds to this identifier: https://golang.org/src/crypto/x509/x509.go?s=3654:3712#L315 (though I have not checked). 

I am tempted to just hack this hardcoding the prefix, but I'll look around a bit more before going that way. Suggestions welcome :)

**Comment by dlorenc** [comment]
Heh - I'm no asn.1 expert but yeah it looks like the encoding is just a static object identifier. There's probably a general-purpose asn1 marshaller for rust, but if this works, go for it!

**Comment by tiziano88** [comment]
Ok I ended up pulling in a proper ASN.1 parser and it seems to work fine in Rust now. Is there a quick way of doing the same thing in C++ using BoringSSL that you know of @dlorenc ? or do I need to parse the ASN.1 struct manually there too?

**Comment by dlorenc** [comment]
No idea actually - I've never played with boringssl. Nice find on the asn1 parser though!

**Comment by tiziano88** [comment]
@daviddrysdale do you happen to know whether boringssl or tink support ASN1 parsing, or, even better, PKIX / x509 ed2559 public keys?

**Comment by daviddrysdale** [comment]
BoringSSL definitely has [ASN.1 parsing functionality](https://github.com/google/boringssl/blob/master/include/openssl/asn1.h), and it looks like there's a [helper for `SubjectPublicKeyInfo`](https://github.com/google/boringssl/blob/master/crypto/evp/evp_asn1.c#L98).   I don't think there's anything in Tink to deal with this though &ndash; Tink mostly avoids legacy formats.

AIUI standards-wise, [RFC 7468](https://tools.ietf.org/html/rfc7468#section-4) says that a PEM file with `BEGIN PUBLIC KEY` should contain an ASN.1 DER-encoded `SubjectPublicKeyInfo` structure from [RFC 5280](https://tools.ietf.org/html/rfc5280#section-4.1) (so the current Oak use of `BEGIN PUBLIC KEY` is technically incorrect).  

The relevant chunks of ASN.1 schema are:

```asn1
   SubjectPublicKeyInfo  ::=  SEQUENCE  {
        algorithm            AlgorithmIdentifier,
        subjectPublicKey     BIT STRING  }

   AlgorithmIdentifier  ::=  SEQUENCE  {
        algorithm               OBJECT IDENTIFIER,
        parameters              ANY DEFINED BY algorithm OPTIONAL  }
```

So for the example you gave earlier:
```
-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAf41SClNtR4i46v2Tuh1fQLbt/ZqRr1lENajCW92jyP4=
-----END PUBLIC KEY----
```
this decodes to hex:
```
302a300506032b65700321007f8d520a536d4788b8eafd93ba1d5f40b6edfd9a91af594435a8c25bdda3c8fe
```
which parses as ASN.1:
```
30 2a                : SEQUENCE len 42 (SubjectPublicKeyInfo)
    30 05            : SEQUENCE len 5 (AlgorithmIdentifier)
       06 03         : OBJECT IDENTIFIER len 3
          2b6570     : 1.3.101.112 = Ed25519
    03 21            : BIT STRING len 33
       00            : number of padding bits at end of content
       7f8d520a536d4788b8eafd93ba1d5f40b6edfd9a91af594435a8c25bdda3c8fe
```

So as long as the lengths don't change it should be a fairly stable prefix.

**Comment by tiziano88** [comment]
Thanks @daviddrysdale ! I think https://github.com/project-oak/oak/pull/1914/ already implements the correct format for the public key in the Rust as per RFC 7468 , as you suggest. I'll look into the functions you pointed out, it seems they should indeed help for C++.
