### ISSUE TITLE
"Oak Functions" loader

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1919]
Tracking issue for a new binary for running "Oak Functions" in the context of an HTTP server. Naming is still TBD, but I suggest `oak_functions_loader`, with corresponding top-level folder to hold its code, and sharing as much code as possible with the rest of Oak (e.g. the Wasm engine, etc.).

Conceptually, this loader is a simple HTTP server; no need to support TLS to start with, let's target running on https://cloud.google.com/run , which handles TLS termination.

For each incoming user request, the loader spawns a new Wasm engine instance with a single Wasm module loaded, and starts executing that. The ABI for these Wasm modules is TBD, in particular it will probably be a custom version of the Oak ABI, including only a subset of functions.

At high level, the functionality made available to Wasm modules includes the following:

- read HTTP request
- write HTTP response
- lookup data from a side-loaded key / value map

Only unary requests are supported, no streaming.

No persistent storage is supported.

We will probably need other issues to track more specific features; I just created the https://github.com/project-oak/oak/labels/Oak%20Functions label and https://github.com/project-oak/oak/milestone/8 milestone for planning.

**Comment by rbehjati** [comment]
I think this can be done in the following small steps:
1. A simple HTTP server that spawns a new wasm engine for every request and runs a very simple input wasm module.
2. Add ABI and SDK functionality for reading the request and writing the response. With this, more interesting wasm modules could be loaded. 
3. Add support for simple policies (e.g., `constant_response_size_bytes` and `constant_process_time_millis`). 
4. Add support for loading key/value maps and lookups. For v0, the map will be loaded only once at startup. It will be non-refreshable, with all wasm engines having shared read access to it. 

Is there anything else that we need to cover in v0?

**Comment by tiziano88** [comment]
we should also think of how to support this ABI in the SDK; we could either have a separate version of the ABI and SDK, or use features to control what gets exposed, or something else...

Cloud Run does not support languages directly, it just runs Docker images, so yes we would need a Dockerfile for deployment.

**Comment by rbehjati** [comment]
I think it would be easier to have a separate ABI and SDK. But it might be easier to decide after the first step, when we have a working loader.

**Comment by tiziano88** [comment]
Thinking of the shape of the new binary: I am thinking it will have the following main flags provided:

- listen address (HTTP / gRPC)
- metrics exporter endpoint
- wasm module of the function to invoke
- fixed configuration parameters (similar to the defense in depth configuration in oak_loader)
- (eventually) data to side load for lookups

Is there anything else missing?

**Comment by rbehjati** [comment]
With the wasm module we also need a function name. Or do we assume that the wasm modules have a specific function, e.g., `oak_main`?

Do we need gRPC support?

**Comment by tiziano88** [comment]
I think a well known function name works, we don't have the requirement of packing multiple entry points in a single Wasm file here.

I think we should start with HTTP only for now.

**Comment by rbehjati** [comment]
This is almost done, perhaps apart from the monitoring part. But I think with get some basic monitoring from Cloud Run.
