### ISSUE TITLE
Side loading data for lookup in Oak Functions Loader

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1930]
Initially we will implement the Oak Functions Loader so that it loads all the data for lookup at startup from a file, and that stays immutable for the lifetime of the loader itself.

In the not-so-distant future though we need to figure a way to have the data periodically refreshed. I think there are two 
fundamental approaches to consider:

## push

An external service periodically pushes a new version of the dataset (over HTTP or gRPC) to the loader.

An advantage of this approach is that it can only update a subset of the dataset if desired.

## pull

The loader periodically calls another server (over HTTP or gRPC) and downloads a new version of the entire dataset, which replaces the previous one.

An advantage of this approach is that there is no need for the loader to authenticate incoming requests to update the data.

---

Are there other approaches to consider? Which one would we want to go with? I think so far the pull approach seems simpler to me, especially because it does not need authentication and authorization for the updates.

@rbehjati @ipetr0v

**Comment by rbehjati** [comment]
I also think that pull is simpler, but perhaps this is a decision that should be made for each application depending on the size of the data and frequency of the changes. I think we could start with pull and then add support for push later if needed.

**Comment by tiziano88** [comment]
SG, what format should we use for the key / value list of entries? In Google we would normally use an [sstable](https://www.quora.com/What-is-an-SSTable-in-Googles-internal-infrastructure) for this, not sure what the open source equivalent is.

**Comment by tiziano88** [comment]
FTR, we discussed that a viable approach could be to pre-process the data into the format of choice, and then serve it statically (e.g. on [Google Cloud Storage](https://cloud.google.com/storage)), and the Oak Functions Loader would periodically retrieve it from there behind a fixed URL. This decouples the format and preprocessing of the source data to a separate pipeline / process that does not need to be embedded in the Oak Functions Loader itself.

**Comment by tiziano88** [comment]
Some potentially relevant references:

- https://cloud.google.com/datastore/docs/export-import-entities
- https://cloud.google.com/firestore/docs/reference/rest/v1/projects.databases
- https://github.com/google/leveldb/blob/master/doc/log_format.md

**Comment by tiziano88** [comment]
I think we should just define our own protobuf format for a key / value holder, and use https://docs.rs/prost/0.7.0/prost/fn.decode_length_delimiter.html to iteratively read subsequent values from a buffer that contains such records back-to-back.

The format can be as simple as

```proto
message Entry {
  bytes key = 1;
  bytes value = 2;
}
```

WDYT @rbehjati @ipetr0v ?

**Comment by ipetr0v** [comment]
> I think we should just define our own protobuf format for a key / value holder, and use https://docs.rs/prost/0.7.0/prost/fn.decode_length_delimiter.html to iteratively read subsequent values from a buffer that contains such records back-to-back ...

Does it mean, that the datastore will not be a hashmap?

**Comment by tiziano88** [comment]
> Does it mean, that the datastore will not be a hashmap?

Yes it is a Rust hashmap. I was talking about the format used to serialize the records into a file so that the Functions loader can load them (either from a local file, or periodically from a URL).
