### ISSUE TITLE
Oak Functions Wasm ABI

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#1935]
Let's use this issue to finalize the desired ABI at the Wasm level.

cc @rbehjati @ipetr0v 

From a hypothetical Rust SDK we would expect to expose the following high-level functions:

```rust
fn read_request() -> Result<Vec<u8>> {}
fn write_response(response: &[u8]) -> Result<()> {}
fn storage_get_item(key: &[u8]) -> Result<Vec<u8>> {}
```

So perhaps we can start from those and work backwards to the Wasm ABI.

We should also consider how much / whether to share with the existing Oak ABI. For instance, `read_request` and `write_response` may just map to the existing `channel_read` and `channel_write`, even if they may have a slightly different semantics, and only bytes (no handles) being moved around.

**Comment by rbehjati** [comment]
I don't see a benefit in sharing with the existing Oak ABI. Since we are not going to use the existing `Runtime` nor the `WasmNode`, it would be more straightforward and more maintainable to have direct ABI counterparts for the SDK functions listed above.

**Comment by tiziano88** [comment]
The benefit would be that the Oak functions ABI and SDK would be a strict subset of the regular Oak ones, so regular Oak could just include them instead of re-implementing them twice. Anyways, the ABI is pretty minimal so I think it's fine to keep them separate if you prefer.

**Comment by ipetr0v** [comment]
Does it mean that the regular Oak Runtime should also implement a read-only data store?

**Comment by ipetr0v** [comment]
> I don't see a benefit in sharing with the existing Oak ABI. Since we are not going to use the existing Runtime nor the WasmNode, it would be more straightforward and more maintainable to have direct ABI counterparts for the SDK functions listed above.

I think we also could try to reuse the same SDK that we use in regular Oak modules (e.g. `Receiver` and `Sender`)

**Comment by ipetr0v** [comment]
Also, it we plan to have a "one-shot" functions, why do we need `fn read_request()` ?
Should we just pass the request to the `main` functions instead?

Also, by the same logic, instead of having a `fn write_response()` function, we can just return data from `main`.

**Comment by tiziano88** [comment]
> Does it mean that the regular Oak Runtime should also implement a read-only data store?

For now the priority is to work on the Functions loader, let's not worry about back-porting functionality to the regular runtime.

**Comment by tiziano88** [comment]
> Also, it we plan to have a "one-shot" functions, why do we need `fn read_request()` ?
> Should we just pass the request to the `main` functions instead?
> 
> Also, by the same logic, instead of having a `fn write_response()` function, we can just return data from `main`.

Yes that's also an option, but keep in mind you cannot pass an array as argument to a function, nor get it back as result, right?

**Comment by ipetr0v** [comment]
> Yes that's also an option, but keep in mind you cannot pass an array as argument to a function, nor get it back as result, right?

I think this could be a part of SDK, where devs just write a macro, that has an `input: ...` argument. And in the background it will we a `main` function that calls `read_request`.
Similar to how it's already done in Oak.

**Comment by tiziano88** [comment]
Yes we can definitely have wrappers in the SDK, I was talking about the ABI.

**Comment by rbehjati** [comment]
> The benefit would be that the Oak functions ABI and SDK would be a strict subset of the regular Oak ones, so regular Oak could just include them instead of re-implementing them twice. Anyways, the ABI is pretty minimal so I think it's fine to keep them separate if you prefer.

IIUC, the main ABI functionality is implemented in `WasmInterface` in `oak_runtime/src/node/wasm/mod.rs`, and this struct relies on the Runtime for some of its functionality. With the current design re-implementing some ABI functionality for Oak functions is inevitable. However, some basic functionality in `WasmInterface` (e.g., `get_memory` or `fetch_bytes`) don't  use the Runtime. Are you suggesting that we refactor that part into a class that can be used both in the existing Runtime and in Oak functions?

**Comment by rbehjati** [comment]
> I think we also could try to reuse the same SDK that we use in regular Oak modules (e.g. `Receiver` and `Sender`)

I might be missing something, but I thought the plan for Oak functions, at least for now, is to have only a single Wasm instance (resembling a single WasmNode in the existing Oak Runtime), no channels and no pseudo-nodes. So, I am not sure how `Receiver` and `Sender` from the existing SDK would be needed.

**Comment by tiziano88** [comment]
> Are you suggesting that we refactor that part into a class that can be used both in the existing Runtime and in Oak functions?

I think that would be good, but not essential. Maybe let's start with a separate version (copy-pasted if necessary, and with pointers to where it came from in comments), and later on let's figure out whether to unify some functionality into a separate crate shared by the existing runtime and the Functions loader.

> I might be missing something, but I thought the plan for Oak functions, at least for now, is to have only a single Wasm instance (resembling a single WasmNode in the existing Oak Runtime), no channels and no pseudo-nodes. So, I am not sure how `Receiver` and `Sender` from the existing SDK would be needed.

I think even with the limited functionality for the Functions loader, the concepts of reading and writing (or receiving and sending) would still apply, even without having a way of passing handles around. Like in Unix applications you expect to read and write from file descriptors, and some of them are special (e.g. stdin, stdout). Here we may have something like: handle 0 is where you read / receive the request, and handle 1 is where you write the response, and handle 2 is where you write metrics (just as an example).

Admittedly this does not work very well for the storage lookup function, which is more like an RPC than a single read / write, so perhaps that would be its own ABI.

Happy to consider alternatives though, it seems each has its pros and cons.

**Comment by ipetr0v** [comment]
Are we planning to serve gRPC or HTTP services via Oak Functions?

**Comment by tiziano88** [comment]
HTTP should be enough, each Oak Function does exactly one thing anyways, so having a gRPC service definition does not seem particularly useful.

**Comment by ipetr0v** [comment]
The problem with HTTP is that we cannot send `Request` in the GET HTTP request.
It probably would need to be encoded in the URL string.
And if we want to use Protobuf for `Request` it's probably very problematic to encoded it into the URL.

**Comment by tiziano88** [comment]
> The problem with HTTP is that we cannot send `Request` in the GET HTTP request.
> It probably would need to be encoded in the URL string.
> And if we want to use Protobuf for `Request` it's probably very problematic to encoded it into the URL.

I think for the weather example encoding an individual location in the URL is simpler than using protobuf anyways, so perhaps we should start with that.

In general I agree though, for instance if we expect the client to send a picture or some other data, URL encoding is not great. Maybe we should just use POST for everything? Or, we could expose a gRPC service from the oak functions loader, but in which the schema is baked in the oak functions loader itself (e.g. `rpc Call(CallRequest) returns CallResponse`), in which they payload to pass to the Wasm function is just a bytes field in the request.

> And the Wasm module would need to serve different URL paths, i.e. `oak.io/weather`, `oak.io/forecast` etc. Instead of reading the request from the ABI.

The Wasm module would either get the full HTTP request, in which case it could differentiate the functionality based on the URL path, or it would just get the payload, in which case the functionality would need to be included as part of the request payload itself.

**Comment by ipetr0v** [comment]
> Maybe we should just use POST for everything?

POST is used for updating data, so it would be a deviation from HTTP guidelines.

> Or, we could expose a gRPC service from the oak functions loader, but in which the schema is baked in the oak functions loader itself

Should we try to use the same mechanism we use in Oak gRPC server node?

> The Wasm module would either get the full HTTP request

Does it mean that the `Vec<u8>` from `fn read_request()` will be bytes of raw HTTP request?

**Comment by tiziano88** [comment]
Let's take a step back. For the weather example, if it were a stand alone HTTP server, what would we use as request method?

**Comment by ipetr0v** [comment]
It would be a REST application where GET requests would be sent to `/city_weather` with a parameter `?city_name=X`

**Comment by tiziano88** [comment]
how about if it was processing a large image, for instance detecting a barcode or something like that?

**Comment by ipetr0v** [comment]
I would probably send a `POST` message to submit a large image, which will return a ID.
And then use this ID in `GET` to request the result of image processing.

**Comment by tiziano88** [comment]
That seems quite inefficient and stateful, and only works if there is persistent server-side storage or strong session stickiness. Personally in a case like this I would not worry about breaking HTTP semantics. In fact, doesn't gRPC basically use POST for everything?

**Comment by tiziano88** [comment]
Also some of the URL paths are going to be reserved for things like remote attestation (e.g. `/report` or similar), so I think we should assume that a Oak Functions service has a single endpoint that actually passes the data to the Wasm function. For instance `/run` (or I hope we can come up with a better name). Then the contract is that the client always does a `POST /run`, in which the HTTP headers are used to control the policy, and the body of the request is the only thing that gets passed to the Wasm module to invoke. The Wasm module only sees the raw bytes of the body, and nothing else, and replies with the raw bytes of the response to send back to the client.

WDYT?

**Comment by tiziano88** [comment]
basically I would like to be able to invoke an Oak Function with curl, like:

```
curl --header "Oak-Policy: ..." \
  --request POST \
  --data '{ "city": "London" }' \
  https://example-function/run
```

**Comment by ipetr0v** [comment]
> basically I would like to be able to invoke an Oak Function with curl, like:

SGTM

**Comment by tiziano88** [comment]
Maybe `/invoke` instead of `/run`.

**Comment by tiziano88** [comment]
FTR I'm starting to encapsulate the Wasm logic so the ABI will be easier to implement later on (I'm not adding any ABI yet).

**Comment by tiziano88** [comment]
Just came across this: https://github.com/proxy-wasm/spec/tree/master/abi-versions/vNEXT
