### ISSUE TITLE
Add an abitest example for oak-functions

### ISSUE THREAD

**Issue by rbehjati** [project-oak/oak#1963]
Similar to the existing `abitest` we need an example to test oak-functions' ABI functions. 
Ref: https://github.com/project-oak/oak/pull/1958#pullrequestreview-634991559 

Some scenarios to include:
- What happens if the abi functions are called more than once

**Comment by ipetr0v** [comment]
> What happens if the abi functions are called more than once

What should happen in this case (not for the `storage_get_item`)?

**Comment by rbehjati** [comment]
We have documented: https://project-oak.github.io/oak/oak_functions/sdk/

For `read_request`: This function is idempotent. Multiple call to this function all return the same value.
For `write_response`: Multiple calls to this function will replace the earlier responses. Only the last response that is written will be kept and returned to the user.
