### ISSUE TITLE
Make maximum log level  for oak-functions configurable

### ISSUE THREAD

**Issue by conradgrobler** [project-oak/oak#1971]
The current logger defaults to using `Info` as the maximum log level. It would be useful to make this configurable via a command-lin flag or in the configuration file.

**Comment by tiziano88** [comment]
@conradgrobler I think we don't need this any more, since we only log at a fixed level from Wasm modules, right?

**Comment by conradgrobler** [comment]
At the moment the level defaults to Debug rather than Info, as the Wasm module logs are seen as Debug. This might still be useful if we want to filter in future to only show warnings and errors from within the runtime, or disable all logging.

**Comment by tiziano88** [comment]
Got it, so perhaps we can just add an entry to the config file to specify this, right?
