### ISSUE TITLE
Load testing of Oak functions

### ISSUE THREAD

**Issue by rbehjati** [project-oak/oak#1986]

**Comment by rbehjati** [comment]
@tiziano88 Previously I have used [Gatling](https://gatling.io/) for load testing.
It has many [advanced features](https://gatling.io/docs/current/cheat-sheet/), for example it allows simulating an interactive session between a user and a server, or defining different types of users. Our scenario seems to be a lot simpler. I believe we have only type of user, and the user sends only one request. We could still use Gatling, for example for simulating ramp ups in the number of users:
```java
setUp(
  // Increase the number of users to 1000 within 10 seconds.
  users.inject(rampUsers(1000).during(10.seconds)),
  admins.inject(rampUsers(2000).during(10.seconds))
).protocols(httpProtocol)
```
or to use its extensive [reporting](https://gatling.io/docs/current/general/reports/).

**Comment by tiziano88** [comment]
Thanks! I also just found this https://github.com/fcsonline/drill
