### ISSUE TITLE
Consider using tokio::signal in the loaders

### ISSUE THREAD

**Issue by rbehjati** [project-oak/oak#1994]
Consider using `tokio::signal` (similar to what we have in tests) for safe handling of the signals in `oak_loader` and `oak_functions_loader`.

_Originally posted by @tiziano88 in https://github.com/project-oak/oak/pull/1979#discussion_r616577361_

**Comment by conradgrobler** [comment]
These monolithic loaders have been deleted and the Oak Functions launcher uses `tokio::signal`.
