### ISSUE TITLE
Use custom Request and Response body for Oak Functions

### ISSUE THREAD

**Issue by rbehjati** [project-oak/oak#2032]
I wonder if we should reconsider the overall approach slightly; instead of basing it on HTTP semantics, we may want our own Request and Response objects, and always return an HTTP OK response.

For instance, the Request message may encapsulate the request body and the policy, and the Response message may encapsulate the response body, the response code, the padding, and eventually additional information (e.g. logs to be sent to the client). Let's not block on it for this PR, but WDYT about that?

_Originally posted by @tiziano88 in https://github.com/project-oak/oak/pull/2011#discussion_r622233572_

**Comment by conradgrobler** [comment]
I thinkg this will be a good improvement. If the response body is always the same size and the response headers do not depend at all on the content of the request or the processing of the Wasm code it should make the policy enforcement much more precise.

**Comment by tiziano88** [comment]
I guess since we already protobuf generated code in the server (for the status enum), we may as well use protobuf objects for this too.
