### ISSUE TITLE
Implement client Keying Material export

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#2048]
After finishing https://github.com/project-oak/oak/pull/1946 we need to implement assertion generation (Keying Material export) on the client side of TLS connections. And also implement assertion negotiation, as described in https://github.com/project-oak/oak/pull/1929.

Currently complicated by https://github.com/hyperium/hyper/issues/2463

**Comment by conradgrobler** [comment]
We deleted the HTTPS attestation implementation, so this is no longer relevant.
