### ISSUE TITLE
Inconsistent view of in-memory lookup data while a Wasm function executes

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#2050]
Because of the way the Oak Functions loader refreshes data in the background, it might happen that if a Wasm module performs multiple lookups, a new version of the lookup data might become available between lookups from the same invocation, which may result in inconsistent behaviour of the module.

We could solve this by acquiring a Read lock on the data at invocation time (or the first time the module invokes the lookup ABI function), and hold it until the invocation is terminated (instead of acquiring it and releasing it as part of each lookup ABI call).

When the loader needs to update the data from the background process, it would still acquire a write lock for it, which would be guaranteed to be exclusive. This is fine because this write lock would be held for a very short time (just to swap the reference behind it), so there should not be too much contention.

I am not sure what priority the read and write portion of the RWLock would get though, and whether it is possible that the background process would starve if there is a constant stream of requests that keep requesting the read lock, or if the write lock has higher priority (and with what characteristics).

**Comment by conradgrobler** [comment]
Another option might be to give each Wasm state instance a new cloned Arc pointing to the hashtable for its lookups. When the data is refreshed, it can create a new Arc to a new hashtable which would be cloned for new incoming requests. The existing requests would still reference the previous hashtable, but once all of them have completed the previous hash table will be dropped. This might mean that there are two distinct hash tables in memory for a short time, but this should be acceptable for most scenarios.

**Comment by tiziano88** [comment]
@anghelcovici interested in taking a look? assigning to you for the time being so we don't duplicate work, feel free to un-assign if you don't have time to look into it

**Comment by anghelcovici** [comment]
Sure, thanks for assigning.

**Comment by mariaschett** [comment]
@conradgrobler @tiziano88 I added a (failing) test in https://github.com/project-oak/oak/pull/2425/files. 

Do you think the test has the behaviour we are looking for, i.e., during the lifetime of a WasmModule the lookup data remains unchanged?

**Comment by conradgrobler** [comment]
Yes, I think so. It is not 100% representative of how the runtime works in practice, but I think it replicates the behaviour well enough to be used as a test to validate that a fix provides the expected result.

**Comment by mariaschett** [comment]
Clarification: do we want the lookup data to be consistent during (a) the lifetime of a WasmHandler (as in the test atm), or (b) during a call to `handle_invoke()`? 

Background: I tried "to give each Wasm state instance a new cloned Arc pointing to the hashtable for its lookups", as [you suggested](https://github.com/project-oak/oak/issues/2050#issuecomment-830173655), @conradgrobler, i.e., lookup_data in [WasmState](https://github.com/project-oak/oak/blob/c33c4e80e589f315c79f2b4c7fd692abab580b2a/oak_functions/loader/src/server.rs#L143) points to the hashtable and has type `Arc<HashMap<Vec<u8>, Vec<u8>>>`.
 
But, as `handle_invoke` [creates a new WasmState](https://github.com/project-oak/oak/blob/c33c4e80e589f315c79f2b4c7fd692abab580b2a/oak_functions/loader/src/server.rs#L619) from the WasmHandler's lookup data---and this lookup data may change during the lifetime of a WasmHandler. 

Now, to rephrase my question: (a) change my test, or (b) change the WasmHandler to not keep a reference to the LookupData but to the LookupData*Entries* (i.e., `Arc<HashMap<Vec<u8>, Vec<u8>>>`)

**Comment by tiziano88** [comment]
I think in order to work out correctly, the Arc needs to be re-created every time from the current lookup data (instead of updating the lookup data instance internally, which would make the outer Arc useless). So for instance, instead of the refresh method mutating the lookup data instance, it should return a new instance -- or better, there should be a top-level function that returns new instances (more functional / less OOP :) ). But I am not sure I remember the difference between the lifetime of the WasmHandler and handle_invoke, I'll take a closer look.
