### ISSUE TITLE
The cancel workflow cancels existing post-merge runs from other users if two PRs are merged close together

### ISSUE THREAD

**Issue by conradgrobler** [project-oak/oak#2056]
It is probably a good idea for the cancel workflow to only cancel workflows related to PRs.

If post-merge workflows from one user is running and another user merges a different PR, the currently running post-merge worflow is canceled.

See for example https://github.com/project-oak/oak/actions/runs/809589091

This means that the reproducibility index might not be updated for each individual merged PR.

**Comment by rbehjati** [comment]
We can probably solve this by replacing

```
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
```

 with 

```
concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
```

And use `github.run_id` as the [fallback](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-fallback-value).

**Comment by rbehjati** [comment]
Closing this as I think #3409 has fixed it. Let me know if you still see a problem.
