### ISSUE TITLE
Implement challenge-response in gRPC Attestation

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#2105]
Currently https://github.com/project-oak/oak/pull/2070 has the possibility of replay attacks, because client cannot check that the ephemeral key generated by server is a new one. I.e. if server's key is leaked, the attacker can just replay the server response that attests the compromised ephemeral key for other clients.

We need to implement a challenge-response mechanism that happens before the key exchange.

Original comment: https://github.com/project-oak/oak/pull/2070#discussion_r634478047

**Comment by ipetr0v** [comment]
If I understand correctly, the challenge response can be incorporated in the existing protocol messages. I.e. instead of:
```
- Client sends a streaming gRPC request with its public key to the Server
- Server sends its public key, a TEE report and Provider's certificate to the Client
    - Where TEE report contains a hash of the public key
    - TEE report is signed by the TEE firmware
```
We will have:
```
- Client sends a streaming gRPC request with its public key and a random challenge string to the Server
- Server sends its public key, a TEE report and Provider's certificate to the Client
    - Where TEE report contains a hash of the public key and a client provided random challenge string
    - TEE report is signed by the TEE firmware
```

**Comment by ipetr0v** [comment]
cc @tiziano88 @sidtelang

**Comment by tiziano88** [comment]
Can the server just use the client public key as nonce, and basically get both public keys attested at once, and return that report to the client?

**Comment by ipetr0v** [comment]
And this shouldn't be a nonce, but just a hash of the client's public in the TEE report.
Nonces should be unique for every message.

**Comment by tiziano88** [comment]
> Is there any possibly future requirement that the server authenticate the client?
> e.g. the TEE stores data (like E2EE keys) for many users and needs to retrieve one for the authenticated user in the request?
> If so, then the client ephemeral key should be bound to a server-issued random challenge too, to ensure it is fresh and not being replayed.
> 
> BTW I fixed the link to the writeup for our handshaker: go/sc-handshaker (it's a small section in a much bigger doc)

Yes, we would like the protocol to support bidirectional attestation eventually (in fact, zero or more attestations for either side).

**Comment by conradgrobler** [comment]
We are no longer using the interactive attestation between clients and server.
