### ISSUE TITLE
Support various claims in gRPC Attestation

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#2106]
Currently in https://github.com/project-oak/oak/pull/2070 server returns `ServerIdentity` that can only contain TEE firmware attestation:
```protobuf
message ServerIdentity {
  // Server public key needed to establish a session key between client and server.
  bytes public_key = 1;
  // Information used for remote attestation such as a TEE report and a TEE provider's certificate.
  // TEE report should contain a hash of the server's public key.
  bytes attestation_info = 2;
}
```

In order to support multiple various TEEs, we need to have a `repeated Claim claims` field in Protobuf.

Original comment: https://github.com/project-oak/oak/pull/2070#discussion_r632668811

**Comment by conradgrobler** [comment]
We are no longer using the interactive attestation between client and server.
