### ISSUE TITLE
Fix logging in oak_functions/client

### ISSUE THREAD

**Issue by rbehjati** [project-oak/oak#2136]
The string formatting in the following line does not work: https://github.com/project-oak/oak/blob/c34a0abccc80b91c949abd53e801c2bb20530839/oak_functions/client/java/src/AttestationClient.java#L53

I think, this formatting only works with [SLF4J](http://www.slf4j.org/manual.html) or some manual formatter libraries.

**Comment by rbehjati** [comment]
@ipetr0v Could you please take a look?

**Comment by ipetr0v** [comment]
Since this library has only 2 calls to the `Logger` - removing it completely and use `System.out.printf`

**Comment by rbehjati** [comment]
Alternatively, since the logs are simple, you could keep the `logger` and build the string using the `+` operator,  instead of using `System.out.printf`:
```java
logger.log(Level.WARNING, "Couldn't receive response: " + status); 
```
