### ISSUE TITLE
Allow users specify policies in Oak Functions requests 

### ISSUE THREAD

**Issue by rbehjati** [project-oak/oak#2144]
Extend the custom Oak Functions `Request` (see #2032) with fields for specifying the policy. 
This is in addition to the policy on the server. We will fallback to the server's policy if needed (e.g., if user's policy is invalid).

**Comment by rbehjati** [comment]
I think this can be closed in favour of #2243 and #2248. WDYT @tiziano88 @conradgrobler?

**Comment by conradgrobler** [comment]
I think thereis still a use for this (unless there is another issue that covers that scenario): for debug purposes the client should be able to request a larger response size to support sending logs back to the client.

**Comment by rbehjati** [comment]
That is a good point. Does not seem that we have another issue for sending logs to the client. So, let's keep this one for now.

**Comment by rbehjati** [comment]
We were also discussing the possibility of allowing the client to specify some privileges, e.g. client wants to use the service but does not want to allow metrics logging if the privacy budget is too high. I think this only makes sense for metrics, but not other features such as TensorFlow support. We should also consider the added complexity of this feature (simply dropping the connection is less error prone than having conditional statements that are affected by several input sources).

**Comment by tiziano88** [comment]
I'm happy with either closing this, or keeping it in a backlog for future reference (not in Functions v0/1), but without concrete plans for implementation yet.

**Comment by tiziano88** [comment]
Not planned.
