### ISSUE TITLE
Support API for native inference via TensorFlow models

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#2236]
https://github.com/sonos/tract seems a good library for this

Thanks to @dominic-mulligan-arm for providing https://github.com/veracruz-project/veracruz/pull/159 as reference

**Comment by rbehjati** [comment]
We can do this by adding an ABI function (with SDK support in Rust) that:
- Assumes a TensorFlow model is loaded by the Oak Functions Loader. A path/URI to the model should be specified in a `config.toml` file similar to the config for the lookup data.
- Has two parameters: a byte array, and a vector specifying the shape of the Tensor. The shape is used to reshape the byte array into a Tensor that can be used for inference by the TensorFlow model. With this design, the WebAssembly developer must ensure that the Tensor shape matches the loaded model's expectation. Alternatively, the Tensor shape could also be specified in `config.toml`. But even in this case, the WebAssembly module must ensure the byte array can be correctly reshaped.

We can later extend this ABI by allowing multiple models, where each model has a unique identified specified in the `config.toml` file. The ABI function should then be extended to accept another parameter specifying the model.

**Comment by conradgrobler** [comment]
This has been superceded by the TFLM implementation.
