### ISSUE TITLE
Investigate integrating Wasmi fuzzers with OSS Fuzz 

### ISSUE THREAD

**Issue by conradgrobler** [project-oak/oak#2269]
Wasmi already provides fuzzers (https://github.com/paritytech/wasmi/tree/master/hfuzz and https://github.com/paritytech/wasmi/tree/master/fuzz). It might be a good idea to integrate these with OSS Fuzz (https://github.com/google/oss-fuzz/) to enable continuous fuzzing.

**Comment by tiziano88** [comment]
Should we ask them directly on their repository first?

**Comment by conradgrobler** [comment]
Yes, makes sense. I was unsure whether OSS Fuzz easily supports cargo fuzz, so I thoutht it would require some initial investigation. But it looks like OSS Fuzz already can support it: https://google.github.io/oss-fuzz/getting-started/new-project-guide/rust-lang/

**Comment by conradgrobler** [comment]
Fuzzing Wasmi did not prove very useful, so closing this.
