### ISSUE TITLE
Make metrics support in Oak Functions an extension  

### ISSUE THREAD

**Issue by rbehjati** [project-oak/oak#2289]
Similar to the TensorFlow support. See #2278.
Add feature gating support for it.

**Comment by rbehjati** [comment]
@tiziano88 @conradgrobler So far my assumption was that the extensions are stateless. But `PrivateMetricsProxy` has an internal state that should be maintained during the Wasm invocation. I think we could have extension factories in `WasmHandler` that create instances of `OakApiNativeExtension` (or `BoxedExtension`) when creating a `WasmState`: 
https://github.com/project-oak/oak/blob/24fef4d14e1d0153c90d9ca3d7fc52b010d41327/oak_functions/loader/src/server.rs#L708-L726

The `ExtensionFactory` can be very simple with just a single create method:
```rust
pub trait ExtensionFactory {
    fn create(&self) -> anyhow::Result<BoxedExtension>;
}
```

What do you think?

**Comment by conradgrobler** [comment]
It seems Lika good approach for now. At some point we should consider refactoring this a bit so that the state is stored independently of the Wasm handler, seeing that we might also want to make the Wasm handler optional in the future.
