### ISSUE TITLE
Add Frame struct to remote attestation messages

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#2295]
Currently every message in the remote attestation protocol has it's own serialized `header`.
We can unify this by creating a higher level `Frame` struct, that will include all of the protocol messages.

Originated from https://github.com/project-oak/oak/pull/2293#discussion_r712912443

**Comment by conradgrobler** [comment]
The serialization and deserialization implementation for the messages have changed, so this is no longer relevant.
