### ISSUE TITLE
Make Oak Functions examples hermetic

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#2306]
Currently they rely on downloading lookup data over the internet; we should change them so that they either load it from a local file, or create a local server that serves the data over HTTP.

e.g.

https://github.com/project-oak/oak/blob/9db00dd2ece9ed75cf93a4f6dda9fa3a2768b853/oak_functions/examples/weather_lookup/config.toml#L1

**Comment by ipetr0v** [comment]
`oak_loader` already supports loading files:
https://github.com/project-oak/oak/blob/8b8e58925fed321f3a953855ca6be92af9318455/oak_functions/loader/src/main.rs#L56

**Comment by tiziano88** [comment]
We should still have some tests exercise the HTTP download logic, even just from a local server.

**Comment by conradgrobler** [comment]
The examples and tests no longer download the lookup data over the internet.
