### ISSUE TITLE
Change LookupData entries from a hash map to a B-tree map

### ISSUE THREAD

**Issue by mariaschett** [project-oak/oak#2317]
Changing [LookupData entries](https://github.com/project-oak/oak/blob/4f2063aea9fc8afa123617d1bf9e518b58469562/oak_functions/loader/src/lookup.rs#L49) from a hash map to a B-tree map as a preceding step to [#2202](https://github.com/project-oak/oak/issues/2202) to ensure no regressions.

**Comment by tiziano88** [comment]
Ah good point, I forgot about that! Interesting to note that the benchmark is expected to take the same amount of time (20ms) for both 10k and 200k entries, so presumably what slows it down is really the data generation? Or does each iteration actually take substantially longer in the 200k case, and 20ms is just an upper bound?

**Comment by mariaschett** [comment]
Is this still relevant?

**Comment by conradgrobler** [comment]
I think that having this as an option for lookup data would still be useful, but I don't think this is a high priority at the moment.

**Comment by conradgrobler** [comment]
I don't think this is relevant at the moment. I will close this for now and we can create a new issue if we have a specific need for this in future.
