### ISSUE TITLE
Use deterministic seed for randomness in benchmarks

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#2318]
https://github.com/project-oak/oak/blob/4f2063aea9fc8afa123617d1bf9e518b58469562/oak_functions/examples/weather_lookup/module/src/tests.rs#L196

I think we should avoid using "real" randomness in tests, and especially in benchmarks, which are expected to converge. So perhaps we should consider a fixed-seed RNG (see https://docs.rs/rand/0.8.4/rand/trait.SeedableRng.html#tymethod.from_seed ).

**Comment by mariaschett** [comment]
We could also use either a pseudo random generator, e.g., [rand_pcg](https://docs.rs/rand_pcg/0.2.1/rand_pcg/), or following [1](https://rust-random.github.io/rand/rand/rngs/struct.StdRng.html) "For a secure reproducible generator, we recommend use of the [rand_chacha](https://crates.io/crates/rand_chacha) crate directly." 

But I believe this would introduce another dependency?
