### ISSUE TITLE
Fail when verifying ServerIdentity if it has unknown fields

### ISSUE THREAD

**Issue by rbehjati** [project-oak/oak#2347]
Newer versions of Oak Functions server may introduce new fields in the definition of `ConfigurationInfo`. When parsing the server identity bytes on an older version of a client, these fields will appear as [unknown fields](https://developers.google.com/protocol-buffers/docs/proto3#unknowns). In such cases, the client may want to fail the verification and refuse to continue the interaction with the server. 

To support this, the verification logic on the client should be able to check the presence of unknown fields. It is not clear how this can be done using `prost` in the Rust client. Similar functionality is required in the Java clients. 

Also see https://github.com/project-oak/oak/pull/2254#discussion_r731131148 from @ipetr0v.

**Comment by tiziano88** [comment]
Not directly relevant to our latest client verification story.
