### ISSUE TITLE
Add additional info to ClientIdentity

### ISSUE THREAD

**Issue by rbehjati** [project-oak/oak#2354]
If we want to support bidirectional attestation, AdditionalInfo containing client configuration needs to be added to the `ClientIdentity`.

_Originally posted by @ipetr0v in https://github.com/project-oak/oak/pull/2254#discussion_r731131910_

**Comment by conradgrobler** [comment]
We are no longer using the interactive attestation between client and server, so adding ClientIdentity struct is no longer relevant.
