### ISSUE TITLE
Update `/scripts/runner run-ci`

### ISSUE THREAD

**Issue by mariaschett** [project-oak/oak#2390]
Update `/scripts/runner run-ci` to

- rename to reflect that it does not run all the CI
- add `run_cargo_fuzz` as step

**Comment by mariaschett** [comment]
Instead of renaming align with [workflows/ci.yaml](https://github.com/project-oak/oak/blob/main/.github/workflows/ci.yaml)

**Comment by rbehjati** [comment]
I think it is good to align `run-ci` with [workflows/ci.yaml](https://github.com/project-oak/oak/blob/main/.github/workflows/ci.yaml), but `run-ci` takes too long to be run locally regularly. It would be useful to have a `presubmit` command to run locally. This command could take a number of flags. For now I can think of a flag for distinguishing between `oak_functions` and `classic_oak`. For instance, we could run `./scripts/runner presubmit --target=oak_functions`. To be able to easily configure what should be run in the presubmit, we could have a `presubmit.toml` file in the root folder, describing the presubmit steps for each target. 
What do you think? cc @project-oak/core.

**Comment by conradgrobler** [comment]
I like the idea. It would make oak_functions changes much faster to check.

**Comment by mariaschett** [comment]
I definitely need some mechanism to check locally fast (<5 min) for common problems failing `run-ci` on github (e.g., format for me). 

So I think I am not clear on two things: 

1. What's fast for everyone?
2. What are "common problems"? Or how to determine them? Related idea: maybe we could extend the --commits= flag?

**Comment by rbehjati** [comment]
1. For me less than 5 min is usually fast enough. 
2. What do you mean by extending the `--commits=` flag? Do you mean adding it to more commands? It currently works for format.

**Comment by mariaschett** [comment]
> 2\. hat do you mean by extending the `--commits=` flag? Do you mean adding it to more commands? It currently works for format.

Perfect :) I'll need to explore the --commits flag more!

Maybe `--commits` is actually a pretty good `presubmit` already. What do you think?

**Comment by rbehjati** [comment]
I use `--commits` all the time. A separate `presubmit` might be easier, but not as flexible. 
In any case, I think it is still a good idea to align `run-ci` with the GitHub actions. The `presubmit` command can be a separate thing.

**Comment by rbehjati** [comment]
One benefit of a `presubmit` command is that we won't have to remember to run `run-cargo-fuzz --build-deps -- -max_total_time=2` to generate the latest `fuzzable.wasm` file.

**Comment by conradgrobler** [comment]
It would also be nice to have a `classic oak` version of the presubmit to update the hashes and signatures in the examples if these changed.

**Comment by mariaschett** [comment]
Moved discussion to #2403 .
