### ISSUE TITLE
Use bash completion for `./scripts/runner`

### ISSUE THREAD

**Issue by mariaschett** [project-oak/oak#2392]
`./scripts/runner completion` prints a bash completion script to stdout. 

To use it, we probably need to figure out where to write it to in our Docker container.

So far I have been unsuccessful with:

`./scripts/runner completion > ~/.bash_completion` (NB: contains too much output from runner) and `source ~/.bash_completion` 

__Links:__
* example of [gen_completion](https://github.com/TeXitoi/structopt/blob/master/examples/gen_completions.rs)

**Comment by mariaschett** [comment]
Autocompletion works with the following steps:

- move output of `./scripts/runner completion` into `~/.bash_completion`
- `source ~/.bash_completion`
- `export PATH=/workspace/scripts:$PATH`
- call runner with `runner` and tab-tab

**Comment by mariaschett** [comment]
@project-oak/core I have added the `/workspace/scripts` to `$PATH` in the Docker image and I have added `scripts/generate_bash_completion_for_runner`. 

I am missing a way to source the generated `bash_completion` file in runner within the Docker image. 

Does anyone have any ideas how?

**Comment by tiziano88** [comment]
Since the Docker image is used to build the runner binary in the first place, I don't think there is a straightforward way of getting the output of runner baked in the Docker image itself?

**Comment by mariaschett** [comment]
Yes, I realized that. :)

**Comment by tiziano88** [comment]
For now, I would say just add a script that makes the autocompletion available, after running a shell inside the Docker container. It should be good enough for most people; we can figure out later how to improve that in the future.

**Comment by mariaschett** [comment]
So everyone would have to run that script---let's call it `add_bash_completion_for_runner_in_docker`---every time the Docker image changes to modify their `.bashrc`---did I understand that correctly?

**Comment by tiziano88** [comment]
Yes something like that, but I don't think it is specific to Docker. Also it is actually a bit worse than that -- it would have to be re-run every time the Docker container is restarted, even if the image was not changed. And I don't think it should modify .bashrc, I was thinking it would just set up the completion for the currently active shell, but I may be misunderstanding how it works.

**Comment by mariaschett** [comment]
Why shouldn't we modify the .bashrc? 

A different solution would be to check the `runner_bash_completion` into the repo and add something like this to the Dockerfile:

```RUN echo "source <path-to-runner_bash_completion-in-repo>" >> /home/docker/.bashrc```

Then autocomplete should be available in every shell in the Docker container.

Caveat: `runner_bash_completion` may get outdated, but could be updated manually when we notice.
