### ISSUE TITLE
Harmonise the logic of the Java and Rust remote attestation clients

### ISSUE THREAD

**Issue by conradgrobler** [project-oak/oak#2420]
The Java and Rust remote attestation clients do not have the same behaviour. The Rust client works fine when no configuration information is speciffied, but the Java client fails.

**Comment by rbehjati** [comment]
I think the correct functionality is to fail when no configuration info is provided. So I think the Rust client must be updated.

**Comment by conradgrobler** [comment]
We are no longer using the interactive attestation protocol between client and server.
