### ISSUE TITLE
Consider running CI on PRs only for modified files

### ISSUE THREAD

**Issue by rbehjati** [project-oak/oak#2455]
Extends #2168 
See also #2403

To have faster CI on PRs we'd want to run the CI steps only for the modified files and the files affected by those modifications. We will still run the full CI on main, after merging a PR, to prevent untouched parts of the code base from rotting over time.

**Comment by rbehjati** [comment]
The main problem is that currently we checkout the repo with `--depth=1`, so it is not possible to get the list of modified files on GitHub. [Fetching the full history](https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches) with the following should fix this: 
```
- uses: actions/checkout@v2
  with:
    fetch-depth: 0
```

With this, it should be possible to use `git diff --name-only main` to get the list of all modified files in the branch.

**Comment by mariaschett** [comment]
To notify the team if the CI failed when merging on main, I see two options:

1. Use the github notifiaction mechanism and [add a notification on failure](https://stackoverflow.com/questions/62304258/github-actions-notifications-on-workflow-failure)

2. [Send an email notifiaction](https://ravgeetdhillon.medium.com/send-an-email-notification-when-github-actions-fails-ea83cbeabbe0).

Do we already have an idea, how we seperate the runs for merging on main/merging PRs?

**Comment by rbehjati** [comment]
> Do we already have an idea, how we seperate the runs for merging on main/merging PRs?

We now have separate conditional steps for `pull-request` and `push` events: https://github.com/project-oak/oak/blob/b29c48a479d92c433e81a7c440174f771f8c65c7/.github/workflows/ci.yaml#L105-L115

**Comment by rbehjati** [comment]
For now we have decided that we don't need email notification since if the CI fails on main, the author and the subscribers will be notified. Closing it now, but we can get back to the email notification later, if we feel the need for it.
