### ISSUE TITLE
Make generated docs for Rust SDK available

### ISSUE THREAD

**Issue by daviddrysdale** [project-oak/oak#246]
Having [improved the SDK doc comments](https://github.com/project-oak/oak/commit/da56a8aa9f3743df5b06e767a98ef90ddc40b5e8), it would be nice if the `cargo doc` generated docs were online somewhere.

Possible options:
 - Publish to https://crates.io : This feels premature and also there's an [existing oak crate](https://crates.io/crates/oak).
 - Put generated files under (say) `./docs/sdk/`: On its own this doesn't help much, because GitHub doesn't serve up .html files as HTML, just .md files.  However&hellip;
 - Put generated files under `./docs/sdk/` and turn on [GitHub pages](https://pages.github.com/) for `docs/` on `master` : This would make the docs visible at https://project-oak.github.io/oak/sdk/; however, the Markdown files in `docs/` would show up at https://project-oak.github.io/oak/ but would not render properly.
 - Put generated files into a new `gh-pages` orphan branch.

I'd lean towards the last of these, with the generated docs stored in an `sdk/` top-level directory so that it's possible to have a top-level `index.html` file that redirects to `sdk/oak/index.html` (because the top directory from `cargo doc` on the `rust/` directory doesn't have an `index.html` file in it).  

Example of how [this](https://github.com/daviddrysdale/oak/commits/gh-pages) would look here: https://daviddrysdale.github.io/oak

(Regardless of which mechanism we adopt, we should add something like a CI check to keep the generated docs up to date&hellip;)

**Comment by daviddrysdale** [comment]
@tiziano88 @michael-kernel-sanders @anghelcovici : thoughts/preferences?

**Comment by anghelcovici** [comment]
I like the example (hence, the last option), maybe we can use github actions to sync that?

**Comment by daviddrysdale** [comment]
Docs are now up at https://project-oak.github.io/oak.  Leaving this issue open to cover setting some automated system for keeping them in sync with `master`.

**Comment by tiziano88** [comment]
Awesome! Could you add a link to that somewhere in the existing docs?

**Comment by daviddrysdale** [comment]
Links to generated docs added in #257

**Comment by daviddrysdale** [comment]
One wrinkle that will apply to any auto-regeneration system: rustdoc does not produce [deterministic output](https://github.com/rust-lang/rust/issues/24473), so it will not be safe to run a script on every commit and commit to `gh-pages` if anything has changed.

**Comment by tiziano88** [comment]
Is there anything left to do for this, apart from the auto-generation?

**Comment by daviddrysdale** [comment]
Still to do:
 - [ ] Automatically update the `gh-pages` branch when `master` is updated (#866).
 - [ ] Remove docs for non-SDK, non-Runtime crates from the generated pages (#765).

**Comment by daviddrysdale** [comment]
Now #866 is in, might as well close this and defer to #765 for what's left.

**Comment by daviddrysdale** [comment]
[Comment above](https://github.com/project-oak/oak/issues/246#issuecomment-547899363) about non-deterministic output looks like it [still applies](https://github.com/project-oak/oak/pull/866#issuecomment-616679397).

**Comment by daviddrysdale** [comment]
The doc generation has been deterministic for a while, so closing this in favour of #765
