### ISSUE TITLE
Update to `prost 0.9.0`

### ISSUE THREAD

**Issue by mariaschett** [project-oak/oak#2476]
Likely involves updating related dependencies such as tonic, which no longer requires (or implements) Sync for bidirectional streaming from v0.5 to 0.6, so also not a straightforward upgrade (which is useful, because it allows to drop the dependency on the sync_wrapper crate and simplify some of our logic)

**Comment by tiziano88** [comment]
Blocked on https://github.com/hyperium/tonic/issues/891
