### ISSUE TITLE
Move code unrelated to the Oak Functions ABI out of the `oak_functions_abi` crate

### ISSUE THREAD

**Issue by conradgrobler** [project-oak/oak#2495]
The `oak_functions_abi` crate contains some shared code that is unrelated to the actual Wasm ABI used by Oak Function.

We should consider moving this to more appropriate shared crates such as the `grpc_attestation` crate.

See e.g. https://github.com/project-oak/oak/pull/2494#discussion_r786964990

**Comment by mariaschett** [comment]
The ABI should also contain only `channel_read/write/wait` (once they are stable), moved outside the loader and re-branded as `uwabi`.

**Comment by tiziano88** [comment]
Done in 43fa6ecc2a89d7a76692f28b992e8be2f1bd0c15 and related commits
