### ISSUE TITLE
Refactor constant time / constant size policies as Future combinators

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#2497]

**Comment by tiziano88** [comment]
If we are leaving out the constant time part for now, it can just accept an arbitrary buffer instead of a function to run, and just wrap it in a PolicyOutput object.

PolicyOutput should be de/serializable to a fixed size buffer (I think it's fine if Size refers to the size of the body instead of the overall serialized buffer, the main point is that it is independent of the input of course).

**Comment by conradgrobler** [comment]
We are no longer using async code in Oak Functions, so this issue is no longer relevant.
