### ISSUE TITLE
Design IDL for ABI

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#2500]
We should be able to statically express the types and wire serialization of the messages that are exchanged via UWABI.

Probably makes sense to use as much as possible existing IDLs, mainly protobuf.

cc @mariaschett

**Comment by mariaschett** [comment]
Some Context:

The messages currently exchanged on the channels are [`pub type AbiMessage = Vec<u8>`](https://github.com/project-oak/oak/blob/d287e2cac6c74c629b40a2d997a279ca2fc2ae76/oak_functions/loader/src/server.rs#L47).

The interpretation of the message depends on which `ChannelHandle` they are sent / the corresponding extension at the runtime. 

Currently we have 3 extensions which we want to gradually want to rewrite to [`UwabiExtensions`](https://github.com/project-oak/oak/blob/d287e2cac6c74c629b40a2d997a279ca2fc2ae76/oak_functions/loader/src/server.rs#L164) exchanging `AbiMessages`:

1. the [lookup extension](https://github.com/project-oak/oak/blob/main/oak_functions/loader/src/metrics.rs)
2. the [metrics extension](https://github.com/project-oak/oak/blob/main/oak_functions/loader/src/metrics.rs)
3. the [tensor flow extension](https://github.com/project-oak/oak/blob/main/oak_functions/loader/src/tf.rs)

For example, for the lookup extension the Wasm module would send a message with the `key : Vec<u8>`. 

The runtime would return a message with a `value : Vec<u8>`, but we also need to indicate if no value was found in the message. (Currently, this currently indicated through the `OakStatus` of [`ERR_STORAGE_ITEM_NOT_FOUND`](https://github.com/project-oak/oak/blob/d287e2cac6c74c629b40a2d997a279ca2fc2ae76/oak_functions/proto/abi.proto#L64) returned by the ABI call [`storage_get_item`](https://github.com/project-oak/oak/blob/d287e2cac6c74c629b40a2d997a279ca2fc2ae76/oak_functions/abi/src/lib.rs#L82), but this will not be possible once we have UWABI.)

Similarily for the other two extensions and [error codes from `OakStatus`](https://github.com/project-oak/oak/blob/d287e2cac6c74c629b40a2d997a279ca2fc2ae76/oak_functions/proto/abi.proto#L55).

**Comment by mariaschett** [comment]
@tiziano88 Can I close this issue? I think it is superseded by other ideas.

**Comment by mariaschett** [comment]
Yeah, the description is horribly out-dated, though. So it might make sense to create a new issue?

**Comment by tiziano88** [comment]
This is done, though there is room for improvement especially in evolving the IDL together with the framing layer, but that is happening separately.
