### ISSUE TITLE
Unused proto import warning

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#254]
From build logs:

`oak/proto/storage.proto:21:1: warning: Import third_party/google/rpc/status.proto but not used.`

**Comment by tiziano88** [comment]
See https://pantheon.corp.google.com/cloud-build/builds/700d7aea-6799-4822-afa1-ec3758e88faf;step=1?project=oak-ci for actual logs.

**Comment by daviddrysdale** [comment]
Fixed in 705d7581acee33b9eec18921d931afc538b6652e
