### ISSUE TITLE
Allow assembling a Runtime binary with a selection of statically defined extensions

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#2551]
Currently we have two flavours of the Oak Functions runtime binary (base and unsafe). They both depend on the Oak Functions library, and indirectly decide what extensions are included in that by means of specifying different features:

https://github.com/project-oak/oak/blob/7bdc4440f43cf839fa6a615aeffec781701176a5/oak_functions/oak_functions_loader_base/Cargo.toml#L9

https://github.com/project-oak/oak/blob/7bdc4440f43cf839fa6a615aeffec781701176a5/oak_functions/oak_functions_loader_unsafe/Cargo.toml#L9

And the main entry point is identical for both:

https://github.com/project-oak/oak/blob/7bdc4440f43cf839fa6a615aeffec781701176a5/oak_functions/oak_functions_loader_unsafe/src/main.rs#L21-L23

Instead, ideally we would have a static config in the runtime entry point:

```rust
pub fn main() -> anyhow::Result<()> { 
  oak_functions_loader::lib_main(hashmap!{
    LOOKUP_DATA_HANDLE => LookupDataExtension::new(),
    TF_DATA_HANDLE => TFExtension::new(),
  })
} 
```

This definitely requires more thinking, we can use this issue to discuss.

**Comment by tiziano88** [comment]
Also, for now I don't think we need to treat Wasm as an extension, otherwise we need to start worrying about extensions of extensions. And I think in practice we are treating Wasm as our "userspace" where processes runs, using the OS terminology. Figuring out how to remove that entirely from a trusted runtime can be left for even further future work.

@mariaschett @conradgrobler WDYT?

**Comment by conradgrobler** [comment]
I think this is a good way forward for now, and agree that we can worry about the possibility of making Wasm an extension later.

For future reference when we start looking at it, here are some of my thoughts on a possible approach:

Every piece of self-contained functionality becomes a service (in a separate crate)
- IO (e.g. the current gRPC server listening for user requests)
- Wasm host
  - Creates a Wasm sandbox instance for every request
  - Creates copies of the same channels it has for the sandbox
  - Proxies comms from the sanbox instance to the corresponding service (e.g. lookup, IO)
- Lookup data provider
- Lookup data refresher

Each service would implemment a trait that would support adding a channel endpoint. We can either automatically assign channel handles based on the order in which the endpoint is added, or allow specifying a handle when adding the channel (for the following examples I will assume we automatically assign channels handles).

So for the normal runtime the startup might be something like:

```Rust
pub fn main() -> anyhow::Result<()> {
  let io = GrpcServer::new();
  let wasm_host = WasmiSandboxHost::new();
  let lookup = LookupData::new;
  // TODO: add lookup data refresher config.
  let (io_left, io_right) = Channel::new();
  io.add_channel(io_left);
  wasm_host.add_channel(io_right);
  let (lookup_left, lookup_right) = Channel::new();
  wasm_host.add_channel(lookup_left);
  lookup.add_channel(lookup_right);
  oak_functions_loader::lib_main(vec![
    io,
    wasm_host,
    lookup,
  ])
} 
```

The Wasm business logic would then use handle `0` for requests and `1` for lookup data.

For the no-Wasm runtime the startup might be something like:

```Rust
pub fn main() -> anyhow::Result<()> {
  let io = GrpcServer::new();
  let lookup = LookupData::new;
  // TODO: add lookup data refresher config.
  let (io_left, io_right) = Channel::new();
  io.add_channel(io_left);
  lookup.add_channel(io_right);
  oak_functions_loader::lib_main(vec![
    io,
    lookup,
  ])
} 
```

**Comment by tiziano88** [comment]
Sounds reasonable, but I don't think channels should be "added" to services, ideally they should be provided at creation time.

Also, I don't think Wasm handles should be assigned automatically, they need to be manually specified in order for them to be stable. They are the equivalent of TCP port numbers, and they need to be known by the Wasm module so that it can create a service "client" over that handle (ideally using the IDL).

**Comment by mariaschett** [comment]
Also: in our current design we have one channel per `WasmState` (Wasm Module) and we have to create the two runtimes at the same time.

So I think we should keep this idea of `ExtensionFactory` from which we create an `Extension` and channel to it for every WasmState.

**Comment by conradgrobler** [comment]
@tiziano88 I agree on those points. It also ocurred to me that most services (IO, lookup etc) will only ever support one channel, so they could create the channels and just expose the external endpoint, or have a constructor that accepts a single endpoint. It is only the Wasm host that need multiple channels at the moment.

@mariaschett in this future world I would expect the Wasm host to be responsible for creating the WasmState instances (one per request) and create the channels for it.

On your description above: Is the current plan for the ExtensionFactory to create a new instance of each extension for every WasmState?

**Comment by mariaschett** [comment]
> On your description above: Is the current plan for the ExtensionFactory to create a new instance of each extension for every WasmState?

That is how it is implemented at the moment: the `WasmHandler` gets [holds extension factories](https://github.com/project-oak/oak/blob/2d182aec5bbf823b6f5e0eadee2a9410548cd0ec/oak_functions/loader/src/server.rs#L688), which are [fixed on start-up](https://github.com/project-oak/oak/blob/2d182aec5bbf823b6f5e0eadee2a9410548cd0ec/oak_functions/loader/src/lib.rs#L220)  and the [creates an extension for every `WasmState`](https://github.com/project-oak/oak/blob/2d182aec5bbf823b6f5e0eadee2a9410548cd0ec/oak_functions/loader/src/server.rs#L719).

**Comment by conradgrobler** [comment]
That seems a bit problematic, unless what an `Extension` is is different to what I expect. As an example, there should be a single instance of the lookup data extension, as we do not want a copy of the entire lookup table for every request. Also, there must be only a singleton instance of the metrics collector (if that is used), because it must aggregate data across multiple requests.

**Comment by mariaschett** [comment]
When creating a `lookup` extension we [clone](https://github.com/project-oak/oak/blob/2d182aec5bbf823b6f5e0eadee2a9410548cd0ec/oak_functions/loader/src/lookup.rs#L59) the [Arc<LookupData>](https://github.com/project-oak/oak/blob/2d182aec5bbf823b6f5e0eadee2a9410548cd0ec/oak_functions/loader/src/lookup.rs#L34)---so we don't copy the entire lookup table.

Similar for the [Metrics Aggregator](https://github.com/project-oak/oak/blob/2d182aec5bbf823b6f5e0eadee2a9410548cd0ec/oak_functions/loader/src/metrics.rs#L257), I believe, but with metrics I am not very familar.

**Comment by conradgrobler** [comment]
Thanks for clarifying. Makes sense.

**Comment by jul-sh** [comment]
Updating this to summarize the related discussion in #2569:

We should delineate between which config should be guarded behind runtime flags, and what should be captured as a separate Oak Functions version. 

Paraphrasing @tiziano88 & @conradgrobler: Does the config affects the security guarantees of the runtime or guards features that will increase TCB size significantly? 
If yes: It should be a runtime variant.
If no: It can be passed at runtime.

**Comment by tiziano88** [comment]
Not planned.
