### ISSUE TITLE
Include a list of files that always trigger rerunning all the CI steps

### ISSUE THREAD

**Issue by rbehjati** [project-oak/oak#2561]
I think we should have a list of files that always trigger rerunning all the test. e.g. the dockerfile, everything under runner/*, also maybe everything under scripts/*?

_Originally posted by @tiziano88 in https://github.com/project-oak/oak/pull/2558#discussion_r812243300_

**Comment by conradgrobler** [comment]
Adding or modifying `example.toml` and `config.toml` files in an example should trigger that example.
