### ISSUE TITLE
Rename `runner` to `xtask`

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#2565]
See https://github.com/matklad/cargo-xtask . I think our `runner` is effectively already basically an `xtask` instance (maybe we can rename some subcommands to align with xtask conventions).

It seems this is an almost de-facto standard in various Rust projects:

- https://github.com/rust-analyzer/rust-analyzer/tree/master/xtask
- https://github.com/rust-osdev/uefi-rs/tree/main/xtask

**Comment by iBhavesh** [comment]
Can I proceed with this?Does it mean that all the folder names, file names and occurrences in all the files should be renamed to xtask?

**Comment by tiziano88** [comment]
Hi @iBhavesh , thanks for offering to look into this! Yes I think as a first pass, just rename the package and all references (including in CI), then we can see what else can be done to align to xtask "standard" practices, in a separate PR.

Please let me know if I can help with this, or if you are all set.
