### ISSUE TITLE
Document feature flagging approach and refactor existing feature flags to match

### ISSUE THREAD

**Issue by jul-sh** [project-oak/oak#2569]
I think our approach to feature flags could be improved a bit. We currently use both runtime and compile time feature flags, and sometimes mix them. (eg tensorflow is a runtime flag but also requires unsafe mode, a config of safe + tensorflow is possible but wouldn't work).

Imo we should default to using compile time configuration as a default. This means only using runtime flags when being able to set a flag at runtime is a functional requirement. (Eg tensorflow would just be a compile time flag). This keeps the resulting binary small, which is not just a general best practice, but especially important for security critical software like Oak and for simplifying the implementation of projects like no_std support. 

Thoughts? cc @tiziano88 @conradgrobler

**Comment by jul-sh** [comment]
The one caveat worth pointing out is that this means we'll end up with more binaries, and we'll need to compile more binaries to run tests. Imo an acceptable tradeoff.

**Comment by jul-sh** [comment]
Thanks for the link to #2551, didn't see it before. That seems very similar indeed. I think if we go with the approach suggested in it (imo we should), it would still make sense to think about how that relates to feature flags. 

> I am in favour of this approach, or even taking it further as suggested in https://github.com/project-oak/oak/issues/2551. Runtime configuration should be used to configure the functionality that is compiled into the binary (e.g. the Wasm business logic to use), not switch functionality on and off.

Or to say it more clearly, we probably do not need any runtime configuration. All configuration could & should be parsed at compile time. 

> I also think that we should prefer setting configuration in a config file rather than using multiple command-line arguments. In some environments command-line arguments will not be feasible (e.g. bare metal/UEFI).

+ 1. In that case, we should decide if we want a) a list of runtimes an app can choose [as the suggestion appears to be in #2551], or b)each app defines which components should be contained in the runtime it uses. To use a culinary analogy, whether apps choose an oak menu, or assembly the runtime a-la-carte. 

Imo ideally it should be b). It allows for combinations that we'll need eventually (eg TF _and_ metrics) and also more easily allows us to move other items like `worker_threads`, `policy`, etc to compile time.

**Comment by tiziano88** [comment]
I agree with the overall sentiment (as https://github.com/project-oak/oak/issues/2551 suggests and https://github.com/project-oak/oak/pull/2550 already starts implementing), but

> Or to say it more clearly, we probably do not need any runtime configuration. All configuration could & should be parsed at compile time.

this seems too extreme, I don't think we can afford to recompile / release / endorse the entire binary if we want to e.g. change the fixed response time or size value. I think we will always need both.

**Comment by tiziano88** [comment]
> Are all features flags handled as adding a new service? That might require duplicating services.

If we go with dedicated binaries, in the long term I don't think we even need feature flags, it would just be a different top-level binary with different building blocks mixed in together (and different sets of deps, of course). Effectively the "flags" are **the** body of the `main` method (and the deps of the binary).


e.g. for unary requests, we would have a crate that does streaming, and another that does unary, and in the top level binary we would use one or the other (without using feature flags, unless they help with something else of course)

**Comment by jul-sh** [comment]
> this seems too extreme, I don't think we can afford to recompile / release / endorse the entire binary if we want to e.g. change the fixed response time or size value. I think we will always need both.

Would you mind giving a bit more context on what the cost would be? 

> If we go with dedicated binaries, in the long term I don't think we even need feature flags, it would just be a different top-level binary with different building blocks mixed in together (and different sets of deps, of course). Effectively the "flags" are the body of the main method (and the deps of the binary).

> e.g. for unary requests, we would have a crate that does streaming, and another that does unary, and in the top level binary we would use one or the other (without using feature flags, unless they help with something else of course)

Yes, that would be possible. I think that down an enum of binaries will likely not scale, but we can address that when it happens.

**Comment by tiziano88** [comment]
> Would you mind giving a bit more context on what the cost would be?

I don't think we want the Oak release process (involving recompiling code, using keys from a locked-down KMS, etc.) to be in the way of a partner team wanting to change some configuration parameter.

The point of an Oak binary being trusted means that it should be regardless of the configuration details. In fact, @conradgrobler pointed out we effectively also consider Wasm code at the same level as configuration details. If we bake in the config and the Wasm code and need a new release every time, then we don't really need Oak, we may as well assume people can review / endorse a new binary every time they need to make any change. Although in this case perhaps Oak would still be useful as a way of guiding and speeding the review process, if nothing else?

Back to your point, maybe the line is that any configuration **that affects the security guarantees of the runtime** should be compiled in the binary (instead of being runtime). E.g. having TF enabled or not would be a compile time config (potentially security-related, especially if the TF code is not fully trusted), but changing a size or time param, or the Wasm code itself, should be a runtime config, since if Oak works correctly, changing those should not affect the overall security guarantees of the runtime.

WDYT?

**Comment by jul-sh** [comment]
Fair, thanks for the additional context. :] "Affects security" is a bit of a fuzzy line, but I agree that there's some validity to the friction of releasing. 

I do think we may want to revisit this in the future, when/if scaling issues of the "enum of runtimes" approach appear. But for now that approach seems reasonable. The release friction seems ultimately solve-able, as you also hinted at with

> Although in this case perhaps Oak would still be useful as a way of guiding and speeding the review process, if nothing else?

**Comment by conradgrobler** [comment]
It is probably just as fuzzy, but in my mind the dividing line should be: if changing the configuration value does not (significantly?) affect the size of the TCB, then it is fine as configuration, otherwise is should be handled during compilation.

Enabling/disabling a service (e.g. TF inference) will significantly change which parts of the code is used, or having support for multiple different versions of a protocol (e.g. unary + streaming gRPC) adds a lot of code to the TCB. Changing the value of the fixed response size should not affect which code is executed.

**Comment by jul-sh** [comment]
I predict we'll have disagreements on the fuzzy line soon, eg as far as I remember @tiziano88 mentioned that runtime flag for unary/streaming would probs be safe. :p

**Comment by jul-sh** [comment]
Updating this with the conclusions from #2569:
We should delineate between which config should be guarded behind runtime flags, and what should be captured as a separate Oak Functions version. 

Paraphrasing @tiziano88 & @conradgrobler: 

Does the config affects the security guarantees of the runtime or guards features that will increase TCB size significantly? 
If yes: It should be a runtime variant.
If no: It can be passed at runtime.

**Comment by conradgrobler** [comment]
> I predict we'll have disagreements on the fuzzy line soon,

I am sure we will. Having unused code in the TCB increases the risks for some attacks (e.g. ROP), but there is a trade-off between marginally increasing/decreasing security risks vs increasing/decreasing the operating complexity. Taking it to the extreme is probably not needed.

**Comment by jul-sh** [comment]
Agreed. Though I sometimes make a very similar argument about rest and semver 😅

Anyways, seems we can close this, summarized conclusions in #2551

**Comment by tiziano88** [comment]
> I predict we'll have disagreements on the fuzzy line soon, eg as far as I remember @tiziano88 mentioned that runtime flag for unary/streaming would probs be safe. :p

TBH I think you convinced me that we should treat it as "unsafe", i.e. in its own binary / feature flag, but I can see argument for both. In any case, this particular feature is something that we expect to fully graduate into the "safe" runtime, so the extra binary / feature / flag / config is just a temporary state.

**Comment by jul-sh** [comment]
Fair enough. :) Worth pointing out that I predict the "seperate out if needed" will probably require some enforcing in code review (which is fine). Our current setup makes adding a new runtime flag a lot easier than adding a new binary, which may well be how we arrived at the status quo of "lots of runtime flags".

**Comment by jul-sh** [comment]
No not the config, that's fine as we discussed. I mean lookup data, tf, metrics. The latter two which use a combination of runtime flags and binary variants.

**Comment by jul-sh** [comment]
Eg the things that led us to pickup https://github.com/project-oak/oak/issues/2551 in the first place. :) Maybe we'll be fine, but did want to mention that adding runtime flags is easier atm. I'm in the shoes "humble new contributor preferring to do what's easy", so I felt that data point might be interesting.
