### ISSUE TITLE
Document wire format of Remote Attestation Key Exchange protocol

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#2572]
Currently we have a high-level description of the protocol in https://github.com/project-oak/oak/blob/main/docs/remote-attestation.md , but it is not possible to implement a client / server from that description (and it is also hard to justify decisions about serialization, see https://github.com/project-oak/oak/pull/2571).

We should define the binary format of each frame somewhere (maybe in the same doc, maybe in another one).

We can use this issue to first collect ideas about how this could be done, e.g.:

- https://cs.fit.edu/~mmahoney/cse4232/tcpip.html
- https://hpbn.co/transport-layer-security-tls/
- https://www.khanacademy.org/computing/computers-and-internet/xcae6f4a7ff015e7d:the-internet/xcae6f4a7ff015e7d:routing-with-redundancy/a/ip-packets

**Comment by jul-sh** [comment]
The `AttestationReport` (part of the RA protocol and in the docs) does use proto as a wire format. Atm only the key exchange handshake messages do not use proto. 

We should document when each format should be used.

**Comment by tiziano88** [comment]
IIRC the protobuf report is just a placeholder, from the point of view of the key exchange protocol is just an opaque blob of data. But yes, we should definitely also have a spec for the inner wire format of that blob at some point.

**Comment by jul-sh** [comment]
@tiziano88 is that in the scope of this issue? Or is this issue just about the format for key exchange messages?

**Comment by tiziano88** [comment]
I would only leave the "binary blob field" in scope for this issue (we would still need to clarify how to encode / decode that, e.g. length prefixed), but not the content of that field, since that's almost guaranteed to change in any meaningful version of remote attestation.

Also, that field would probably be handled (i.e. parsed and inspected) at the application layer, not by the handshaker directly. I imagine the handshaker would just validate its integrity (i.e. that its content is included in the transcript and / or any other checksum that is bound to the crypto key), and make it available up one level, or something like that. But I'm not sure.

**Comment by jul-sh** [comment]
Fair, but we should probably update the title reflect the scope of "just the key exchange & encryption layer" then. Atm we use "Remote Attestation protocol" a little bit fuzzily, sometimes including the report in the scope and sometimes not
