### ISSUE TITLE
Move the structs and traits related to extensions to a separate crate

### ISSUE THREAD

**Issue by conradgrobler** [project-oak/oak#2576]
This will allow us to move the implementations of extensions to separate crates without running into circular reference issues.

**Comment by mariaschett** [comment]
I am happy to do that! 

Do you have a structure in mind? E.g., would every extension go to their own crate, or would we have one crate `oak_extensions` (we could also rename them to services at the same go)?

Also: I am not sure what you mean with the circular reference issue?

**Comment by conradgrobler** [comment]
My view is that each extension should be in its own crate. At the moment the traits for defining an extension is in the oak_functions_loader crate. If I create a new crate for an extension (say tf_inference) and want to also define its extension (and the trait implementations) there it will need to reference oak_functions_loader. For oak_functions_loader to know about the extension, it would need to reference the tf_inference crate. This is where the circular dependency comes from.

If the traits are defined in an external crate (e.g oak_functions_extensions (or oak_functions_common if we want to move more common structs and traits there)), then it can be referenced by the oak_functions_loader and by the tf_inference to remove the circular dependency.

I am already creating a separate oak_logger crate with an OakLogger trait as part of refactoring to do something similar for logging support in extractred crates.

**Comment by tiziano88** [comment]
See also https://github.com/project-oak/oak/issues/2551

**Comment by conradgrobler** [comment]
The WIP example PR for moving the TF Inference component to a crate is https://github.com/project-oak/oak/pull/2577

**Comment by conradgrobler** [comment]
One additional point here: I think this task should only be done after all the extensions have been moved to UWABI. Moving the extension traits before then would mean a depency on WasmState and Wasmi in the extension traits crate.
