### ISSUE TITLE
Decide on no_std-compatible approach for HashMaps

### ISSUE THREAD

**Issue by conradgrobler** [project-oak/oak#2593]
We can either switch to using `BTreeMap`s everywhere (as sugested for lookup data in #2317) if the performance would be sufficient, or we can use something like the `hashbrown` crate.

**Comment by tiziano88** [comment]
I think we should choose base on each use case; if we are expecting to do hash lookups, then we should go with hashbrown. BTree maps may be useful in some other cases in which we need to preserve sort order, or traverse entries in the map, but I don't think we need that at the moment (though https://github.com/project-oak/oak/issues/2317 tracks that for the lookup data functionality)

**Comment by conradgrobler** [comment]
Most of the hashmaps have been converted to use the hashbrown crate, but there are still parts for the codebase (e.g. lookup data generator) that still uses the std HashMap.

**Comment by conradgrobler** [comment]
We have standardised on using the hashbrown implementation.
