### ISSUE TITLE
Implement Framing mechanism for untrusted / trusted communication

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#2651]
Probably a len-delimited format woould be sufficient. See https://docs.rs/tokio-util/latest/tokio_util/codec/length_delimited/index.html for some ideas (though the implementation is probably not usable for the UEFI runtime because it relies on std).

For the UEFI runtime, this may wrap an underlying serial port, via https://docs.rs/uefi/latest/uefi/proto/console/serial/struct.Serial.html#method.read .

**Comment by conradgrobler** [comment]
This has been implemented already.
