### ISSUE TITLE
Fix flakiness in `test_long_response_time`

### ISSUE THREAD

**Issue by conradgrobler** [project-oak/oak#2658]
The 10ms margin is not always sufficient, causing the test to fail in CI from from time to time.

https://github.com/project-oak/oak/blob/910bf1a7b8c036099213bc6c527c63986d6a8b97/oak_functions/loader/src/tests.rs#L83-L89

We could either increase the margin, or remove the margin-related logic completely as it does not seem to add much value while introducing flakiness.

**Comment by tiziano88** [comment]
It seems fine to increase the margin to 100 ms or similar, I think the test is useful to keep.
