### ISSUE TITLE
`collect2: error: ld returned 1 exit status` error in CI

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#2683]
See https://github.com/project-oak/oak/runs/5836846751

Possibly caused by 02728149e8958100fcd1da8c59263952b9750664

**Comment by tiziano88** [comment]
I tried reproducing locally several times, but it does not seem to happen there. @project-oak/core could someone else also give it a try and let me know if it works locally?

This is the command I am using

```
./scripts/docker_run ./scripts/xtask --commands --scope=all run-cargo-tests
```

**Comment by conradgrobler** [comment]
I tried as well and also could not reproduce locally.

**Comment by jul-sh** [comment]
Thanks for fixing. 😇
