### ISSUE TITLE
Add test coverage reports

### ISSUE THREAD

**Issue by mariaschett** [project-oak/oak#2696]
Adding test coverage reports to also check on xtask.

**Comment by mariaschett** [comment]
@rbehjati Do you have any pointers?

**Comment by rbehjati** [comment]
I think at some point we have been using https://github.com/project-oak/oak/blob/00c87846b6988f89f76d9f35e2633b60e08b0f64/scripts/run_tests_coverage. But now the command is incorrect, and I hope it is not being used anywhere. 

This is where we previously generated coverage: https://github.com/project-oak/oak/blob/971c7d29a9edceee6feaaf7cb0d1110a257830e7/runner/src/main.rs#L370-L380 (I cannot find the PR that removed this part). I think there was also something in the CI for visualising the reports. I cannot find the PR that removed it either.

**Comment by rbehjati** [comment]
I found this earlier PR: https://github.com/project-oak/oak/commit/56ee7fa6b625b59244eff9b45467af5ec662613a
This issue gives more info: https://github.com/project-oak/oak/issues/1187 
Interestingly, we still have https://github.com/project-oak/oak/blob/main/.codecov.yml in the code base. 

I don't think we'd want to use codecov anymore (although I can see that our copy of `ring` in third-party does have CI steps with codecov!). Not sure if there are any good alternatives.
