### ISSUE TITLE
Improve or disable fuzzing in CI

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#2732]
Currently whenever dependencies are updated, the generated Wasm file that is used as part of fuzzing gets outdated, and needs to be manually updated and checked in. This makes automatic dependency management by @dependabot very inconvenient, since most of those auto generated PRs fail because they (rightly) are not aware of the wasm file that needs to be updated.

Ideally we should change the fuzzing logic so that the wasm file is actually compiled on the fly as part of fuzzing, instead of being checked in as a binary artifact.

In the meanwhile, I suggest we remove fuzzing from CI, since I don't think it has been particularly helpful so far. But if anyone has any other suggestion, please let me know here.

**Comment by rbehjati** [comment]
I don't think so. I think we should disable it, or at least try and solve the issue with `fuzzable.wasm`. I can spend some time on it next week and see if I can find a work around for `fuzzable.wasm`.

**Comment by rbehjati** [comment]
Closing this for now.
