### ISSUE TITLE
Share remote attestation server logic

### ISSUE THREAD

**Issue by jul-sh** [project-oak/oak#2741]
Most of the non-gRPC specific bits in `grpc_unary_attestation/src/server.rs` will be needed for both the linux runtime (that exposes a gRPC endpoint directly) _and_ the bare-metal/UEFI runtime (that performs handshakes but communicates with clients through a loader app). Specifically those bits are

- [X] the LRU cache track of sessions
- [ ] and the logic for iterating the handshaker with incoming messages.

It would be nice to break out those parts from the grpc crate and use them in both runtimes.

**Comment by conradgrobler** [comment]
I agree. I think this will be very useful refactoring.

**Comment by tiziano88** [comment]
@jul-sh what's the state of this? Has it already happened as part of your refactorings?

**Comment by jul-sh** [comment]
Sorry for the late update. This issue consists of two tasks, the more impactful of which is done. 

- [X] the LRU cache track of sessions (done in #2743)
- [ ] and the logic for iterating the handshaker with incoming messages.

It'd be nice to also share the logic of iterating the handshaker, these two methods atm contain a lot of duplicate code: https://github.com/project-oak/oak/blob/228236fefa5c8279b42138d2452b7fd87f7ff9b1/experimental/oak_baremetal_runtime/src/remote_attestation.rs#L64 and https://github.com/project-oak/oak/blob/main/grpc_unary_attestation/src/server.rs#L71.

Right now however, sharing that logic is non-trivial however. 

The linux runtime's logic needs to be async, while bare-metal runtime does not have an async executor. Logic could only be shared by either a) making more of the linux runtime logic blocking (unacceptable runtime perf cost) or b) adding a blocking executor (ala https://github.com/jonay2000/blocker) to the bare-metal runtime (added complexity imo not worth it).

It will be easier to solve this once the bare-metal runtime supports multiple CPUs (some time away). This issue is left open until then.

**Comment by conradgrobler** [comment]
We are no longer using the intereactive remote attestation handshaker, so this is no longer relevant.
