### ISSUE TITLE
Use Bazel rules for Rust code

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#28]
We are currently using Bazel for most of the C++ code, but Rust code is still built using `cargo`, and Rust protobuf are built manually by installing and running the `protoc` compiler, which makes achieving reproducible builds hard.

We should instead rely on https://github.com/bazelbuild/rules_rust , possibly by auto-generating BUILD files from the current Cargo.toml files using https://github.com/google/cargo-raze.

**Comment by wildarch** [comment]
I have some experience with building Rust for no_std targets using rules_rust and cargo-raze, so I might be able to look into this.

It would probably be good if we allowed people to at least build the SDK with cargo as well. We could try to support both Cargo and Bazel as build systems?

**Comment by blaxill** [comment]
I think the intention is for the SDK to remain cargo-buildable, the priority of Bazel rules is for getting the rust runtime buildable with the same build chain as the other runtime components (Asylo, cpp runtime) so it's easier to link them together. 

There is some outstanding work to be done on the runtime before it's fully `no_std` compatible  #546

**Comment by ipetr0v** [comment]
Since we currently mostly use `cargo` (https://github.com/project-oak/oak/commit/b2512de77098802d4329c15679d537c674ea3c6d), should this issue be closed?

**Comment by daviddrysdale** [comment]
Yep, I think so.
