### ISSUE TITLE
Update fuzzing WASM

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#2800]
Dependabot PR (#2799) is currently [failing](https://github.com/project-oak/oak/runs/6264192954?check_suite_focus=true) because the WASM fuzzing module needs to be updated manually.

**Comment by tiziano88** [comment]
This will happen with any dependabot PR that causes the Wasm file to be updated, it is not a breakage in the repo. The solution is to create a PR that does the same upgrade as dependabot, that also includes the updated Wasm file for fuzzing (basically the same workflow for any manually authorsed PR)

**Comment by ipetr0v** [comment]
Which WASM should be updated?
Is there a script for this?

**Comment by tiziano88** [comment]
https://github.com/project-oak/oak/blob/main/oak_functions/loader/fuzz/README.md

**Comment by ipetr0v** [comment]
hm, and now #2799 have passed all of the checks

**Comment by conradgrobler** [comment]
This is because #2795 removed `thiserror` as a dependency from the ABI crate, so updating it no longer changes `fuzzable.wasm`

**Comment by ipetr0v** [comment]
Can this issue be closed?
