### ISSUE TITLE
Create library version of Oak Runtime

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#2823]
This should be a new top-level target that compiles to a library version of Oak that can be embedded (i.e. statically linked) in a larger C / C++ application.

It should expose a single "invoke" function (or similar) (with C calling convention) over which the embedder can communicate commands to the Oak Runtime (e.g. loading lookup data, or handling user requests). This would be roughly similar to what the UEFI / bare metal version of Oak would receive over the serial port, and will eventually benefit from relying on the [IDL](https://github.com/project-oak/oak/tree/main/oak_idl) in order to generate type safe bindings for the communication over the invoke function (in multiple languages, if needed).

It should not handle remote attestation at all (which may require some additional refactoring compared to the current version).

**Comment by tiziano88** [comment]
cc @solokacher

**Comment by tiziano88** [comment]
A prerequisite to this is to make sure that the runtime object is already wrapped in an implementation of the server trait that is auto generated from the current IDL. 

@conradgrobler @jul-sh I believe the current version of this interface is https://github.com/project-oak/oak/blob/main/experimental/oak_baremetal_channel/schema.fbs , is that correct? Is there a version of the runtime library that implements the generated server trait already too?

Note that this interface lacks the policy configuration at the moment (mostly because we don't have a way of implementing that in a no_std compatible way without timers).

**Comment by conradgrobler** [comment]
> @conradgrobler @jul-sh I believe the current version of this interface is https://github.com/project-oak/oak/blob/main/experimental/oak_baremetal_channel/schema.fbs , is that correct? Is there a version of the runtime library that implements the generated server trait already too?

Yes, that is correct. The generated server trait is used in https://github.com/project-oak/oak/blob/main/experimental/oak_baremetal_runtime/src/framing.rs#L59

**Comment by tiziano88** [comment]
Thanks @conradgrobler , that's exactly what I was looking for.

@mariaschett I think the remaining work for this task is to use that version of the runtime library (which happens to also be no_std / bare metal compatible) and invoke it via the methods that are exposed via that trait (which correspond to the ones defined via the IDL).

This will probably mean refactoring https://github.com/project-oak/oak/blob/main/oak_functions/loader/src/lib.rs so that all the interaction between the "loader" library (assuming we keep that name) and the actual trusted runtime library happens over those methods.

WDYT?

**Comment by tiziano88** [comment]
A prerequisite for this is to add the policy config to the init message:

https://github.com/project-oak/oak/blob/1f2c12221697420f5282b366473bf9b205375c57/experimental/oak_baremetal_channel/schema.fbs#L23-L25

**Comment by tiziano88** [comment]
@mariaschett I think this can be closed; if anything related comes up again, we can create more specific issues in the future. WDYT?

**Comment by mariaschett** [comment]
Agreed.
