### ISSUE TITLE
Define and implement a communication protocol between the trusted runtime and loader app

### ISSUE THREAD

**Issue by jul-sh** [project-oak/oak#2848]
See the in [progress design doc](https://docs.google.com/document/d/1Q4u5hYzOFF74_RfwZzpRWgSSwJwfQ-GXRvNllgCXOO8/edit?usp=sharing) (Google Internal).

**Comment by mariaschett** [comment]
Resolved. Here is the [SPEC](https://github.com/project-oak/oak/blob/88b65242e794076b870d3d068a8f1562e039eb04/oak_channel/SPEC.md) of version 0.
