### ISSUE TITLE
Avoid polling when waiting on channels

### ISSUE THREAD

**Issue by daviddrysdale** [project-oak/oak#288]
Possibly based on `absl::Notification` (although that says multiple calls to `Notify()` are undefined behaviour, so it's not an immediate fit).

**Comment by blaxill** [comment]
The rust runtime also currently uses sleep. We should instead implement correct thread suspension. This could possibly be based on Condvar in rust or through some use of the future framework.

**Comment by blaxill** [comment]
Some notes

- `crossbeam` appears to spin for `no_std` [link](https://github.com/crossbeam-rs/crossbeam/blob/b8ef633154225c678b903b35ab9a193285eedc62/crossbeam-utils/src/backoff.rs#L205)

- [crossbeam wait_group example](https://github.com/crossbeam-rs/crossbeam/blob/424f926673d652f306f266d4309ed8717e931144/crossbeam-utils/src/sync/wait_group.rs)

- The `wait_on_channels` case is the most difficult as a single Condvar isn't enough.

- `Futures` with `no_std` support is mixed as any actual implementations need OS support for thread-things. 

- Assuming we go with an enclave abstraction layer, this PR will likely use sync primitives defined there

**Comment by daviddrysdale** [comment]
For the C++ side of this, I've dumped my experiments into #589.

Also, there's some interesting and possibly relevant stuff in ["Go channels on steroids"](https://docs.google.com/document/d/1yIAYmbvL3JxOKOjuCyon7JhW4cSv1wy5hC0ApeGMV9s/edit#)
