### ISSUE TITLE
Support additional attestation info in `ClientIdentity`

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#2914]
`ServerIdentity` contains a field for storing additional attestation data:

https://github.com/project-oak/oak/blob/b960c7821c775f4176159e9d773d5d3153ad403c/remote_attestation/rust/src/message.rs#L122-L127

but `ClientIdentity` does not seem to, even though the two should be symmetric. 

https://github.com/project-oak/oak/blob/b960c7821c775f4176159e9d773d5d3153ad403c/remote_attestation/rust/src/message.rs#L130-L160

**Comment by conradgrobler** [comment]
We are no longer using the interactive remote attestation, so this is no longer relevant.
