### ISSUE TITLE
Implement remote attestation verification logic in Java client

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#2917]

**Comment by rbehjati** [comment]
The Rust implementation of the schema for the report is in https://github.com/project-oak/oak/blob/c4a00dd9711b81591624d320a2aa7a22810301cd/oak_sev_guest/src/guest.rs#L343-L349

It uses a C layout, so for something like Java one would have to parse the individual byte ranges, as described in Table 21 of https://www.amd.com/system/files/TechDocs/56860.pdf.
