### ISSUE TITLE
Implement transcript signing logic in Java client

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#2918]
It seems that the Java client does not actually sign the transcript as part of remote attestation (and the Rust logic happily skips over it).

https://github.com/project-oak/oak/blob/b43decc6069103a256c368d9c7cef85e6b9252fe/remote_attestation/java/src/com/google/oak/remote_attestation/ClientHandshaker.java#L146-L147

https://github.com/project-oak/oak/blob/b43decc6069103a256c368d9c7cef85e6b9252fe/remote_attestation/rust/src/handshaker.rs#L508-L533

**Comment by conradgrobler** [comment]
We are no longer using the interactive remote attestation handshake, so this is no longer relevent.
