### ISSUE TITLE
Make OakIDL no_std compatible

### ISSUE THREAD

**Issue by jul-sh** [project-oak/oak#2920]
- [X] the flatc compiler outputs code that requires std. Fixed by #2905
- [ ] the flatbuffers crate depends on the core2 crate in `no_std`, but does not disables its std feature.
- [ ] the flatbuffers crate depends on thethiserror-core2 crate, which is missing some imports of traits from core.

**Comment by conradgrobler** [comment]
We are no longer using flatbuffers.
