### ISSUE TITLE
Replace protobufs and bincode serialisation with the flatbuffers-baesd IDL in the Oak Functions ABI

### ISSUE THREAD

**Issue by conradgrobler** [project-oak/oak#2975]
Manual serialisation in the ABI crate should also be repaced with the IDL generated code.

**Comment by tiziano88** [comment]
This is about the Wasm ABI, right?

**Comment by mariaschett** [comment]
+1. Do we want to replace, e.g., [StorageGetItemResponse](https://github.com/project-oak/oak/blob/65179ae5d477e9ee41564080fc411434e428f70e/oak_functions/abi/src/lib.rs#L60)?

**Comment by conradgrobler** [comment]
Yes, the bincode serialisation is related to the ABI invoke requests and responses. So e.g. StorageGetItemResponse should be replaced.

I think the protobufs are not related to the Wasm ABI, so should probably be split into a separate crate as mentioned in #2495.

**Comment by tiziano88** [comment]
Not planned. We are now using https://github.com/project-oak/oak/tree/main/micro_rpc for this.
