### ISSUE TITLE
Set up Continuous Integration

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#3]
This may end up being more complicated than expected because of the additional dependencies needed by Asylo that need to be installed on the system or in a docker image in which tests are run.

**Comment by tiziano88** [comment]
BTW the plan is to use https://travis-ci.org/ .

**Comment by Sidnioulz** [comment]
Tiziano, you have set up a built bot already, is that correct?

**Comment by tiziano88** [comment]
Yes, we have https://travis-ci.org/project-oak/oak , though there is room for improvement (tracked in separate issues)
