### ISSUE TITLE
Dynamic Oak Node creation

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#300]
Now that we have policies that propagate across channels, even a simple applications like https://github.com/project-oak/oak/tree/master/examples/chat accumulates policies from all the incoming messages and does not have any way of getting rid of them. While declassification according to specific policies would offer a way to do that, we should have a more fundamental way to instantiate a new Oak Node based on the code provided  in the application configuration, which would start off with a clean label (e.g. no secrecy label attached, since it has not seen any secret data yet). Then we can use this construct to e.g. dynamically create a node per chat room, so that participants of that room can keep sending data with an appropriate restrictive policy and that would not affect the policy of other rooms in the same application.

**Comment by daviddrysdale** [comment]
(Aside: #259 was added with this in mind too.)

**Comment by tiziano88** [comment]
Also note that this is a dynamic mechanism that works for data belonging to an active Oak Node that is online and reachable by all the interested clients. When we add things like replication and redundancy the story gets more complicated, as it would require synchronizing not only data but also policies across Oak Nodes on different machines. Perhaps this gets independently solved by the Oak storage layer though.

**Comment by tiziano88** [comment]
Something we already discussed but worth writing down for the sake of the conversation: maybe eventually we can get rid of the static application configuration entirely, in favour of an Oak Application having a "main" Oak Node that is in charge of dynamically creating any other Oak Nodes and channels between them, using the programmatic API offered at the Wasm level.

**Comment by daviddrysdale** [comment]
Done in #344 and #340
