### ISSUE TITLE
Fetch the Signing Public Key before doing the remote attestation handshake

### ISSUE THREAD

**Issue by conradgrobler** [project-oak/oak#3096]
The public key is currently sent as part of the remote attestation handshake. We should fetch the key before the handhake starts (via a separate call to the untrusted launcher) and validate the public key before starting the handshake.

This means the we need to make the key available to the untrusted launcher before serving requests (e.g. add signing public key to the response from the call to `Initialize`).

The public key should be presented with all the required evidence to be able to validate it, including:

- Remote attestation report that includes the hash of the signing public key
- Certificate chain for validating the attestation report
- Appropriate artefacts from the transparent release process

All of the evidence must be independently verifiable by the client, as it will be provided by the untrusted launcher.

**Comment by tiziano88** [comment]
cc @sidtelang

**Comment by conradgrobler** [comment]
We are no longer doing the interactive attestation between client and server. Fetching the public key, attestation report and other info first will naturally happen as part of the interactive attestation implementation.
