### ISSUE TITLE
Compile and link Rust and C++ for enclave code

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#313]
Experiment with a hybrid C++ / Rust enclave binary, so that we can leverage https://github.com/google/asylo bindings and abstractions, but be able to implement at least parts of the Oak Runtime in Rust.

**Comment by tiziano88** [comment]
BTW it seems https://github.com/google/asylo/pull/46 is implementing something in Rust, though I have not looked into it yet.

**Comment by tiziano88** [comment]
https://edp.fortanix.com/docs/concepts/rust-std/ has more details

**Comment by tiziano88** [comment]
@blaxill I suspect this is already effectively on your plate, feel free to dedup (close) this against other issues, or just have those other issue "block" this one, up to you.

**Comment by blaxill** [comment]
Closing in favour of #540 and #546
