### ISSUE TITLE
Migrate from Google Cloud Container Registry to Artifact Registry

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#3228]
Container Registry is in maintenance mode and not getting any new features, and users are encouraged to move to Artifact Registry.

See https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr .

**Comment by mariaschett** [comment]
Do we need to move everywhere, e.g., [Trusted Shuffler](https://github.com/project-oak/oak/blob/b8c625ee21d01723ebf3e1af83994c3a163a8975/trusted_shuffler/scripts/common#L11)?

**Comment by tiziano88** [comment]
Ideally over time yes, but it's not urgent, I don't think Container Registry is going to disappear any time soon, but we should align with the current best practices if possible. Before migrating the remaining images, I wanted to do a pass in our repo removing images that seem completely unused; then we can migrate the remaining ones. But if you are creating new images, it may be simpler to just start with Artifact Registry (it's just a matter of changing the URL really).
