### ISSUE TITLE
Remove "unsafe" versions of monolithic Oak Functions binaries

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#3242]
We are not planning to use them anyways, so I would rather delete them to simplify the migration towards #3075 .

This would mean that we have only a single version of Oak Functions, packaged to run either on the Oak Restricted Kernel or as a Linux binary.

In particular, we would not have support to run TF models via tract, nor to export differentially private metrics.

Also, logging from the Wasm code would not be possible, at least until we re-introduce it via some other way that is compatible with the Oak Restricted Kernel (e.g. by sending logs back alongside the response message).

@conradgrobler WDYT? Is if fine to delete these?

**Comment by conradgrobler** [comment]
I think so. I agree that we should probably reintroduce the differentially private metrics later, but as you point out for the logging case we would need a better mechanism to publish the data rather than just writing it to stderr.
