### ISSUE TITLE
Move CI completely from Travis to Google Cloud Build

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#325]
GCB already does most of the work for CI and it is faster and more stable than Travis. I suggest getting rid of Travis entirely and only keeping GCB around.

Note that last time I checked, GCB is still missing the step that checks for changes in generated files:

https://github.com/project-oak/oak/blob/f4d5627dd46dbedd40f1915c224348fbef39c6d9/.travis.yml#L29

@project-oak/core let me know if anyone has any objections or suggestions.

**Comment by tiziano88** [comment]
@ipetr0v could you take a look at this? I think it boils down to add the `check_generated` line to https://github.com/project-oak/oak/blob/master/cloudbuild.yaml , but it probably needs some minor adjustment. After that's done we can decide what to do with the travis config (feel free to leave that as it is for now).

**Comment by tiziano88** [comment]
Now that all the functionality is covered in GCB I'd like to disable Travis for CI, since it keeps being flaky and erroring out.

@daviddrysdale @anghelcovici IIRC you were still trying to debug something on Travis, would you like to leave it on for longer while you investigate, or are you fine with disabling it now?

**Comment by daviddrysdale** [comment]
I'd still like to get to the bottom of #200, but I can do that on my personal Travis builds (as long as I don't sync past this commit).

**Comment by tiziano88** [comment]
Note also that disabling Travis will take away our build badge. There are some [other ways](https://github.com/sbsends/cloud-build-badge) of doing something that looks like a build badge manually, but I also think that a link to cloud build dashboard should suffice for now.
