### ISSUE TITLE
Add support for TensorFlow Lite for Microcontrollers

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#3297]
We need to create a new runtime that can run [TensorFlow Lite for Microcontrollers](https://github.com/tensorflow/tflite-micro) (TFLM).

This work will include:
- Compiling TFLM with `no-std`
- Adding C++ bindings to the Rust runtime
- Add memory management support to the Restricted Kernel

**Comment by ipetr0v** [comment]
@ianull please reference this issue with when submitting code related to TFLM

**Comment by tiziano88** [comment]
Not planned.
