### ISSUE TITLE
Vendor patches needed to build wabt into the oak repository

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#332]
Currently we are depending on a fork of wabt including some additional commits that add a BUILD file for Bazel and other minor changes:

https://github.com/project-oak/oak/blob/2d1c17c26fda5590b643a0e89a0985d052a7fdee/WORKSPACE#L94-L98

This is hard to maintain, and in fact we are stuck at a relatively old version of wabt because of this friction.

We should:

- switch from `git_repository` to `http_archive`: https://docs.bazel.build/versions/master/repo/http.html#http_archive
- use the `build_file` attribute of `http_archive` to specify the contents of the BUILD file that is needed to build wabt, while keeping the BUILD file itself in oak
- figure out which of the additional commits in https://github.com/daviddrysdale/wabt/commits/master still need to be patched, and apply them via the `patches` attribute of `http_archive`, maintaining the patches themselves in oak
- point the dependency back to the upstream wabt repository (possibly at an old commit to start with)
- update the dependency on wabt to point to a more recent commit

**Comment by tiziano88** [comment]
Was `wabt` also updated to the latest version in the end? If not, could you create an issue to track that? And I hope that would fix #276 too.

**Comment by blaxill** [comment]
@tiziano88 sorry I missed this. The version was not updated, I'll look into it.
