### ISSUE TITLE
Implement HTTP(S) client node type

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#337]
Similar to [`LoggingNode`](https://github.com/project-oak/oak/blob/master/oak/server/logging_node.h), but sending data over an HTTP(S) connection to an external service, i.e. outside of Oak.

With respect to the policy system, only data that is "public" (i.e. empty secrecy tag set) can be sent out via this node, but for now there is no need to worry about that aspect.

- create new `HttpClientNode` class in https://github.com/project-oak/oak/tree/master/oak/server
- create a new `node_type` variant in the application configuration:

  https://github.com/project-oak/oak/blob/2d1c17c26fda5590b643a0e89a0985d052a7fdee/oak/proto/manager.proto#L39-L44
- initially the node may be configured with a fixed URL and method, and always send incoming data  out according to these parameters
- later on the URL and method (and possibly other parameters) may be specified as part of the messages it handles (e.g. in protobuf form)
- initially the node may have only an incoming channel, and provide no feedback to the caller; then it should provide an outgoing channel over which the caller can read back the response to the HTTP request (e.g. for fetching data coming from outside Oak)

**Comment by tiziano88** [comment]
@blaxill could you look into this? I suggest trying to run the existing examples and tests to start with, and figuring out how the existing things fit together. Happy to chat in person in front of a whiteboard at some point.

**Comment by blaxill** [comment]
I'm looking into this.

**Comment by blaxill** [comment]
I'm ready to integrate an http client library to https://github.com/project-oak/oak/compare/master...blaxill:http-node

Any suggestions for a http library?

(I've messed up the PR flow a bit because i switched from a project-oak/oak branch to blaxill/oak branch as per development guidelines)

**Comment by tiziano88** [comment]
I don't have any suggestions off the top of my head, @daviddrysdale or @michael-kernel-sanders may have more experience.

Also perhaps look around and see what's available / commonly used in google3.

**Comment by daviddrysdale** [comment]
Is there any separately-usable HTTP client code buried in the gRPC client libraries by any chance?

By the way, what do we expect to do if we want an Oak Application to interact with an external gRPC service?  Are we expecting to use one of these HTTP client nodes and layer the gRPC stuff on top of it (e.g. in a gRPC library linked inside the Wasm Node), or do we expect to have another gRPC client pseudo-Node type?

**Comment by tiziano88** [comment]
I was expecting we would need a native gRPC pseudo-node type, but if someone manages to have a Rust gRPC stack working on top of a transport based on Oak channels connected to an HTTPS node, that would be great!

**Comment by blaxill** [comment]
I'm currently prioritising Rust work, and will come back to this to create a HTTP node in the Rust oak runtime.

**Comment by blaxill** [comment]
Closing as no longer relevant.
