### ISSUE TITLE
Investigate the need for uploading Rekor LogEntries to Ent

### ISSUE THREAD

**Issue by rbehjati** [project-oak/oak#3405]
The "Build Provenance" workflow currently uploads the binary and its signed provenance to `Ent`. Do we need to upload the Rekor LogEntries to `Ent` as well? 

While the binary and the provenance are required as input to the endorser tool for generating endorsements, the Rekor LogEntry does not seem to be required. In particular, [slsa-verifier](https://github.com/slsa-framework/slsa-verifier) seems to already be integrated with Rekor, and if we use something similar to it for verifying provenances then passing the LogEntry as an explicit input to the endorser/verifier seems unnecessary. 

cc @mariaschett

**Comment by thmsbinder** [comment]
We ended up downloading all files as sidecars in the package, so this is no longer relevant.
