### ISSUE TITLE
warning when compiling oak_functions: unknown feature specified for `-Ctarget-feature`: `soft-float`

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#3433]
```console
$ cd oak_functions_freestanding_bin && cargo build --no-default-features --features=simple_io_channel --release
warning: unknown feature specified for `-Ctarget-feature`: `soft-float`
  |
  = note: it is still passed through to the codegen backend
  = note: consider filing a feature request
```

@andrisaar can that be removed directly, or do we need it and the warning is a false positive?

**Comment by andrisaar** [comment]
Last time I checked we needed it, otherwise the crypto-related crates didn't compile. But feel free to check whether that's still the case.

**Comment by conradgrobler** [comment]
Actually, the reverse is true. The x86_64-unknown-none target has soft-float enabled by default, and we disable it because of an LLVM bug when building the sha2 crate.
