### ISSUE TITLE
Update and evaluate `wasmi`

### ISSUE THREAD

**Issue by mariaschett** [project-oak/oak#3449]
With the wasmi update we should revisit whether our original assumptions and reasons for choosing wasmi still hold.

Our reasons for wasmi:
- no JIT compilation, hence requires no executable memory
- we do not need wasi
- we need `no_std`

**Comment by tiziano88** [comment]
For the record, I believe you were suggesting looking at https://github.com/bytecodealliance/wasmtime , right?

**Comment by mariaschett** [comment]
As wasmi does not support calling Wasm functions from host functions after the update (cf. [github.com/paritytech/wasmi/issues/572](https://github.com/paritytech/wasmi/issues/572)), our current implementation of `alloc` deadlocks.
