### ISSUE TITLE
Create buildconfig file for Oak Functions enclave binary

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#3507]
We currently have https://github.com/project-oak/oak/blob/main/buildconfigs/oak_functions_freestanding_bin.toml as a placeholder, but we should make it not depend on xtask. Also I suspect we would need to add support for env variables to the buildconfig file format, since for this binary we first need to change PWD, and I don't think we want to involve the shell in this.

@rbehjati if you think that adding support for env variables makes sense, perhaps we should track it as a separate issue for transparent release?

Currently these are the steps we manually run for this specific binary:

```sh
cd oak_functions_freestanding_bin
cargo build --no-default-features --features=simple_io_channel --release
```

We should also probably rename the buildconfig file itself to `oak_functions_enclave.toml`.

**Comment by tiziano88** [comment]
Actually we can probably use the `env` binary for that for the time being.

**Comment by rbehjati** [comment]
Regarding env variables, I think https://github.com/slsa-framework/slsa-github-generator/ (and in particular https://github.com/slsa-framework/slsa-github-generator/issues/1191) is a better place as we are moving the builder code to slsa-github-generator.

If the problem with the command above is related to `cd`, is not it the same as the following?

```
cargo build --no-default-features --features=simple_io_channel --release --manifest-path= oak_functions_freestanding_bin/Cargo.toml
```

If so, I don't understand how the support for env variables can solve this.

**Comment by tiziano88** [comment]
Unfortunately that's not exactly the same, because in that case cargo would not pick up this file: https://github.com/project-oak/oak/blob/main/testing/oak_echo_bin/.cargo/config.toml (it only looks at the PWD from which it is invoked). In fact I tried and it failed (incidentally, the transparent-release tool did not seem to print logs while running, and at the end it claimed that some logs would be in a file that was empty).

Anyways for now I managed to make things work with `env --chdir=... cargo build ...`

**Comment by rbehjati** [comment]
I see. Thanks for the clarification. 

> (incidentally, the transparent-release tool did not seem to print logs while running, and at the end it claimed that some logs would be in a file that was empty)

Thanks for reporting this. We'll have to look into it. Perhaps create an issue on transparent-release.
