### ISSUE TITLE
GCB does not update Bazel cache

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#357]
Currently [Google Cloud Build](https://pantheon.corp.google.com/cloud-build/builds?project=oak-ci) does not update the remote Bazel cache:
```bash
bazel build --remote_cache=https://storage.googleapis.com/oak-bazel-cache --remote_upload_local_results=false --config=enc-sim //oak/server/asylo:oak
```
So the cache is always old, and this could possibly lead to very long builds.
Currently, after the introduction of `clang-tidy`, they are 20+ min.

@tiziano88 WDYT?

**Comment by tiziano88** [comment]
If you set up local gcloud credentials on your machine, then your own runs will populate the cache. I will add instructions on how to do that.

But then we should also make it so that after merging, the CI jobs can populate the cache. Note we do not want CI jobs for PRs to have write access to the cache, for security reasons.

**Comment by tiziano88** [comment]
@ipetr0v could you look into this when you have time? currently I think I am the only one who has set Google credentials locally, so the remote cache is only populated when I run things locally, which is not ideal.

We should create a role account on our [GCB project](https://pantheon.corp.google.com/cloud-build/builds?project=oak-ci), create JSON credentials for it, and then I think we should be able to use the [substitution variables](https://pantheon.corp.google.com/cloud-build/triggers/edit/16e67b67-cc42-4799-abf0-ad22b6c8559b?project=oak-ci) section of GCB to pass those in. Or maybe there is a better way of passing secrets to build runs.

**Comment by tiziano88** [comment]
Potentially useful: https://cloud.google.com/cloud-build/docs/securing-builds/use-encrypted-secrets-credentials#using_the_encrypted_variable_in_build_requests
