### ISSUE TITLE
Delete provenance-related git tags

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#3622]
https://github.com/project-oak/oak/tags shows there are hundreds of tags related to provenance generation, which I don't think we need any more, and they drown out the few tags that we may actually care about (e.g. https://github.com/project-oak/oak/releases/tag/trusted-shuffler-2022 ).

@rbehjati is it ok to remove them? If that's fine I can do that, as it probably requires admin permissions on the repo (though I'm not sure)

**Comment by rbehjati** [comment]
Yes. They can be removed. These belong to the previous style of generating provenances that we no longer use (since #3404). Is there an easy way to remove tags in batches?
