### ISSUE TITLE
Implement Rust Hybrid Encryption

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#3639]
We need to implement Hybrid Encryption scheme which will be used in the [Non-Interactive Attestation](https://github.com/project-oak/oak/blob/main/docs/remote-attestation.md) to send messages from clients to the enclave.

The reasons why we don't want to use [Tink Hybrid Encryption](https://developers.google.com/tink/hybrid) are:
1) Tink doesn't allow to serialize a symmetric key which we want to send to the enclave for encrypting responses
2) We want to split the logic of deriving a session key and encrypting actual messages between the kernel and the user space (i.e. key derivation logic should stay inside the kernel, because we don't want to share the private key with the user space)

We are planning to use crates from the [RustCrypto](https://github.com/RustCrypto) project. And use NIST curves for Diffie-Hellman key exchange.

Ref https://github.com/project-oak/oak/issues/3442

**Comment by tiziano88** [comment]
I just realised that hybrid encryption RFC has a section on bidirectional encryption: https://www.rfc-editor.org/rfc/rfc9180.html#name-bidirectional-encryption . Would that work for us? And is that implemented in Tink?

**Comment by tiziano88** [comment]
https://github.com/google/tink/blob/0d9af8f93fde9705711ff662d1b393770bb666ac/cc/hybrid/internal/hpke_context.h#L102-L108 seems to be the C++ implementation for this

**Comment by tiziano88** [comment]
cc @sidtelang

**Comment by tiziano88** [comment]
cc @daviddrysdale

**Comment by daviddrysdale** [comment]
The Rust port does not include HPKE &ndash; it was added in version 1.7.0 of Tink, but the Rust code is still based on 1.6.x.

**Comment by ipetr0v** [comment]
> I just realised that hybrid encryption RFC has a section on bidirectional encryption: https://www.rfc-editor.org/rfc/rfc9180.html#name-bidirectional-encryption . Would that work for us? And is that implemented in Tink?

Yes, I'm implementing it from the RFC. It has a key exporter, that generates the response key.

**Comment by ipetr0v** [comment]
Implemented a wrapper around Rust HPKE [crate](https://github.com/rozbb/rust-hpke) here: https://github.com/project-oak/oak/pull/3654

Though, this crate doesn't implement bidirectional encryption (i.e. sending responses back to the client), so I had to add this logic as well: https://github.com/project-oak/oak/blob/f3bafea62faaa0a3fc9c3ba003bc14bfa34480b2/oak_crypto/src/hpke.rs#L184-L238
