### ISSUE TITLE
Implement a server-side attester

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#3640]
We need to implement a server-side Attester (as per [RATS terminology](https://datatracker.ietf.org/doc/html/rfc9334)) which will generate attestation evidence and transfer it to the client.

The architecture will look as following:
- A user-space AttesterInterface will use a `write` sys-call (with a special descriptor) to send a protobuf request to the kernel Attester
- Attester runs in the restricted kernel (which is invoked via a sys-call) will write the evidence back into the special descriptor

**Comment by ipetr0v** [comment]
Ref https://github.com/project-oak/oak/issues/3442

**Comment by conradgrobler** [comment]
This has been supeceded by the DICE implementation. For now the approach is that the enclave applications reads all the DICE attestation evidence from a special descriptor. The application is responsible for sending it to the host application/launcher.
