### ISSUE TITLE
Implement client-side attestation verification

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#3641]
We need to implement a client-side Verifier (as per [RATS terminology](https://datatracker.ietf.org/doc/html/rfc9334)) which will verify/appraise evidence (and endorcements) provided by the server-side Attester (https://github.com/project-oak/oak/issues/3640).

**Comment by ipetr0v** [comment]
Ref https://github.com/project-oak/oak/issues/3442

**Comment by tiziano88** [comment]
Do we still need this issue, or do we have other / better ones that cover this?

**Comment by tiziano88** [comment]
@ipetr0v is this done?

**Comment by ipetr0v** [comment]
Yes, it's done
The library and the corresponding client code can be found here:
- https://github.com/project-oak/oak/tree/main/oak_attestation_verification
- https://github.com/project-oak/oak/tree/main/oak_client

But right now we don't have C++ and Java bindings in open-source
