### ISSUE TITLE
Update Oak proto to include a full enclave evidence

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#3656]
Our current Oak interface between the Client and the Launcher doesn't include all of the things necessary for performing a Client-Side Attestation Verification (https://github.com/project-oak/oak/issues/3641).

The structure (that should be probably renamed to `Evidence`) looks like this:
https://github.com/project-oak/oak/blob/d8c147476db02e4360ae06ba19c1363c5260fe13/oak_remote_attestation_noninteractive/proto/v1/messages.proto#L24-L31

And in order to do the attestation verification we need the following things to be sent to the client:
- Enclave public key
- Enclave config
- Attestation report
- AMD certificates
- Endorcement
- Rekor inclusion proof

Ref https://github.com/project-oak/oak/issues/3442

**Comment by ipetr0v** [comment]
cc @rbehjati

**Comment by rbehjati** [comment]
Do the other `PublicKeyInfo` proto messages and structs such as the following have to be kept in sync with the proto here?

https://github.com/project-oak/oak/blob/2667589021cd523d356caa545ee91567ee473be8/oak_functions_service/proto/oak_functions.proto#L44-L47

https://github.com/project-oak/oak/blob/2667589021cd523d356caa545ee91567ee473be8/oak_functions_service/src/remote_attestation.rs#L30-L37

https://github.com/project-oak/oak/blob/2667589021cd523d356caa545ee91567ee473be8/oak_grpc_unary_attestation/proto/unary_server.proto#L39-L44

cc @tiziano88, @conradgrobler

**Comment by ipetr0v** [comment]
`oak_grpc_unary_attestation` is not going to be used.

And `oak_functions_service` will use the [oak/oak_remote_attestation_noninteractive/proto/v1/messages.proto](https://github.com/project-oak/oak/blob/d8c147476db02e4360ae06ba19c1363c5260fe13/oak_remote_attestation_noninteractive/proto/v1/messages.proto#L24-L31) once I finish the remote attestation logic.

**Comment by rbehjati** [comment]
> `oak_grpc_unary_attestation` is not going to be used.

Does this mean that the entire `oak_grpc_unary_attestation` crate can be removed?

> And `oak_functions_service` will just receive the `encrypted_body` from the [oak/oak_remote_attestation_noninteractive/proto/v1/messages.proto](https://github.com/project-oak/oak/blob/d8c147476db02e4360ae06ba19c1363c5260fe13/oak_remote_attestation_noninteractive/proto/v1/messages.proto#L24-L31) once I finish the remote attestation logic.

Is https://github.com/project-oak/oak/issues/3640 the tracking issue for it?

**Comment by ipetr0v** [comment]
> Does this mean that the entire `oak_grpc_unary_attestation` crate can be removed?

I'll remove it once we have a new attestation done

> Is https://github.com/project-oak/oak/issues/3640 the tracking issue for it?

Yes
