### ISSUE TITLE
Add limitations on lookup data

### ISSUE THREAD

**Issue by mariaschett** [project-oak/oak#3662]
Currently, when we load lookup data we don't do much to prevent the host from observing memory access patterns.

We should add this as a limitation to the [README](https://github.com/project-oak/oak/tree/main/oak_functions/lookup) on lookup data.

Some protection is given by:
- the page size,
- the host cannot feed entries key by key and observe the memory patterns when loading the lookup data (the whole lookup data is updated at the same time),
- the entries are stored in a hash map and not laid out consecutively in memory.

However, we leak 
- which clients looked up the same region,
- if the hash function to map the keys is fixed (which I believe it is), the fact they entries are not laid out consecutively in memory does not help much.

Anything else we can think about @conradgrobler , @andrisaar ?

**Comment by conradgrobler** [comment]
A malicious operator can create a fake client that iterates through all possible keys and note the page where each one was looked up, so the randomisation of the hash table only makes this more expensive but does not stop the host from finding this out.
