### ISSUE TITLE
`oak_remote_attestation_noninteractive` crate is rebuilt every time

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#3694]
If I run `cargo check` twice in a row, the `oak_remote_attestation_noninteractive` is always rebuilt, even if nothing has changed. This is probably due to some [rerun-if-changed](https://doc.rust-lang.org/cargo/reference/build-scripts.html#rerun-if-changed) that points to incorrect paths, and therefore cargo thinks that those files have been deleted and re-runs the entire build script and recompiles the crate (though I have not checked in detail).

```
root@tzn0:/workspace# cargo check
   Compiling oak_remote_attestation_noninteractive v0.1.0 (/workspace/oak_remote_attestation_noninteractive)
   Compiling oak_tensorflow_service v0.1.0 (/workspace/oak_tensorflow_service)
   Compiling oak_client v0.1.0 (/workspace/oak_client)
    Checking oak_functions_client v0.1.0 (/workspace/oak_functions_client)
    Checking oak_functions_launcher v0.1.0 (/workspace/oak_functions_launcher)
    Checking oak_functions_load_test v0.1.0 (/workspace/oak_functions/load_test)
    Checking oak_functions_test_utils v0.1.0 (/workspace/oak_functions_test_utils)
    Finished dev [unoptimized + debuginfo] target(s) in 1.28s
```

**Comment by ipetr0v** [comment]
Looks like both `oak_remote_attestation_noninteractive` and `oak_client` use `oak_grpc_utils::generate_grpc_code` in their `build.rs`.
- Is this function outdated?
- Should we use `micro_rpc` instead?

**Comment by tiziano88** [comment]
> Looks like both `oak_remote_attestation_noninteractive` and `oak_client` use `oak_grpc_utils::generate_grpc_code` in their `build.rs`.
> 
> * Is this function outdated?

I don't think so, it seems the correct one to use, but I'm not sure whether there is a more updated one.

> * Should we use `micro_rpc` instead?

No, microRPC is not an alternative to gRPC at all. We still need a tonic server running proper gRPC.

**Comment by tiziano88** [comment]
My guess is that there is something wrong / inconsistent in how we are passing absolute vs relative paths to protobuf files, but I'm not sure.

**Comment by ipetr0v** [comment]
It's possible to fix it by adding `.emit_rerun_if_changed(false)` in
https://github.com/project-oak/oak/blob/4222f413fd48fc29d30e5641e0e1f4ec5670b851/oak_grpc_utils/src/lib.rs#L64-L66

But I'm not sure whether it's a correct solution - since it won't recompile the files if something changed.

**Comment by tiziano88** [comment]
No that's not acceptable, we should figure out the correct solution that rebuilds the protos when changed. Did you manage to get the list of files as emitted by the build.rs file? So we can see if they are correct

**Comment by ipetr0v** [comment]
So we pass the following in the `prost-build` [`compile`](https://github.com/hyperium/tonic/blob/3a38a32a024ad7349735988b2e63c839cc64bf63/tonic-build/src/prost.rs#L443-L444) function:
```
protos: ["../oak_remote_attestation_noninteractive/proto/v1/messages.proto", "../oak_remote_attestation_noninteractive/proto/v1/service_streaming.proto"]
includes: ["../"]
```

**Comment by ipetr0v** [comment]
So these are relative paths.
And looks like there are some problems with relative paths and using `rerun-if-changed`: https://internals.rust-lang.org/t/relative-paths-in-cargo-rerun-if-changed-are-not-properly-resolved-in-depfiles/14563

**Comment by tiziano88** [comment]
Right, so can you try with [absolute paths](https://github.com/project-oak/oak/blob/4222f413fd48fc29d30e5641e0e1f4ec5670b851/micro_rpc/build.rs#L21) and see if that fixes it?

**Comment by ipetr0v** [comment]
Already tried with `std::fs::canonicalize`, but it still recompiles the crates.

**Comment by ipetr0v** [comment]
Another possibility could be that we put our whole repo into the `includes`.

**Comment by ipetr0v** [comment]
If I put a correct include: `oak_remote_attestation_noninteractive/proto/v1` it stops recompiling the packages (except for tensorflow, but there is probably a different error).

But in the proto files we need to change imports to relative paths, i.e. from
```
import "oak_remote_attestation_noninteractive/proto/v1/messages.proto";
```
to
```
import "messages.proto";
```
But because of this VSCode shows this as an error (though it compiles correctly).

**Comment by tiziano88** [comment]
This keeps being a problem (and requires rebuilding a lot of crates every time, even for invoking simple tests), could you propose a PR for now and we discuss there? Or do you think we should move protos to a different folder structure?

**Comment by tiziano88** [comment]
@ipetr0v this is still an issue, is there anything we can do to fix it?

**Comment by tiziano88** [comment]
This is still a major problem, it causes all crates to be rebuilt almost every time.

Should we just move all the protos under a top-level proto folder? After all we could treat that as a separate language (similar to java).

@thmsbinder do you have any suggestions?

**Comment by tiziano88** [comment]
I'm trying something in #3940 to try and address the issue in the meanwhile

**Comment by thmsbinder** [comment]
`oak_remote_attestation_noninteractive` contains `build.rs` which is not contained in most other projects. Apparently a service stub is compiled. Can this be achieved by some other means?

**Comment by tiziano88** [comment]
I think this was fixed along the way.
