### ISSUE TITLE
Remove patch for virtio-drivers crate when the next version is released

### ISSUE THREAD

**Issue by conradgrobler** [project-oak/oak#3706]
When upgrading the virtio-drivers crate I had to create https://github.com/rcore-os/virtio-drivers/pull/62 to be able to use the virtio console device as a comms channel. Once that is merged and released we must stop overriding the dependency.

**Comment by tiziano88** [comment]
@conradgrobler can the patch be removed now?

**Comment by conradgrobler** [comment]
Yes, I think so. I will remove it.
