### ISSUE TITLE
Race condition in the xtask run-launcher-test

### ISSUE THREAD

**Issue by conradgrobler** [project-oak/oak#3715]
The virtualised branch of run-launcher-test fails if the client is already built (e.g. when running it twice in a row). The server takes too long to load the enclave application. It always passes in CI, since it must always rebuild the client and that takes long enough that the server finishes loading the enclave application before the client starts making requests.

**Comment by tiziano88** [comment]
Yeah i noticed this too yesterday, we should probably add a sleep somewhere :)
