### ISSUE TITLE
Remove linux variant for of Oak Functions

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#3738]
We should consider dropping the linux variant, and doing everything with the KVM variant only (e.g. in tests and examples). I don't see much value in keeping both at this point, since we are already set on KVM.

The main advantage of the linux variant would be that it can run on machines without KVM, and perhaps that it's marginally faster, but booting the Oak Restricted Kernel seems fast enough that we can use it for everything.

WDYT @andrisaar ?

**Comment by andrisaar** [comment]
Yeah, I dont think we get much value from the Linux variants these days. Plus, this means we can delete the Linux binaries in addition to the loader.

**Comment by andrisaar** [comment]
@ipetr0v may also have opinions.

**Comment by conradgrobler** [comment]
I agree that they don't add much value at the moment

**Comment by jul-sh** [comment]
I agree we should remove it. Eventually doing so would also allow us to clean up our code a bit.

**Comment by jul-sh** [comment]
Does this issue propose dropping just https://github.com/project-oak/oak/tree/main/oak_functions_linux_vsock_bin, or also https://github.com/project-oak/oak/tree/main/oak_functions_linux_fd_bin?

**Comment by jul-sh** [comment]
#3758 added benchmarks relying on the file descriptor linux version. Are we okay to remove them or do we want to implement benchmarks with the VM version?

**Comment by tiziano88** [comment]
The main reason for that was that we could not run KVM tests or benchmarks on GitHub actions, but now that we are running everything on Kokoro I think we should make everything use the KVM stack that is closest to production, and remove the Linux one.

**Comment by jul-sh** [comment]
Alright, I shall dutifully filet the code and rip out everything though. I fixed the thread leak btw, ref: #3919

**Comment by jul-sh** [comment]
@mariaschett Do you think you could take another look at the data integration tests you added in #3661 to work with the KVM version? 

@tiziano88 added a version of a lookup data test to the same file in #3884. But I want to make sure the KVM tests cover all the concerns your tests do.

**Comment by mariaschett** [comment]
Hi @jul-sh , sorry for my late reply! 

I am sure the test is fine, otherwise we fix it when we need it again, not worth spending a lot of thought now :) 

It is basically to try and load 2 GiB of lookup data and it takes ages (because it is inefficient).

**Comment by jul-sh** [comment]
Okay! thanks for confirming.

**Comment by jul-sh** [comment]
> The main reason for that was that we could not run KVM tests or benchmarks on GitHub actions, but now that we are running everything on Kokoro I think we should make everything use the KVM stack that is closest to production, and remove the Linux one.

Updated the title to reflect the clarified scope of the issue

**Comment by jul-sh** [comment]
currently blocked by #3931
