### ISSUE TITLE
Simplify `update_lookup_data` by removing `START` and `START_AND_FINISH`

### ISSUE THREAD

**Issue by mariaschett** [project-oak/oak#3763]
We currently have [UpdateActions](https://github.com/project-oak/oak/blob/3cc6ae8592ef347d95f78b88b944bf8fe0a4638a/oak_functions_service/proto/oak_functions.proto#L67) to explicitly `start` and `start_and_finish` an update of lookup data.

The only advantage I can see is that the service will return an error when starting twice. However, I don't see much benefit. 
 
So as discussed before and suggested by @conradgrobler --- I want to remove `start` and `start_and_finish` and rename `continue` to `extend`. This would simplify the logic quite a bit.

**Comment by mariaschett** [comment]
Any objections, @tiziano88 , @conradgrobler ?

**Comment by conradgrobler** [comment]
No, I think it is a good idea.
