### ISSUE TITLE
Create single-application Oak server

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#383]
Implement a new binary called `oak_server` or similar, which is effectively a slimmed down version of the Oak Manager that loads a single Oak Application provided as a command line argument (i.e. the argument points to a file containing a textual or binary representation of the Oak Application).

`oak_server` creates a single enclave with an instance of the Oak Runtime and loads the provided Application there.

`oak_server` does not expose an untrusted gRPC interface, though the Oak Application that it runs may have a gRPC node that exposes a trusted gRPC interface (used by clients to interact with the Oak Application).

It is not possible to create multiple enclaves or to change the Oak Application that is running; instead this would require restarting the `oak_server` instance.

Related to #382 (but not necessarily blocking in either direction).

**Comment by tiziano88** [comment]
@ipetr0v could you look into this? It feels like a natural continuation of #382 .

**Comment by ipetr0v** [comment]
Sure, I'll look into this
