### ISSUE TITLE
Define serialization format for Oak messaging system

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#389]
It is still early to talk about this in details, but at some point we will need a protocol that allows messages and handles to be serialized and deserialized, both when moving around a single Oak Runtime, and also when talking to remote Oak Runtimes.

It looks like FIDL already supports most of the things we would need, and it has bindings for Rust and C++, among others. See https://fuchsia.dev/fuchsia-src/development/languages/fidl/reference/wire-format . It is unclear how easy it is to use it outside of Fuchsia though.

It would be nice to extend the wire format and client libraries to support attaching labels to objects, so that e.g. the primary object may have a different label than the secondary objects. This would allow us to support cases in which a single message contains data with different levels of secrecy / integrity. For instance, in a chat application, a message may contain the chat room id as a public field, but have a more restrictive label for the actual content of the message. In order to support this, we would probably need the message buffers to be owned by the runtime, and offer special functions provided by the runtime that allow traversing messages and change the label of the node performing the operation based on the label of the inspected fields.

@daviddrysdale assigning this to you for now since you have already put a lot of thought into the current messaging and policy system.

/cc @anghelcovici @conradgrobler since we talked about related aspects.

**Comment by daviddrysdale** [comment]
@tiziano88, you seem to be running with this now.
