### ISSUE TITLE
MicroRPC: Pass ownership of requests to the service implementation

### ISSUE THREAD

**Issue by jul-sh** [project-oak/oak#3898]
Presently the server generated by microRPC passes the parsed request to the service implementation as a borrowed value ([source code](https://github.com/project-oak/oak/blob/1fd2accd09a52a9b7b55e798a99ba45236a1862d/micro_rpc_build/src/lib.rs#L205)). The consequence is that the service implementation usually clones the borrowed request. 

This clone isn't ideal if the request is very large (such is the case in #3791). For #3791 we'd like to avoid this clone.

This can be done by amending server code generated by microRPC. Imo it's safe to do this for pretty much all cases. At the present this change should only affect the rust version (the only other microRPC version is C++, and at present it only contains client side logic).

**Comment by tiziano88** [comment]
For my understanding: Is this similar to #3848 but specifically about the server ownership of the request? If so, is the idea that the client will still only borrow the request, since it needs to serialize it into a request proto anyways (and hence copy it there at least once), but from then on, we can pass the parsed request by value to the server, which can then take ownership of it (e.g. avoid reallocating individual vecs that are contained in the request)? I also want to make sure that https://github.com/project-oak/oak/issues/3848#issuecomment-1506828020 is addressed; if my above understanding is correct, that would require an extra copy in the server, since by default we would only get a reference into the Wasm memory, but now we would have to clone that into an owned Vec in order to pass ownership of it to the server implementation.

**Comment by jul-sh** [comment]
> For my understanding: Is this similar to #3848 but specifically about the server ownership of the request? If so, is the idea that the client will still only borrow the request, since it needs to serialize it into a request proto anyways (and hence copy it there at least once)

yes


> but from then on, we can pass the parsed request by value to the server, which can then take ownership of it (e.g. avoid reallocating individual vecs that are contained in the request)?

yes, with the clarification that we already pass the an owned request to the server. 

>I also want to make sure that [#3848 (comment)](https://github.com/project-oak/oak/issues/3848#issuecomment-1506828020) is addressed; if my above understanding is correct, that would require an extra copy in the server, since by default we would only get a reference into the Wasm memory, but now we would have to clone that into an owned Vec in order to pass ownership of it to the server implementation.

I'm not sure I fully understand your comment. Could you possibly rephrase? At which point do we read from the Wasm memory? — I might be misunderstanding, but from what I can tell at the moment this should not be a concern. The response returned from the Wasm module is already cloned. It would not be affected by this change.

**Comment by tiziano88** [comment]
I am thinking specifically about migrating the Wasm ABI to use micro RPC (which I realise I haven't written down, so I just did: #3900 ).

In that case, the "server" implementation of the ABI (in which the Wasm module is the client, and the Oak Functions runtime is the server) will only get a "view" of the client request in the Wasm memory (i.e. will not be able to own it, unless we make an extra copy). Does that make sense?

**Comment by jul-sh** [comment]
> I am thinking specifically about migrating the Wasm ABI to use micro RPC 

ah ok, I was wondering if you were. 

> In that case, the "server" implementation of the ABI (in which the Wasm module is the client, and the Oak Functions runtime is the server) will only get a "view" of the client request in the Wasm memory (i.e. will not be able to own it, unless we make an extra copy). Does that make sense?

I don't think this matter for the this proposed change. The server [already only gets a borrowed slice](https://github.com/project-oak/oak/blob/5e359989de9a14852cc41564b724fe4ef2edd5b7/micro_rpc_tests/out/micro_rpc.tests.rs.txt#L29). [It then decodes an owned request message from the borrowed slice](https://github.com/project-oak/oak/blob/5e359989de9a14852cc41564b724fe4ef2edd5b7/micro_rpc_tests/out/micro_rpc.tests.rs.txt#L46). This will not change.

**Comment by tiziano88** [comment]
Ah yes great point -- proto deserialization will always end up with an owned object, so my point is irrelevant.
