### ISSUE TITLE
Scorecards analysis failing at HEAD

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#3901]
See https://github.com/project-oak/oak/actions/runs/4787487355/jobs/8512786216

@rbehjati can this be deleted by any chance? If not, could you look into a fix?

**Comment by rbehjati** [comment]
Created #3902, but I am not sure if it fixes the problem.
We can remove scorecards integration, as we have not really been using it.

**Comment by tiziano88** [comment]
Yes let's remove it if it's not needed
