### ISSUE TITLE
Create separate crates / libraries for Rust runtime

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#392]
#386 made the Rust Oak Runtime more amenable to be embedded in the [Rust part of the server](https://github.com/project-oak/oak/tree/master/oak/server/rust). We would still like to be able to use the runtime in various contexts though, including:

- running in SGX via Asylo C++ bindings
- running in SGX via some other Rust SDK (e.g. https://github.com/fortanix/rust-sgx)
- running without enclave support (similar to what we currently call ["dev" server](https://github.com/project-oak/oak/tree/master/oak/server/dev))
- running as part of tests

In order to do this, we need to define a clear interface of what the Runtime needs / expects from the underlying system (e.g. allocator, panic handler, enclave primitives, etc.), and implement such interfaces for the various contexts described above. I guess this may be done by defining one or more traits and some sort of "manual dependency injection" of the correct implementation of such trait into the runtime (my preferred approach), or by using [conditional feature gates](https://doc.rust-lang.org/1.0.0/book/conditional-compilation.html) (similar to how `std` is implemented for different platforms).

https://github.com/project-oak/oak/blob/ec5b3384c10546ff64e6381000f14d58cb9cfc41/oak/server/rust/src/lib.rs#L26-L27

https://github.com/project-oak/oak/blob/ec5b3384c10546ff64e6381000f14d58cb9cfc41/oak/server/rust/src/lib.rs#L33-L43

/cc @daviddrysdale @blaxill

**Comment by blaxill** [comment]
I guess I'm somewhat addressing this with my asylo/rust compatibility stuff at

https://github.com/project-oak/oak/compare/master...blaxill:rust-runtime

This is basically core+alloc+threads+mutexes- I haven't supported backtrace/panic handling as it requires things unsupported by Asylo.

**Comment by tiziano88** [comment]
Thanks, makes sense, so I guess you are leaning towards global functions for creating and manipulating things (e.g. `enclave::Mutex::new()`), and provide different implementations of those based on feature gates, is that correct?

**Comment by blaxill** [comment]
Yeah either rust feature gates or bazel rules. I see it as - my `enclave` subdirectory can become `asylo` and the parent `oak_runtime_compat` will contain generic types that use the implementations in subdirectories.

**Comment by tiziano88** [comment]
To clarify, the alternative I was referring to would be something like the following:

```rust
trait Platform {
  fn new_mutex() -> Mutex
  fn new_thread() -> Thread
  ...
}
```

and pass an implementation of that in to an instance of the Oak Runtime.

**Comment by blaxill** [comment]
I've been following `std::*` which doesn't expose a Platform trait, but is a similar effect:

~~~rust
fn new_mutex() -> impl::Mutex;
fn new_thread() -> impl::Thread;
~~~

Since there are never multiple `impl` types in scope (due to feature gating). Although I see the value in defining a `Platform` trait for us to have a better definition for the functions/types we need exposed.

**Comment by tiziano88** [comment]
If only we had algebraic effects... :) or at least monads!

**Comment by blaxill** [comment]
I suppose the compatibility layer needs to support the features needed by our hardcoded nodes: untrusted file interaction, network (or just https?), and grpc(or whatever we replace it with?)

**Comment by blaxill** [comment]
Closing in favour of #540
