### ISSUE TITLE
Oak Functions integration benches failing

### ISSUE THREAD

**Issue by jul-sh** [project-oak/oak#3931]
`cargo bench --package=oak_functions_launcher`

Fails with the following log at [head](https://github.com/project-oak/oak/commit/1b5ddb66ca32c28dcd720ddc525420e5eba01406).

```
thread 'main' panicked at 'server encountered an unrecoverable error: couldn't receive message

Caused by:
    0: couldn't read frame
    1: failed to fill whole buffer', oak_functions_linux_fd_bin/src/main.rs:67:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test bench_key_value_lookup ... FAILED

failures:

---- bench_key_value_lookup stdout ----
thread 'main' panicked at 'assertion failed: response.is_ok()', oak_functions_launcher/benches/integration_benches.rs:86:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    bench_key_value_lookup

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 16.21s

```

We should either remove this bench, or fix the failure and add a check in CI.

**Comment by tiziano88** [comment]
Thanks for filing this, we should fix it, and then look into whether it's possible to add it to CI in a reasonable way. I don't know how long it takes at the moment to run the entire benchmark, perhaps we need to pass some flag just so that we run it once to make sure it's correct, instead of doing all the iterations

**Comment by tiziano88** [comment]
I have a partial fix, to unblock some basic benchmarking.

**Comment by jul-sh** [comment]
sweet! 🏃

**Comment by tiziano88** [comment]
But I'll send it out tomorrow (I mostly wanted to unblock the Wasm / no-Wasm comparison)

**Comment by jul-sh** [comment]
sgtm, either way it's almost 11pm your time :-)  🌙
