### ISSUE TITLE
Replace bash scripts

### ISSUE THREAD

**Issue by blaxill** [project-oak/oak#396]
It would be nice to have building/formatting/etc. scripts in a language more maintainable/editable than bash. This would also allow a number of other small wins E.g. Currently the scripts are not compatible with macOS even though all the building / running can be execute in docker (it requires some bash shims to fix macOS unsupported thing(s)).

Some more thoughts here https://github.com/project-oak/oak/pull/394#discussion_r359858779

**Comment by tiziano88** [comment]
Rust all the things!

**Comment by tiziano88** [comment]
ref. https://doc.rust-lang.org/std/process/struct.Command.html

**Comment by blaxill** [comment]
I'm not opposed to using Rust, but it would be great if we could choose something that did dependency freshness tracking (where applicable).

**Comment by tiziano88** [comment]
FWIW Bazel already does deps tracking. If we go with Rust, it would just replace our shell scripts, not Bazel.

Also there may be ways of integrating the Rust workflows more tightly by using [`bazel query`](https://docs.bazel.build/versions/master/query-how-to.html) -- though I don't think it will be necessary.

**Comment by blaxill** [comment]
Yeah maybe we should try to Bazel-all-the-things first then see what remains. Some things might benefit from dependency tracking but not fit the Bazel model, such as formatting? (Does Bazel prevent overwriting?)

**Comment by tiziano88** [comment]
You are right, things like formatting and linting are not great fits for Bazel, but it's also simpler and cheaper to just rerun these tools unconditionally on all the source files anyways. That shouldn't really be a problem for a while, I hope, unless we end up with a lot more files than we have now!

**Comment by blaxill** [comment]
As a note, some of our bash scripts will fail loudly (e.g. bazel errors), others will fail "quietly" (e.g. error codes but no error message for missing formatters)

**Comment by tiziano88** [comment]
Tentatively self-assigning to try something out.
