### ISSUE TITLE
Create example for setting up full bidirectional communication between nodes.

### ISSUE THREAD

**Issue by conradgrobler** [project-oak/oak#402]
It would be useful to build a hello world example that uses two nodes that communicate with each other:

- gRPC node creates node 1.
- Node 1 creates node  2.
- Node 1 sends a message to node 2.
- Node 2 modified it and sends it back to node 1.
- Node 1 sends it back to the gRPC node.

**Comment by daviddrysdale** [comment]
BTW, the abitest example does do this but it's buried in a bunch of test code and so not helpful as an example to point at.

**Comment by conradgrobler** [comment]
There is now a good sample of this with translator client used in the hello world example: #537
