### ISSUE TITLE
Implement DICE Attestation

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#4074]
We are planning to implement Remote Attestation Evidence generation and verification using DICE.

DICE will allow us to have separate Evidence entries for each Layer, where a Layer is represented by its code and config. The reason for using DICE is to generate Attestation Evidence for both current use-cases: Restricted Kernel and Linux Kernel.

References:
- [DICE Attestation Architecture](https://trustedcomputinggroup.org/wp-content/uploads/TCG_DICE_Attestation_Architecture_r22_02dec2020.pdf)
- [DICE Layering Architecture](https://trustedcomputinggroup.org/wp-content/uploads/DICE-Layering-Architecture-r19_pub.pdf)

Ref https://github.com/project-oak/oak/issues/3442

**Comment by ipetr0v** [comment]
cc @tiziano88 @conradgrobler @andrisaar @sidtelang

**Comment by tiziano88** [comment]
@ipetr0v maybe this can be closed - I think we have a corresponding one in b/ now, which has more details and links to other related issues.

**Comment by ipetr0v** [comment]
Agree, can close the issue

Also because most of the DICE attestation logic has already been implemented
