### ISSUE TITLE
`cargo udeps` does not work on `stage0_bin` crate

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#4129]
```console
$ env --chdir=./stage0_bin cargo udeps
error: Package `test v0.0.0 (/nix/store/8y16j8ja4jpr61gxkq4mcqj5k94pk17z-rust-default-1.72.0-nightly-2023-07-03/lib/rustlib/src/rust/library/test)` does not have the feature `backtrace` 
```

It seems caused by the `build-std` config:

https://github.com/project-oak/oak/blob/e5aadbef274a583f90a08c2d9b43c03d9c7abcff/stage0_bin/.cargo/config.toml#L9

(removing it makes it work again)

Possibly related to https://github.com/est31/cargo-udeps/issues/153

**Comment by conradgrobler** [comment]
It also does not work on `oak_restricted_kernel_wrapper` either. I think it is because `cargo udeps` still checks the test-related dependencies even if the binary is marked as having no tests and not benches in the Cargo.toml file.
