### ISSUE TITLE
Enable Hybrid Encryption in Oak

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#4146]
We need to enable Hybrid Encryption in all of our examples simultaneously.

Ref https://github.com/project-oak/oak/issues/3442

**Comment by tiziano88** [comment]
Since we will need to then import the binaries and fix the internal code at the same time, please make sure that all the libraries are ready, and that the importer tool works correctly for all the binaries, so we don't run into issues that would leave the state inconsistent for too long.

cc @rbehjati @thmsbinder

**Comment by ipetr0v** [comment]
Add the list places where encryption should be enabled as a reminder:

- Rust
https://github.com/project-oak/oak/blob/c07612d761deeb553f99919bcbbcf4fc7898e62c/oak_crypto/src/hpke/mod.rs#L162-L166
https://github.com/project-oak/oak/blob/c07612d761deeb553f99919bcbbcf4fc7898e62c/oak_crypto/src/hpke/mod.rs#L182-L186
https://github.com/project-oak/oak/blob/c07612d761deeb553f99919bcbbcf4fc7898e62c/oak_crypto/src/hpke/mod.rs#L209-L216
https://github.com/project-oak/oak/blob/c07612d761deeb553f99919bcbbcf4fc7898e62c/oak_crypto/src/hpke/mod.rs#L239-L246

- Java
https://github.com/project-oak/oak/blob/c07612d761deeb553f99919bcbbcf4fc7898e62c/java/src/main/java/com/google/oak/crypto/hpke/Context.java#L42-L48
https://github.com/project-oak/oak/blob/c07612d761deeb553f99919bcbbcf4fc7898e62c/java/src/main/java/com/google/oak/crypto/hpke/Context.java#L79-L85
https://github.com/project-oak/oak/blob/c07612d761deeb553f99919bcbbcf4fc7898e62c/java/src/main/java/com/google/oak/crypto/hpke/Context.java#L116-L122
https://github.com/project-oak/oak/blob/c07612d761deeb553f99919bcbbcf4fc7898e62c/java/src/main/java/com/google/oak/crypto/hpke/Context.java#L153-L159
