### ISSUE TITLE
Add structs for working with claims and in-toto statements

### ISSUE THREAD

**Issue by rbehjati** [project-oak/oak#4196]
We need these strcuts both in the ML-transparency runner, and for parsing and verifying endorsement statements.

**Comment by rbehjati** [comment]
@tiziano88 I am thinking of creating a top-level `claims` folder for these structs. Do you think that is a good place for it?

**Comment by tiziano88** [comment]
SG; will we need Rust, Java and C++ versions for these, eventually?
