### ISSUE TITLE
Document build steps without Docker

### ISSUE THREAD

**Issue by aalmos** [project-oak/oak#42]
Add documentation for building without Docker on selected platforms (Ubuntu?). I was able to build it on Arch, it should be possible to do so on arbitrary distros. Note that the project doesn't compile with Bazel version <0.2.3, it should be asserted too.

**Comment by tiziano88** [comment]
Thanks! How did you install the Intel SGX SDK? was it available as a package? Or did you follow the steps from the [Asylo Dockerfile](https://github.com/google/asylo/blob/master/asylo/distrib/toolchain/Dockerfile)?

**Comment by aalmos** [comment]
I followed the one from Asylo Dockerfile (compile-install manually). It's still unclear to me how to specify a custom asylo directory though, but I'll figure that out. I'll make a PR on this when I'll have some free time.

**Comment by aalmos** [comment]
Plus one idea: shall we build a deb/rpm package for Asylo? Do know of a package source that could host that for us?

**Comment by daviddrysdale** [comment]
The [docs/INSTALL-OSX.md file](https://github.com/project-oak/oak/blob/master/docs/INSTALL-OSX.md) [now](https://github.com/project-oak/oak/pull/837) has some instructions for building without Docker (albeit on MacOS).
