### ISSUE TITLE
Make `Handle` an opaque non-serializable type

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#427]
It is too easy to accidentally or intentionally serialize this to bytes and send it to a different node, but handles need to be explicitly sent across node boundaries and remapped on the other side in order to be meaningful, therefore we should have an API that ensures that handles are pulled out and reconstructed on the other side when performing `write` / `read` operations.

https://github.com/project-oak/oak/blob/ba65f62d67217eea1e5ff2ba749492741c4451d7/sdk/rust/oak/src/lib.rs#L37-L40

**Comment by blaxill** [comment]
Closing as #429 is now merged
