### ISSUE TITLE
Rename micro RPC request / response messages

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#4295]
I think the current names are too generic, and easily mixed up with other types or variable names.

Perhaps we should rename those messages to `RequestWrapper` / `ResponseWrapper`.

@conradgrobler @pmcgrath17 @ipetr0v WDYT?

https://github.com/project-oak/oak/blob/281da281eb50e8f1312c1d7cc6c1868227d6f1fc/micro_rpc/proto/messages.proto#L22

https://github.com/project-oak/oak/blob/281da281eb50e8f1312c1d7cc6c1868227d6f1fc/micro_rpc/proto/messages.proto#L45

**Comment by conradgrobler** [comment]
Sounds like a good idea.

**Comment by pmcgrath17** [comment]
Makes sense to me

**Comment by pmcgrath17** [comment]
The proto message names have been changed. Closing.
