### ISSUE TITLE
Remove Oak Manager

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#431]
When #413 is done we should also change the tests so that they compile and package the server side Oak application, run it in a single-app Oak server, and remove the need for the client code to interact with the Oak manager.

In fact I think we should consider dropping the Oak manager eventually and just keep the single-app server.

If anyone in @project-oak/core can think of a reason / use case to keep around the Oak manager, please reply here.

**Comment by blaxill** [comment]
Could you clarify what the difference between single-app vs manager is- Am I correct in thinking that the manager can serve multiple oak-based apps where as the single-app is per instance?

**Comment by ipetr0v** [comment]
The key difference is that with current version of `Manager` a client needs to compile a Wasm module and load it remotely into the server.
In the single-app scenario this module is loaded on `oak` startup without involving a client.

**Comment by tiziano88** [comment]
@blaxill yes the proposal is for the Oak runner (for lack of a better name) to provision and run a single instance of an Oak application.

Conceptually the Oak runner is similar to an interpreter / server that reads the configuration at startup, it will have a flag pointing to a file containing the serialized (probably protobuf) Oak application, and run that. Somewhat similar to how [wasmer](https://github.com/wasmerio/wasmer#usage) runs individual wasm files.

**Comment by daviddrysdale** [comment]
Some notes on what needs updating for a shift to using a single-Application server everywhere:
 - Documentation:
      - Programming Oak doc, esp. [section on client invocation](https://github.com/project-oak/oak/blob/master/docs/programming-oak.md#using-an-oak-application-from-a-client)
      - Concepts doc, esp. [Oak Manager section](https://github.com/project-oak/oak/blob/master/docs/concepts.md#oak-manager) and diagrams
      - Dev doc, replacing multi-Application server invocation with solo-App server instructions
 - Scripting
      - [Runs of all examples against Asylo dev server](https://github.com/project-oak/oak/blob/master/scripts/run_examples)
      - ASAN/TSAN [runs of all examples against local dev server](https://github.com/project-oak/oak/blob/master/scripts/run_examples_dev)
      - [Drop](https://github.com/project-oak/oak/blob/master/scripts/run_server_asylo) [scripts](https://github.com/project-oak/oak/blob/master/scripts/run_server_dev) for running multi-App server
 - Client code:
      - Remove all application creation from example clients
        - **Note**: this will remove the chat app's current functionality that allows parallel independent chat environments to be running on the same server.
 - Server code:
      - Drop both of `//oak/server/{dev,asylo}/`

**Comment by ipetr0v** [comment]
Additionally need to delete `NewApplicationId` logic.
Based on the following comment:
https://github.com/project-oak/oak/pull/553/files#r375387887
