### ISSUE TITLE
Non-blocking channel read 

### ISSUE THREAD

**Issue by blaxill** [project-oak/oak#432]
Currently there is no way to check if a channel has messages in a non-blocking way. That is, `channel_read` and `wait_on_channels` will both block until a message is available. For example [Fuchsia `channel_read`](https://fuchsia.dev/fuchsia-src/reference/syscalls/channel_read) is non-blocking.

**Comment by daviddrysdale** [comment]
`channel_read` [returns immediately](https://github.com/project-oak/oak/blob/master/oak/server/wasm_node.cc#L322-L333) if no message is available, with [zero length/count](https://github.com/project-oak/oak/blob/master/examples/abitest/module/rust/src/lib.rs#L334-L343).

**Comment by blaxill** [comment]
Thanks, can you clarify for me:

- Is this distinguishable from sending a zero length message? (Do we support sending a zero length/zero channel count message?)
- Perhaps we should add an additional "channel empty" status code to return?

I'll leave this issue open until we've updated https://github.com/project-oak/oak/blob/master/docs/abi.md

**Comment by daviddrysdale** [comment]
Ah, good spot, I don't think an empty channel is distinguishable from one with a totally empty message in it &ndash; we should check/fix.

**Comment by blaxill** [comment]
Closed by #450
