### ISSUE TITLE
Investigate options for minimal web server that can run inside the Oak runtime

### ISSUE THREAD

**Issue by conradgrobler** [project-oak/oak#438]
It might be useful to have a web server we can run inside the Oak runtime for Chrome - Oak web apps.

Some basic requirements (although some of these features can run in wasm nodes):

- Support TLS
- TLS stack should be extensible to allow adding remote attestation support
- Should be able to serve static content such as scripts and html
- Should be able to route REST requests to appropriate WASM nodes to handle them
- Would be nice to support web sockets as well

**Comment by michael-kernel-sanders** [comment]
I've previously used CivetWeb as an embedded HTTPS/WebSocket server:
https://github.com/civetweb/civetweb

**Comment by conradgrobler** [comment]
If we move more of the TCB to rust, we can also consider:
For http:
https://docs.rs/hyper/0.13.1/hyper/
https://github.com/hyperium/h2
https://tiny-http.github.io/tiny-http/tiny_http/index.html

For websockets:
https://github.com/snapview/tungstenite-rs

These all provide lightweight, low-level protocol libraries. Most can easily integrate with (or are built on top of) https://tokio.rs/.

Unfortunately, none of these seem to have reached a production-ready release state.

**Comment by conradgrobler** [comment]
Running these inside an enclave (as TLS must terminate in the enclave) will require significant patching.

As an example:
Baidu ported a fork of MIO to run under teaclave (https://github.com/mesalock-linux/mio-sgx/commit/ac3d400b275abe9015de90c1ccd560e79ea7f633). This in turn required porting _log_, _slab_, _net2_ and _iovec_. Patching _log_ in turn required _serde_ to be patched.

They also ported _rustls_ to provide TLS support in the enclave, which required porting _base64_, _ring_, _sct_, and _webpki_.

**Comment by conradgrobler** [comment]
Hyper has been chosen, and the runtime does not currently require no_std, so no patching is required.
