### ISSUE TITLE
Centralize protos under project-oak/oak/proto

### ISSUE THREAD

**Issue by thmsbinder** [project-oak/oak#4392]
Currently, most protocol buffer definitions are stored in folders along with Rust crate folders. However, they are not subordinate to Rust; they are equally used by all languages (notably C++ and Java).

Another advantage is that we can unconditionally mirror the new proto directory to Piper using copybara, and have more reliable internal dependencies on it.

**Comment by thmsbinder** [comment]
Let's keep open since there are more proto defs in various Rust module directories.

**Comment by thmsbinder** [comment]
Right now, at head `bazel build proto/...` fails. It doesn't block anything but is not nice. We should have build_tests everywhere (and make this a soft requirement).

**Comment by ipetr0v** [comment]
We also have the following proto directories that could also be moved:
- [`oak_containers/proto/`](https://github.com/project-oak/oak/tree/main/oak_containers/proto)
  - Could be moved into the recently added [`proto/containers/`](https://github.com/project-oak/oak/tree/main/proto/containers)
  - I also think we could split different Orchestrator and Hostlib services into separate `.proto` files
- [`oak_crypto/proto/v1/`](https://github.com/project-oak/oak/tree/main/oak_crypto/proto/v1)
  - Could be moved into `proto/crypto/`
- [`oak_remote_attestation/proto/v1/`](https://github.com/project-oak/oak/tree/main/oak_remote_attestation/proto/v1)
  - It currently only contains Oak Session repated protos
  - Could be moved into `proto/session/`

**Comment by ipetr0v** [comment]
> @ipetr0v is the plan to eventually delete the session protos?

I think we'll still use session protos for some of our use-cases

**Comment by tiziano88** [comment]
Just want to check about this -- @ipetr0v @k-naliuka  is it correct that we expect the client SDKs eventually to work against any gRPC streaming method taking RequestWrapper and returning ResponseWrapper? But also that we don't expect client teams to use literally the service defined in StreaminSession (below), but we expect them to define their own service elsewhere (and this service will be removed then)?

https://github.com/project-oak/oak/blob/7beb64f51fe7b54d85f5a1c2cbae5441e670ff2c/proto/session/service_streaming.proto#L40-L56

**Comment by ipetr0v** [comment]
> Just want to check about this -- @ipetr0v @k-naliuka is it correct that we expect the client SDKs eventually to work against any gRPC streaming method taking RequestWrapper and returning ResponseWrapper? But also that we don't expect client teams to use literally the service defined in StreaminSession (below), but we expect them to define their own service elsewhere (and this service will be removed then)?

Yes, clients can either use our default service, or implement their own version of the [`Transport`](https://github.com/project-oak/oak/blob/main/java/src/main/java/com/google/oak/transport/Transport.java) and [`EvidenceProvider`](https://github.com/project-oak/oak/blob/main/java/src/main/java/com/google/oak/transport/EvidenceProvider.java) interfaces - and in this case they won't even need to use `RequestWrapper`/`ResponseWrapper`.

**Comment by tiziano88** [comment]
Ok great, even better. So each client should create and own their service definition, and we can delete session.proto, right? In fact, even for our own examples, I think we should create separate service definitions.

**Comment by ipetr0v** [comment]
Yes, the clients need to own their own code (though I still think it may be convenient for some clients to just rely on the default services/transport implementations).

As for our examples, I think there will be a lot of code duplication if we want to have separate service definitions (and thus transport implementations).

**Comment by tiziano88** [comment]
> As for our examples, I think there will be a lot of code duplication if we want to have separate service definitions (and thus transport implementations).

Well I think that's something we should think about, if we are asking client teams to do the same. Personally I think an acceptable trade off would be to still expose the RequestWrapper and ResponseWrapper messages, and also provide a Java transport implementation that works on any method that has that signature (so it would be only one line of code from the client side to specify which gRPC method to use to implement the transport, and everything is type safe).

Sharing the same gRPC service is not semantically correct anyways IMO, since each example does something different in general.
