### ISSUE TITLE
Rename `GetPublicKey` to `GetEndorsedEvidence`

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#4417]
Before sending an encrypted request to Oak, clients request an attestation evidence that contains a public key used for encryption.

Current method for requesting evidence is called `GetPublicKey` in both Unary:
https://github.com/project-oak/oak/blob/c8587e96af6b02e7bae4b248ae3a268ddafec6c2/oak_remote_attestation/proto/v1/service_unary.proto#L28-L29

And Streaming implementations:
https://github.com/project-oak/oak/blob/c8587e96af6b02e7bae4b248ae3a268ddafec6c2/oak_remote_attestation/proto/v1/service_streaming.proto#L26-L31

1) This name is outdated and it will conflict with our DICE Attestation implementation (https://github.com/project-oak/oak/issues/4074), so we need to rename all `GetPublicKey` methods to `GetEndorsedEvidence` (and also update corresponding service argument and variable names). This changes will need to be done both on Github and internally.

2) The evidence that is returned to the client is currently called `AttestationBundle`:
https://github.com/project-oak/oak/blob/c8587e96af6b02e7bae4b248ae3a268ddafec6c2/oak_remote_attestation/proto/v1/messages.proto#L46-L54

This name also conflicts with [RATS](https://datatracker.ietf.org/doc/html/rfc9334) terminology and it should be renamed to `EndorsedEvidence`

**Note**: We already have an `EndorsedEvidence` in a separate package:
https://github.com/project-oak/oak/blob/c8587e96af6b02e7bae4b248ae3a268ddafec6c2/proto/attestation/endorsement.proto#L59-L67

And this proto will be used in the future once DICE Attestation is implemented, but it's not done yet. So for now we just need to rename existing `AttestationBundle` to `EndorsedEvidence` to prepare the codebase for the proto change.

**Comment by flooxo** [comment]
Hey, maybe someone can take a quick look at my PR and give me some feedback/run the tests :)

**Comment by ipetr0v** [comment]
> Hey, maybe someone can take a quick look at my PR for this issue and give me some feedback/run the tests :)

I think there are only 2 tests failing:
1) One is formatting error, could just be fixed by running `./scripts/xtask format` (inside the [`nix`](https://github.com/project-oak/oak/blob/main/docs/development.md) environment)
2) Potentially uninitialized Java variable
```
║ java/src/test/java/com/google/oak/client/OakClientTest.java:64: error: variable EndorsedEvidence might not have been initialized
║       EndorsedEvidence EndorsedEvidence = EndorsedEvidence.newBuilder()
║                                           ^
```
[Link](https://github.com/project-oak/oak/actions/runs/6676665355/job/18158316540?pr=4426)

**Comment by ipetr0v** [comment]
Changing the label to "breaking-change", since this issue should be done in multiple steps to avoid breaking internal tests
