### ISSUE TITLE
Extract and de-dupe DICE encoding/decoding logic 

### ISSUE THREAD

**Issue by jul-sh** [project-oak/oak#4485]
stage0, restricted kernel, stage1, the orchestrator each include logic for decoding and encoding dice data. We dedupe this logic by moving it into the oak_dice crate. While we're at it, it would also be nice to have more descriptive error messages in case of a panic, as pointed out it https://github.com/project-oak/oak/pull/4481#discussion_r1396266785.

**Comment by conradgrobler** [comment]
One challenge with fully deduplicating this is that stage1 and the orchestrator include protos in the DICE representation and stage0 and the restricted kernel doesn't. `oak_dice` should be kept free of proto dependencies.
