### ISSUE TITLE
Make GitHub workflows reliable and predictable

### ISSUE THREAD

**Issue by thmsbinder** [project-oak/oak#4534]
This issue is a collection of a number of bugs and shortcomings. It is not possible to fully identify reasons/symptoms at this point, but this issue calls for a (1) smooth successful operation of all GitHub workflows and (2) equivalence of the pre- and post-merge checks. So, if the pre-merge checks pass the post-merge checks should not complain about things that could have been flagged in the first place.

Symptoms currently observed include:

- builder times out (https://github.com/project-oak/oak/actions/runs/7105965206/job/19359926362)
- Flaky unit test, e.g. `key_value_lookup tests::test_server` fails intermittently ([sponge](https://fusion2.corp.google.com/invocations/2c036cfc-16dd-4ab2-988e-58dfbf1d8053/targets/oak%2Fpresubmit_run_tests;config=default/log), [src](https://github.com/project-oak/oak/blob/c4faa1cc9be016dcc2491597c5f4d7a47d48850b/oak_functions_launcher/tests/integration_test.rs#L29C10-L29C10))
- Unclarity about run-cargo-clippy bringing in crates with rejected licenses, but the rejection only happens postmerge (https://github.com/project-oak/oak/actions/runs/7113465489/job/19365472089)

Previous related issues:

- Ref #4123

**Comment by tiziano88** [comment]
regarding the cargo deny (not clippy, was that a mistake?), here is a comparison of success and failure:

- [successful pre-merge](https://github.com/project-oak/oak/actions/runs/7102167011/job/19331903801?pr=4529#step:5:2686)
- [failed post-merge](https://github.com/project-oak/oak/actions/runs/7113465489/job/19365472089#step:5:2897)

**Comment by tiziano88** [comment]
So I suspect this is just because a crate was yanked from crates.io in between the pre-merge and post-merge runs (and now keeps failing -- fix in #4535, but I cannot mark that as fixing this issue as there is more here).

Specifically, the zerocopy crate: https://crates.io/crates/zerocopy/versions

**Comment by thmsbinder** [comment]
Related to timeouts:

https://github.com/actions/runner/issues/1326
