### ISSUE TITLE
Unify `oak_abi` and `oak::wasm` Rust crates

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#454]
- https://github.com/project-oak/oak/tree/master/oak/server/rust/oak_abi
- https://github.com/project-oak/oak/blob/master/sdk/rust/oak/src/wasm/mod.rs

It seems to me they both define ABI-level types, and they are basically always going to be used together.

@daviddrysdale @blaxill is my understanding correct?

**Comment by blaxill** [comment]
Yes I think you are correct.

**Comment by blaxill** [comment]
@daviddrysdale In that case perhaps `oak_abi` should be at `oak/oak_abi` or `oak/rust/oak_abi` instead of `oak/server/rust/oak_abi`?

**Comment by daviddrysdale** [comment]
@tiziano88, yeah moving chunks of `oak::wasm` into `oak_abi` was next on my list (but it looks like @blaxill has gotten there first).

@blaxill that move probably makes sense, but I don't think it's worth rushing to do &ndash; if/when we move to Rust-everywhere there will probably be all sorts of directory shuffles that could encompass this move too.
