### ISSUE TITLE
Targets in the `proto` directory do not build

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#4540]
Currently we are not running `bazel build` and `bazel test` in xtask for the new [`proto`](https://github.com/project-oak/oak/tree/main/proto) directory.
https://github.com/project-oak/oak/blob/39341c7819938460c0d82a72ce83ccb0c93c5a16/xtask/src/main.rs#L688-L689
https://github.com/project-oak/oak/blob/39341c7819938460c0d82a72ce83ccb0c93c5a16/xtask/src/main.rs#L695-L696

**Comment by ipetr0v** [comment]
Keep in mind that because of this, some of our build targets do not compile anymore. For example this one:
https://github.com/project-oak/oak/blob/39341c7819938460c0d82a72ce83ccb0c93c5a16/proto/micro_rpc/BUILD#L36-L39
```
ERROR: /usr/local/google/home/ivanpetrov/src/oak/proto/micro_rpc/BUILD:26:14: in @_builtins//:common/java/proto/java_lite_proto_library.bzl%java_lite_proto_aspect aspect on proto_library rule //proto/micro_rpc:messages_proto: 
Traceback (most recent call last):
	File "/virtual_builtins_bzl/common/java/proto/java_lite_proto_library.bzl", line 59, column 46, in _aspect_impl
	File "/virtual_builtins_bzl/common/java/proto/java_proto_library.bzl", line 117, column 40, in java_compile_for_protos
Error: @_builtins//:common/java/proto/java_lite_proto_library.bzl%java_lite_proto_aspect aspect on proto_library has to declare 'proto' as a required fragment in target configuration in order to access it. Please update the 'fragments' argument of the rule definition (for example: fragments = ["proto"])
ERROR: Analysis of target '//proto/micro_rpc:messages_proto' failed
```
Though I'm not sure why we need a Java ProtoLite rule for Micro RPC

**Comment by tiziano88** [comment]
the java proto is used by Oak Functions to return a status (error or success)

it does not use micro RPC transport, just the status proto: https://github.com/project-oak/oak/blob/39341c7819938460c0d82a72ce83ccb0c93c5a16/proto/micro_rpc/messages.proto#L35-L45
