### ISSUE TITLE
`Error: Process completed with exit code 139` on GitHub Actions

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#4541]
Github CI is currently flaky and may sometimes fail with the following error:
```
Error: Process completed with exit code 139.
```

Failures:

- https://github.com/project-oak/oak/actions/runs/7127064350/job/19406199175?pr=4539
- https://github.com/project-oak/oak/actions/runs/7127195821/job/19406620080?pr=4536
- https://github.com/project-oak/oak/actions/runs/7129709962/job/19414398976?pr=4536

**Comment by tiziano88** [comment]
The title `Github CI is flaky` is not very descriptive (imagine seeing this issue listed somewhere, where the title is expanded, for instance as part of #4534 -- it would not be very helpful to just see `Github CI is flaky` in a list).

For instance, here is what it looks like when added to a list:

- #4541
