### ISSUE TITLE
Error building tensorflow example locally

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#476]
Not sure why, but this started failing for me locally when running the following command in the latest Docker image:

```
./scripts/docker_run ./scripts/build_examples
```

logs:

```log
+ bazel build --config=emscripten //examples/tensorflow/module/cpp:all
INFO: Writing tracer profile to '/.cache/bazel/_bazel_tzn/b6bc0828d5b43c7085b650e0698bf388/command.profile.gz'
INFO: Analyzed target //examples/tensorflow/module/cpp:tensorflow.wasm (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /.cache/bazel/_bazel_tzn/b6bc0828d5b43c7085b650e0698bf388/external/org_tensorflow/tensorflow/lite/c/BUILD:6:1: C++ compilation of rule '@org_tensorflow//tensorflow/lite/c:c_api_internal' failed (Exit 1)
Traceback (most recent call last):
  File "/usr/local/emsdk/upstream/emscripten/emcc.py", line 41, in <module>
    import emscripten
  File "/usr/local/emsdk/upstream/emscripten/emscripten.py", line 24, in <module>
    from tools import shared
  File "/usr/local/emsdk/upstream/emscripten/tools/shared.py", line 300, in <module>
    generate_config(EM_CONFIG, first_time=True)
  File "/usr/local/emsdk/upstream/emscripten/tools/shared.py", line 226, in generate_config
    open(abspath, 'w').write(config_file)
IOError: [Errno 2] No such file or directory: '/.cache/bazel/_bazel_tzn/b6bc0828d5b43c7085b650e0698bf388/execroot/oak/~/.emscripten'
Target //examples/tensorflow/module/cpp:tensorflow.wasm failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.933s, Critical Path: 0.28s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

**Comment by ipetr0v** [comment]
If I understand correctly, Emscripten creates a `.emscripten` config file in the `$HOME` directory.
If docker run as `root` (as in GCB) then this file is created in `/root` directory and is accessible.
But if docker is run not as `root`, then `/` directory is treated as `$HOME`, but the process doesn't have permissions to access this file.

And even if we will set correct permissions on the `.emscripten` file, then it will also fail, since it will try to create `.emscripten_cache.lock` in the same inaccessible directory.

**Comment by ipetr0v** [comment]
The obvious solution is to create a special directory for this file:
```shell
mkdir -p config
chmod ugo+rwx config
export EM_CONFIG=/config/.emscripten
```
But I'm not sure, if it's an ok solution.

Also, when it doesn't have access to an `EM_CONFIG` directory, it tries to create it inside Bazel `$(bazel info execution_root)/~/.emscripten` and fails.

**Comment by ipetr0v** [comment]
This is a common problem, when building Docker image with Emscripten:
https://github.com/trzecieu/emscripten-docker/blob/c623888b50286667e8a29dd6c04f8eb2e1ae4dca/docker/trzeci/emscripten-upstream/Dockerfile#L79-L81

Will set `$HOME` to `/tmp` in Docker

**Comment by ipetr0v** [comment]
Instead of using `$HOME` variable, emscripten uses Python's `expanduser`:
https://github.com/emscripten-core/emscripten/blob/eecf6f5a465f4fd213c14e5087288981af70b69b/tools/shared.py#L224-L226
