### ISSUE TITLE
Implement policies for chat application example

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#488]
I suggest the following architecture for the chat Oak Application:

- a gRPC entry node
- a "router" WebAssembly node, whose job is, for each incoming gRPC message, to inspect its associated label, create a new "room" node for each unique label, and hold a reference to the write end of a channel to the room node in a map; this is somewhat similar to what the current "frontend" node does:
  https://github.com/project-oak/oak/blob/6a2aa7315628a668ff3a091aa7f4b67e2f73f6c2/examples/chat/module_0/rust/src/lib.rs#L34-L37
  Except that the concept of "room id" would disappear, since a room would be uniquely identified by its label (assuming one room per label for now, i.e. the same set of participants may not have more than room).
  Note the router node does not implement the gRPC service interface, it merely inspects labels (which are public) and routes opaque messages to downstream nodes, therefore not getting tainted with any label itself. This may require some changes to the way the gRPC node forward requests, perhaps by introducing a new "read" channel alongside each message (which will also be useful for client streaming).
- the "room" node keeps any state relative to the current room, and participants who want to send a message to the same group of users (identified by the policy) would be routed to the same node

**Comment by tiziano88** [comment]
@rbehjati FYI I think this is the canonical issue for labels in the chat application, could you look into it once we have a C++ client that can perform challenge-response auth, or some other mechanism?

I am guessing this flag would be replaced with a pointer to the private key to use for auth (either the key itself, or a file name containing the key):

https://github.com/project-oak/oak/blob/4e2c742c3557d71bcf9b8e1fdb986d720ec8873f/examples/chat/client/cpp/chat.cc#L32-L33

And then the actual crypto would be done by `oak_sign`, either as a library or as a stand-alone binary that is invoked by the client.

WDYT?

**Comment by tiziano88** [comment]
Ah I guess this is tracked by https://github.com/project-oak/oak/issues/1851 , closing in favour of that.

**Comment by rbehjati** [comment]
Sorry, I had not yet got the chance to look into the details of the `chat` example, and I was a bit intimidated by the term "policy" here! But I think what you suggested is essentially what needs to be done. I'll fix it as part of #1851 :)
