### ISSUE TITLE
Add clang-format check to CI

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#49]

**Comment by hansman** [comment]
Hi @tiziano88! I am very interested in your project and am looking for a first issue to get engaged right now. Is this still a valid one? The clang-format is checked in [scripts/check_formatting#L10 ](https://github.com/project-oak/oak/blob/master/scripts/check_formatting#L10) and triggered in [.travis.yml](https://github.com/project-oak/oak/blob/master/.travis.yml#L7) for CI.

**Comment by tiziano88** [comment]
Thanks @hansman , you are right, this was already implemented:
https://github.com/project-oak/oak/blob/c0388891913f3af156f16f9c814b92cb396e75a8/scripts/check_formatting#L10-L21
Would you like to take a look at some other issue perhaps? #68 may be a good one to start with. Let me know by replying there and I'll assign to you. Thanks in advance for offering!

**Comment by hansman** [comment]
Yes, I am happy to get going with #68 and uploaded a PR for it, https://github.com/project-oak/oak/pull/105. Excited to get started!
