### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by dmercer-google** [project-oak/oak#5046]
The link to the Noise Explorer [here](https://github.com/project-oak/oak/tree/be2f0577ec833c54558e503147297caa488f0b39/oak_crypto/src/noise_handshake#:~:text=%5BNoise%20explorer%5D(https%3A//noiseexplorer.com/patterns/NK/%5D) is broken.  It looks like you need to replace the trailing ```]``` with ```)```

![BrokenLink](https://github.com/user-attachments/assets/338ca65e-7d9b-46df-a713-2e23618e3abc)

**Comment by conradgrobler** [comment]
Thanks for pointing this out.

**Comment by conradgrobler** [comment]
Fixed in https://github.com/project-oak/oak/commit/b7f7d812f18e6350d23e1407ecbe3894a5676ea3
