### ISSUE TITLE
Create per-connection channels from gRPC pseudo-node

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#507]
This should help with both #97 and #488 . Even if we support only unary client calls from gRPC, having a dedicated handle for each incoming gRPC connection will allow us to associate more granular labels to it, as opposed to the current model, in which there is a single channel between the gRPC pseudo-node and the "main" node, over which messages from every incoming gRPC connection are multiplexed.

I'd imagine this boils down to the gRPC pseudo-node keeping its single channel to the "main" node, but sending messages through it which encapsulate a pair of channels connecting from and to the gRPC client.

In case it helps, in my current Rust prototype for the chat app this looks something like:

```rust
pub struct GrpcConnection {
    request_receiver: oak::io::Receiver<oak::proto::grpc_encap::GrpcRequest>,
    response_sender: oak::io::Sender<oak::proto::grpc_encap::GrpcResponse>,
}
```

which gets (manually) encoded / decoded as a pair of handles (and no bytes).

**Comment by daviddrysdale** [comment]
Note that this would also be needed for support of client-side streaming (#97)
