### ISSUE TITLE
Unify error handling

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#51]
We currently use a combination of the following approaches for error handling:
- return `::grpc::Status`
- return `::asylo::StatusOr`
- log errors (at inconsistent levels) and discard them

For gRPC methods it makes sense to keep returning `::grpc::Status`, but for general methods that may fail we should probably converge on something like `StatusOr`; unfortunately this is not available in absl yet, but I think we could piggyback on the asylo implementation for now, and switch to the absl version once it becomes available.

@michael-kernel-sanders WDYT?

**Comment by expectocode** [comment]
StatusOr is now available in absl: https://abseil.io/blog/2020-091021-status

**Comment by daviddrysdale** [comment]
Thanks, that's good to know!

(However, there's not much C++ code left that uses `StatusOr`, since we moved the Runtime from C++ to Rust &ndash; just `oak/common/hmac.h` I think. But we could get maybe get rid of `third_party/asylo/statusor.h` and use `absl::StatusOr` there instead.)
