### ISSUE TITLE
Migrate off deprecated Asylo AesGcmSivCryptor

### ISSUE THREAD

**Issue by daviddrysdale** [project-oak/oak#517]
After the [Asylo version upgrade](https://github.com/project-oak/oak/pull/511) we get:

```log
2020-01-23 11:31:28  INFO  oak_runtime.cc : 119 : Create storage proxy node named {storage-0-oak_main} connecting to 127.0.0.1:7867
2020-01-23 11:31:28  ERROR  aes_gcm_siv.h : 89 : The AesGcmSivCryptor is deprecated and will be removed. Please migrate to AeadCryptor instead.
```
from https://github.com/google/asylo/commit/df55fa14cf39e3997adbeb93227095c293874203

**Comment by tiziano88** [comment]
@rbehjati could you check if this is still current, and either fix it or close this issue? Thanks!

**Comment by daviddrysdale** [comment]
This looks to be more significant than just a change to use a different entrypoint; the replacement `asylo::AeadCryptor` class doesn't appear to allow a user-specified nonce-generator, which means that the current approach of using `oak::FixedNonceGenerator` (which generates a deterministic nonce from the key) when encrypting storage names won't work any more.

That might be a good thing; [AES GCM SIV](https://en.wikipedia.org/wiki/AES-GCM-SIV) is nonce-misuse resistant, but is apparently [not infinitely so](https://www.imperialviolet.org/2017/05/14/aesgcmsiv.html):

> &hellip;that name appears to have caused some people to believe that they are infinitely resistant. I.e. that an unlimited number of messages can be encrypted with a fixed nonce with no loss in security. That is not the case &hellip;

(However, IANAC.)

**Comment by daviddrysdale** [comment]
Done in #720
