### ISSUE TITLE
OSS-fuzz "Coverage build failure"

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#539]
We keep getting frequent email messages about coverage build failure for Oak in OSS-fuzz: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=18366

We should sort out whatever coverage information needs to be set up, or disable such notifications.

refs:

- our project: https://github.com/google/oss-fuzz/blob/master/projects/oak/project.yaml
- gRPC project: https://github.com/google/oss-fuzz/tree/master/projects/grpc
- envoy project: https://github.com/google/oss-fuzz/tree/master/projects/envoy

**Comment by tiziano88** [comment]
@rbehjati could you start looking into this when you have some time? I suspect the change (if any) would need to be done on the oss-fuzz project itself, rather than in our repository, but I may be wrong.

**Comment by rbehjati** [comment]
@tiziano88 Sure! I'll start working on it next week.

**Comment by tiziano88** [comment]
@rbehjati since there is nothing to fuzz now, should we disable this? Or can we set it up so that it fuzzes some Rust target instead?

cc @daviddrysdale

**Comment by rbehjati** [comment]
I'd say eventually we'd want to fuzz for Rust. But I have not looked into it at all. Do we have an issue for fuzzing for Rust?

**Comment by tiziano88** [comment]
@rbehjati I don't think we have one, could you create it?

**Comment by rbehjati** [comment]
I have created #893. I'll close this one.

**Comment by tiziano88** [comment]
We keep getting those fuzzing failure email messages, so I think we should keep this issue open until that is fixed (either disabling the notifications, or fixing the fuzzing target so that it works for Rust #893).

**Comment by tiziano88** [comment]
Possibly related to #1163.

In any case, I still think there is no value in the current state of the integration, and we keep getting error notifications.

@rbehjati could you look into disabling our project on oss-fuzz for the time being? Ideally we should leave the project definition there, so that we can reuse it if / when we integrate with Rust, but just stop fuzzing for now (since it's probably also wasting Google's compute power for no good reason).

**Comment by rbehjati** [comment]
I have created this PR: https://github.com/google/oss-fuzz/pull/4053

Since the `'oak/server:wasm_node_fuzz'` target [does not exist any more](https://github.com/project-oak/oak/commit/e915929b0e17a519c81529e39e861483650ec524#diff-02bbe288c989b6781e584b3cf8b2004f), I have also removed `'oak/server:wasm_node_fuzz'` from the `FUZZER_TARGETS` (making it an empty list):
https://github.com/google/oss-fuzz/blob/26af5e0e257b02e7f3a760b8288181928e0b41a9/projects/oak/build.sh#L46

**Comment by rbehjati** [comment]
We now have fuzzing for Rust.
