### ISSUE TITLE
Move grpc_request to oak_runtime

### ISSUE THREAD

**Issue by blaxill** [project-oak/oak#543]
See:

https://github.com/project-oak/oak/blob/9bcde5e90be5e23657f839fa77c6525ee90319f7/sdk/rust/oak_tests/src/lib.rs#L91-L97

~~This requires some proto dependency shuffling as the modules are in sdk/oak and it would be better not to add a dependency of sdk/oak to oak_runtime.~~

~~See  https://github.com/project-oak/oak/pull/472/files/33f0554b884f04111fc807b7f16f2fc21f6f5726#r371958877~~

~~Blocked by #472~~

**Comment by blaxill** [comment]
Closing as sdk/oak is no longer a dependency of oak_runtime

**Comment by daviddrysdale** [comment]
Could you amend the [`TODO`](https://github.com/project-oak/oak/blob/master/sdk/rust/oak_tests/src/lib.rs#L91) if it's TODOne please?

**Comment by blaxill** [comment]
Thanks, I misread this issue as GitHub has eaten the comment, the inline TODO is more informative.

**Comment by ipetr0v** [comment]
Was this issue closed by https://github.com/project-oak/oak/pull/1156 ?

**Comment by daviddrysdale** [comment]
Yep, gone in 1c8039f035867224bfeaec4ec62be508aef0b0c6
