### ISSUE TITLE
Investigate making rust-protobuf `no_std` compatible 

### ISSUE THREAD

**Issue by blaxill** [project-oak/oak#550]
It should be possible to make rust-protobuf `no_std` compatible. There are different approaches we could take either:

- Use `no-std-compat` or similar to compile rust-protobuf to `no_std`. This would potentially be the least amount of work, but likely would require vendoring rust-protobuf under `third_party/` and re-adding the `std::prelude` import to all the files (as `no_std` removes the implicit prelude import)
- Edit all files to use alloc / core and fix any remaining issues manually. Hopefully as automated as possible.

If it is not viable to move rust-protobuf to `no_std`, then we may be required to move to a different library such as `prost`.

**Comment by daviddrysdale** [comment]
We moved to Prost everywhere in #829, and away from Asylo in #709 &ndash; is this still relevant?
