### ISSUE TITLE
Rename `${NAME}Node` to `${NAME}Server` in gRPC generated code

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#556]
For instance:

https://github.com/project-oak/oak/blob/f3eb28bba3c78167ee6300f41aa03ad86320c0b4/examples/hello_world/module/rust/src/proto/hello_world_grpc.rs#L26-L32

should be renamed from `HelloWorldNode` to `HelloWorldServer`.

This will allow us to later also generate bindings for gRPC client nodes.

The code generation happens here:

https://github.com/project-oak/oak/blob/f3eb28bba3c78167ee6300f41aa03ad86320c0b4/third_party/grpc-rust/grpc-compiler/src/codegen.rs#L194-L197

**Comment by daviddrysdale** [comment]
Might be best to use ${NAME}Service rather than Server; I think the trait can then be re-used for #549.

**Comment by tiziano88** [comment]
That would be nice, but I am not convinced that the same exact trait may be used for both, since server and client interfaces usually require different contexts, and also streaming methods would probably look quite different for client vs server.

Re: server vs service, there seems to be inconsistency in gRPC official documentation too:

- Go: "server" https://grpc.io/docs/tutorials/basic/go/
- C++: "service" https://grpc.io/docs/tutorials/basic/cpp/
- Java: "service" https://grpc.io/docs/tutorials/basic/java/

But also some of them don't actually qualify the trait / interface name, only the concrete instance, so perhaps it's simpler to just use `${NAME}` for the server and `${NAME}Client` for #549.

**Comment by daviddrysdale** [comment]
Yeah, you're right &ndash; I was just thinking about non-streaming methods, any streaming methods wouldn't be able to share signature between client & server.
