### ISSUE TITLE
Implement ECDSA / EdDSA authentication and labelling system

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#565]
To replace the current bearer token mechanism.

A possible implementation would be to extend the `GrpcTag` message with a `ecdsa_public_key` field, which clients may use to label data with the literal public key of the intended recipient(s).

https://github.com/project-oak/oak/blob/1528e03883bf23e727f858e1342f335ddf041b06/oak/proto/policy.proto#L44-L57

On the other side, the gRPC pseudo-node would authenticate users by requiring a proof of possession of the corresponding private key, in order to be able to declassify data labelled with a public key.

Note that the private key never leaves the client device, and in fact it may be desirable to perform the signature scheme in hardware (via a TPM or secure element) as much as possible, for production use cases.

Note that we already have a dependency on `boringssl`, so we can leverage that for any crypto-related operations.

Also note that Asylo may support a native way of authenticating users based on PKI at some point, but it's unclear how / when.

For the time being, we may rely on a non-interactive proof of possession of the private key, for instance by having the client sign a server-provided challenge, or, failing that, a fixed value concatenated with a timestamp.

See https://keybase.io/docs/api/1.0/call/login for a vaguely related auth scheme, though it is only for inspiration, I am not suggesting we would be able to depend on it or share any code with it.

**Comment by tiziano88** [comment]
@rbehjati I think this is just a dup / slightly different version (perhaps explained in a slightly more general way) of what you are already working on, could you dedup against the current one, and see if there is anything interesting in addition to what we already have elsewhere? Thanks

**Comment by rbehjati** [comment]
I am closing this, since the challenge-response based authentication (#1357) which is currently under implementation, replaces the bearer token and provides more or less the same functionality described here.
