### ISSUE TITLE
Unify generated gRPC traits with `oak::grpc::OakNode`

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#577]
This is the code generated by the gRPC compiler:

https://github.com/project-oak/oak/blob/5d0a6a5a894595121d60f945e3b3c58f812039f4/examples/chat/module/rust/src/proto/chat_grpc.rs#L26-L45

It includes a server trait that the target node needs to implement, and a `dispatch` method that parses an incoming request and dispatches that to the correct method on an object that implement the server trait.

In practice though, we need gRPC server nodes to implement the `oak::grpc::OakNode` trait:

https://github.com/project-oak/oak/blob/5d0a6a5a894595121d60f945e3b3c58f812039f4/sdk/rust/oak/src/grpc/mod.rs#L119-L140

But currently we do this manually by manually providing an adaptor implementation that simply calls the appropriate `dispatch` generated method:

https://github.com/project-oak/oak/blob/5d0a6a5a894595121d60f945e3b3c58f812039f4/examples/chat/module/rust/src/lib.rs#L63-L65

It would be nice if we could express that the `oak::grpc::OakNode` trait is automatically implemented by any object that implements the generated server trait.

**Comment by wildarch** [comment]
I was trying to make this nicer by have an automated trait impl for `OakNode`, but unfortunately the orphan rule forbids impls of the type `impl<T: ChatNode> OakNode for T`, the type system does not allow you to implement a trait for all types that some other trait. I think that option is off the table, but there are a few other things we could do.

I think the best way to solve this would be to rethink how we use `OakNode` and the bootstrapping of nodes (with `OakExport`). Maybe we could allow the user to supply a function that returns some `OakNode` instead? e.g.

```rust
#[oak_init]
fn init() -> impl OakNode {
  ...
}
```

Then I think we can also drop `OakNode::new` and make the trait define just `invoke`. To make it easier to work with these gRPC generated types we could introduce a convenient type `GrpcDispatcher` so you could write something like:

```rust
#[oak_init]
fn init() -> impl OakNode {
    let node = Node::new();
    GrpcDispatcher::new(node, dispatch)
}
```

As an alternative, we can keep the current macro `OakExport` and just have that assume that there exists a function named `dispatch` on the type it is derived for, but that might be a bit brittle.
