### ISSUE TITLE
It is not possible to use `derive(OakExports)` on more than one struct in the same crate

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#591]
Because the effect of `derive(OakExports)` is to generate a public, global `oak_main` function, it means that at most one struct in the same crate is able to rely on it. Since we now support multiple nodes (and corresponding entry points) in the same Rust crate, we should find a better way of handling this.

Potential approaches:

1. let the `OakExports` macro generate an entry point named based on the name of the struct to which it is attached:

    ```rust
    #[derive(OakExports)]
    struct Router { ... }
    ```
    
    would generate an entrypoint called `router` (or some variation); perhaps we could also have an additional inert attribute that can be additionally attached to the struct to specify a different name:

    ```rust
    #[derive(OakExports)]
    #[oak_entrypoint = "router"]
    struct Router { ... }
    ```

    Note that in this case, `oak_entry_point` would not do anything, apart from being used by `OakExports` to determine the entry point name.

1. remove the `OakExports` derive macro, and add a [macro by example](https://doc.rust-lang.org/reference/macros-by-example.html) (which is much simpler to implement than a procedural macro, and does not require being defined in its own crate) to map a single entry point name to a Node:

    ```rust
    oak_entrypoint!("router" => Router);
    ```

1. (similar to the previous one, but supporting multiple entrypoints at once): remove the `OakExports` derive macro, and add a new [macro by example](https://doc.rust-lang.org/reference/macros-by-example.html) to map multiple entry point names to structs implementing the `Node` trait, and generates all the appropriate exported functions; e.g.

    ```rust
    oak_entrypoints!{
      "router" => Router,
      "room" => Room,
    }
    ```

    This has the advantage of being able to generate additional data structures, e.g. a hash table from entrypoint names to structs, to be used in tests to emulate node creation by name; the downside is that it should be invoked only once, ideally at the crate root, but that is probably a good practice anyways, as opposed to having entrypoints spread out around different mods

1. remove the `OakExports` derive macro, and add a new [attribute macro](https://doc.rust-lang.org/reference/procedural-macros.html#attribute-macros) to add on individual nodes, parametrized with the name of the exported function:

    ```rust
    #[oak_entry_point = "router"]
    struct Router { ... }
    ```

1. do not use macros at all, and just rely on the exported functions being manually defined, and provide a little more logic in the form of a regular function to handle things like panics and logs, which are currently generated by the `OakExports` macro:

    ```rust
    pub extern "C" fn router(in_handle: u64) {
      oak::run_event_loop(Router::default(), in_handle);
    }
    ```

    in which `run_event_loop` would be modified to include the `std::panic::catch_unwind` handling which is currently generated by `OakExports`:

    https://github.com/project-oak/oak/blob/d7d8dbdda09f68ddd07a82075cb7458fc466cd45/sdk/rust/oak_derive/src/lib.rs#L60-L71

**Comment by tiziano88** [comment]
cc @wildarch

**Comment by tiziano88** [comment]
perhaps options 2 or 3 above can be combined with the suggestion in https://github.com/project-oak/oak/issues/577#issuecomment-584262049 : a macro for defining a mapping from a single entry point to an expression that evaluates to the node instance to use, which would allow wrapping a node in an adaptor trait so that it satisfies the correct interface:

```rust
#[derive(Default)]
struct Node { ... }

impl HelloWorldService for Node { ... }

oak::entrypoint!("hello" => oak::grpc::Dispatcher(Node::default()))
```

**Comment by tiziano88** [comment]
passing thought: maybe there is also a way of avoiding the double construction of `Dispatcher` and `Node`, by forwarding one to the other, and just exposing an API similar to `oak::grpc::Dispatcher::<Node>::new(dispatch)`

**Comment by wildarch** [comment]
In my mind the most ergonomic and clear way to implement this is to take option 3 and make the mapping to an expression. In the main `lib.rs` of your crate you would then write something like:
```rust
fn complex_node() -> ComplexNode {
    // Complicated setup
   ....
}

oak::entrypoints!(
    "hello" => oak::grpc::Dispatcher::new(HelloServiceImpl::default(), dispatch)),
    "thing" => complex_node(),
)
```

This would desugar to two `#[no_mangle] extern "C"` functions just like `OakExports`.

As @tiziano88 points out this is a much simpler macro to implement than the `OakExports` we have now.

This design does actually allow people to place this macro anywhere they want in their crate, and they could also use the macro multiple times in one crate. That should probably be considered bad practice, but not necessarily something we want the compiler to catch. Because of macro hygiene we don't really have a way to enforce this, unless we opt for a procedural macro with the same API.

**Comment by wildarch** [comment]
> passing thought: maybe there is also a way of avoiding the double construction of `Dispatcher` and `Node`, by forwarding one to the other, and just exposing an API similar to `oak::grpc::Dispatcher::<Node>::new(dispatch)`

That would require the dispatcher to know how to instantiate new `Node`s. If in practice all `OakNode` types implement `Default` that would not necessarily be an issue though.

**Comment by tiziano88** [comment]
the difference between options 2 and 3 above is just whether the macro defines a single entrypoint, or multiple ones. Since as @wildarch says there is no way of enforcing that it cannot be invoked more than once anyways, and since we don't have a use case for generating anything else with this information apart from the entry point fns, I think we should go with option 2, and let developers call it more than once if necessary. Also make it so that the RHS is an expression, which may be inlined or a function call, as @wildarch suggested.

The final version would look something like

```rust
fn complex_node() -> ComplexNode {
    // Complicated setup
   ....
}

oak::entrypoint!("hello" => oak::grpc::Dispatcher::new(HelloServiceImpl::default(), dispatch)))
oak::entrypoint!("thing" => complex_node())
```

We can always easily implement the multi-entrypoint macro later if needed, but for now it seems it would avoid extra complexity, especially as we experiment with these macro constructs.
