### ISSUE TITLE
oak::io::Receiver is tightly bound to directly read from a channel

### ISSUE THREAD

**Issue by daviddrysdale** [project-oak/oak#592]
The current `oak::io::Receiver<T>` is a `struct` that wraps a particular `ReadHandle`.  This means it is not possible for any kind of transformation to be applied to the values received down the channel: if the `Receiver` emits type `T` then the channel must carry Encoded values of type `T`.

Sometimes it would be helpful to have a `Receiver<T>` where the underlying channel carries Encoded values of a different type `S`.  (For example, `S` might be the `GrpcResponse` wrapper type, but in a situation where the wrapped type is always a specific protocol buffer message `T`).

**Comment by tiziano88** [comment]
Perhaps a starting point would be for `Receiver` to support a couple additional methods:

- `Receiver::<T>::receive_future() -> Future<T>`
  + see https://docs.rs/futures/0.3.4/futures/prelude/trait.Future.html
- `Receiver::<T>::receive_stream() -> Stream<T>`
  + see https://docs.rs/futures/0.3.4/futures/stream/trait.Stream.html

Then we can use standard combinators on those traits to additionally transform the resulting values.

Quite related to #186.

/cc @wildarch
