### ISSUE TITLE
Collect garbage when generating Wasm files

### ISSUE THREAD

**Issue by blaxill** [project-oak/oak#601]
It appears calling `cargo build` with a custom target directory is generating a lot of [garbage](https://github.com/project-oak/oak/pull/533#issuecomment-585276160). Either collect the garbage or use the default directory and parse the location from cargo.

**Comment by tiziano88** [comment]
If the goal of #578 was to make it easier to determine the location of the artifacts, and make sure they are up-to-date, I think it could be achieved without having to rebuild everything and using a separate temp folder. For instance, it may rebuild things in-place (if necessary), and then have some logic to figure out the current target directory. Would this help?

**Comment by blaxill** [comment]
Rebuilding in place is fine, the default target path depends on the location of the workspace. We could

- Use `out-dir` instead of `target-dir` to a temp dir, then clean up after the test (this should reuse intermediate build artefacts)
- Parse the cargo json blob to get the default target directory for the current workspace.
