### ISSUE TITLE
gRPC error propagation broken

### ISSUE THREAD

**Issue by daviddrysdale** [project-oak/oak#632]
Commit 31a4bd2c19e4c (#165) added a deliberate `INVALID_ARGUMENT(3)` error to the `hello_world` example, to check that gRPC errors from the server got propagated to the client.

However, that change didn't add a check that the expected error code was returned, and the error code displayed by the client is now `UNIMPLEMENTED (12)`.

Manually bisecting through log statements in old Travis runs, it looks like:
 - [Job 621](https://travis-ci.org/project-oak/oak/jobs/578743286?utm_medium=notification&utm_source=github_status) on ae3b8d63dc31431b9d34e1ebf085e92204aa616c had the correct error
 - [Job 622](https://travis-ci.org/project-oak/oak/jobs/578747314?utm_medium=notification&utm_source=github_status) on https://github.com/project-oak/oak/commit/92add062f9550ea5712deb3b5883e7a4e185c33b had the wrong error.

So it looks like #189 affected gRPC error propagation in some way.

As well as fixing the error path, we should also change the example to abort on an unexpected error.

**Comment by tiziano88** [comment]
Thanks for looking into this and figuring out what went wrong there @daviddrysdale .

@ipetr0v FYI since I think you mentioned running into this (or a similar) issue earlier today?
