### ISSUE TITLE
Make oak_abi no_std compatible 

### ISSUE THREAD

**Issue by blaxill** [project-oak/oak#638]
Currently `oak/server/rust/oak_abi` requires `std` as the generated protobuf files use `std`. The rust runtime is intended to be `no_std` compatible and so needs `oak_abi` to also be `no_std` compatible. The options available in approximate order of effort to benefit:

- Patch the generated generated protobuf files
- Patch the upstream protobuf generator to be `no_std` compatible 
- Replace the protobuf files with manual instantiations (at the cost of losing auto-synchronisation for oak abi definitions)

**Comment by tiziano88** [comment]
Another alternative would be to instead define those constants in a `.h` file, and use [rust-bindgen](https://github.com/rust-lang/rust-bindgen) to generate Rust bindings for them (they would look like separate consts rather than actual enums though, which is not great).

**Comment by daviddrysdale** [comment]
No longer relevant &ndash; we're not targetting a no_std build of Rust code any more.
