### ISSUE TITLE
Run clang-tidy as part of CI

### ISSUE THREAD

**Issue by aalmos** [project-oak/oak#64]
I found an other GitHub project who were able to get clang-tidy work with Bazel and run it in the CI pipeline: https://github.com/envoyproxy/envoy/issues/921.

We could adopt this too.

**Comment by tiziano88** [comment]
Possibly add it to https://github.com/project-oak/oak/blob/master/scripts/run_tests

**Comment by ipetr0v** [comment]
In order to run `clang-tidy` we need to get a [compilation database](https://sarcasm.github.io/notes/dev/compilation-database.html) from bazel: a list of all build commands with arguments.
Bazel does not provide this, but it can be done with a [third-party library](https://github.com/grailbio/bazel-compilation-database) that has an Apache-2.0 licence.
Is it ok to use it?

This library provides a new build target, so it will look like this:
```
load("@com_grail_bazel_compdb//:aspects.bzl", "compilation_database")
compilation_database(
    name = "oak_compilation_database",
    targets = [
        ":oak",
    ],
)
```

**Comment by tiziano88** [comment]
Have you looked at https://github.com/kythe/kythe (which BTW is a Google project)?

**Comment by tiziano88** [comment]
re: the license, I think it is fine, but perhaps @sarahdeh should take a look and confirm?

**Comment by ipetr0v** [comment]
Previous [third party script](https://github.com/grailbio/bazel-compilation-database) has problems with `*.pb.h` include files, since they are generated in directory different from `$(bazel info execution_root)`.
Currently looking into Kythe, but it looks like it requires a lot of stuff:
https://github.com/kythe/kythe/blob/0b74112bca47852cd4c10597dc7487be39c0b250/external.bzl#L1-L13
Probably may slow down building process (but I'm not sure yet).

**Comment by ipetr0v** [comment]
Also, in order to use Kythe, we need to compile all targets with `--experimental_action_listener`, and may be very slow:
https://github.com/bazelbuild/bazel/issues/3420

**Comment by tiziano88** [comment]
Agreed, Kythe seem to have too much overhead and IIUC it is also always triggered, which means it would slow down runs even when the compilation database is not needed (e.g. when rebuilding a component locally to test some new changes). 

@ipetr0v feel free to go ahead with bazel-compilation-database, it looks like the license is fine by internal Google guidelines: http://go/thirdpartylicenses#notice

**Comment by ipetr0v** [comment]
Looks like bazel-compilation-database doesn't work with custom build rules at all.
For example, this I get from `cc_proto_library`:
```
ERROR: /opt/my-project/oak/proto/BUILD:63:1: in @bazel_compilation_database//:aspects.bzl%compilation_database_aspect aspect on cc_proto_library rule //oak/proto:manager_cc_proto: 
Traceback (most recent call last):
        File "/opt/my-project/oak/proto/BUILD", line 63
                @bazel_compilation_database//:aspects.bzl%compilation_database_aspect(...)
        File "/root/.cache/bazel/_bazel_root/b6bc0828d5b43c7085b650e0698bf388/external/bazel_compilation_database/aspects.bzl", line 266, in _compilation_database_aspect_impl
                _cc_compiler_info(ctx, target, srcs, feature_configurati..., ...)
        File "/root/.cache/bazel/_bazel_root/b6bc0828d5b43c7085b650e0698bf388/external/bazel_compilation_database/aspects.bzl", line 125, in _cc_compiler_info
                cc_common.get_memory_inefficient_command_line(feature_configuration = feature_..., <2 more arguments>)
Invalid toolchain configuration: Cannot find variable named 'output_file'.
ERROR: Analysis of target '//oak/server/asylo:oak_compilation_database' failed; build aborted: Analysis of target '//oak/proto:manager_cc_proto' failed; build aborted
```
And this from `enclave_loader`:
```
ERROR: /opt/my-project/oak/server/asylo/BUILD:149:1: in compilation_database rule //oak/server/asylo:oak_compilation_database: 
Traceback (most recent call last):
        File "/opt/my-project/oak/server/asylo/BUILD", line 149
                compilation_database(name = 'oak_compilation_database')
        File "/root/.cache/bazel/_bazel_root/b6bc0828d5b43c7085b650e0698bf388/external/bazel_compilation_database/aspects.bzl", line 344, in _compilation_database_impl
                compilation_db.append(target[CompilationAspect].compil...)
        File "/root/.cache/bazel/_bazel_root/b6bc0828d5b43c7085b650e0698bf388/external/bazel_compilation_database/aspects.bzl", line 344, in compilation_db.append
                target[CompilationAspect]
<merged target //oak/server/asylo:oak> doesn't contain declared provider 'CompilationAspect'
ERROR: Analysis of target '//oak/server/asylo:oak_compilation_database' failed; build aborted: Analysis of target '//oak/server/asylo:oak_compilation_database' failed; build aborted
```

Will look into fixing this.
Also will try to create a separate script that builds everything with kythe, so we will not notice the slowdown while building oak locally without clang-tidy. But this will still increase GCB time by 3x.

**Comment by ipetr0v** [comment]
Found an interesting issue, that Kythe generating a compilation database, where all paths point to a non-existing directory (that only exists during the compilation process):
https://github.com/kythe/kythe/issues/4238

**Comment by ipetr0v** [comment]
This issue got fixed.
Managed to run `clang-tidy` with a compilation database, but it shows same errors for all project files:
```bash
/opt/my-project# clang-tidy -p "$(bazel info execution_root)" oak/common/app_config.cc
Error while processing /opt/my-project/oak/common/app_config.cc.
error: unknown argument: '-fno-canonical-system-headers' [clang-diagnostic-error]
external/com_google_asylo/asylo/platform/posix/include/sched.h:35:16: error: typedef redefinition with different types ('CpuSet' vs 'struct cpu_set_t') [clang-diagnostic-error]
typedef CpuSet cpu_set_t;
               ^
/usr/include/x86_64-linux-gnu/bits/cpu-set.h:42:3: note: previous definition is here
} cpu_set_t;
  ^
Found compiler error(s).
```
Looks like `'-fno-canonical-system-headers'` that are automatically set by Bazel, are not recognized by Clang.

Also compilation database is not being generated for `asylo_oak_manager`, `enclave_loader` and for all header files.

**Comment by ipetr0v** [comment]
I have deleted all external files from the compilation database, but `clang-tidy` still tries to check them:
```bash
/opt/my-project# clang-tidy -p "$(bazel info execution_root)" oak/common/policy.cc -header-filter=oak/common/policy.h
1 error generated.
Error while processing /opt/my-project/oak/common/policy.cc.
external/com_google_asylo/asylo/platform/posix/include/sched.h:35:16: error: typedef redefinition with different types ('CpuSet' vs 'struct cpu_set_t') [clang-diagnostic-error]
typedef CpuSet cpu_set_t;
               ^
/usr/include/x86_64-linux-gnu/bits/cpu-set.h:42:3: note: previous definition is here
} cpu_set_t;
  ^
Found compiler error(s).
```

**Comment by ipetr0v** [comment]
Even 
```bash
clang-tidy -p "$(bazel info execution_root)" oak/common/policy.cc -header-filter=".*;-external/com_google_asylo/asylo/platform/posix/include/sched.h"
```
does not prevent `sched.h` from being processed.

**Comment by ipetr0v** [comment]
Created a pull request https://github.com/project-oak/oak/pull/348
The only thing that left is that `buildifier` doesn't like the usage of private functions:
```
./WORKSPACE:199: bzl-visibility: Module "@io_bazel_rules_go//go/private:compat/compat_repo.bzl" can only be loaded from files located inside "@io_bazel_rules_go//go", not from "//". (https://gith
ub.com/bazelbuild/buildtools/blob/master/WARNINGS.md#bzl-visibility)
```
But it is required for Kythe to work https://github.com/kythe/kythe/issues/4237
https://github.com/kythe/kythe/blob/9941fe8eabba4612daea78ce69c5cc205e9b0791/WORKSPACE#L28-L39

**Comment by ipetr0v** [comment]
It's possible to disable a single warning for a single command:
https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#how-to-disable-warnings
