### ISSUE TITLE
Support plain TLS in gRPC server pseudo-node

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#644]
This would be in alternative to [EKEP](https://asylo.dev/docs/concepts/ekep.html), in cases in which hardware-based remote attestation is not necessary / desired.

While `DevOakLoader` already effectively supports a no-attestation workflow, it still relies on EKEP, which may be inconvenient for clients that do not care about remote attestation.

In fact, currently the gRPC pseudo-node is always instantiated with EKEP (although with Null credentials), even for the dev server:

https://github.com/project-oak/oak/blob/324e3a180e2aca02c69ed342b22483502c8e7c85/oak/server/oak_grpc_node.cc#L39-L41

At the very least this must be configurable to allow for different credentials to be instantiated based on the underlying hardware (e.g. Null vs SGX), but as part of this issue I am suggesting we also allow plain TLS credentials.

This would also require figuring out a way of passing a TLS key to the binary, so that it may use it to terminate TLS.

Unless we assume that TLS is terminated by a proxy or load balancer that sits in front of the actual binary, in which case we may get away using a self-signed cert or similar between the proxy and the binary.

@uberspot do you have any suggestions?

**Comment by tiziano88** [comment]
I cannot find a good reference in the C++ API of gRPC for how to set up secure credentials, all [examples in the official documentation](https://grpc.io/docs/tutorials/basic/cpp/) seem to just use insecure credentials!

I guess we need to call [SslServerCredentials](https://grpc.github.io/grpc/cpp/namespacegrpc__impl.html#a70396ff9cd00198734d857d2e446ab52) at some point, but I wish there was an example of this somewhere.

**Comment by tiziano88** [comment]
This is the only example I have found so far of a server using TLS credentials: https://github.com/grpc/grpc/issues/9593#issuecomment-277946137

**Comment by uberspot** [comment]
https://grpc.io/docs/guides/auth/ this seems useful as well and has some examples with SSLServerCredentials as well as custom types of creds.

**Comment by tiziano88** [comment]
Potentially relevant for deployment:

- https://cloud.google.com/endpoints/docs/grpc/enabling-ssl
- https://cloud.google.com/endpoints/docs/grpc/get-started-kubernetes-engine#deploying_the_sample_api_and_esp_to_the_cluster

**Comment by tiziano88** [comment]
> https://grpc.io/docs/guides/auth/ this seems useful as well and has some examples with SSLServerCredentials as well as custom types of creds.

@uberspot I think could not find anything there that shows how to actually load TLS credentials from a key file or similar for C++, or did I miss it?

```cpp
auto channel_creds = grpc::SslCredentials(grpc::SslCredentialsOptions());
auto channel = grpc::CreateChannel("myservice.example.com", channel_creds);
std::unique_ptr<Greeter::Stub> stub(Greeter::NewStub(channel));
...
```

For instance, the Go example at least refers to the key and cert files:

```go
creds, _ := credentials.NewServerTLSFromFile(certFile, keyFile)
s := grpc.NewServer(grpc.Creds(creds))
lis, _ := net.Listen("tcp", "localhost:50051")
// error handling omitted
s.Serve(lis)
```

**Comment by tiziano88** [comment]
@conradgrobler , since you are already looking at both gRPC termination and also at running workloads on cloud / VMs, could you look into this?

I would like the short-term result to be an Oak Application running on an Oak Runtime that we can deploy on regular cloud infrastructure, using standard TLS termination (no remote attestation, no enclave isolation, no load balancing, single instance).

It would be fine to use whatever TLS certificates are most readily available on cloud, I expect the end result to be something running on an endpoint like `https://xxxxxxxxxxxxxxxxxxxxxx.oak-test.gcloud.com` or whatever, let's not worry about getting a proper domain for now.

**Comment by conradgrobler** [comment]
I will look into it.

**Comment by tiziano88** [comment]
@conradgrobler any update on this? do we need to figure out how to provision those certs all the way to the Oak Runtime binary, or is there a simpler solution in which those certs are provisioned by GCP itself, for instance on an envoy instance running in the same container as the binary, and communicating with the binary over pipes or something else?

**Comment by conradgrobler** [comment]
I have not yet looked into this in a lot of detail. I am unsure what you mean by 'certs are provisioned by CGP itself'. Assuming this refers to Google Managed TLS certificates, these can only be used by external load balancers or GKE Ingress as far as I can tell. This would still mean that we need to create and use self-signed certificates to secure the communication to the service. Using envoy running in the same VM or container should work fine, but it seems a bit excessive in terms of resource usage.

**Comment by tiziano88** [comment]
@conradgrobler and I discussed a few options. 

The first decision to make is whether the TLS server should be using Asylo at all or not. If not, then there is another choice: either keeping the gRPC generic server loop in C++ (using plain TLS credentials), or moving also that to Rust, trying to hook into the internals of the [tonic](https://docs.rs/tonic/0.1.1/tonic/) gRPC server.

IIRC the plan of record is not to use Asylo, but keep the gRPC generic server in C++, even if / when we migrate the rest of the runtime to Rust.

@conradgrobler could you confirm, or add any details I may be forgetting?

**Comment by tiziano88** [comment]
cc @ipetr0v this may affect the Docker image generation, and GCP deployment (ideally it would make things simpler).

**Comment by conradgrobler** [comment]
So far I have been working towards making the protocol pluggable on the dev server, so that it can run either TLS or EKEP. Changing the dev server to be TLS only will simplify it a great deal.

Regarding C++ gRPC vs Tonic: there is a pending task to investigate the feasibility of using TOnic if we move to a full Rust runtime, but I am treating it as a very low priority.
