### ISSUE TITLE
Merge `oak_log` crate in `oak`

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#645]
There is not a strong reason for keeping this as a separate crate, it does introduce an extra dependency on `log`, but that's a very lightweight one anyways (it's just a facade).

I think we can simply move everything under `oak::log` in the main SDK crate.

Ref. https://github.com/project-oak/oak/tree/master/sdk/rust/oak_log

@rbehjati perhaps you could look into it after #555 ?

In the meanwhile, if anyone thinks of any reason why we should keep these crates separate, please reply here.

**Comment by daviddrysdale** [comment]
Maybe there was some idea that not having a dependency on `oak_log` would make it clear that a Node didn't use the logging channel and so couldn't leak information that way?  

However, not having a `LogConfiguration` in the `ApplicationConfiguration` is a stronger way of checking that, so merging `oak_log` into `oak` seems sensible.
