### ISSUE TITLE
Separate builds for debug and non-debug.

### ISSUE THREAD

**Issue by daviddrysdale** [project-oak/oak#672]
Debugging functionality is essential for developing and maintaining Oak Applications and the Oak platform, but exposes a potential leakage of private data.  

Debug information should therefore be switchable, and moreover the switch needs to be a compile-time switch so that the hash of the binary (which gets attested to) includes the state of the switch (i.e. knowing an attested hash gives certainty that the binary involved doesn't leak debug information).

Debugging function to gate on the flag includes:
- ~~[ ] Stack traces from crashes (#669)~~ (removed now we don't have an Asylo runner)
- [x] Internal logging from the Runtime.
    - [ ] Add checks that logging doesn't accidentally get re-introduced
- [ ] Exported metrics, particularly if not aggregated.
- ~~[ ] Output from the logging pseudo-Node.~~ (this should be covered by information flow control mechanisms)

**Comment by tiziano88** [comment]
The last two points (metrics and logging) may be allowed even in production build, as long as the labels allow it (e.g. handling public data). So perhaps I'm thinking that most of the logic may boil down to debug builds bypassing the labelling / information flow control, perhaps by printing a warning if something was allowed that would not be allowed in a production build.

Stack traces and internal logging would probably still be exclusively controlled by the debug mode switch, with no influence from policies.

**Comment by daviddrysdale** [comment]
Note: compile-time control of logging needs to be re-implemented in the Rust runtime.

**Comment by daviddrysdale** [comment]
#859 made Rust logging controlled by the value of the `OAK_DEBUG` preprocessor macro in the Bazel/C++ build.  #902 adds an `oak_debug` feature for the `oak_runtime` crate, but there isn't (yet) a connection between Bazel/`OAK_DEBUG` and Rust/`oak_debug`.

**Comment by daviddrysdale** [comment]
The `oak_debug` feature now controls whether logging is emitted, and whether the introspection and metrics servers are enabled.
