### ISSUE TITLE
Oak asylo runner hanging when example fails to run

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#677]
To reproduce:

```bash
./scripts/docker_sh
# Then run the following command in the Docker prompt.
./scripts/run_example -e chat -- --address=
```

Then on a terminal outside Docker:

```bash
ps -aux | grep runner
tzn      170194  298  1.9 2577500 1268956 pts/0 Sl   13:07   8:31 ./oak/server/asylo/asylo_oak_runner_host_loader --enclave_path=oak/server/asylo/oak_enclave_debug.so --application=/opt/my-project/bazel-client-bin/examples/chat/config/config.bin
```

Note it is still running, and using 300% CPU

**Comment by tiziano88** [comment]
I'm not sure #710 actually solved this, the problem seems to be that the server keeps using 300% CPU. Sure, you can solve it by killing it, but the root problem is still there?

**Comment by tiziano88** [comment]
In fact now it's harder to debug this issue, since the server is killed immediately :)

**Comment by ipetr0v** [comment]
I have rerun this example with `dev` server (since `asylo` server was [deleted](https://github.com/project-oak/oak/pull/713)) - and don't see CPU load (even if I don't remove the server).
Could you confirm that this is not happening on your machine too?

**Comment by tiziano88** [comment]
I think you are right, this seems to only happen with the Asylo version, which is going away soon. Not sure why, anyway let's keep an eye on it and let's see if it happens again with the dev server, in the meanwhile it's fine to close.
