### ISSUE TITLE
Oak Runtime with (v)TPM root of trust

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#684]
Support a version of the Oak Runtime that uses (v)TPM-based root of trust for terminating gRPC connections. EKEP should eventually support something like this, but I think in the shorter term it should be possible to do it over standard TLS.

I am not sure what such a certificate would look like though: would it be self-signed? Or would it be signed by google.com or another CA?

See https://cloud.google.com/blog/products/gcp/virtual-trusted-platform-module-for-shielded-vms-security-in-plaintext

**Comment by tiziano88** [comment]
May be related to #644 .

**Comment by tiziano88** [comment]
I think we should prioritize this, and see whether we can get something up and running using gRPC over TLS, where the certificate comes from a TPM root of trust and contains a quote of the boot process, or something along those lines.

@conradgrobler do you think that's feasible at all? I remember you looked into this a while ago

**Comment by conradgrobler** [comment]
Getting this set up with a certificate owned by the vTPM seems feasible, but I am not sure how feasible it is to include the measured boot quote in the certificate. GCP supports shielded VMs which does measured boot for validating the startup, but I have not seen the option to get a quote from this process from the vTPM. Also, at the moment there is not support for post-boot quotes (such as additional software running, configuration details etc) that I am aware of.

I will look into this in some more detail.

**Comment by conradgrobler** [comment]
Based on re-reading some of the documentation, it seems to be possible to at least get access to the measured boot information and the vTPM public keys used for signing and sealing:

- https://cloud.google.com/security/shielded-cloud/shielded-vm
- https://cloud.google.com/security/shielded-cloud/retrieving-endorsement-key

Measuring the post-boot process (e.g. loading the Oak runtime) would require creating a custom image and adding support for post-boot measurements to the OS:

- https://cloud.google.com/security/shielded-cloud/creating-shielded-images

**Comment by tiziano88** [comment]
I think getting a quote of any stage of the boot process would be a good starting point. It's still unclear to me how that interacts with TLS though, does it mean that the machine has to get a TLS cert from the TPM? How does that compose with the TLS cert for the domain, which is provisioned separately?

**Comment by conradgrobler** [comment]
We would have to generate a certificate signing request at startup that includes the measured boot information as an extension field. The CSR should also contain the SAN entry for the domain (which I guess can be specified as part of the startup config). We would then need to sign the certificate. Signing has some challenges:

- I am not aware of a Rust crate that allows signing the certificate using a vTPM, but I haven't looked in much detail.
- Seeing that we are building the runtime using musl, ring does not use openssl, so this restricts our options.
- It might be possible to get an intermediate certificate that can be used to sign server-specific certificates, but this will be complicated to manage and ensure the private key remains secure. This option might be suitable for a large operation that is used to doing secure key management and owns HSMs, but not for the general case.
- Perhaps we can automatically sign the certificate through a CA API during startup (something like https://letsencrypt.org/docs/client-options/)

**Comment by conradgrobler** [comment]
I did some further investigation. It seems that access from a Docker container to the vTPM is not supported. GKE does support shielded nodes, which uses a vTPM to make sure the Kubernetes node hosting the containers is running a trusted version of the OS, but the vTPM is not accessible from within the containers.

This means that we would need to change our deployment model to use shielded VMs to be able to access the vTPM.

**Comment by tiziano88** [comment]
I guess we would have to do that for any remote attestation scheme to work anyways, so perhaps it's worth investigating further? Although I'm not sure what that would mean exactly: would we need to produce a bootable img / iso instead of a docker image?

**Comment by conradgrobler** [comment]
Yes, we would need to create a bootable VM image, which should either be built from an existing shielded public VM image (e.g. Ubuntu 18.04 lts) or we could create our own from scratch by following https://cloud.google.com/security/shielded-cloud/creating-shielded-images

We used to create a Hello World image with Bazel and Packer, but it has been removed in favour of Docker images. It should be relatively simple to redo with scripts calling the gcloud command line to:

- Create a new shielded VM and start it up
- Copy the runner and app config onto it
- Run a config script on the VM:
  - Install any missing prerequisites (I don't actually think there are any at the moment)
  - Configure the runner to start at boot time
- Save a snapshot of the VM image as a new reusable image
- Delete the VM

Packer's GCP component was basically a Go application that did the above version using the Go GCP SDK client library. There is not a Rust client library, but we could use one of the other supported language if we don't want to use scripts:
https://cloud.google.com/apis/docs/cloud-client-libraries

**Comment by tiziano88** [comment]
Perhaps it's worth first coming up with a smaller experimental pure Rust binary that actually gets a vTPM quote from the system and just prints it out, and try to package that in a bootable image, so that we get a feel of how / whether it can work at all.

**Comment by conradgrobler** [comment]
I did some initial checks with shielded VM in GCE. There is an API to retrieve the signing keys ans encryption keys from the vTPM associated with each VM: https://cloud.google.com/compute/docs/reference/rest/v1/instances/getShieldedInstanceIdentity

Below is some example output from running the gcloud equivalent command. As expected, the keys are different for each VM. The ekCert field is always empty. It seems that a unique keys are generated for each VM, but certificates are not. I could not find any configuration option that would cause certificates to be generated.

This makes validation on the client-side problematic. While it is possible to list the public keys via the API, this requires a user to log in and have permission on the GCP project, so would not be accessible to general end-users. As there are no certificates based on another root of trust, the end-user will have no way of validating whether the signature is valid. It would be possible to publish the public key somewhere, but the user than has no way of knowing whether the public key is related to a primary key that is actually in a vTPM.

```
encryptionKey:
  ekPub: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA9a/4n1LXJuV/xc56qBWW
    hHdo/x6aQQoSiMoK0PggFUYABjUaF7j/BeqJIJT0cuL55kQI/KhEPjjh8gAJBb5F
    aeJI0vjCMWS0EM7+AfQCR4WhdARyn2M9Bk6sP3ppfZ7eSF224dH46JlTywCCN7CN
    ZUABNucHF2BHsHNErR0ZDCoTgGQshexe6yaIvRH8xM19XcqjoN0M0yVUuDtN4Naw
    v+cmLEUZIq4t7bpQD3FAUrimr24xKxbBTy0zYE1ZNjb+R3uIALo++LlAUdDKHtAx
    ayyNAe6aU/dw/4CHkY5OxA5+cO7I93l4XDSX6Kzc/FqqQ4Vr2nNHsbs65xEhJVk3
    dQIDAQAB
    -----END PUBLIC KEY-----
kind: compute#shieldedInstanceIdentity
signingKey:
  ekPub: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuSzU06DdrABTVfqueuop
    bePooxeCDf7r9W1hGiUkhjGaYrKQYTicGmQE+iQLtiAxVhnGn//Umf5ah33Uv0cp
    hG9c3360/Rx6LlDOcdyEqhKQixqo/SyP7UoH4MK4L8zBW+zN+RhiFcTVi+c4MZLr
    Qg6xe+dfcWmVc/0BeYV6Q5O23TB5sMMkK0SYlKfKppHmJODWsqJ8PX23/NQW33ST
    Ns1+z4+lL27rfCtD+kYySOG0RACn092rCE/s8v/Lji6Fwtp9BYoJLXAiYPqq2TRb
    Khr7NLwJecPnMBEYxLcp3FRrZ/D9B0rTtujh84U53hkZeF31Z1dc0FMHHExX+0V7
    SQIDAQAB
    -----END PUBLIC KEY-----
```

The next step I am planning is to install some TPM tools (https://github.com/tpm2-software/tpm2-tools) on a shieled VM and seeing whether there is perhaps a certificate on the TPM that is just not exposed by the API.

**Comment by conradgrobler** [comment]
After some further thinking, I don't believe TPM-based remote attestation can really attest to the version of the runtime that is running (or provide any security guarantees to a remote user). Secure/measured boot using the TPM provides proof about the specific version of firmware and OS that was loaded using PCRs. This provides attestation of the boot-state to the machine owner (e.g. that there are no rootkits loaded at startup). We could extend the idea by including a startup script in the OS image that will run at the end of the boot sequence. That startup script can take a measurement of the Runtime and extend the PCR values with this measurement before starting the Runtime. So far it is fine, but the PCR value represents a point in time. 

After this sequence completes, an administrator on the machine can stop the runtime and load a different (potentially malicious) version. The TPM will not have any way of knowing about this. The modified version can then request a quote from the TPM that covers the PCR values and use that for remote attestation. These will still look as if the original version of the runtime is still running.

In an SGX-like enclave this is prevented by sealing the enclave so that no external code/users can modify the executable memory. In a VM running a vTPM, there is nothing preventing modification of the memory/processes by an administrator.
