### ISSUE TITLE
Link Rust Oak Runtime to Asylo C++ platform

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#694]
@daviddrysdale suggested that we may be able to link the Oak Runtime to the Asylo C++ "platform" by providing no-op implementations of symbols that are not currently provided by the Asylo version of libc. This approach is similar to what @ipetr0v has done in order to compile TFlite to Wasm by [adding placeholder functions to satisfy the linker](https://github.com/project-oak/oak/blob/master/oak/module/placeholders.h). For Oak Runtime we probably need to be a bit more lenient with what we do in these placeholders, I suspect in some cases (e.g. setting thread stack size) we should just do nothing, rather than abort.

To clarify: if this works, it would allow us to have a regular (i.e. no `no_std`) version of the Oak Runtime, and link it directly against the C++ code, without having to fork Rust `std`.

@daviddrysdale @blaxill , depending on how much you have looked into this already, could you share any information you already have, and what's left to do? Then we can decide who should own this issue.

**Comment by tiziano88** [comment]
Now I remember a few more details about this from previous discussions: some of those symbols are actually [defined in Asylo's libc](https://github.com/google/asylo/blob/421c663bd2cef12aa8c6e0cef5b9b551bfecc4c5/asylo/platform/posix/pthread.cc#L920-L943), but they just always return `ENOSYS`. In this case, it seems harder that we may be able to override them with no-op implementations.

Perhaps we may convince the Asylo team to whitelist a few of those symbols to not return errors (or we may maintain a patch for that).

**Comment by blaxill** [comment]
Closing as Oak is moving away from Asylo
