### ISSUE TITLE
Investigate feasibility of a Rust-only Oak server based on Tonic

### ISSUE THREAD

**Issue by conradgrobler** [project-oak/oak#695]

**Comment by conradgrobler** [comment]
We could implement a generic service as a specialisation of the Tower Service (Service<http::Request<HyperBody>>). This could then proxy the raw bytes from the request body to the node. It would be up to the node to decode the byte stream into proto objects and encode the result back into a stream of bytes. Any bytes returned from the node can then be proxied back to the client.

Adding the generic service to a Tonic server should be possible using something like:
    Server::builder()
        .add_service(generic_service_instance)
        .serve(addr)
        .await?;

**Comment by conradgrobler** [comment]
Some more datails about implementing the generic service:

- The Request exposes the HTTP [path](https://docs.rs/http/0.2.0/http/request/struct.Request.html#method.uri) and [method](https://docs.rs/http/0.2.0/http/request/struct.Request.html#method.method) 
- The content (bytes) of the Hyper body can retrieved using an approach similar to the hyper api [example](https://github.com/hyperium/hyper/blob/master/examples/web_api.rs#L43)
- The extracted bytes can be encapsulated in a proto Any type similarly to what is currently done in the c++ [ModuleInvocation](https://github.com/project-oak/oak/blob/master/oak/server/module_invocation.cc#L95)
- The encapsulated proto can be forwarded to the wasm node that can decapsulate the data and parse the inner proto

**Comment by tiziano88** [comment]
> Some more datails about implementing the generic service:
> 
> * The Request exposes the HTTP [path](https://docs.rs/http/0.2.0/http/request/struct.Request.html#method.uri) and [method](https://docs.rs/http/0.2.0/http/request/struct.Request.html#method.method)

Can we get access to deserialized gRPC metadata key / value pairs? Otherwise we need to re-implement that logic somewhere ourselves, and it risks getting out of sync with the actual gRPC one.

> * The content (bytes) of the Hyper body can retrieved using an approach similar to the hyper api [example](https://github.com/hyperium/hyper/blob/master/examples/web_api.rs#L43)
> * The extracted bytes can be encapsulated in a proto Any type similarly to what is currently done in the c++ [ModuleInvocation](https://github.com/project-oak/oak/blob/master/oak/server/module_invocation.cc#L95)

Why is an `Any` type needed? I think we should just pass them as `bytes`, we will never know the actual type upfront anyways, so I'd say let's be even more generic.

> * The encapsulated proto can be forwarded to the wasm node that can decapsulate the data and parse the inner proto

**Comment by conradgrobler** [comment]
> Can we get access to deserialized gRPC metadata key / value pairs? Otherwise we need to re-implement that logic somewhere ourselves, and it risks getting out of sync with the actual gRPC one.

The custom metadata is set as http headers. These can be retrieved from the request via https://docs.rs/http/0.2.0/http/request/struct.Request.html#method.headers

> Why is an `Any` type needed? I think we should just pass them as `bytes`, we will never know the actual type upfront anyways, so I'd say let's be even more generic.

Makes sense.

**Comment by tiziano88** [comment]
So of the stack that we are considering now, how much is really gRPC specific, vs just generic HTTP2?

**Comment by conradgrobler** [comment]
In this scenario nothing in the rutnime is grpc-specific, apart from interpreting the headers as custom metadata. The interpretations of the method, path and bytes must be done in the wasm node.

**Comment by conradgrobler** [comment]
Now included in #751
