### ISSUE TITLE
Investigate options for provisioning secrets to VM instances in GCP

### ISSUE THREAD

**Issue by conradgrobler** [project-oak/oak#696]
Also understand how service accounts are provisioned onto VM instances, and whether the mechanism is reusable/extensible.

**Comment by tiziano88** [comment]
It seems that using the metadata service does indeed [rely on some network magic on the VM](https://cloud.google.com/compute/docs/storing-retrieving-metadata?hl=en_GB#is_metadata_information_secure).

In fact this seems to be the recommended way of [obtaining access tokens](https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances?hl=en_GB#applications) from applications.

The [secret manager API](https://cloud.google.com/secret-manager/docs/accessing-the-api?hl=en_GB#compute) should then be able to use those credentials to retrieve further secrets.

**Comment by tiziano88** [comment]
Partly related to #689.

**Comment by conradgrobler** [comment]
For images that specifically use Kubernetes, I think the best option is to use it to manage the secrets such as private keys:
https://kubernetes.io/docs/concepts/configuration/secret/

For VM-based images the metadata service and secret manager API makes sense as a mechanism to distribute certificate keys and other secrets.

**Comment by tiziano88** [comment]
@conradgrobler what are the next steps then? can you look into how to get our generated certs as secrets on kubernetes?

**Comment by conradgrobler** [comment]
Ok.

**Comment by conradgrobler** [comment]
I don't think we should make the SDK GCP-specific. Secrets provisioning, storage etc. would depend on the platform. We seem to be moving to Kubernetes for deployments, and in that case Kubernetes Secrets would be the way to go.

I agree that an HTTP client node will be useful for accessing the metadata service from VM instance, but I will add it as a separate task. Everything else should be implemented as examples or library nodes in my opinion.

**Comment by conradgrobler** [comment]
Having thought about is some more: seeing that the provisioning of secrets will be different for each platform, secret provisioning should be part of the enclave abstraction layer (EAL) and probably injected into the runtime only at startup.

In the short term, until the EAL is in place, we should use Kubernetes for deployments and use Kubernetes Secrets for provisioning the secrets. In the case of the certificate private key, it will be mounted as a file and passed into the runtime using the standard command line flag.

**Comment by tiziano88** [comment]
It looks like Kubernetes does indeed allow to [mount secrets as files](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets) (or alternatively env variables).

In the short term, we should be able to just use that to provision the TLS key (no code changes required), since it is a flag on the oak_loader binary itself, so @conradgrobler could you try and do that and let us know if it works out? I guess we should add a script that pushes the secret (for now just the existing checked-in cert key) to the kubernetes cluster, and then modify the pod definition and / or docker image so that they pass the appropriate flag to oak_loader.

**Comment by conradgrobler** [comment]
Yes, I am working on it.
