### ISSUE TITLE
Set docker UID

### ISSUE THREAD

**Issue by remyabel** [project-oak/oak#70]
By default, Docker container has uid 0 (root). This is not only a security risk, but annoying because any files output by the container will be owned by root.

**Comment by tiziano88** [comment]
This may help with other Docker-related workflows, so it's perhaps worth prioritising.

See also https://medium.com/redbubble/running-a-docker-container-as-a-non-root-user-7d2e00f8ee15

**Comment by remyabel** [comment]
Just a question for my information. Are there any security advantages to creating a user/group inside Docker instead of using the `--user` flag? (Ignoring convenience since you add `/home/$USERNAME` to the PATH for the installed binaries)

**Comment by tiziano88** [comment]
Thanks @remyabel , actually that's the first thing we tried, but it seems if we set user via that flag then we are not able to install software as root with `apt-get` from within the container. Do you know how to fix that cleanly?

**Comment by remyabel** [comment]
I don't think it's necessary to make it non-root during the `docker build` stage, only the `docker run` stage. Here's how [google-cloud-cpp](https://github.com/googleapis/google-cloud-cpp/blob/a186208b79d900b4ec71c6f9df3acf7638f01dc6/ci/kokoro/docker/build.sh#L146) does it. There's also some Bazel specific stuff in there.
