### ISSUE TITLE
Rename Oak dev server

### ISSUE THREAD

**Issue by conradgrobler** [project-oak/oak#700]
The current 'dev' server will be the default server running in many cases (eg inside VM's, on trusted devices etc.), so it will not really be only a 'development' version.

Perhaps 'standard' or 'default' will be more appropriate.

**Comment by tiziano88** [comment]
How about:

- `process_oak_loader` using standard linux process isolation
- `asylo_oak_loader` using Asylo enclave isolation

This may need re-visiting if / when Asylo started supporting EKEP in the context of secure VMs, but let's not worry about that for now.

cc @project-oak/core if anyone has any objections / suggestions.

Not high priority, but this could be done in between tasks perhaps, if anyone is blocked on other work.

**Comment by daviddrysdale** [comment]
Since #709, possibly just `oak_loader` ?
