### ISSUE TITLE
Create Rust `oak_loader` binary

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#723]
We have the starting point of an [oak runtime](https://github.com/project-oak/oak/tree/master/oak/server/rust/oak_runtime) Rust **library**, but we do not have the entry point of a Rust **binary**, i.e. a counterpart to [`dev_oak_runner`](https://github.com/project-oak/oak/blob/master/oak/server/dev/dev_oak_runner_main.cc) but in Rust.

**Comment by tiziano88** [comment]
@ipetr0v perhaps you could look into this, it should be similar to the work you did when splitting the dev and asylo loader.

**Comment by daviddrysdale** [comment]
cf. #540 which covers the Rust runtime library

**Comment by ipetr0v** [comment]
Should we continue using `protobuf` config files or switch to a something new (JSON, YAML etc.) ?
Related to https://github.com/project-oak/oak/issues/689

**Comment by tiziano88** [comment]
A large chunk of the config files will still be the serialized wasm modules, and for that I think protobuf is the one that makes more sense. JSON or YAML would presumably require to base64 encode them as binary data, which does not seem that great.

**Comment by ipetr0v** [comment]
Also, if I understand correctly gRPC client nodes are currently not created by the Rust Runtime, right?
