### ISSUE TITLE
Decide the fate of C++ storage pseudo-node implementation

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#727]
https://github.com/project-oak/oak/tree/master/oak/server/storage

Let's use this issue to decide what to do with the existing implementation of the storage pseudo-node, with respect to #540 .

The main options are (in @tiziano88 's decreasing order of preference):

- delete the C++ code now and re-implement it in Rust if and when necessary
  + the new implementation may follow a more minimalist design, in which we rely only on a simpler "encryption" pseudo-node or Wasm node for the encryption / decryption logic, which paired together with a gRPC client pseudo-node achieves the same functionality as the current one
  + note that without a hardware root of trust with sealing capabilities, it does not seem to make much sense for a storage pseudo-node to exist, since any encryption key would have to be provisioned from outside of the oak runtime
- keep the C++ around, and eventually transform it into a C++ pseudo-node running on top of the Rust runtime
  + blocked by #724

@daviddrysdale any other options / considerations?

**Comment by daviddrysdale** [comment]
C++ implementation removed in #1016.
