### ISSUE TITLE
Support Roughtime from Rust

### ISSUE THREAD

**Issue by daviddrysdale** [project-oak/oak#730]
We currently have some Roughtime client code in C++ (#428, #461, #468).  It's not yet plumbed into the runtime (there's no ABI to expose it yet), but it will eventually need to be accessible from the Rust-based version of the runtime (#723).   That could either be:
 - because it's possible to link C++ functionality into the Rust runtime (#724), or
 - because we have a pure Rust implementation of the Roughtime client.

**Comment by daviddrysdale** [comment]
As of #845 and #801 the Rust runtime can use the C++ Roughtime client pseudo-Node via FFI.

**Comment by conradgrobler** [comment]
#1047 adds a Rust version of the c++ Roughtime client to the runtime. The pseudo-node will follow.
