### ISSUE TITLE
Implement ABI test client in Rust

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#734]
Similar to https://github.com/project-oak/oak/tree/master/examples/abitest/client .

**Comment by daviddrysdale** [comment]
For what purpose? Is there any reason why the existing C++ abitest client can't be used to test a Rust-based runtime?

**Comment by tiziano88** [comment]
We can definitely keep using the C++ client (and we should in the short term, which is why I didn't even add this to https://github.com/project-oak/oak/milestone/3).

In the longer term I think we should have at least some of this functionality in Rust too in order to:

- exercise Rust client bindings
- have a way of running tests so that the entire stack is in Rust (useful for local development, etc)
