### ISSUE TITLE
gRPC server pseudo-node in Rust Oak Runtime

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#751]
Currently Rust Oak Runtime doesn't support TLS gRPC credentials that is supported by the C++ version:
https://github.com/project-oak/oak/blob/09c7d6d86dd3a6c3808f3157884dc702c5352a50/oak/server/dev/dev_oak_loader.h#L33-L34
Necessary, since we are moving towards using a Rust Oak Loader binary in the future #749.

**Comment by ipetr0v** [comment]
Currently Rust Oak Runtime does not have a gRPC server node for receiving messages from clients.

Before Split gRPC (#627) is implemented we could have a gRPC server node implemented as a [Tonic](https://docs.rs/tonic/) server that encapsulates client requests in a generic Protobuf message:
https://github.com/project-oak/oak/blob/09c7d6d86dd3a6c3808f3157884dc702c5352a50/oak/proto/grpc_encap.proto#L30-L34
and passes it to the initial Oak node, specified in the config:
https://github.com/project-oak/oak/blob/09c7d6d86dd3a6c3808f3157884dc702c5352a50/examples/hello_world/config/config.textproto#L12-L13

**Comment by ipetr0v** [comment]
@conradgrobler 

The C++ implementation of the gRPC pseudo-node uses the [grpc::AsyncGenericService](https://grpc.github.io/grpc/cpp/classgrpc_1_1_async_generic_service.html), that accepts all gRPC calls and does not implement any schema
https://github.com/project-oak/oak/blob/09c7d6d86dd3a6c3808f3157884dc702c5352a50/oak/server/oak_grpc_node.cc#L43-L45

Have you seen similar service for Tonic?
IIUC Tonic requires some schema in order to start server
https://github.com/project-oak/oak/blob/09c7d6d86dd3a6c3808f3157884dc702c5352a50/examples/hello_world/proto/hello_world.proto#L30-L35
https://github.com/project-oak/oak/blob/09c7d6d86dd3a6c3808f3157884dc702c5352a50/experimental/split_grpc/server/src/main.rs#L84-L88

**Comment by conradgrobler** [comment]
The approach I was considering was to create a new generic service (see https://github.com/project-oak/oak/issues/695#issuecomment-600616807). The service would need to implement a call method that can receive a generic Request object.

This service would look similar to some of the code generated by Tonic for a proto file (eg https://github.com/project-oak/oak/pull/647/files#diff-6116dfd8bdebbd1ea4776bec4c89ecccR65)

Initially, we can test using only a unary service and later figure out how to handle client streaming or bidirectional streaming services in a generic way.

This service could then be added using 'add_service'

**Comment by ipetr0v** [comment]
In order to be able to use `add_service`, the service should implement a `tonic::transport::server::NamedService` trait:
https://github.com/project-oak/oak/pull/647/files#diff-6116dfd8bdebbd1ea4776bec4c89ecccR229-R231
And it requires to set a service name (e.g. `"oak.examples.hello_world.HelloWorld"`).

Is it enough to just set an empty string as a service name? Because it looks like upon receiving a message from a client Tonic searches for a corresponding service based on its name.

**Comment by conradgrobler** [comment]
Looking at the Tonic code, it seems that the routing just checks that the request URI starts with `/` followed by the service name.
https://github.com/hyperium/tonic/blob/master/tonic/src/transport/server/mod.rs#L328

I would think that an empty string would work, although it feels like it might be brittle if the logic changes in future. For initial testing it should be OK, but it might be better in the long term to use hyper directly, rather than Tonic, as we are not currently relying on any real gRPC functionality in the gRPC pseudo node. The code could look very similar to the hyper web API example:
https://github.com/hyperium/hyper/blob/master/examples/web_api.rs#L100

**Comment by tiziano88** [comment]
Yes, my suggestion is to aim directly for a Hyper service, and not involve Tonic at all, if possible.

**Comment by conradgrobler** [comment]
Tonic provides a nice mechanism for configuring TLS. When using Hyper directly, it would need code similar to the following:
https://users.rust-lang.org/t/use-hyper-server-with-tls/18535

**Comment by ipetr0v** [comment]
Since Hyper requires the function that creates and starts a server to be `async`:
https://github.com/hyperium/hyper/blob/97ed0478a871f45555ee1985ae228a0adc27c35a/examples/hello.rs#L18-L23

Do we need to consider making `node_create` function `async` as well?
https://github.com/project-oak/oak/blob/589b2d20bbd9e0d8388f58e8b50b50522842013c/oak/server/rust/oak_runtime/src/runtime/mod.rs#L615-L633

But I think this may require rewriting a lot of internal Runtime code in `async`/`await`.
