### ISSUE TITLE
Rely on memory allocation in Wasm ABI

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#754]
Currently, most Wasm ABI functions that expect to read data from other nodes or from the runtime need to pre-allocate a buffer, and pass a pointer (really a Wasm linear memory offset) and size as part of the function call, which is not very ergonomic and potentially also wasteful (since in general the caller does not know the exact size of the data to be returned upfront).

We could mitigate this by requiring an Oak Wasm module to expose a Wasm function (e.g. `oak_alloc(len: usize)` or similar) that allocates the specified number of bytes into Wasm linear memory **using the Rust memory allocator**, and returns its offset in the Wasm linear memory. This would be used by the Oak runtime itself when fulfilling calls that require returning owned allocated objects.

For instance, [channel_read](https://github.com/project-oak/oak/blob/master/docs/abi.md#channel_read) could return two allocated buffers (one for bytes, one for handles), instead of requiring the caller to pass them in. This may get simpler with the addition of [multiple return values](https://hacks.mozilla.org/2019/11/multi-value-all-the-wasm/) to Wasm.

This is just a placeholder issue for now, in case anyone has any additional information that we should consider.

**Comment by tiziano88** [comment]
Potentially relevant: https://www.fastly.com/blog/webassembly-memory-management-guide-for-c-rust-programmers

**Comment by tiziano88** [comment]
@conradgrobler I think this is similar to what we were talking about yesterday.

I think `oak_alloc` may allocate the desired size in a Vec or slice, and then convert it to a box with [`Vec::into_boxed_slice`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.into_boxed_slice) and then [`Box::into_raw`](https://doc.rust-lang.org/std/boxed/struct.Box.html#method.into_raw) ; on the other hand, when such a pointer is passed back as an "out value" of some ABI call, it will be converted back to an owned box in the SDK via [`Box::from_raw`](https://doc.rust-lang.org/std/boxed/struct.Box.html#method.from_raw).

As we have more and more ABI methods that return pointers to allocated memory, and require three parameters for each target buffer plus retry logic in the SDK to get the buffer size right, I think this proposal may help.

@daviddrysdale @conradgrobler WDYT?

**Comment by daviddrysdale** [comment]
Random incoherent thoughts:
 - exposing the Node's allocator would certainly make the resizing dance simpler
 - on the other hand, most of the resize+retry code is encapsulated in the SDK, so (Rust) application developers don't generally have to worry about it
 - requiring a Node to provide an allocator would preclude a Node being written as `no_std` (without `alloc`)
    - &hellip;but that's probably unlikely to be relevant in practice
    - except maybe if Oak was deployed on-embedded-device?
 - upcalls from "kernel" into "userspace" make me nervous, but that may just be because they're comparatively unusual in [other systems](https://developer.ibm.com/technologies/linux/articles/l-user-space-apps/)
    - the upcalls would only ever occur during the processing of a "system call", so there shouldn't be any signal/interrupt-like concerns
    - any future [multi-threading](https://github.com/WebAssembly/threads/blob/master/proposals/threads/Overview.md) support would need to be thought about carefully though

**Comment by tiziano88** [comment]
@project-oak/core FYI this might help with the Oak Functions ABI, specifically with the lookup functionality, since it would make it possible to return the value in a correctly sized slice, without requiring the Wasm code to retry, in which case the underlying data may be refreshed and lead to inconsistencies.

BTW on the Rust side, I think https://doc.rust-lang.org/std/slice/fn.from_raw_parts.html would be the correct function to use to reconstruct the slice.

**Comment by tiziano88** [comment]
Also see https://radu-matei.com/blog/practical-guide-to-wasm-memory/
