### ISSUE TITLE
Refactor `Configuration` names in Rust Oak Runtime

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#755]
Currently we have 3 different Configurations in Rust `oak_runtime`:
- Configuration in `src/runtime`:
https://github.com/project-oak/oak/blob/09c7d6d86dd3a6c3808f3157884dc702c5352a50/oak/server/rust/oak_runtime/src/runtime/mod.rs#L47-L51
- Configuration in `src/node`:
https://github.com/project-oak/oak/blob/09c7d6d86dd3a6c3808f3157884dc702c5352a50/oak/server/rust/oak_runtime/src/node/mod.rs#L28-L40
- And also `ApplicationConfiguration` proto message that is used to configure the Runtime:
https://github.com/project-oak/oak/blob/09c7d6d86dd3a6c3808f3157884dc702c5352a50/oak/server/rust/oak_runtime/src/config.rs#L110-L115

I think we can refactor and call them differently to prevent confusion.

cc @project-oak/core what do you think could be possible new names?

**Comment by ipetr0v** [comment]
Also after https://github.com/project-oak/oak/issues/689 we may have separate "configurations" passed to each node (like `{"grpc_port": 8080}` passed to the gRPC pseudo-node).

**Comment by blaxill** [comment]
`src/runtime` `Configuration` could probably be removed, making the members arguments to `configure_and_run` as I think that is the only place it is used now.

`node::Configuration` could be called `NodeConfiguration` but that overlaps with proto names. `node::Configuration` is primarily used to share the parsed `wasmi::Module` between instances of Wasm nodes of the same Wasm module.

**Comment by tiziano88** [comment]
Perhaps we can get rid of `node::Configuration`, by pushing the mapping from module names to wasm bytecode in the Runtime itself (no need for reference counting, let's just load all of the available modules at startup and keep them around), then we can use the protobuf configuration objects directly in the runtime, we would not need an extra Rust type. We would still have Rust structs corresponding to individual instances of nodes (e.g. WasmNode, LogNode, etc) to encapsulate any internal state, if necessary.

**Comment by daviddrysdale** [comment]
I think this can be closed, as things are more disambiguated now:
 - `ApplicationConfiguration` is the app config proto message with the Wasm node contents in it.
 - `NodeConfiguration` is the node config proto message used for `node_create` operations.
 - `GrpcConfiguration` holds TLS and OpenID config information.
 - `RuntimeConfiguration` holds other runtime config, including ports for auxiliary servers to run on.
