### ISSUE TITLE
Set up thread-sanitizer run of Rust runtime in CI

### ISSUE THREAD

**Issue by daviddrysdale** [project-oak/oak#778]
The Rust runtime has a fair number of locks in it (5 x `RwLock` + 2 x `Mutex`), and while Rust prevents simple data races it doesn't automatically prevent lock inversions.

So it would be good to get Cloudbuild to run tests using the Rust runtime with ThreadSanitizer turned on.

**Comment by blaxill** [comment]
Note that this will require a nightly newer than 2020.03.19 see https://github.com/project-oak/oak/issues/780#issuecomment-605301862

**Comment by blaxill** [comment]
Blocked until rust nightlies past 2020.03.19 have all necessary components (clippy, rls, rustfmt, etc)

Available components can be checked [here https://rust-lang.github.io/rustup-components-history/](https://rust-lang.github.io/rustup-components-history/)

**Comment by blaxill** [comment]
This is no longer blocked as there are new nightlies with the required components such as 2020-04-17
