### ISSUE TITLE
race condition when starting newly created nodes

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#788]
in the Rust oak runtime, we start the new node instance before inserting it in the map of running nodes:

https://github.com/project-oak/oak/blob/5c07357bf2f603a0a8426c00539f26b729874ada/oak/server/rust/oak_runtime/src/runtime/mod.rs#L678-L692

this introduces a race between the node instance trying to perform any operation that requires its entry to be present in the runtime (e.g. anything involving labels), and the runtime inserting the instance in its `nodes` field.

@blaxill @daviddrysdale any idea how to sort this out?

**Comment by blaxill** [comment]
I think your approach in #789 is the way to go: splitting the instances out of Node(Info) already was already starting to make sense for e.g. stopping nodes.
