### ISSUE TITLE
Move `GrpcRequest` to `oak_abi`

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#799]
Since `GrpcRequest` is necessary for implementing gRPC pseudo node (https://github.com/project-oak/oak/pull/772) it will add a dependency on the Oak SDK, that may not be appropriate.
So we need to split Protobuf generated files and move `GrpcRequest` to `oak_abi`.

Based on the following comment https://github.com/project-oak/oak/pull/772#discussion_r401132390

**Comment by daviddrysdale** [comment]
I think this is the same as #764 ?

**Comment by ipetr0v** [comment]
Yes, #764 includes this issue in its scope.
