### ISSUE TITLE
`wait_on_channels` ABI call should fail immediately if any channel handle is invalid

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#803]
Currently it just ignores invalid handles, unless all of them are invalid, in which case it does return an error.

See https://github.com/project-oak/oak/blob/c2b2ff4b666de2a4f5fe7ff7cbfadbfc00af69f2/docs/abi.md#wait_on_channels

This should also allow to simplify some of the Runtime logic dealing with optional handles for this ABI call:

https://github.com/project-oak/oak/blob/c2b2ff4b666de2a4f5fe7ff7cbfadbfc00af69f2/oak/server/rust/oak_runtime/src/runtime/mod.rs#L427-L431

**Comment by daviddrysdale** [comment]
I don't think this is a good idea; [details here](https://github.com/project-oak/oak/pull/907#discussion_r416736009).

**Comment by tiziano88** [comment]
I thought we can return a status for individual channel from this ABI function, is that not the case? My point is to return it early if **any** channel is in an invalid or orphan state.

**Comment by daviddrysdale** [comment]
My concern is a situation where the code that calls `wait_on_channels` has dozens of channels that it's waiting on; with a return type of `Result<<Vec<ChannelReadStatus>, OakStatus>`, any sort of `Err` result means that the per-channel `Vec` is missing, and the code has a tough job figuring out which one of the (say) 100 channels is closed.  

But maybe I'm misunderstanding &ndash; if you're talking about a change that finishes early but still returns a per-channel `Vec`, then my concern evaporates.

[This is admittedly quite far in the future, but I'm thinking of a situation where a complex Oak app is using various third-party libraries, all of which make use of a common base scheduling library for managing work sources, callbacks, closures, futures, promises etc.  At the bottom of that base library, there's basically going to be a core loop that calls `select`/`poll` on UNIX platforms, `WaitForMultipleObjects` on Windows, and `wait_on_channels` on Oak.  That core loop will end up with dozens of file descriptors (UNIX) /`HANDLE`s (Windows) / `Handle`s (Oak), each of which corresponds to an internal data structure in the scheduling library, and each of which was provided by one of the library's users.  If one of those `Handle`s was provided wrongly, or has subsequently been closed by the other end, then it's very awkward for the scheduling library to have to bisect or iterate to find out which one.]

**Comment by tiziano88** [comment]
> But maybe I'm misunderstanding – if you're talking about a change that finishes early but still returns a per-channel `Vec`, then my concern evaporates.

Yes that's what I'm suggesting (apologies if I was not clear): the error bit on the corresponding erroring channel(s) would be set in the "output" vector immediately.
