### ISSUE TITLE
Deduplicate oak_abi documentation

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#812]
Currently the following two files both describe the Wasm ABI host functions, but with slightly different wordings and parameter names

- https://github.com/project-oak/oak/blob/master/docs/abi.md#host-functions
- https://github.com/project-oak/oak/blob/master/oak/server/rust/oak_abi/src/lib.rs

This does not seem to add much value, and in fact it's easy for them to get out of sync over time, or end up with slightly inconsistent descriptions. We should pick one of them as the source of truth, and just add links to it from the other one.

For language-specific details (e.g. Rust types) we can of course have a more detailed documentation in addition to the link, but it should not try to replicate the contents of the master documentation.

@daviddrysdale WDYT?

**Comment by daviddrysdale** [comment]
Closing in favour of #877
