### ISSUE TITLE
TLS tag for information flow

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#814]
Introduce a new type of tag to the information flow control system, which specifies the [common name (CN)](https://www.ssl.com/faqs/common-name/) (and / or other fields) of a certificate that needs to be presented over TLS by a non-Oak destination server.

For instance, data labelled with a secrecy tag of "tls:spanner.google.com" may be sent to that destination via a gRPC client pseudo-node.

The enforcement of this label is managed by the gRPC client pseudo-node implementation. If and when other kinds of pseudo-nodes are implemented (e.g. HTTP client), those will also need to enforce such label. Effectively, the gRPC client pseudo-node must have the ability to declassify this label, based on the details of the entity on the other side of a TLS connection.

https://github.com/project-oak/oak/blob/006b9210e02e6483d298d24ec2940cff394906ee/oak/proto/policy.proto#L37-L42

**Comment by conradgrobler** [comment]
This should probably use subject alternative names (SAN), as the use of CN is considered deprecated.

**Comment by tiziano88** [comment]
Related to #819

**Comment by tiziano88** [comment]
I am implementing this now, but I cannot find a way of getting the actual server name from an established [gRPC channel](https://docs.rs/tonic/0.2.1/tonic/transport/struct.Channel.html).

I am considering adding a `tls_domain_name` to the `GrpcClientConfiguration` proto message:

https://github.com/project-oak/oak/blob/9679f79ad98f79e70973aecb1042048b94d4ee57/oak/proto/application.proto#L103-L113

and then pass that to [`ClientTlsConfig::domain_name`](https://docs.rs/tonic/0.2.1/tonic/transport/struct.ClientTlsConfig.html#method.domain_name) in addition to the URI, then use `tls_domain_name` to determine the privilege of the gRPC node to declassify the TLS tag.

@daviddrysdale @conradgrobler @ipetr0v does this sound reasonable? It would need we would have to pass both from existing application when creating a gRPC client node though.

Alternatively, I don't think there is a way of uniquely determining the TLS domain name from just the URI, right? i.e. `account.google.com` may in principle be served with a cert for `account.google.com`, or for `*.google.com`, right? Or am I misunderstanding how TLS works?

**Comment by conradgrobler** [comment]
I think the trusted domain and the SAN entries in the certificates can be separated. If a user trusts a domain (e.g. `account.google.com`) I don't think it matters whether there is a SAN entry in the certificate that matches `account.google.com`. If the user trusts the domain, and the domain is verified by a certificate that the Oak runtime trusts (whether wildcard or exact match) it should be ok. Also, if a user trusts all subdomains of `google.com` it should not matter whether a connection to `account.google.com` is verified by a certificate with a wildcard SAN entry or an exact entry for `account.google.com`.

Another (but probably future and separate) feature that might be useful would be to be able to specify a certificate fingerprint to trust, in which case the domain name is not important, only that it was verified using a specific certificate.

**Comment by tiziano88** [comment]
So if the connection is to `account.google.com`, but the TLS tag the user specified on the data is `google.com`, how do we resolve the gap? Do we just do a naive suffix match, on the components separated by dots?

> Another (but probably future and separate) feature that might be useful would be to be able to specify a certificate fingerprint to trust, in which case the domain name is not important, only that it was verified using a specific certificate.

This goes back to my original question: how do we get any details about an established TLS connection, for instance in order to check fingerprint or any other details of the cert used for the handshake?

**Comment by conradgrobler** [comment]
> So if the connection is to `account.google.com`, but the TLS tag the user specified on the data is `google.com`, how do we resolve the gap? Do we just do a naive suffix match, on the components separated by dots?
> 

If we allow users to specify wildcards for trust (I am not sure we should), we should be quite strict and require explicit wildcards. E.g. if a user specifies `google.com`, it should only match `google.com` and not `account.google.com`. If a user specifies `*.google.com`, it should match `account.google.com`, but not `test.account.google.com` or `google.com`. If we allow wildcards we should probably only allow one and only as the left-most component of a domain name.

> > Another (but probably future and separate) feature that might be useful would be to be able to specify a certificate fingerprint to trust, in which case the domain name is not important, only that it was verified using a specific certificate.
> 
> This goes back to my original question: how do we get any details about an established TLS connection, for instance in order to check fingerprint or any other details of the cert used for the handshake?

I suspect this would involve using lower level components from rustls for setting up the initial connection (perhaps by writing a custom TLS connector that stores the certificate information). The Channel is generic, and can represent a plain unenctyped connection or a TLS encrypted channel if TLS is enabled.

**Comment by daviddrysdale** [comment]
> This goes back to my original question: how do we get any details about an established TLS connection, for instance in  order to check fingerprint or any other details of the cert used for the handshake?

For simple cases, is this needed?  If we've asked `tonic` to connect to `https://some.domain.com/sub/path` and have provided the relevant TLS configuration, doesn't a valid returned `Channel` object give us confirmation that we are indeed connected to `some.domain.com` over TLS (and so the gRPC client pseudo-Node is allowed to declassify `domain:some.domain.com` labels)?   

To put it another way, could we get away with just extracting `config.uri.authority().host()` and checking that `config.uri.scheme() == Some(Scheme::HTTPS)` ?

**Comment by tiziano88** [comment]
This is what I ended up doing in fact (PR coming soon), but it seems in the future we may want more flexibility, for instance if `a.domain.com` and `b.domain.com` use the same certificate, it makes sense that there would be a way of declassifying to either of them.

**Comment by daviddrysdale** [comment]
> if `a.domain.com` and `b.domain.com` use the same certificate, it makes sense that there would be a way of declassifying to either of them.

I'm not sure it would be safe to assume any correlation between the SAN domains covered in a UCC cert ([example](https://crt.sh/?id=2379600289)).
