### ISSUE TITLE
Extend gRPC pseudo node to intercept and handle requests intended for the Oak Runtime

### ISSUE THREAD

**Issue by conradgrobler** [project-oak/oak#853]
Clients might need to interact with the Runtime directly, rather than a wasm node. For example, interaction with the Runtime is needed for OpenID Connect authentication:

- Request a nonce that will be included in the ID token to prevent replay attacks
- Exchange an ID token for a bearer token that can be attached as an integrity tag in future requests

If we use a consistent naming for Oak Runtime Service Endpoints, we can intercept all requests (based on the `path` specific in the request) that match this pattern (eg starts with `oak.runtime.`) and process them directly in the gRPC pseudo node rather than forwarding it to the wasm node.

**Comment by tiziano88** [comment]
Alternatively, we can just have a separate service that we bring up on a separate port, which is dedicated to authentication. It does not really need to be connected to anything else, does it? In fact, usually, OAuth2 would use plain HTTP requests (not gRPC) to exchange tokens etc. Perhaps could you sketch out the sequence of interactions that you expect a client to perform with the Oak Runtime, and also with the auth provider?

**Comment by conradgrobler** [comment]
The client steps are described in #854.

**Comment by conradgrobler** [comment]
The required server features are described in #855.

**Comment by conradgrobler** [comment]
A separate service on a separate port should work OK, as long as there is a mechanism to share state between the auth service and the rest of the runtime. The downside of using a different port is that it will always require firewall/proxy rules (eg from corporate networks to the internet) to be reconfigured to allow clients to connect to Oak servers. In many environments 443 is already open to the internet. So if a single well known https port is used it will be much easier to use in many environments.

Another option is to not use gRPC. We could keep only an HTTP server inside the gRPC pseudo node (it should probalby be renamed then) and add a REST handler for specific paths to proces the Runtime interaction requests.
