### ISSUE TITLE
OpenID Connect: Add support to the Oak Runtime

### ISSUE THREAD

**Issue by conradgrobler** [project-oak/oak#855]
The Oak Runtime needs to provide some services to support authentication via OpenID Connect:

- Provide nonces to clients to prevent replay attacks
  - The nonce must be stored for future reference to be able to validate the resulting ID token
  - The nonce must have enough entropy to avoid collisions (eg 256 bits)
- Exchange ID tokens for bearer tokens
  - [Validate ID token](https://developers.google.com/identity/protocols/oauth2/openid-connect#validatinganidtoken)
    - This involves downloading current certificates from a Google server
    - The certificates change about once per day, so ideally it would be good to cache these for the `max-age` specified in the `cache-control` response header when downloading
  - Generate bearer token that expires (eg in 24 hours)
  - Store mapping between bearer token and unique user id (`sub` field in ID token)
  - Return bearer token to the client

The Oak Runtime must store some state to support the authentication process
- The list of nonces that were issued so that it could be used to later validate the resulting ID tokens
- The list of nonces that were already used to validate ID tokens to avoid replay attacks
- The mappings between unique user accounts and bearer tokens (including expiry date of the bearer tokens)
  - The bearer token will be for short term use, but it should be possible to resolve the unique identity of the user they apply to
  - It would be possible to skip storing this if the bearer token included the user unique ID and a signature, but this would make the size of the token much bigger. In that case it might be better to always use ID tokens directly instead of exchanging them for bearer tokens
- Mapping between unique users accounts and refresh tokens (if we decide to support refresh tokens)

**Comment by conradgrobler** [comment]
As part of the validation of the ID token, the client ID used for generating the ID token must be known. This could be done by either:

- Assume there is a single client ID that will be used by the Oak instance, so include it in the server config; or
- Require it as a parameter for generating a nonce, and store a mapping between the nonce and the client ID

**Comment by conradgrobler** [comment]
One issue that needs to be clarified is how the list of nonces will be persisted to prevent replay attacks.
- The nonce must be stored for at least as long as the expiry time of the identity token
- If multiple Oak instances accept tokens from the same client ID, there must be some mechanism to propage this between them, or they should use shared external state storage (eg for load balancing etc)

**Comment by tiziano88** [comment]
How about a slightly different design:

- introduce a new "auth server" stand alone binary (probably also implemented in Rust) which performs the operations described above (either over gRPC or HTTP) until the openID token verification step; once that is verified, the server creates a session cookie (containing auth details, at a minimum just the verified email address of the user), and signs it with a private key that it is provisioned with (optionally also encrypts it, if necessary); it also includes a TTL after which the cookie expires and needs to be refreshed
- provision the oak loader binary with a flag to list (to allow for rotation) public keys from the auth servers it trusts
- a client authenticates using the auth server first, obtains the signed cookie, then attaches it to any subsequent gRPC (and ideally this should also work for HTTP) requests; the gRPC server node now just reads the cookie and verifies its signature and validity, which can do only using the auth server public key(s)

The downside of this approach is that it introduces an additional root of trust, but in the current model in which we don't have hardware enclaves, this root of trust is equivalent to the root of trust of the oak loader binary itself. When we move to enclaves or confidential VMs, a key escrow could be designed to provision those keys while being rooted in the same underlying hardware, anyways we can think about it later on.

@conradgrobler thoughts?

**Comment by conradgrobler** [comment]
I don't think it makes much of a difference. The code will be basically the same, just hosted in a different binary. It should be easier to build it as a separate binary for now, as it can be done mostly independently. It should be easy to host the code in the runtime if we decide in future to combine it.

But moving this logic outside of the runtime does not remove it from the TCB. The auth server will generate tokens that can be used to declassify any user's data. This means that the entire new auth server would have to be considered part of the TCB, and should be run in an enclave and capable of remote attestation when these features are available.

**Comment by conradgrobler** [comment]
On a somewhat related point, I have been thinking about moving the logic to exchange the auth code for an ID token to a server rather than doing it from the client. The API call to do the exchange requires the client secret, and distributing a secret to all clients means that it is no longer secret. Using a server (or the Oak Runtime) to make the API call means that the client secret never needs to be sent to clients.

**Comment by conradgrobler** [comment]
Some additional specific points to the detail in the suggestion:

> the server creates a session cookie (containing auth details, at a minimum just the verified email address of the user), and signs it with a private key that it is provisioned with (optionally also encrypts it, if necessary);

Email address cannot be considered a unique identifier. It is possible to associate multiple email addresses with a single Google account. The `sub` field returned in the ID token is the unique identifier for the account. I would not want to lose access to my data e.g. if I change my email address or log into my same google account using one of my other email aliases.

> it also includes a TTL after which the cookie expires and needs to be refreshed

TTL alone is not enough protection. There should be a nonce linked to the specific Oak runtime for which the token is intended to prevent reuse on other instances. Without this the token becomes a golden ticket and if it is stolen (eg by malware) it can be reused to steal the user's data on all other instances where the auth server is trusted, not only the current session.

> * provision the oak loader binary with a flag to list (to allow for rotation) public keys from the auth servers it trusts

Once remote attestation is available, this will need to be attested to as well. The user should make sure they trust all the auth servers that the Oak runtime is trusting as any one of them will be able to create a token to access the user's data on that Oak instance.

> * a client authenticates using the auth server first, obtains the signed cookie, then attaches it to any subsequent gRPC (and ideally this should also work for HTTP) requests; the gRPC server node now just reads the cookie and verifies its signature and validity, which can do only using the auth server public key(s)

As mentioned above there must be some information (such as a nonce) tying the cookie to the specific Oak instance. This requires communication between the auth server and the Oak runtime and state being stored on the Oak server.

With that in mind, it seems that many of the features moved to the auth server will also still have to be duplicated in the Runtime as well to validate the token signed by the auth server. In essence the auth server creates something very similar to a new OAuth token, just signed by a different authority. The validation steps would have to be similar to OAuth token validation to ensure security.

**Comment by tiziano88** [comment]
> On a somewhat related point, I have been thinking about moving the logic to exchange the auth code for an ID token to a server rather than doing it from the client. The API call to do the exchange requires the client secret, and distributing a secret to all clients means that it is no longer secret. Using a server (or the Oak Runtime) to make the API call means that the client secret never needs to be sent to clients.

Yes the token exchange (in both OAuth2 and OpenID Connect) must be done by the server, because it relies on a secret, which obviously cannot be entrusted to clients.

**Comment by tiziano88** [comment]
> TTL alone is not enough protection. There should be a nonce linked to the specific Oak runtime for which the token is intended to prevent reuse on other instances. Without this the token becomes a golden ticket and if it is stolen (eg by malware) it can be reused to steal the user's data on all other instances where the auth server is trusted, not only the current session.

Do you mean that a session cookie should be specific to an Oak application? That seems an orthogonal concern, if two applications want to share the same auth server instance, they will provision themselves with the auth server public key, otherwise they will create their own auth server instances and keep the keys separate. This design allows for the root of trust to be controlled.

**Comment by conradgrobler** [comment]
Any Oak instance can decide to trust the Auth server's public key. An attacker can trick a user to sign into a fake Oak instance (many users will not verify remote attestation data in the same way that many users don't check TLS cert details and get phished) that uses the same Auth server and get a token from the user that can be reused to steal the data on the actual Oak instance.

Even if a user decides to check the remote attestation, they can only check the version of Oak on the single instance they are connecting to. They have no way of enumerating the other Oak instances that also trusts the same Auth server, so they do not know the blast radius if the token is stolen if they cannot tie the token to a single instance.

It does not have to be a nonce, but there must be a mechanism (such as client ID in OAuth) to limit the scope of the token to a single application or instance. This requires communication between the auth server and the runtime and storing state in the Runtime.

**Comment by conradgrobler** [comment]
Another possible option is to provision (or negotiate) a shared secret between the Oak instances in an applications and the auth server (and have a 1-1 mapping between auth server an application). An example could be a symmetric encryption key that is used to encrypt the token so that only an Oak instance that forms part of the application can decrypt it and use it.

**Comment by tiziano88** [comment]
What's the plan of record for now?

**Comment by conradgrobler** [comment]
At the moment I think the best approach is to implement the logic inside the runtime, seeing that all auth code must be inside the TCB anyway and there is a need to have shared secrets between the runtime and the auth server if it is split.

I am currently working on an initial client (in Rust) that will get the auth code that can be exchanged for an ID token.

After that, the next step is to build an OpenID Connect auth pseudo node that will exchange this for an ID token, issue bearer tokens to the client, and store the needed state. The auth pseudo node will be configured using the same app config approach as for other pseudo nodes.

Currently the client will have the request details hardcoded, but as soon as the Runtime supports a mechanism for the client to talk to the OpenID Connect auth pseudo node, the client will request details such as the URL and client ID from the Runtime.
