### ISSUE TITLE
Roughtime client unnecessarily serializes requests.

### ISSUE THREAD

**Issue by daviddrysdale** [project-oak/oak#867]
The current Roughtime client works through its entire list of Roughtime servers accumulating their times, then looks for an overlap.  If there are 10 servers but only 3 overlaps required, this is probably overkill.  It would be nice if:
 - Requests to the servers were parallellized, so one unresponding server doesn't slow down the whole process.   Probably want to fire off requests to N of M servers at a time (i.e. not to every server at once), with *which* N servers randomized.
 - On receiving each response, check whether there's a quorum of overlapping times.  If there is, terminate the process there and then, rather than sending requests that aren't needed.  Can also drop the results of any requests that are still in flight.

**Comment by conradgrobler** [comment]
Although it is not currently done, the serialisation is done to support future chaining of requests to support the ecosystem in detecting misbehaving servers. It is still TBD whether we should ignore the chaining for performance, or trade off performance to support chaining and publishing of the chains once the Roughtime ecosystem grows.
