### ISSUE TITLE
Provide gRPC read handle to the Oak entrypoint

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#874]
Function that runs an event loop for a **Node** is called in the `entrypoint` (aka `oak_main`) created by this macro:
https://github.com/project-oak/oak/blob/6712ee6ba89aa0cd93361b83aa0e5597540ba713/sdk/rust/oak/src/lib.rs#L567-L576
This entrypoint requires an `in_handle` to receive messages, and this handle is provided by the Runtime upon creating this **Node**.
In the case of gRPC server _pseudo-Node_ this `in_handle` is created during the _pseudo-Node_ creation. But this _pseudo-Node_ is created by the original **Node** with an entrypoint, that at this point has already been created and provided with an `in_handle`.
And this results in a loop.

We need to change a way of how the initial **Node** is created. 
We have several possible options:
- **Node** creates a gRPC server _pseudo-Node_, receives invocations from it, and dispatches them to the `impl` of the gRPC service, which is all in the same node.
- **Node** creates a gRPC server _pseudo-Node_, and the gRPC service node (which will still be declared using the current entrypoint macro), then forwards invocations to that node.
- Runtime creates two Nodes: a gRPC server _pseudo-Node_ and the main **Node** (which uses a `handle` returned by the former). This approach is similar to the current approach used in the C++ Runtime.

Originated from a Slack thread: https://project-oak.slack.com/archives/CHE9E13C3/p1587068768173500

cc @tiziano88 @daviddrysdale

**Comment by tiziano88** [comment]
My preference would be towards the second approach:

> **Node** node creates a gRPC server pseudo-Node, and the gRPC service node (which will still be declared using the current entrypoint macro), then forwards invocations to that node.

Since it is more composable, and also plays better with IFC, especially when introducing per-user labels. For instance, this would make it easy for the "main" Node to act as a router based on the labels of individual gRPC invocations.

**Comment by ipetr0v** [comment]
It might be possible to use a [procedural macro](https://doc.rust-lang.org/book/ch19-06-macros.html#procedural-macros-for-generating-code-from-attributes) just like [`tokio::main`](https://docs.rs/tokio/0.2.18/tokio/attr.main.html):
```rust
#[oak::main]
fn main(handle: Handle) {
    let node = RunningAverageDispatcher::new(Node::default());
    let grpc_handle = oak::grpc::server::init();
    oak::run_event_loop(node, grpc_handle);
}
```
And it will be more convenient for developers since it will be just a regular `main` function.

**Comment by tiziano88** [comment]
procedural macros are a pain to maintain, we used to have them but we removed a while ago, I would avoid reintroducing them unless absolutely necessary

**Comment by ipetr0v** [comment]
Then it may just be already existing `entrypoint`, but it will not call an event loop by itself (so a developer will need to do this manually):
```rust
oak::entrypoint!(oak_main => {
    let node = RunningAverageDispatcher::new(Node::default());
    let grpc_handle = oak::grpc::server::init();
    oak::run_event_loop(node, grpc_handle);
})
```
This will allow a developer to choose which pseudo-Nodes to run and listen to (e.g. gRPC or HTTP) without introducing multiple new macros for each combination of pseudo-Nodes.
