### ISSUE TITLE
Consolidate Oak ABI documentation

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#877]
Currently the documentation of ABI-level functions is partially replicated in various places. In some cases it makes sense for it to be more precise in the context of a particular object or programming language, but I wonder whether we can do a better job at least at cross-referencing these various pieces together.

For instance, for the `node_create` call:

`Runtime` object:

https://github.com/project-oak/oak/blob/bc98624bdcf6629c4f3ef4aa139bd4a0892f3744/oak/server/rust/oak_runtime/src/runtime/mod.rs#L787-L798

`oak_abi` crate:

https://github.com/project-oak/oak/blob/bc98624bdcf6629c4f3ef4aa139bd4a0892f3744/oak/server/rust/oak_abi/src/lib.rs#L131-L142

Oak ABI documentation:

https://github.com/project-oak/oak/blob/bc98624bdcf6629c4f3ef4aa139bd4a0892f3744/docs/abi.md#node_create

@daviddrysdale do you have any ideas / suggestions?

**Comment by daviddrysdale** [comment]
Is this the same as #812 ?

**Comment by daviddrysdale** [comment]
Some of the duplicate comments have been removed (two copies dropped in #883, one in #979). 

Current places that describe ABI functions, using `node_create` as an example:
 - [ABI doc](https://github.com/project-oak/oak/blob/master/docs/abi.md#node_create) has a description in terms of a WebAssembly host function signature.
 - [`oak_abi::node_create`](https://github.com/project-oak/oak/blob/master/oak_abi/src/lib.rs#L137-L155) has a description in terms of a Rust `unsafe` function.
 - ([`wasm::WasmInterface::node_create`](https://github.com/project-oak/oak/blob/master/oak/server/rust/oak_runtime/src/node/wasm/mod.rs#L104-L106) redirects to the ABI doc.)
 - ([`wasm::WasmInterface::invoke_index`](https://github.com/project-oak/oak/blob/master/oak/server/rust/oak_runtime/src/node/wasm/mod.rs#L496-L502) is silent.)
 - ([`wasm::oak_resolv_func`](https://github.com/project-oak/oak/blob/master/oak/server/rust/oak_runtime/src/node/wasm/mod.rs#L556-L568) is silent.)
 - ([`RuntimeProxy::node_create`](https://github.com/project-oak/oak/blob/master/oak/server/rust/oak_runtime/src/runtime/mod.rs#L1165-L1175) redirects to `Runtime::node_create`)
 - [`Runtime::node_create`](https://github.com/project-oak/oak/blob/master/oak/server/rust/oak_runtime/src/runtime/mod.rs#L975-L992) has a description in terms of native/internal Rust types.

De-duped enough?
