### ISSUE TITLE
Cache bazel artifacts in CI

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#89]
I tried naively caching the whole bazel cache folder via the standard [Travis mechanism](https://docs.travis-ci.com/user/caching/#arbitrary-directories), but it always fails to restore it, even if I increase the timeout. I think the cache is too large and there are too many small files for Travis to unpack it in a reasonable time.
Another option could be to use a [Bazel remote cache](https://docs.bazel.build/versions/master/remote-caching.html#google-cloud-storage), which has the advantage that we could also share the same cache when building locally.

**Comment by tiziano88** [comment]
FYI I have created a Google Cloud Storage bucket for this (on google.com): https://pantheon.corp.google.com/storage/browser/oak-bazel-cache?project=oak-ci (only googlers have access to it)

**Comment by tiziano88** [comment]
Also created a role account and generated a JSON key, and stored that under the `BAZEL_GOOGLE_CREDENTIALS` env variable in Travis (as a secret).

**Comment by anghelcovici** [comment]
The EXAMPLES_TEST build step in TRAVIS is taking almost 50 mins on PRs. I've added additional work on it and it timed out. We need to fix this asap

**Comment by anghelcovici** [comment]
I've made the cache work for master and that saves about 10-15 mins, but only on master. PR are still an issue.

**Comment by tiziano88** [comment]
Currently the [GCB cache](https://pantheon.corp.google.com/storage/browser/oak-bazel-cache?project=oak-ci) is set to allow read from anyone (unauthenticated) and write from people manually added to the project.

We should create a role account for CI and pass its credentials to GCB workflow so that when running on CI (post-merge), the cache will be updated.

Because we don't want to expose the credentials to the public, we probably need to avoid using them on the pull request CI runs instead (since anyone could send a PR that just logs the credentials for them to see).
