### ISSUE TITLE
Investigate fuzz testing with OSS-Fuzz for Rust

### ISSUE THREAD

**Issue by rbehjati** [project-oak/oak#893]
Now that most of the code is migrated to Rust, we need to replace the existing fuzzing with fuzzing for Rust. [OSS-Fuzz](https://google.github.io/oss-fuzz/) already supports Rust. 
However, according to the [Rust Fuzz book](https://rust-fuzz.github.io/book/cargo-fuzz.html), [cargo-fuzz](https://github.com/rust-fuzz/cargo-fuzz) is the recommended tool for fuzz testing Rust code.

**Comment by daviddrysdale** [comment]
See also #1163

**Comment by tiziano88** [comment]
To avoid confusion: let's keep this issue for additional OSS-fuzz specific integration work, once #1163 is done.
