### ISSUE TITLE
Application Config serializer log statements ignored

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#916]
See https://github.com/project-oak/oak/blob/878bba2c3d336d34fdca611c62ab9d303ed6cfda/oak/common/app_config_serializer.cc#L43

Needs a similar treatment to #904.

The issue here is more urgent, because any `OAK_FATAL` statement is silently ignored (!) and the program keeps going despite failures, and it even eventually succeeds.

**Comment by daviddrysdale** [comment]
Fixed by #1016 &ndash; the serializer now uses raw gLog.
