### ISSUE TITLE
Investigate long pause in abitest_tests

### ISSUE THREAD

**Issue by daviddrysdale** [project-oak/oak#955]
When running the `abitest` suite via `cargo test --package=abitest_tests`, there's often a ~8second pause in processing, where there's just a bunch of log messages:
```log
2020-05-06 08:39:33,684 TRACE [oak_runtime::runtime] NodeId(0): validating readability of Handle(9771623940782918200)
2020-05-06 08:39:33,684 TRACE [oak_runtime::runtime] NodeId(0): runtime can read from any channel
2020-05-06 08:39:33,684 INFO  [oak_tests] no pending gRPC response message; poll again soon
```

Worth investigating at some point to see if there's a reason why things don't proceed immediately.

[I noticed this a while ago, so not due to any recent changes]

**Comment by daviddrysdale** [comment]
This *seems* to be ~7 seconds spent executing:
```Rust
    let exclude = regex::Regex::new("(Storage|GrpcClient|Roughtime)")
```

**Comment by tiziano88** [comment]
I think behind the scenes it's sending the string to @anghelcovici for hand-compilation, and waiting for his reply.

**Comment by tiziano88** [comment]
FWIW the documentation says it may be expensive, but ~milliseconds, not ~seconds: https://docs.rs/regex/1.3.7/regex/#example-avoid-compiling-the-same-regex-in-a-loop

**Comment by tiziano88** [comment]
Is this still happening? I had the impression that tests are faster lately, not sure if anything actually changed though

**Comment by daviddrysdale** [comment]
I'm still seeing a ~6 sec pause (and I've upgraded machine in the meanwhile).

**Comment by daviddrysdale** [comment]
Doesn't seem to pause any more.
