### ISSUE TITLE
Pass TLS credentials to gRPC server pseudo-node without modifying the ApplicationConfiguration

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#961]
https://github.com/project-oak/oak/blob/ca7f1eeed15af9357a59e4be3b4354c432c626c2/oak/server/rust/oak_loader/src/main.rs#L88-L96

Apart from not being very idiomatic (why does oak_loader modify the ApplicationConfiguration object that was supposed to run?), it is problematic for #917 and other related refactorings.

I guess the final solution may be dependant on #689 , but in the meanwhile we can just pass the TLS credentials directly to the Runtime object, and have that propagate them to the gRPC pseudo-node at creation time.

**Comment by tiziano88** [comment]
@ipetr0v have you started work on this? If not, I can look into it, since it helps with #917

**Comment by ipetr0v** [comment]
No, I haven't yet.
Will take a look.

**Comment by tiziano88** [comment]
Happy to take a look myself as part of #917, thanks!
