### ISSUE TITLE
Support client-streaming gRPC methods (in both gRPC server and client pseudo-Nodes)

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#97]
Currently we only support unary RPCs, but gRPC allows any combination of client and server streaming.
See https://grpc.io/docs/guides/concepts/ for more context.

**Comment by daviddrysdale** [comment]
Partially done in #173 (server-side streaming)

**Comment by tiziano88** [comment]
@daviddrysdale is the client-side streaming still to be done?

**Comment by daviddrysdale** [comment]
Yep.  I'm assuming non-urgent because it's usually possible to re-organize a service definition to not need it.
