### ISSUE TITLE
Use graceful shutdown for aux hyper servers

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#986]
https://github.com/project-oak/oak/blob/af7923012686474e93fea530bd8aae730ac0f711/oak/server/rust/oak_runtime/src/runtime/introspect.rs#L158

I think we should be able to just pass the notification channel directly to the `hyper` server instance with [with_graceful_shutdown](https://docs.rs/hyper/0.13.5/hyper/server/struct.Server.html#method.with_graceful_shutdown), rather than having our own `select`.

cc @daviddrysdale @ipetr0v

**Comment by daviddrysdale** [comment]
Oh, good find &ndash; I went looking for exactly that and failed to find it (I was looking in the Tokio docs rather than the Hyper docs&hellip;).   #987 incoming.

**Comment by daviddrysdale** [comment]
cc @ipetr0v for #985

**Comment by ipetr0v** [comment]
Thanks!
But looks like it's only possible if I use the raw `hyper` server, and not the `tonic` wrapper.
https://github.com/project-oak/oak/blob/b5322ac6b355a1052127db8b9b7fb6a039694469/oak/server/rust/oak_runtime/src/node/grpc/server.rs#L122-L125

**Comment by ipetr0v** [comment]
Or maybe not, looks like there is a similar function:
https://docs.rs/tonic/0.2.1/tonic/transport/server/struct.Router.html#method.serve_with_shutdown
