### ISSUE TITLE
Embed root CAs in oak_loader binary

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#999]
the `oak_loader` binary should not depend on external roots of trust that may affect the meaning of any Information Flow Control labels; labels are expected to have the same meaning across instances, and therefore it must not be possible to override root CAs either by specifying different flags or configuring the system differently.

We should end up with a self-contained `oak_loader` binary that includes the list of all allowed root CAs in the binary itself (and therefore contribute to its remotely attestable state by affecting its hash). In particular such root CAs are the ones that are used to establish the validity of the TLS endpoint tag:

https://github.com/project-oak/oak/blob/54e2ab272f74ef1897b377d0cc5a0dfcf8a9a35d/oak/proto/label.proto#L65-L81

@conradgrobler I think we discussed something along those lines in the past, could you look into it, and figure out what's necessary? In particular I think we need to answer the following:

- where to get an authoritative list of CAs in the first place
- how to embed it in the `oak_loader` rust binary
- how to ensure that gRPC server pseudo-node makes use of them (and only them)
- how this affects declassification of TLS endpoint tags

cc @ipetr0v

**Comment by tiziano88** [comment]
For reference, in Google Chrome, the list of root CAs can be seen under chrome://settings/certificates?search=cert -> "Authorities", but I think it just comes from the underlying system-wide CA-store (from Linux or Windows).

**Comment by conradgrobler** [comment]
> - how to ensure that gRPC server pseudo-node makes use of them (and only them)
Do you mean the gRPC client pseudo-node? It is up to the client to decide whether or not to trust the gRPC server node. The gRPC server node does not do any validation of certificates at the moment.

**Comment by tiziano88** [comment]
Yes sorry, I meant gRPC client pseudo-node.

**Comment by conradgrobler** [comment]
Android's list is available at https://android.googlesource.com/platform/system/ca-certificates/+/master/files/

Microsoft's list (which includes code signing and client authentication certs) is available at https://ccadb-public.secure.force.com/microsoft/IncludedCACertificateReportForMSFT

Mozilla's list is here: https://ccadb-public.secure.force.com/mozilla/IncludedCACertificateReport

Curl uses Mozilla's list: https://curl.haxx.se/docs/caextract.html

These are quite different, and some include additional certificate types. I think we should perhaps start with the Android list as it seems the most minimal.

**Comment by tiziano88** [comment]
Great! Note that I think it is important that we are able to convince ourselves (and others) that we are indeed importing a legitimate snapshot of some trusted CA store. I think just manually copying the files in our repository is not going to be very convincing. If we went with the Android one, for instance, we should think how to make sure that we include all and only the contents of the https://android.googlesource.com/platform/system/ca-certificates/ repository. Maybe using git submodules, or just a shell script that downloads the contents at a specific commit and vendors it under third_party, and instructions to show how to verify that the vendored version is indeed in sync with upstream.

**Comment by conradgrobler** [comment]
@tiziano88 how should we handle the aggregator examples? If I enforce that only trusted CA cert will work, we will no longer be able to use the gRPC client to connect to a service that uses our self-signed certs.

**Comment by tiziano88** [comment]
Perhaps this boils down to prod vs debug builds of `oak_loader`. We already know that we need two different versions (based on compile time features), for instance to disable logging of internal details that may leak confidential information. So in a debug build we may include a different set of CAs, or have a flag to specify the actual CA (similar to what we have now).

cc @daviddrysdale @ipetr0v

**Comment by ipetr0v** [comment]
I'm not sure if should prohibit developers from using self-signed certificates. We can still have the ability to add a self-signed cert, while having a list of predetermined root CAs.

**Comment by tiziano88** [comment]
> I'm not sure if should prohibit developers from using self-signed certificates. We can still have the ability to add a self-signed cert, while having a list of predetermined root CAs.

That's exactly what we want to avoid.

**Comment by tiziano88** [comment]
To clarify: we want to avoid that a developer adds a self-signed cert for google.com, or something like that.

**Comment by ipetr0v** [comment]
But he still can add a certificate for `specific_example.com`, right?
